.TH "__gmp_sgn_function" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_sgn_function
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBeval\fP (\fBmpz_srcptr\fP \fBz\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpq_srcptr\fP q)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpf_srcptr\fP \fBf\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int __gmp_sgn_function::eval (\fBmpf_srcptr\fP f)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_sgn_function::eval (\fBmpq_srcptr\fP q)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_sgn_function::eval (\fBmpz_srcptr\fP z)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
