.TH "__gmp_expr< mpq_t, mpq_t >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_expr< mpq_t, mpq_t >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmp_bitcnt_t\fP \fBget_prec\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBcanonicalize\fP ()"
.br
.ti -1c
.RI "\fB__gmp_expr\fP ()"
.br
.ti -1c
.RI "\fB__gmp_expr\fP (\fBconst\fP \fB__gmp_expr\fP &q)"
.br
.ti -1c
.RI "template<class T > \fB__gmp_expr\fP (\fBconst\fP \fB__gmp_expr\fP< \fBmpz_t\fP, \fBT\fP > &expr)"
.br
.ti -1c
.RI "template<class T > \fB__gmp_expr\fP (\fBconst\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBT\fP > &expr)"
.br
.ti -1c
.RI "template<class T , class U > \fB__gmp_expr\fP (\fBconst\fP \fB__gmp_expr\fP< \fBT\fP, \fBU\fP > &expr)"
.br
.ti -1c
.RI "\fB__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS\fP \fB__gmp_expr\fP (\fBconst\fP char *s, int base=0)"
.br
.ti -1c
.RI "\fB__gmp_expr\fP (\fBconst\fP std::string &s, int base=0)"
.br
.ti -1c
.RI "\fB__gmp_expr\fP (\fBmpq_srcptr\fP q)"
.br
.ti -1c
.RI "\fB__gmp_expr\fP (\fBconst\fP \fBmpz_class\fP &\fBnum\fP, \fBconst\fP \fBmpz_class\fP &den)"
.br
.ti -1c
.RI "\fB~__gmp_expr\fP ()"
.br
.ti -1c
.RI "void \fBswap\fP (\fB__gmp_expr\fP &q) \fB__GMPXX_NOEXCEPT\fP"
.br
.ti -1c
.RI "\fB__gmp_expr\fP & \fBoperator=\fP (\fBconst\fP \fB__gmp_expr\fP &q)"
.br
.ti -1c
.RI "template<class T , class U > \fB__gmp_expr\fP< \fBvalue_type\fP, \fBvalue_type\fP > & \fBoperator=\fP (\fBconst\fP \fB__gmp_expr\fP< \fBT\fP, \fBU\fP > &expr)"
.br
.ti -1c
.RI "\fB__GMPXX_DEFINE_ARITHMETIC_ASSIGNMENTS\fP \fB__gmp_expr\fP & \fBoperator=\fP (\fBconst\fP char *s)"
.br
.ti -1c
.RI "\fB__gmp_expr\fP & \fBoperator=\fP (\fBconst\fP std::string &s)"
.br
.ti -1c
.RI "int \fBset_str\fP (\fBconst\fP char *s, int base)"
.br
.ti -1c
.RI "int \fBset_str\fP (\fBconst\fP std::string &s, int base)"
.br
.ti -1c
.RI "std::string \fBget_str\fP (int base=10) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBmpz_class\fP & \fBget_num\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBmpz_class\fP & \fBget_num\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBmpz_class\fP & \fBget_den\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBmpz_class\fP & \fBget_den\fP ()"
.br
.ti -1c
.RI "\fBmpq_srcptr\fP \fB__get_mp\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBmpq_ptr\fP \fB__get_mp\fP ()"
.br
.ti -1c
.RI "\fBmpq_srcptr\fP \fBget_mpq_t\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBmpq_ptr\fP \fBget_mpq_t\fP ()"
.br
.ti -1c
.RI "\fBmpz_srcptr\fP \fBget_num_mpz_t\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBmpz_ptr\fP \fBget_num_mpz_t\fP ()"
.br
.ti -1c
.RI "\fBmpz_srcptr\fP \fBget_den_mpz_t\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBmpz_ptr\fP \fBget_den_mpz_t\fP ()"
.br
.ti -1c
.RI "double \fBget_d\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::\fB__gmp_expr\fP ()\fC [inline]\fP"

.SS "\fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::\fB__gmp_expr\fP (\fBconst\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP > & q)\fC [inline]\fP"

.SS "template<class T > \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::\fB__gmp_expr\fP (\fBconst\fP \fB__gmp_expr\fP< \fBmpz_t\fP, \fBT\fP > & expr)\fC [inline]\fP"

.SS "template<class T > \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::\fB__gmp_expr\fP (\fBconst\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBT\fP > & expr)\fC [inline]\fP"

.SS "template<class T , class U > \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::\fB__gmp_expr\fP (\fBconst\fP \fB__gmp_expr\fP< \fBT\fP, \fBU\fP > & expr)\fC [inline]\fP, \fC [explicit]\fP"

.SS "\fB__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::\fB__gmp_expr\fP (\fBconst\fP char * s, int base = \fC0\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "\fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::\fB__gmp_expr\fP (\fBconst\fP std::string & s, int base = \fC0\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "\fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::\fB__gmp_expr\fP (\fBmpq_srcptr\fP q)\fC [inline]\fP, \fC [explicit]\fP"

.SS "\fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::\fB__gmp_expr\fP (\fBconst\fP \fBmpz_class\fP & num, \fBconst\fP \fBmpz_class\fP & den)\fC [inline]\fP"

.SS "\fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::~\fB__gmp_expr\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBmpq_ptr\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::__get_mp ()\fC [inline]\fP"

.SS "\fBmpq_srcptr\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::__get_mp () const\fC [inline]\fP"

.SS "void \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::canonicalize ()\fC [inline]\fP"

.SS "double \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_d () const\fC [inline]\fP"

.SS "\fBmpz_class\fP& \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_den ()\fC [inline]\fP"

.SS "\fBconst\fP \fBmpz_class\fP& \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_den () const\fC [inline]\fP"

.SS "\fBmpz_ptr\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_den_mpz_t ()\fC [inline]\fP"

.SS "\fBmpz_srcptr\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_den_mpz_t () const\fC [inline]\fP"

.SS "\fBmpq_ptr\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_mpq_t ()\fC [inline]\fP"

.SS "\fBmpq_srcptr\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_mpq_t () const\fC [inline]\fP"

.SS "\fBmpz_class\fP& \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_num ()\fC [inline]\fP"

.SS "\fBconst\fP \fBmpz_class\fP& \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_num () const\fC [inline]\fP"

.SS "\fBmpz_ptr\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_num_mpz_t ()\fC [inline]\fP"

.SS "\fBmpz_srcptr\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_num_mpz_t () const\fC [inline]\fP"

.SS "\fBmp_bitcnt_t\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_prec () const\fC [inline]\fP"

.SS "std::string \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::get_str (int base = \fC10\fP) const\fC [inline]\fP"

.SS "\fB__gmp_expr\fP& \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::operator= (\fBconst\fP \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP > & q)\fC [inline]\fP"

.SS "template<class T , class U > \fB__gmp_expr\fP<\fBvalue_type\fP, \fBvalue_type\fP>& \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::operator= (\fBconst\fP \fB__gmp_expr\fP< \fBT\fP, \fBU\fP > & expr)\fC [inline]\fP"

.SS "\fB__GMPXX_DEFINE_ARITHMETIC_ASSIGNMENTS\fP \fB__gmp_expr\fP& \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::operator= (\fBconst\fP char * s)\fC [inline]\fP"

.SS "\fB__gmp_expr\fP& \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::operator= (\fBconst\fP std::string & s)\fC [inline]\fP"

.SS "int \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::set_str (\fBconst\fP char * s, int base)\fC [inline]\fP"

.SS "int \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::set_str (\fBconst\fP std::string & s, int base)\fC [inline]\fP"

.SS "void \fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP >::swap (\fB__gmp_expr\fP< \fBmpq_t\fP, \fBmpq_t\fP > & q)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
