.TH "__gmp_binary_expr< T, U, Op >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_binary_expr< T, U, Op >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__gmp_binary_expr\fP (\fBconst\fP \fBT\fP &v1, \fBconst\fP \fBU\fP &v2)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__gmp_resolve_ref\fP< \fBT\fP >::ref_type \fBval1\fP"
.br
.ti -1c
.RI "\fB__gmp_resolve_ref\fP< \fBU\fP >::ref_type \fBval2\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T , class U , class Op > \fB__gmp_binary_expr\fP< \fBT\fP, \fBU\fP, Op >::\fB__gmp_binary_expr\fP (\fBconst\fP \fBT\fP & v1, \fBconst\fP \fBU\fP & v2)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<class T , class U , class Op > \fB__gmp_resolve_ref\fP<\fBT\fP>::ref_type \fB__gmp_binary_expr\fP< \fBT\fP, \fBU\fP, Op >::val1"

.SS "template<class T , class U , class Op > \fB__gmp_resolve_ref\fP<\fBU\fP>::ref_type \fB__gmp_binary_expr\fP< \fBT\fP, \fBU\fP, Op >::val2"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
