.TH "__gmp_temp< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_temp< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class U , class V > \fB__gmp_temp\fP (\fBU\fP \fBconst\fP &\fBu\fP, \fBV\fP)"
.br
.ti -1c
.RI "\fB__gmp_resolve_expr\fP< \fBT\fP >::srcptr_type \fB__get_mp\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > template<class U , class V > \fB__gmp_temp\fP< \fBT\fP >::\fB__gmp_temp\fP (\fBU\fP \fBconst\fP & u, \fBV\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > \fB__gmp_resolve_expr\fP<\fBT\fP>::srcptr_type \fB__gmp_temp\fP< \fBT\fP >::__get_mp () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
