.TH "__gmp_cmp_function" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_cmp_function
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBeval\fP (\fBmpz_srcptr\fP \fBz\fP, \fBmpz_srcptr\fP w)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpz_srcptr\fP \fBz\fP, unsigned long int l)"
.br
.ti -1c
.RI "static int \fBeval\fP (unsigned long int l, \fBmpz_srcptr\fP \fBz\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpz_srcptr\fP \fBz\fP, signed long int l)"
.br
.ti -1c
.RI "static int \fBeval\fP (signed long int l, \fBmpz_srcptr\fP \fBz\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpz_srcptr\fP \fBz\fP, double d)"
.br
.ti -1c
.RI "static int \fBeval\fP (double d, \fBmpz_srcptr\fP \fBz\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpq_srcptr\fP q, \fBmpq_srcptr\fP r)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpq_srcptr\fP q, unsigned long int l)"
.br
.ti -1c
.RI "static int \fBeval\fP (unsigned long int l, \fBmpq_srcptr\fP q)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpq_srcptr\fP q, signed long int l)"
.br
.ti -1c
.RI "static int \fBeval\fP (signed long int l, \fBmpq_srcptr\fP q)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpq_srcptr\fP q, double d)"
.br
.ti -1c
.RI "static int \fBeval\fP (double d, \fBmpq_srcptr\fP q)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpq_srcptr\fP q, \fBmpz_srcptr\fP \fBz\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpz_srcptr\fP \fBz\fP, \fBmpq_srcptr\fP q)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpf_srcptr\fP \fBf\fP, \fBmpf_srcptr\fP g)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpf_srcptr\fP \fBf\fP, unsigned long int l)"
.br
.ti -1c
.RI "static int \fBeval\fP (unsigned long int l, \fBmpf_srcptr\fP \fBf\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpf_srcptr\fP \fBf\fP, signed long int l)"
.br
.ti -1c
.RI "static int \fBeval\fP (signed long int l, \fBmpf_srcptr\fP \fBf\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpf_srcptr\fP \fBf\fP, double d)"
.br
.ti -1c
.RI "static int \fBeval\fP (double d, \fBmpf_srcptr\fP \fBf\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpf_srcptr\fP \fBf\fP, \fBmpz_srcptr\fP \fBz\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpz_srcptr\fP \fBz\fP, \fBmpf_srcptr\fP \fBf\fP)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpf_srcptr\fP \fBf\fP, \fBmpq_srcptr\fP q)"
.br
.ti -1c
.RI "static int \fBeval\fP (\fBmpq_srcptr\fP q, \fBmpf_srcptr\fP \fBf\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int __gmp_cmp_function::eval (double d, \fBmpf_srcptr\fP f)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (double d, \fBmpq_srcptr\fP q)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (double d, \fBmpz_srcptr\fP z)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpf_srcptr\fP f, double d)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpf_srcptr\fP f, \fBmpf_srcptr\fP g)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpf_srcptr\fP f, \fBmpq_srcptr\fP q)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpf_srcptr\fP f, \fBmpz_srcptr\fP z)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpf_srcptr\fP f, signed long int l)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpf_srcptr\fP f, unsigned long int l)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpq_srcptr\fP q, double d)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpq_srcptr\fP q, \fBmpf_srcptr\fP f)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpq_srcptr\fP q, \fBmpq_srcptr\fP r)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpq_srcptr\fP q, \fBmpz_srcptr\fP z)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpq_srcptr\fP q, signed long int l)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpq_srcptr\fP q, unsigned long int l)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpz_srcptr\fP z, double d)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpz_srcptr\fP z, \fBmpf_srcptr\fP f)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpz_srcptr\fP z, \fBmpq_srcptr\fP q)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpz_srcptr\fP z, \fBmpz_srcptr\fP w)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpz_srcptr\fP z, signed long int l)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (\fBmpz_srcptr\fP z, unsigned long int l)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (signed long int l, \fBmpf_srcptr\fP f)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (signed long int l, \fBmpq_srcptr\fP q)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (signed long int l, \fBmpz_srcptr\fP z)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (unsigned long int l, \fBmpf_srcptr\fP f)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (unsigned long int l, \fBmpq_srcptr\fP q)\fC [inline]\fP, \fC [static]\fP"

.SS "static int __gmp_cmp_function::eval (unsigned long int l, \fBmpz_srcptr\fP z)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
