.TH "__gmp_temp< mpf_t >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_temp< mpf_t >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class U > \fB__gmp_temp\fP (\fBU\fP \fBconst\fP &\fBu\fP, \fBmpf_ptr\fP \fBres\fP)"
.br
.ti -1c
.RI "\fBmpf_srcptr\fP \fB__get_mp\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class U > \fB__gmp_temp\fP< \fBmpf_t\fP >::\fB__gmp_temp\fP (\fBU\fP \fBconst\fP & u, \fBmpf_ptr\fP res)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBmpf_srcptr\fP \fB__gmp_temp\fP< \fBmpf_t\fP >::__get_mp () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
