.TH "__gmp_expr< T, __gmp_unary_expr< __gmp_expr< T, U >, Op > >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_expr< T, __gmp_unary_expr< __gmp_expr< T, U >, Op > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__gmp_expr\fP (\fBconst\fP \fBval_type\fP &\fBval\fP)"
.br
.ti -1c
.RI "void \fBeval\fP (typename \fB__gmp_resolve_expr\fP< \fBT\fP >::ptr_type \fBp\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBval_type\fP & \fBget_val\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBmp_bitcnt_t\fP \fBget_prec\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T , class U , class Op > \fB__gmp_expr\fP< \fBT\fP, \fB__gmp_unary_expr\fP< \fB__gmp_expr\fP< \fBT\fP, \fBU\fP >, Op > >::\fB__gmp_expr\fP (\fBconst\fP \fBval_type\fP & val)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T , class U , class Op > void \fB__gmp_expr\fP< \fBT\fP, \fB__gmp_unary_expr\fP< \fB__gmp_expr\fP< \fBT\fP, \fBU\fP >, Op > >::eval (typename \fB__gmp_resolve_expr\fP< \fBT\fP >::ptr_type p) const\fC [inline]\fP"

.SS "template<class T , class U , class Op > \fBmp_bitcnt_t\fP \fB__gmp_expr\fP< \fBT\fP, \fB__gmp_unary_expr\fP< \fB__gmp_expr\fP< \fBT\fP, \fBU\fP >, Op > >::get_prec () const\fC [inline]\fP"

.SS "template<class T , class U , class Op > \fBconst\fP \fBval_type\fP& \fB__gmp_expr\fP< \fBT\fP, \fB__gmp_unary_expr\fP< \fB__gmp_expr\fP< \fBT\fP, \fBU\fP >, Op > >::get_val () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
