.TH "__gmp_unary_increment" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_unary_increment
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBeval\fP (\fBmpz_ptr\fP \fBz\fP)"
.br
.ti -1c
.RI "static void \fBeval\fP (\fBmpq_ptr\fP q)"
.br
.ti -1c
.RI "static void \fBeval\fP (\fBmpf_ptr\fP \fBf\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void __gmp_unary_increment::eval (\fBmpf_ptr\fP f)\fC [inline]\fP, \fC [static]\fP"

.SS "static void __gmp_unary_increment::eval (\fBmpq_ptr\fP q)\fC [inline]\fP, \fC [static]\fP"

.SS "static void __gmp_unary_increment::eval (\fBmpz_ptr\fP z)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
