.TH "__gmp_binary_greater" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_binary_greater
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T , class U > static bool \fBeval\fP (\fBT\fP \fBt\fP, \fBU\fP \fBu\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class T , class U > static bool __gmp_binary_greater::eval (\fBT\fP t, \fBU\fP u)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
