.TH "__gmp_resolve_ref< __gmp_expr< T, U > >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_resolve_ref< __gmp_expr< T, U > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP typedef \fB__gmp_expr\fP< \fBT\fP, \fBU\fP > & \fBref_type\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<class T , class U > \fBconst\fP typedef \fB__gmp_expr\fP<\fBT\fP, \fBU\fP>& \fB__gmp_resolve_ref\fP< \fB__gmp_expr\fP< \fBT\fP, \fBU\fP > >::ref_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
