.TH "__gmp_resolve_expr< mpf_t, mpq_t >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_resolve_expr< mpf_t, mpq_t >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBmpf_t\fP \fBvalue_type\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBmpf_t\fP \fB__gmp_resolve_expr\fP< \fBmpf_t\fP, \fBmpq_t\fP >::\fBvalue_type\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
