.TH "__gmp_expr< mpz_t, __gmp_urandomm_value >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gmp_expr< mpz_t, __gmp_urandomm_value >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmpxx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__gmp_expr\fP (\fBgmp_randstate_t\fP s, \fBconst\fP \fBmpz_class\fP &\fBz\fP)"
.br
.ti -1c
.RI "void \fBeval\fP (\fBmpz_ptr\fP \fBz\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBmp_bitcnt_t\fP \fBget_prec\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fB__gmp_expr\fP< \fBmpz_t\fP, \fB__gmp_urandomm_value\fP >::\fB__gmp_expr\fP (\fBgmp_randstate_t\fP s, \fBconst\fP \fBmpz_class\fP & z)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void \fB__gmp_expr\fP< \fBmpz_t\fP, \fB__gmp_urandomm_value\fP >::eval (\fBmpz_ptr\fP z) const\fC [inline]\fP"

.SS "\fBmp_bitcnt_t\fP \fB__gmp_expr\fP< \fBmpz_t\fP, \fB__gmp_urandomm_value\fP >::get_prec () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
