.TH "lib/iegenlib/src/parser Directory Reference" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/parser Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBjsoncons\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgen_parser\&.cc\fP"
.br
.ti -1c
.RI "file \fBgen_parser\&.hh\fP"
.br
.ti -1c
.RI "file \fBgen_scanner\&.cc\fP"
.br
.ti -1c
.RI "file \fBparser\&.cc\fP"
.br
.RI "Implementations to methods declared in \fBparser\&.h\fP\&. "
.ti -1c
.RI "file \fBparser\&.h\fP"
.br
.RI "a namespace to allow the user to make use of the parser "
.ti -1c
.RI "file \fBparser_test\&.cc\fP"
.br
.RI "Test file for parsing sets and relations from an omega-like syntax\&. "
.in -1c
