.TH "lib/chill/omega/omega_lib/src Directory Reference" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBomega_core\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclosure\&.cc\fP"
.br
.ti -1c
.RI "file \fBevac\&.cc\fP"
.br
.ti -1c
.RI "file \fBfarkas\&.cc\fP"
.br
.ti -1c
.RI "file \fBhull\&.cc\fP"
.br
.ti -1c
.RI "file \fBhull_legacy\&.cc\fP"
.br
.ti -1c
.RI "file \fBhull_simple\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_beaut\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_cnstr\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_col\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_conj\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_decl\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_dnf\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_form\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_gen\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_logic\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_print\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_quant\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_rear\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_subs\&.cc\fP"
.br
.ti -1c
.RI "file \fBpres_var\&.cc\fP"
.br
.ti -1c
.RI "file \fBreach\&.cc\fP"
.br
.ti -1c
.RI "file \fBRelation\&.cc\fP"
.br
.ti -1c
.RI "file \fBRelations\&.cc\fP"
.br
.ti -1c
.RI "file \fBRelBody\&.cc\fP"
.br
.ti -1c
.RI "file \fBRelVar\&.cc\fP"
.br
.in -1c
