.TH "scripts Directory Reference" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcodegen\fP"
.br
.ti -1c
.RI "directory \fBiegenlib\fP"
.br
.ti -1c
.RI "directory \fBpdfg\fP"
.br
.ti -1c
.RI "directory \fBtools\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbackprop\&.py\fP"
.br
.ti -1c
.RI "file \fBcg_parse\&.py\fP"
.br
.ti -1c
.RI "file \fBchartgen\&.py\fP"
.br
.ti -1c
.RI "file \fBgraph2isl\&.py\fP"
.br
.ti -1c
.RI "file \fBiegen_test\&.py\fP"
.br
.ti -1c
.RI "file \fBiegen_to_omega\&.py\fP"
.br
.ti -1c
.RI "file \fBislcodegen\&.py\fP"
.br
.ti -1c
.RI "file \fBislextract\&.py\fP"
.br
.ti -1c
.RI "file \fBllvm_test\&.py\fP"
.br
.ti -1c
.RI "file \fBmfd\-graph\-dot\&.py\fP"
.br
.ti -1c
.RI "file \fBpdfgcomp\&.py\fP"
.br
.ti -1c
.RI "file \fBperfmodel\&.py\fP"
.br
.ti -1c
.RI "file \fBtftest\&.py\fP"
.br
.in -1c
