.TH "lib/chill/omega/omega_lib/include Directory Reference" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBomega\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBomega\&.h\fP"
.br
.in -1c
