.TH "lib/chill Directory Reference" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBomega\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcalculator_eval\&.cc\fP"
.br
.ti -1c
.RI "file \fBchill_ast\&.cc\fP"
.br
.ti -1c
.RI "file \fBchill_ast\&.hh\fP"
.br
.ti -1c
.RI "file \fBchill_error\&.hh\fP"
.br
.RI "CHiLL runtime exceptions\&. "
.ti -1c
.RI "file \fBchill_io\&.cc\fP"
.br
.ti -1c
.RI "file \fBchill_io\&.hh\fP"
.br
.ti -1c
.RI "file \fBchill_run\&.cc\fP"
.br
.ti -1c
.RI "file \fBchill_run_util\&.cc\fP"
.br
.ti -1c
.RI "file \fBchill_run_util\&.hh\fP"
.br
.ti -1c
.RI "file \fBchillmodule\&.cc\fP"
.br
.ti -1c
.RI "file \fBchillmodule\&.hh\fP"
.br
.RI "chill interface to python "
.ti -1c
.RI "file \fBcudaize_codegen_v2\&.cc\fP"
.br
.ti -1c
.RI "file \fBcudaize_codegen_v2_helper_funcs\&.cc\fP"
.br
.ti -1c
.RI "file \fBdep\&.cc\fP"
.br
.ti -1c
.RI "file \fBdep\&.hh\fP"
.br
.RI "Data dependence vector and graph\&. "
.ti -1c
.RI "file \fBir_chill\&.cc\fP"
.br
.ti -1c
.RI "file \fBir_chill\&.hh\fP"
.br
.ti -1c
.RI "file \fBir_code\&.hh\fP"
.br
.RI "CHiLL's compiler intermediate representation interface that extends Omega's builder interface to accomodate compiler analyses and extra code generation\&. "
.ti -1c
.RI "file \fBir_cudachill\&.cc\fP"
.br
.ti -1c
.RI "file \fBir_cudachill\&.hh\fP"
.br
.ti -1c
.RI "file \fBir_enums\&.hh\fP"
.br
.ti -1c
.RI "file \fBirtools\&.cc\fP"
.br
.ti -1c
.RI "file \fBirtools\&.hh\fP"
.br
.RI "Useful tools to analyze code in compiler IR format\&. "
.ti -1c
.RI "file \fBloop\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop\&.hh\fP"
.br
.RI "Core loop transformation functionality\&. "
.ti -1c
.RI "file \fBloop_basic\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop_cuda\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop_cuda_chill\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop_cuda_chill\&.hh\fP"
.br
.ti -1c
.RI "file \fBloop_extra\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop_ghostcells\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop_omp\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop_sparse\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop_stencil\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop_tile\&.cc\fP"
.br
.ti -1c
.RI "file \fBloop_unroll\&.cc\fP"
.br
.ti -1c
.RI "file \fBmem_mapping_utils\&.cc\fP"
.br
.ti -1c
.RI "file \fBmem_mapping_utils\&.hh\fP"
.br
.ti -1c
.RI "file \fBomegatools\&.cc\fP"
.br
.ti -1c
.RI "file \fBomegatools\&.hh\fP"
.br
.ti -1c
.RI "file \fBstencil\&.cc\fP"
.br
.ti -1c
.RI "file \fBstencil\&.hh\fP"
.br
.in -1c
