.TH "_MiniFluxDivData" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_MiniFluxDivData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <miniFluxDiv\-fuseAllCLOReduxOverlap\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnumCell\fP"
.br
.ti -1c
.RI "int \fBnumBox\fP"
.br
.ti -1c
.RI "int \fBnumComp\fP"
.br
.ti -1c
.RI "int \fBnThreads\fP"
.br
.ti -1c
.RI "int \fBnGhost\fP"
.br
.ti -1c
.RI "int \fBfullNumCell\fP"
.br
.ti -1c
.RI "int \fBfullNumCell2\fP"
.br
.ti -1c
.RI "int \fBfullNumCell3\fP"
.br
.ti -1c
.RI "int \fBnumberOfCaches\fP"
.br
.ti -1c
.RI "int * \fBsizeOfCaches\fP"
.br
.ti -1c
.RI "double \fBinnerTime\fP"
.br
.ti -1c
.RI "\fBReal\fP *** \fBlocations\fP"
.br
.ti -1c
.RI "\fBReal\fP ** \fBg_caches\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int _MiniFluxDivData::fullNumCell"

.SS "int _MiniFluxDivData::fullNumCell2"

.SS "int _MiniFluxDivData::fullNumCell3"

.SS "\fBReal\fP** _MiniFluxDivData::g_caches"

.SS "double _MiniFluxDivData::innerTime"

.SS "\fBReal\fP *** _MiniFluxDivData::locations"

.SS "int _MiniFluxDivData::nGhost"

.SS "int _MiniFluxDivData::nThreads"

.SS "int _MiniFluxDivData::numberOfCaches"

.SS "int _MiniFluxDivData::numBox"

.SS "int _MiniFluxDivData::numCell"

.SS "int _MiniFluxDivData::numComp"

.SS "int * _MiniFluxDivData::sizeOfCaches"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
