.TH "a_list" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
a_list
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBcol_\fP"
.br
.ti -1c
.RI "float \fBa\fP [(\fBR\fP *\fBC\fP)]"
.br
.ti -1c
.RI "struct \fBa_list\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float a_list::a[(\fBR\fP *\fBC\fP)]"

.SS "unsigned short a_list::col_"

.SS "struct \fBa_list\fP* a_list::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
