.TH "AST" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AST
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AST\&.hh>\fP
.PP
Inherited by \fBAST_And\fP, \fBAST_constraints\fP, \fBAST_declare\fP, \fBAST_Not\fP, and \fBAST_Or\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinstall\fP (\fBomega::Formula\fP *F)=0"
.br
.ti -1c
.RI "virtual void \fBprint\fP ()=0"
.br
.ti -1c
.RI "virtual \fB~AST\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual AST::~AST ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void AST::install (\fBomega::Formula\fP * F)\fC [pure virtual]\fP"

.PP
Implemented in \fBAST_declare\fP, \fBAST_constraints\fP, \fBAST_forall\fP, \fBAST_exists\fP, \fBAST_Not\fP, \fBAST_Or\fP, and \fBAST_And\fP\&.
.SS "virtual void AST::print ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAST_constraints\fP, \fBAST_forall\fP, \fBAST_exists\fP, \fBAST_declare\fP, \fBAST_Not\fP, \fBAST_Or\fP, and \fBAST_And\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
