.TH "AST_forall" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AST_forall
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AST\&.hh>\fP
.PP
Inherits \fBAST_declare\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAST_forall\fP (\fBDeclaration_Site\fP *dV, \fBAST\fP *\fBc\fP)"
.br
.ti -1c
.RI "\fB~AST_forall\fP ()"
.br
.ti -1c
.RI "virtual void \fBinstall\fP (\fBomega::Formula\fP *F)"
.br
.ti -1c
.RI "virtual void \fBprint\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AST_forall::AST_forall (\fBDeclaration_Site\fP * dV, \fBAST\fP * c)\fC [inline]\fP"

.SS "AST_forall::~AST_forall ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void AST_forall::install (\fBomega::Formula\fP * F)\fC [virtual]\fP"

.PP
Implements \fBAST_declare\fP\&.
.SS "virtual void AST_forall::print ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBAST_declare\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
