.TH "ast.Operator" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast.Operator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBast\&.Node\fP\&.
.PP
Inherited by \fBast\&.BinaryOper\fP, \fBast\&.CompoundAssignOper\fP, and \fBast\&.UnaryOper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBvalue\fP='', \fBstart\fP=(0, 0), \fBend\fP=(0, 0), \fBlevel\fP=0, \fBlabel\fP='\fBOperator\fP')"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ast\&.Operator\&.__init__ ( self,  value = \fC''\fP,  start = \fC(0,0)\fP,  end = \fC(0,0)\fP,  level = \fC0\fP,  label = \fC'\fBOperator\fP'\fP)"

.PP
Reimplemented from \fBast\&.Node\fP\&.
.PP
Reimplemented in \fBast\&.UnaryOper\fP, \fBast\&.CompoundAssignOper\fP, and \fBast\&.BinaryOper\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
