.TH "AST_Or" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AST_Or
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AST\&.hh>\fP
.PP
Inherits \fBAST\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAST_Or\fP (\fBAST\fP *l, \fBAST\fP *r)"
.br
.ti -1c
.RI "\fB~AST_Or\fP ()"
.br
.ti -1c
.RI "virtual void \fBinstall\fP (\fBomega::Formula\fP *F)"
.br
.ti -1c
.RI "virtual void \fBprint\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAST\fP * \fBleft\fP"
.br
.ti -1c
.RI "\fBAST\fP * \fBright\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AST_Or::AST_Or (\fBAST\fP * l, \fBAST\fP * r)\fC [inline]\fP"

.SS "AST_Or::~AST_Or ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void AST_Or::install (\fBomega::Formula\fP * F)\fC [virtual]\fP"

.PP
Implements \fBAST\fP\&.
.SS "virtual void AST_Or::print ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBAST\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAST\fP* AST_Or::left"

.SS "\fBAST\fP * AST_Or::right"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
