.TH "ast.Statement" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast.Statement
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBast\&.Node\fP\&.
.PP
Inherited by \fBast\&.CompoundStmt\fP, \fBast\&.DeclStmt\fP, \fBast\&.ForStmt\fP, \fBast\&.IfStmt\fP, \fBast\&.LabelStmt\fP, \fBast\&.NullStmt\fP, and \fBast\&.ReturnStmt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBvalue\fP='', \fBstart\fP=(0, 0), \fBend\fP=(0, 0), \fBlevel\fP=0, \fBlabel\fP='\fBStatement\fP')"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ast\&.Statement\&.__init__ ( self,  value = \fC''\fP,  start = \fC(0,0)\fP,  end = \fC(0,0)\fP,  level = \fC0\fP,  label = \fC'\fBStatement\fP'\fP)"

.PP
Reimplemented from \fBast\&.Node\fP\&.
.PP
Reimplemented in \fBast\&.ReturnStmt\fP, \fBast\&.NullStmt\fP, \fBast\&.LabelStmt\fP, \fBast\&.IfStmt\fP, \fBast\&.ForStmt\fP, \fBast\&.DeclStmt\fP, and \fBast\&.CompoundStmt\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
