.TH "ast.Constructor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast.Constructor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBast\&.Method\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBvalue\fP='', \fBstart\fP=(0, 0), \fBend\fP=(0, 0), \fBlevel\fP=0, \fBlabel\fP='\fBConstructor\fP')"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ast\&.Constructor\&.__init__ ( self,  value = \fC''\fP,  start = \fC(0,0)\fP,  end = \fC(0,0)\fP,  level = \fC0\fP,  label = \fC'\fBConstructor\fP'\fP)"

.PP
Reimplemented from \fBast\&.Method\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
