.TH "ast::Exp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ast::Exp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AST\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExp\fP (\fBomega::coef_t\fP \fBc\fP)"
.br
.ti -1c
.RI "\fBExp\fP (\fBVariable_Ref\fP *v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::map\fP< \fBVariable_Ref\fP *, \fBomega::coef_t\fP > \fBcoefs\fP"
.br
.ti -1c
.RI "\fBomega::coef_t\fP \fBconstantTerm\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddTerm\fP (\fBomega::coef_t\fP coef, \fBomega::Variable_ID\fP v)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ast::Exp::Exp (\fBomega::coef_t\fP c)"

.SS "ast::Exp::Exp (\fBVariable_Ref\fP * v)"

.SH "Member Function Documentation"
.PP 
.SS "void ast::Exp::addTerm (\fBomega::coef_t\fP coef, \fBomega::Variable_ID\fP v)\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::map\fP<\fBVariable_Ref\fP *, \fBomega::coef_t\fP> ast::Exp::coefs"

.SS "\fBomega::coef_t\fP ast::Exp::constantTerm"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
