.TH "lib/isl/include/isl/deprecated/ast_int.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/deprecated/ast_int.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/deprecated/int\&.h>\fP
.br
\fC#include <isl/ast\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_ast_expr_get_int\fP (\fB__isl_keep\fP \fBisl_ast_expr\fP *expr, \fBisl_int\fP *v)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isl_ast_expr_get_int (\fB__isl_keep\fP \fBisl_ast_expr\fP * expr, \fBisl_int\fP * v)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
