.TH "backprop" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backprop
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsigmoid\fP (\fBx\fP)"
.br
.ti -1c
.RI "def \fBsigmoid_prime\fP (\fBx\fP)"
.br
.ti -1c
.RI "def \fBcost\fP (y_hat, \fBy\fP)"
.br
.ti -1c
.RI "def \fBinitialize_parameters\fP ()"
.br
.ti -1c
.RI "def \fBforward_propagation\fP (\fBX\fP, initialize=True)"
.br
.ti -1c
.RI "def \fBback_propagation\fP (\fBX\fP, \fBy\fP, initialize=True, debug=False, verbose=False)"
.br
.ti -1c
.RI "def \fBbackprop_test\fP ()"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBLAYERS\fP = [2, 2, 2, 1]"
.br
.ti -1c
.RI "int \fBETA\fP = \&.1"
.br
.ti -1c
.RI "list \fBTHETA\fP = []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def backprop\&.back_propagation ( X,  y,  initialize = \fCTrue\fP,  debug = \fCFalse\fP,  verbose = \fCFalse\fP)"

.SS "def backprop\&.backprop_test ()"

.SS "def backprop\&.cost ( y_hat,  y)"

.SS "def backprop\&.forward_propagation ( X,  initialize = \fCTrue\fP)"

.SS "def backprop\&.initialize_parameters ()"

.SS "def backprop\&.main ()"

.SS "def backprop\&.sigmoid ( x)"

.SS "def backprop\&.sigmoid_prime ( x)"

.SH "Variable Documentation"
.PP 
.SS "int backprop\&.ETA = \&.1"

.SS "list backprop\&.LAYERS = [2, 2, 2, 1]"

.SS "list backprop\&.THETA = []"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
