.TH "lib/chill/omega/basic/include/basic/Bag.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/basic/include/basic/Bag.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <basic/Iterator\&.h>\fP
.br
\fC#include <basic/Collection\&.h>\fP
.br
\fC#include <basic/Link\&.h>\fP
.br
\fC#include <basic/Bag\&.c>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::Bag< T >\fP"
.br
.ti -1c
.RI "class \fBomega::Ordered_Bag< T >\fP"
.br
.ti -1c
.RI "class \fBomega::Set< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBinstantiate_Bag\fP(\fBT\fP)"
.br
.ti -1c
.RI "#define \fBinstantiate_Ordered_Bag\fP(\fBT\fP)"
.br
.ti -1c
.RI "#define \fBinstantiate_Set\fP(\fBT\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define instantiate_Bag(\fBT\fP)"
\fBValue:\fP
.PP
.nf
                    template class Bag<T>; \
                    instantiate_List_Element(T);
.fi
.SS "#define instantiate_Ordered_Bag(\fBT\fP)"
\fBValue:\fP
.PP
.nf
                  template class Ordered_Bag<T>; \
                    instantiate_Bag(T)
.fi
.SS "#define instantiate_Set(\fBT\fP)"
\fBValue:\fP
.PP
.nf
                  template class Set<T>; \
                    instantiate_Ordered_Bag(T)
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
