.TH "bases" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bases
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmp\-impl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBchars_per_limb\fP"
.br
.ti -1c
.RI "\fBmp_limb_t\fP \fBlogb2\fP"
.br
.ti -1c
.RI "\fBmp_limb_t\fP \fBlog2b\fP"
.br
.ti -1c
.RI "\fBmp_limb_t\fP \fBbig_base\fP"
.br
.ti -1c
.RI "\fBmp_limb_t\fP \fBbig_base_inverted\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmp_limb_t\fP bases::big_base"

.SS "\fBmp_limb_t\fP bases::big_base_inverted"

.SS "int bases::chars_per_limb"

.SS "\fBmp_limb_t\fP bases::log2b"

.SS "\fBmp_limb_t\fP bases::logb2"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
