.TH "lib/isl/basis_reduction_templ.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/basis_reduction_templ.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <isl_ctx_private\&.h>\fP
.br
\fC#include <isl_map_private\&.h>\fP
.br
\fC#include <isl_vec_private\&.h>\fP
.br
\fC#include <isl_options_private\&.h>\fP
.br
\fC#include 'isl_basis_reduction\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBisl_tab\fP * \fBisl_tab_compute_reduced_basis\fP (struct \fBisl_tab\fP *tab)"
.br
.ti -1c
.RI "struct \fBisl_mat\fP * \fBisl_basic_set_reduced_basis\fP (struct \fBisl_basic_set\fP *bset)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBisl_mat\fP* isl_basic_set_reduced_basis (struct \fBisl_basic_set\fP * bset)"

.SS "struct \fBisl_tab\fP* isl_tab_compute_reduced_basis (struct \fBisl_tab\fP * tab)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
