.TH "test/BenchmarkTest.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/BenchmarkTest.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <initializer_list>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <util/LIKWID\&.hpp>\fP
.br
\fC#include <util/Strings\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest::BenchmarkTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtest\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBomp_get_thread_num\fP()   0"
.br
.ti -1c
.RI "#define \fBomp_get_max_threads\fP()   1"
.br
.ti -1c
.RI "#define \fBomp_get_num_threads\fP()   1"
.br
.ti -1c
.RI "#define \fBomp_set_num_threads\fP(\fBn\fP)   \fBn\fP=\fBn\fP"
.br
.ti -1c
.RI "#define \fBEPSILON\fP   1E\-6"
.br
.ti -1c
.RI "#define \fBGTEST_COUT\fP   cout << '[   INFO   ] '"
.br
.ti -1c
.RI "#define \fBGTEST_CERR\fP   cerr << '[  ERROR   ] '"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EPSILON   1E\-6"

.SS "#define GTEST_CERR   cerr << '[  ERROR   ] '"

.SS "#define GTEST_COUT   cout << '[   INFO   ] '"

.SS "#define omp_get_max_threads()   1"

.SS "#define omp_get_num_threads()   1"

.SS "#define omp_get_thread_num()   0"

.SS "#define omp_set_num_threads(\fBn\fP)   \fBn\fP=\fBn\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
