.TH "lib/chill/omega/basic/include/basic/boolset-test.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/basic/include/basic/boolset-test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'boolset\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfoo\fP (\fBconst\fP \fBBoolSet\fP<> &\fBB\fP)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void foo (\fBconst\fP \fBBoolSet\fP<> & B)"

.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
