.TH "bsr_data_t" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bsr_data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBR\fP"
.br
.ti -1c
.RI "int \fBC\fP"
.br
.ti -1c
.RI "int \fBN_R\fP"
.br
.ti -1c
.RI "int \fBN_C\fP"
.br
.ti -1c
.RI "\fBitype\fP * \fBbset\fP"
.br
.ti -1c
.RI "\fBitype\fP \fBnb\fP"
.br
.ti -1c
.RI "\fBitype\fP * \fBb_col\fP"
.br
.ti -1c
.RI "\fBitype\fP * \fBb_index\fP"
.br
.ti -1c
.RI "\fBreal\fP * \fBA_prime\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBreal\fP* bsr_data_t::A_prime"

.SS "\fBitype\fP* bsr_data_t::b_col"

.SS "\fBitype\fP* bsr_data_t::b_index"

.SS "\fBitype\fP* bsr_data_t::bset"

.SS "int bsr_data_t::C"

.SS "int bsr_data_t::N_C"

.SS "int bsr_data_t::N_R"

.SS "\fBitype\fP bsr_data_t::nb"

.SS "int bsr_data_t::R"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
