.TH "lib/chill/omega/code_gen/src/CG.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/code_gen/src/CG.cc
.SH SYNOPSIS
.br
.PP
\fC#include <typeinfo>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <omega\&.h>\fP
.br
\fC#include <omega/code_gen/include/codegen\&.h>\fP
.br
\fC#include <code_gen/CG\&.h>\fP
.br
\fC#include <code_gen/CG_outputBuilder\&.h>\fP
.br
\fC#include <code_gen/CG_stringBuilder\&.h>\fP
.br
\fC#include <code_gen/CG_utils\&.h>\fP
.br
\fC#include <code_gen/codegen_error\&.h>\fP
.br
\fC#include <stack>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDYINGHERE\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::vector< std::vector< int > > \fBomega::smtNonSplitLevels\fP"
.br
.ti -1c
.RI "std::vector< std::vector< std::string > > \fBomega::loopIdxNames\fP"
.br
.ti -1c
.RI "std::vector< std::pair< int, std::string > > \fBomega::syncs\fP"
.br
.ti -1c
.RI "bool \fBomega::fillInBounds\fP = false"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DYINGHERE"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
