.TH "lib/chill/omega/code_gen/include/code_gen/CG.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/code_gen/include/code_gen/CG.h
.SH SYNOPSIS
.br
.PP
\fC#include <omega/Relation\&.h>\fP
.br
\fC#include <basic/boolset\&.h>\fP
.br
\fC#include <code_gen/CG_outputBuilder\&.h>\fP
.br
\fC#include <set>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBomega::CG_result\fP"
.br
.RI "Tree-like structure holding the iteration space\&. "
.ti -1c
.RI "struct \fBomega::CG_split\fP"
.br
.RI "\fBStatement\fP sequence\&. "
.ti -1c
.RI "struct \fBomega::CG_loop\fP"
.br
.RI "\fBLoop\fP\&. "
.ti -1c
.RI "struct \fBomega::CG_leaf\fP"
.br
.RI "Leaf - a basic code block\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
