.TH "test/cg_par.cpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/cg_par.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <omp\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <util/LIKWID\&.hpp>\fP
.br
\fC#include <util/MatrixIO\&.hpp>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <Eigen/Sparse>\fP
.br
\fC#include <Eigen/SparseExtra>\fP
.br
\fC#include <Eigen/IterativeLinearSolvers>\fP
.br
\fC#include 'coo_csr_insp\&.h'\fP
.br
\fC#include 'coo_dsr_insp\&.h'\fP
.br
\fC#include 'coo_ell_insp\&.h'\fP
.br
\fC#include 'coo_ellmap_insp\&.h'\fP
.br
\fC#include 'coo_csb_insp\&.h'\fP
.br
\fC#include 'coo_dia_insp\&.h'\fP
.br
\fC#include 'conjgrad_coo\&.h'\fP
.br
\fC#include 'conjgrad_csr\&.h'\fP
.br
\fC#include 'conjgrad_dsr\&.h'\fP
.br
\fC#include 'conjgrad_ell\&.h'\fP
.br
\fC#include 'conjgrad_ellmap\&.h'\fP
.br
\fC#include 'conjgrad_csb\&.h'\fP
.br
\fC#include 'conjgrad_dia\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Eigen::Triplet< double > \fBTriple\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBget_wtime\fP ()"
.br
.ti -1c
.RI "void \fBsetup\fP (\fBconst\fP char *matrix, unsigned *nnz, unsigned *nrow, unsigned *ncol, unsigned *maxiter, unsigned **rows, unsigned **cols, double *__restrict *vals, double *__restrict *\fBx\fP, double *__restrict *\fBb\fP, SparseMatrix< double > &Aspm, VectorXd &xVec, VectorXd &bVec)"
.br
.ti -1c
.RI "void \fBteardown\fP (unsigned **rows, unsigned **cols, double *__restrict *vals, double *__restrict *\fBx\fP, double *__restrict *\fBb\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef Eigen::Triplet<double> \fBTriple\fP"

.SH "Function Documentation"
.PP 
.SS "double get_wtime ()"

.SS "int main (int argc, char ** argv)"

.SS "void setup (\fBconst\fP char * matrix, unsigned * nnz, unsigned * nrow, unsigned * ncol, unsigned * maxiter, unsigned ** rows, unsigned ** cols, double *__restrict * vals, double *__restrict * x, double *__restrict * b, SparseMatrix< double > & Aspm, VectorXd & xVec, VectorXd & bVec)"

.SS "void teardown (unsigned ** rows, unsigned ** cols, double *__restrict * vals, double *__restrict * x, double *__restrict * b)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
