.TH "scripts/cg_parse.py" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/cg_parse.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcg_parse\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcg_parse\&.usage\fP ()"
.br
.ti -1c
.RI "def \fBcg_parse\&.command\fP (cmd)"
.br
.ti -1c
.RI "def \fBcg_parse\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
