.TH "cg_parse" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cg_parse
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBusage\fP ()"
.br
.ti -1c
.RI "def \fBcommand\fP (cmd)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def cg_parse\&.command ( cmd)"

.SS "def cg_parse\&.main ()"

.SS "def cg_parse\&.usage ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
