.TH "lib/chill/omega/code_gen/include/code_gen/CG_roseBuilder.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/code_gen/include/code_gen/CG_roseBuilder.h
.SH SYNOPSIS
.br
.PP
\fC#include <basic/Tuple\&.h>\fP
.br
\fC#include <code_gen/rose_attributes\&.h>\fP
.br
\fC#include <code_gen/CG_outputBuilder\&.h>\fP
.br
\fC#include <code_gen/CG_roseRepr\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::CG_roseBuilder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< SgVarRefExp * > \fBomega::substitute\fP (SgNode *tnl, \fBconst\fP SgVariableSymbol *sym, SgExpression *expr, SgNode *root)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBomega::k_ocg_comment\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
