.TH "lib/chill/chillmodule.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/chillmodule.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'chill_io\&.hh'\fP
.br
\fC#include 'parser/clang\&.h'\fP
.br
\fC#include 'parser/rose\&.h'\fP
.br
\fC#include 'chillmodule\&.hh'\fP
.br
\fC#include 'chill_run_util\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_loop_num_start\fP ()"
.br
.ti -1c
.RI "int \fBget_loop_num_end\fP ()"
.br
.ti -1c
.RI "void \fBfinalize_loop\fP (int loop_num_start, int loop_num_end)"
.br
.ti -1c
.RI "void \fBfinalize_loop\fP ()"
.br
.ti -1c
.RI "PyMODINIT_FUNC \fBinitchill\fP (void)"
.br
.RI "pass C methods to python "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBloop_t\fP * \fBmyloop\fP = nullptr"
.br
.ti -1c
.RI "\fBIR_Code\fP * \fBir_code\fP = nullptr"
.br
.ti -1c
.RI "bool \fBis_interactive\fP = false"
.br
.ti -1c
.RI "std::string \fBprocedure_name\fP"
.br
.ti -1c
.RI "std::string \fBsource_filename\fP"
.br
.ti -1c
.RI "int \fBloop_start_num\fP"
.br
.ti -1c
.RI "int \fBloop_end_num\fP"
.br
.ti -1c
.RI "std::string \fBdest_filename\fP"
.br
.ti -1c
.RI "std::vector< \fBIR_Control\fP * > \fBir_controls\fP"
.br
.ti -1c
.RI "std::vector< int > \fBloops\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void finalize_loop ()"

.SS "void finalize_loop (int loop_num_start, int loop_num_end)"

.SS "int get_loop_num_end ()"

.SS "int get_loop_num_start ()"

.SS "PyMODINIT_FUNC initchill (void)"

.PP
pass C methods to python 
.SH "Variable Documentation"
.PP 
.SS "std::string dest_filename"

.SS "\fBIR_Code\fP* ir_code = nullptr"

.SS "std::vector<\fBIR_Control\fP *> ir_controls"

.SS "bool is_interactive = false"

.SS "int loop_end_num"

.SS "int loop_start_num"

.SS "std::vector<int> loops"

.SS "\fBloop_t\fP* myloop = nullptr"

.SS "std::string procedure_name"

.SS "std::string source_filename"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
