.TH "lib/chill/chillmodule.hh" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/chillmodule.hh \- chill interface to python  

.SH SYNOPSIS
.br
.PP
\fC#include <Python\&.h>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include 'loop\&.hh'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBLoop\fP \fBloop_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfinalize_loop\fP (int loop_num_start, int loop_num_end)"
.br
.ti -1c
.RI "int \fBget_loop_num_start\fP ()"
.br
.ti -1c
.RI "int \fBget_loop_num_end\fP ()"
.br
.ti -1c
.RI "PyMODINIT_FUNC \fBinitchill\fP ()"
.br
.RI "pass C methods to python "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBloop_t\fP * \fBmyloop\fP"
.br
.ti -1c
.RI "\fBIR_Code\fP * \fBir_code\fP"
.br
.ti -1c
.RI "bool \fBis_interactive\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
chill interface to python 


.SH "Typedef Documentation"
.PP 
.SS "typedef \fBLoop\fP \fBloop_t\fP"

.SH "Function Documentation"
.PP 
.SS "void finalize_loop (int loop_num_start, int loop_num_end)"

.SS "int get_loop_num_end ()"

.SS "int get_loop_num_start ()"

.SS "PyMODINIT_FUNC initchill ()"

.PP
pass C methods to python 
.SH "Variable Documentation"
.PP 
.SS "\fBIR_Code\fP* ir_code"

.SS "bool is_interactive"

.SS "\fBloop_t\fP* myloop"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
