.TH "chillAST_TypedefDecl" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chillAST_TypedefDecl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chill_ast\&.hh>\fP
.PP
Inherits \fBchillAST_node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetStructInfo\fP (\fBchillAST_RecordDecl\fP *arrdee)"
.br
.ti -1c
.RI "\fBchillAST_RecordDecl\fP * \fBgetStructDef\fP ()"
.br
.ti -1c
.RI "bool \fBisAStruct\fP () override"
.br
.ti -1c
.RI "bool \fBisAUnion\fP () override"
.br
.ti -1c
.RI "void \fBsetStruct\fP (bool tf)"
.br
.ti -1c
.RI "void \fBsetUnion\fP (bool tf)"
.br
.ti -1c
.RI "void \fBsetStructName\fP (\fBconst\fP char *newname)"
.br
.ti -1c
.RI "char * \fBgetStructName\fP ()"
.br
.ti -1c
.RI "bool \fBnameis\fP (\fBconst\fP char *\fBn\fP)"
.br
.ti -1c
.RI "\fBchillAST_VarDecl\fP * \fBfindSubpart\fP (\fBconst\fP char *\fBname\fP)"
.br
.ti -1c
.RI "\fBchillAST_TypedefDecl\fP ()"
.br
.ti -1c
.RI "\fBchillAST_TypedefDecl\fP (\fBconst\fP char *\fBt\fP, \fBconst\fP char *nt)"
.br
.ti -1c
.RI "\fBchillAST_TypedefDecl\fP (\fBconst\fP char *\fBt\fP, \fBconst\fP char *nt, \fBconst\fP char *\fBa\fP)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBgetUnderlyingType\fP () override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBnewtype\fP"
.br
.ti -1c
.RI "char * \fBunderlyingtype\fP"
.br
.ti -1c
.RI "char * \fBarraypart\fP"
.br
.ti -1c
.RI "\fBchillAST_RecordDecl\fP * \fBrd\fP"
.br
.ti -1c
.RI "vector< \fBchillAST_VarDecl\fP * > \fBsubparts\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "chillAST_TypedefDecl::chillAST_TypedefDecl ()"

.SS "chillAST_TypedefDecl::chillAST_TypedefDecl (\fBconst\fP char * t, \fBconst\fP char * nt)"

.SS "chillAST_TypedefDecl::chillAST_TypedefDecl (\fBconst\fP char * t, \fBconst\fP char * nt, \fBconst\fP char * a)"

.SH "Member Function Documentation"
.PP 
.SS "\fBchillAST_VarDecl\fP * chillAST_TypedefDecl::findSubpart (\fBconst\fP char * name)"

.SS "\fBchillAST_RecordDecl\fP * chillAST_TypedefDecl::getStructDef ()"

.SS "char* chillAST_TypedefDecl::getStructName ()\fC [inline]\fP"

.SS "\fBconst\fP char* chillAST_TypedefDecl::getUnderlyingType ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "bool chillAST_TypedefDecl::isAStruct ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "bool chillAST_TypedefDecl::isAUnion ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "bool chillAST_TypedefDecl::nameis (\fBconst\fP char * n)\fC [inline]\fP"

.SS "void chillAST_TypedefDecl::setStruct (bool tf)\fC [inline]\fP"

.SS "void chillAST_TypedefDecl::setStructInfo (\fBchillAST_RecordDecl\fP * arrdee)\fC [inline]\fP"

.SS "void chillAST_TypedefDecl::setStructName (\fBconst\fP char * newname)\fC [inline]\fP"

.SS "void chillAST_TypedefDecl::setUnion (bool tf)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char* chillAST_TypedefDecl::arraypart"

.SS "char* chillAST_TypedefDecl::newtype"

.SS "\fBchillAST_RecordDecl\fP* chillAST_TypedefDecl::rd"

.SS "vector<\fBchillAST_VarDecl\fP *> chillAST_TypedefDecl::subparts"

.SS "char* chillAST_TypedefDecl::underlyingtype"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
