.TH "chillAST_FloatingLiteral" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chillAST_FloatingLiteral
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chill_ast\&.hh>\fP
.PP
Inherits \fBchillAST_node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCHILL_ASTNODE_TYPE\fP \fBgetType\fP () override"
.br
.ti -1c
.RI "\fBchillAST_FloatingLiteral\fP (float \fBval\fP)"
.br
.ti -1c
.RI "\fBchillAST_FloatingLiteral\fP (double \fBval\fP)"
.br
.ti -1c
.RI "\fBchillAST_FloatingLiteral\fP (double \fBval\fP, int pre)"
.br
.ti -1c
.RI "\fBchillAST_FloatingLiteral\fP (double \fBval\fP, \fBconst\fP char *printable)"
.br
.ti -1c
.RI "\fBchillAST_FloatingLiteral\fP (double \fBval\fP, int pre, \fBconst\fP char *printable)"
.br
.ti -1c
.RI "\fBchillAST_FloatingLiteral\fP (\fBchillAST_FloatingLiteral\fP *old)"
.br
.ti -1c
.RI "void \fBsetPrecision\fP (int precis)"
.br
.ti -1c
.RI "int \fBgetPrecision\fP ()"
.br
.ti -1c
.RI "\fBchillAST_node\fP * \fBconstantFold\fP () override"
.br
.RI "Folding constant, to some degree\&. "
.ti -1c
.RI "\fBchillAST_node\fP * \fBclone\fP () override"
.br
.ti -1c
.RI "void \fBgatherArrayRefs\fP (std::vector< \fBchillAST_ArraySubscriptExpr\fP * > &refs, bool w) override"
.br
.ti -1c
.RI "void \fBgatherScalarRefs\fP (std::vector< \fBchillAST_DeclRefExpr\fP * > &refs, bool writtento) override"
.br
.ti -1c
.RI "void \fBgatherVarDecls\fP (vector< \fBchillAST_VarDecl\fP * > &decls) override"
.br
.RI "gather ACTUAL variable declarations "
.ti -1c
.RI "void \fBgatherVarDeclsMore\fP (vector< \fBchillAST_VarDecl\fP * > &decls) override"
.br
.ti -1c
.RI "void \fBgatherScalarVarDecls\fP (vector< \fBchillAST_VarDecl\fP * > &decls) override"
.br
.RI "gather ACTUAL scalar variable declarations "
.ti -1c
.RI "void \fBgatherArrayVarDecls\fP (vector< \fBchillAST_VarDecl\fP * > &decls) override"
.br
.RI "gather ACTUAL array variable declarations "
.ti -1c
.RI "void \fBgatherVarUsage\fP (vector< \fBchillAST_VarDecl\fP * > &decls) override"
.br
.ti -1c
.RI "void \fBgatherDeclRefExprs\fP (vector< \fBchillAST_DeclRefExpr\fP * > &refs) override"
.br
.RI "gather both scalar and array references "
.ti -1c
.RI "void \fBreplaceVarDecls\fP (\fBchillAST_VarDecl\fP *olddecl, \fBchillAST_VarDecl\fP *newdecl) override"
.br
.ti -1c
.RI "bool \fBfindLoopIndexesToReplace\fP (\fBchillAST_SymbolTable\fP *symtab, bool forcesync=false) override"
.br
.RI "this just looks for ForStmts with preferred index metacomment attached "
.ti -1c
.RI "bool \fBisSameAs\fP (\fBchillAST_node\fP *other) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "char * \fBallthedigits\fP"
.br
.ti -1c
.RI "int \fBprecision\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "chillAST_FloatingLiteral::chillAST_FloatingLiteral (float val)\fC [explicit]\fP"

.SS "chillAST_FloatingLiteral::chillAST_FloatingLiteral (double val)\fC [explicit]\fP"

.SS "chillAST_FloatingLiteral::chillAST_FloatingLiteral (double val, int pre)"

.SS "chillAST_FloatingLiteral::chillAST_FloatingLiteral (double val, \fBconst\fP char * printable)"

.SS "chillAST_FloatingLiteral::chillAST_FloatingLiteral (double val, int pre, \fBconst\fP char * printable)"

.SS "chillAST_FloatingLiteral::chillAST_FloatingLiteral (\fBchillAST_FloatingLiteral\fP * old)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBchillAST_node\fP * chillAST_FloatingLiteral::clone ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "\fBchillAST_node\fP * chillAST_FloatingLiteral::constantFold ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Folding constant, to some degree\&. We should need to delegate this to the backend compiler 
.PP
\fBReturns\fP
.RS 4
This node 
.RE
.PP

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "bool chillAST_FloatingLiteral::findLoopIndexesToReplace (\fBchillAST_SymbolTable\fP * symtab, bool forcesync = \fCfalse\fP)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
this just looks for ForStmts with preferred index metacomment attached 
.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::gatherArrayRefs (std::vector< \fBchillAST_ArraySubscriptExpr\fP * > & refs, bool w)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::gatherArrayVarDecls (vector< \fBchillAST_VarDecl\fP * > & decls)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
gather ACTUAL array variable declarations 
.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::gatherDeclRefExprs (vector< \fBchillAST_DeclRefExpr\fP * > & refs)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
gather both scalar and array references 
.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::gatherScalarRefs (std::vector< \fBchillAST_DeclRefExpr\fP * > & refs, bool writtento)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::gatherScalarVarDecls (vector< \fBchillAST_VarDecl\fP * > & decls)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
gather ACTUAL scalar variable declarations 
.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::gatherVarDecls (vector< \fBchillAST_VarDecl\fP * > & decls)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
gather ACTUAL variable declarations 
.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::gatherVarDeclsMore (vector< \fBchillAST_VarDecl\fP * > & decls)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::gatherVarUsage (vector< \fBchillAST_VarDecl\fP * > & decls)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "int chillAST_FloatingLiteral::getPrecision ()\fC [inline]\fP"

.SS "\fBCHILL_ASTNODE_TYPE\fP chillAST_FloatingLiteral::getType ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "bool chillAST_FloatingLiteral::isSameAs (\fBchillAST_node\fP * other)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::replaceVarDecls (\fBchillAST_VarDecl\fP * olddecl, \fBchillAST_VarDecl\fP * newdecl)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "void chillAST_FloatingLiteral::setPrecision (int precis)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char* chillAST_FloatingLiteral::allthedigits"

.SS "int chillAST_FloatingLiteral::precision"

.SS "double chillAST_FloatingLiteral::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
