.TH "lib/chill/chill_run.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/chill_run.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'chill_io\&.hh'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <argp\&.h>\fP
.br
\fC#include 'chillmodule\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
