.TH "chillAST_RecordDecl" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chillAST_RecordDecl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chill_ast\&.hh>\fP
.PP
Inherits \fBchillAST_node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBchillAST_RecordDecl\fP ()"
.br
.ti -1c
.RI "\fBchillAST_RecordDecl\fP (\fBconst\fP char *nam)"
.br
.ti -1c
.RI "\fBchillAST_RecordDecl\fP (\fBconst\fP char *nam, \fBconst\fP char *orig)"
.br
.ti -1c
.RI "void \fBsetName\fP (\fBconst\fP char *newname)"
.br
.ti -1c
.RI "char * \fBgetName\fP ()"
.br
.ti -1c
.RI "vector< \fBchillAST_VarDecl\fP * > & \fBgetSubparts\fP ()"
.br
.ti -1c
.RI "bool \fBisAUnion\fP () override"
.br
.ti -1c
.RI "bool \fBisAStruct\fP () override"
.br
.ti -1c
.RI "void \fBsetStruct\fP (bool tf)"
.br
.ti -1c
.RI "void \fBsetUnion\fP (bool tf)"
.br
.ti -1c
.RI "\fBchillAST_SymbolTable\fP * \fBaddVariableToSymbolTable\fP (\fBchillAST_VarDecl\fP *vd) override"
.br
.ti -1c
.RI "int \fBnumSubparts\fP ()"
.br
.ti -1c
.RI "void \fBaddSubpart\fP (\fBchillAST_VarDecl\fP *s)"
.br
.ti -1c
.RI "\fBchillAST_VarDecl\fP * \fBfindSubpart\fP (\fBconst\fP char *name)"
.br
.ti -1c
.RI "\fBchillAST_VarDecl\fP * \fBfindSubpartByType\fP (\fBconst\fP char *typ)"
.br
.ti -1c
.RI "void \fBprintStructure\fP (int indent=0, FILE *fp=stderr)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "chillAST_RecordDecl::chillAST_RecordDecl ()"

.SS "chillAST_RecordDecl::chillAST_RecordDecl (\fBconst\fP char * nam)\fC [explicit]\fP"

.SS "chillAST_RecordDecl::chillAST_RecordDecl (\fBconst\fP char * nam, \fBconst\fP char * orig)"

.SH "Member Function Documentation"
.PP 
.SS "void chillAST_RecordDecl::addSubpart (\fBchillAST_VarDecl\fP * s)\fC [inline]\fP"

.SS "\fBchillAST_SymbolTable\fP * chillAST_RecordDecl::addVariableToSymbolTable (\fBchillAST_VarDecl\fP * vd)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "\fBchillAST_VarDecl\fP * chillAST_RecordDecl::findSubpart (\fBconst\fP char * name)"

.SS "\fBchillAST_VarDecl\fP * chillAST_RecordDecl::findSubpartByType (\fBconst\fP char * typ)"

.SS "char* chillAST_RecordDecl::getName ()\fC [inline]\fP"

.SS "vector<\fBchillAST_VarDecl\fP *>& chillAST_RecordDecl::getSubparts ()\fC [inline]\fP"

.SS "bool chillAST_RecordDecl::isAStruct ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "bool chillAST_RecordDecl::isAUnion ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBchillAST_node\fP\&.
.SS "int chillAST_RecordDecl::numSubparts ()\fC [inline]\fP"

.SS "void chillAST_RecordDecl::printStructure (int indent = \fC0\fP, FILE * fp = \fCstderr\fP)"

.SS "void chillAST_RecordDecl::setName (\fBconst\fP char * newname)\fC [inline]\fP"

.SS "void chillAST_RecordDecl::setStruct (bool tf)\fC [inline]\fP"

.SS "void chillAST_RecordDecl::setUnion (bool tf)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
