.TH "client::createIdentifier" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client::createIdentifier
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateIdentifier\fP (std::vector< \fBCG_outputRepr\fP * > &code, std::vector< std::string > &code_string, std::string &string_ref, \fBCG_outputBuilder\fP &builder_, std::vector< std::string > &index_names)"
.br
.ti -1c
.RI "template<typename IteratorT > void \fBoperator()\fP (IteratorT, IteratorT) \fBconst\fP"
.br
.ti -1c
.RI "template<typename IteratorT > void \fBoperator()\fP (IteratorT) \fBconst\fP"
.br
.ti -1c
.RI "void \fBoperator()\fP (qi::unused_type, qi::unused_type, qi::unused_type) \fBconst\fP"
.br
.ti -1c
.RI "void \fBoperator()\fP (char &s, qi::unused_type, qi::unused_type) \fBconst\fP"
.br
.ti -1c
.RI "void \fBoperator()\fP (int &s, qi::unused_type, qi::unused_type) \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "client::createIdentifier::createIdentifier (std::vector< \fBCG_outputRepr\fP * > & code, std::vector< std::string > & code_string, std::string & string_ref, \fBCG_outputBuilder\fP & builder_, std::vector< std::string > & index_names)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void client::createIdentifier::operator() (char & s, qi::unused_type, qi::unused_type) const\fC [inline]\fP"

.SS "void client::createIdentifier::operator() (int & s, qi::unused_type, qi::unused_type) const\fC [inline]\fP"

.SS "template<typename IteratorT > void client::createIdentifier::operator() (IteratorT) const\fC [inline]\fP"

.SS "template<typename IteratorT > void client::createIdentifier::operator() (IteratorT, IteratorT) const\fC [inline]\fP"

.SS "void client::createIdentifier::operator() (qi::unused_type, qi::unused_type, qi::unused_type) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
