.TH "CMakeLists-r2.txt" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeLists-r2.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcmake_minimum_required\fP (\fBVERSION\fP 3\&.9) project(edsl \fBC\fP CXX) \fBset\fP(CMAKE_C_COMPILER/cm/local/apps/gcc/7\&.2\&.0/bin/gcc) \fBset\fP(CMAKE_CXX_COMPILER/cm/local/apps/gcc/7\&.2\&.0/bin/g++) \fBset\fP(CMAKE_CXX_STANDARD 11) \fBset\fP(CMAKE_CXX_FLAGS '$"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "cmake_minimum_required (\fBVERSION\fP 3\&. 9)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
