.TH "src/pdfg/Codegen.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pdfg/Codegen.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <poly/PolyLib\&.hpp>\fP
.br
\fC#include <pdfg/GraphIL\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpdfg::Codegen\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpdfg\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPOLYEXT_CODEGEN_HPP\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define POLYEXT_CODEGEN_HPP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
