.TH "lib/chill/omega/code_gen/src/code_gen.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/code_gen/src/code_gen.cc
.SH SYNOPSIS
.br
.PP
\fC#include <omega\&.h>\fP
.br
\fC#include <omega/Rel_map\&.h>\fP
.br
\fC#include <basic/Collection\&.h>\fP
.br
\fC#include <basic/Bag\&.h>\fP
.br
\fC#include <basic/Map\&.h>\fP
.br
\fC#include <basic/util\&.h>\fP
.br
\fC#include <basic/omega_error\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <code_gen/CG\&.h>\fP
.br
\fC#include <code_gen/code_gen\&.h>\fP
.br
\fC#include <code_gen/CG_outputBuilder\&.h>\fP
.br
\fC#include <code_gen/CG_outputRepr\&.h>\fP
.br
\fC#include <code_gen/CG_stringBuilder\&.h>\fP
.br
\fC#include <code_gen/CG_stringRepr\&.h>\fP
.br
\fC#include <code_gen/output_repr\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::JunkStaticInit\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CG_result * \fBomega::gen_recursive\fP (int level, IntTuple &isActive)"
.br
.ti -1c
.RI "SetTuple \fBomega::filter_function_symbols\fP (SetTuple &sets, bool keep_fs)"
.br
.ti -1c
.RI "RelTuple \fBomega::strip_function_symbols\fP (SetTuple &sets)"
.br
.ti -1c
.RI "RelTuple \fBomega::extract_function_symbols\fP (SetTuple &sets)"
.br
.ti -1c
.RI "std::string \fBomega::MMGenerateCode\fP (RelTuple &\fBT\fP, SetTuple &old_IS, Relation &known, int effort)"
.br
.ti -1c
.RI "CG_outputRepr * \fBomega::MMGenerateCode\fP (CG_outputBuilder *ocg, RelTuple &\fBT\fP, SetTuple &old_IS, \fBconst\fP Tuple< CG_outputRepr * > &stmt_content, Relation &known, int effort)"
.br
.ti -1c
.RI "CG_outputRepr * \fBomega::MMGenerateCode\fP (CG_outputBuilder *ocg, RelTuple &\fBT\fP, SetTuple &old_IS, \fBconst\fP Tuple< CG_outputRepr * > &stmt_content, Relation &known, Tuple< IntTuple > &smtNonSplitLevels_, std::vector< std::pair< int, std::string > > syncs_, \fBconst\fP Tuple< Tuple< std::string > > &loopIdxNames_, int effort=1)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SetTuple \fBomega::new_IS\fP"
.br
.ti -1c
.RI "SetTupleTuple \fBomega::projected_nIS\fP"
.br
.ti -1c
.RI "Tuple< CG_outputRepr * > \fBomega::statementInfo\fP"
.br
.ti -1c
.RI "RelTuple \fBomega::transformations\fP"
.br
.ti -1c
.RI "int \fBomega::code_gen_debug\fP =0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
