.TH "lib/chill/omega/code_gen/include/code_gen/code_gen.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/code_gen/include/code_gen/code_gen.h
.SH SYNOPSIS
.br
.PP
\fC#include <basic/Tuple\&.h>\fP
.br
\fC#include <omega/Relation\&.h>\fP
.br
\fC#include <code_gen/CG\&.h>\fP
.br
\fC#include <code_gen/CG_outputRepr\&.h>\fP
.br
\fC#include <code_gen/CG_outputBuilder\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBomega::Polyhedra\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Tuple< int > \fBomega::IntTuple\fP"
.br
.ti -1c
.RI "typedef Tuple< Relation > \fBomega::SetTuple\fP"
.br
.ti -1c
.RI "typedef Tuple< SetTuple > \fBomega::SetTupleTuple\fP"
.br
.ti -1c
.RI "typedef Tuple< Relation > \fBomega::RelTuple\fP"
.br
.ti -1c
.RI "typedef Tuple< RelTuple > \fBomega::RelTupleTuple\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CG_outputRepr * \fBomega::MMGenerateCode\fP (CG_outputBuilder *ocg, Tuple< Relation > &\fBT\fP, Tuple< Relation > &old_IS, \fBconst\fP Tuple< CG_outputRepr * > &stmt_content, Relation &known, int effort=1)"
.br
.ti -1c
.RI "std::string \fBomega::MMGenerateCode\fP (Tuple< Relation > &\fBT\fP, Tuple< Relation > &old_IS, Relation &known, int effort=1)"
.br
.ti -1c
.RI "CG_outputRepr * \fBomega::MMGenerateCode\fP (CG_outputBuilder *ocg, RelTuple &\fBT\fP, SetTuple &old_IS, \fBconst\fP Tuple< CG_outputRepr * > &stmt_content, Relation &known, Tuple< IntTuple > &smtNonSplitLevels_, std::vector< std::pair< int, std::string > > syncs_, \fBconst\fP Tuple< Tuple< std::string > > &loopIdxNames_, int effort=1)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
