.TH "lib/gmp/compat.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/compat.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'gmp\&.h'\fP
.br
\fC#include 'gmp\-impl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmp_limb_t\fP \fB__MPN\fP() \fBdivexact_by3\fP (\fBmp_ptr\fP dst, \fBmp_srcptr\fP src, \fBmp_size_t\fP \fBsize\fP)"
.br
.ti -1c
.RI "\fBmp_limb_t\fP \fB__MPN\fP() \fBdivmod_1\fP (\fBmp_ptr\fP dst, \fBmp_srcptr\fP src, \fBmp_size_t\fP \fBsize\fP, \fBmp_limb_t\fP divisor)"
.br
.ti -1c
.RI "int \fB__gmpz_legendre\fP (\fBmpz_srcptr\fP \fBa\fP, \fBmpz_srcptr\fP \fBb\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int __gmpz_legendre (\fBmpz_srcptr\fP a, \fBmpz_srcptr\fP b)"

.SS "\fBmp_limb_t\fP \fB__MPN\fP() divexact_by3 (\fBmp_ptr\fP dst, \fBmp_srcptr\fP src, \fBmp_size_t\fP size)"

.SS "\fBmp_limb_t\fP \fB__MPN\fP() divmod_1 (\fBmp_ptr\fP dst, \fBmp_srcptr\fP src, \fBmp_size_t\fP size, \fBmp_limb_t\fP divisor)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
