.TH "conjgrad_ell_params" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conjgrad_ell_params
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <conjgrad_ell_cu\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double *__restrict__ \fBr\fP"
.br
.ti -1c
.RI "double *__restrict__ \fBd\fP"
.br
.ti -1c
.RI "double *__restrict__ \fBs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double* __restrict__ conjgrad_ell_params::d"

.SS "double* __restrict__ conjgrad_ell_params::r"

.SS "double* __restrict__ conjgrad_ell_params::s"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
