.TH "test/ConjGradTest.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/ConjGradTest.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <omp\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <Eigen/Sparse>\fP
.br
\fC#include <Eigen/SparseExtra>\fP
.br
\fC#include <Eigen/IterativeLinearSolvers>\fP
.br
\fC#include <pdfg/Digraph\&.hpp>\fP
.br
\fC#include <util/MatrixIO\&.hpp>\fP
.br
\fC#include 'InspExecTest\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest::ConjGradTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtest\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Eigen::Triplet< double > \fBTriple\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef Eigen::Triplet<double> \fBTriple\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
