.TH "coo_data_t" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coo_data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBitype\fP \fBnnz\fP"
.br
.ti -1c
.RI "\fBitype\fP \fBorder\fP"
.br
.ti -1c
.RI "\fBreal\fP * \fBB\fP"
.br
.ti -1c
.RI "\fBitype\fP * \fBdims\fP"
.br
.ti -1c
.RI "\fBitype\fP * \fBindex\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBreal\fP* coo_data_t::B"

.SS "\fBitype\fP* coo_data_t::dims"

.SS "\fBitype\fP* coo_data_t::index"

.SS "\fBitype\fP coo_data_t::nnz"

.SS "\fBitype\fP coo_data_t::order"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
