.TH "scripts/codegen/cpp.py" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/codegen/cpp.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcpp\&.CppParser\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcpp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcpp\&.verbose\fP (*args, **kwargs)"
.br
.ti -1c
.RI "def \fBcpp\&.noSystemIncludes\fP (cursor, level)"
.br
.ti -1c
.RI "def \fBcpp\&.mainFileOnly\fP (cursor, level)"
.br
.ti -1c
.RI "def \fBcpp\&.isValidType\fP (type)"
.br
.ti -1c
.RI "def \fBcpp\&.qualifiers\fP (type)"
.br
.ti -1c
.RI "def \fBcpp\&.showLevel\fP (level, *args)"
.br
.ti -1c
.RI "def \fBcpp\&.showType\fP (type, level, title)"
.br
.ti -1c
.RI "def \fBcpp\&.showAST\fP (cursor, filterPred=verbose, level=0)"
.br
.ti -1c
.RI "def \fBcpp\&.getAST\fP (parser, cursor, filterPred=verbose, level=0, node=None)"
.br
.ti -1c
.RI "def \fBcpp\&.fixForNode\fP (parser, node)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
