.TH "cpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCppParser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBverbose\fP (*args, **kwargs)"
.br
.ti -1c
.RI "def \fBnoSystemIncludes\fP (cursor, level)"
.br
.ti -1c
.RI "def \fBmainFileOnly\fP (cursor, level)"
.br
.ti -1c
.RI "def \fBisValidType\fP (type)"
.br
.ti -1c
.RI "def \fBqualifiers\fP (type)"
.br
.ti -1c
.RI "def \fBshowLevel\fP (level, *args)"
.br
.ti -1c
.RI "def \fBshowType\fP (type, level, title)"
.br
.ti -1c
.RI "def \fBshowAST\fP (cursor, filterPred=\fBverbose\fP, level=0)"
.br
.ti -1c
.RI "def \fBgetAST\fP (parser, cursor, filterPred=\fBverbose\fP, level=0, node=None)"
.br
.ti -1c
.RI "def \fBfixForNode\fP (parser, node)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def cpp\&.fixForNode ( parser,  node)"

.SS "def cpp\&.getAST ( parser,  cursor,  filterPred = \fC\fBverbose\fP\fP,  level = \fC0\fP,  node = \fCNone\fP)"

.SS "def cpp\&.isValidType ( type)"

.SS "def cpp\&.mainFileOnly ( cursor,  level)"

.SS "def cpp\&.noSystemIncludes ( cursor,  level)"

.SS "def cpp\&.qualifiers ( type)"

.SS "def cpp\&.showAST ( cursor,  filterPred = \fC\fBverbose\fP\fP,  level = \fC0\fP)"

.SS "def cpp\&.showLevel ( level, * args)"

.SS "def cpp\&.showType ( type,  level,  title)"

.SS "def cpp\&.verbose (* args, ** kwargs)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
