.TH "cpp.CppParser" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp.CppParser
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBpath\fP='')"
.br
.ti -1c
.RI "def \fBread\fP (self, \fBpath\fP)"
.br
.ti -1c
.RI "def \fBparse\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBindex\fP"
.br
.ti -1c
.RI "\fBunit\fP"
.br
.ti -1c
.RI "\fBast\fP"
.br
.ti -1c
.RI "\fBincludes\fP"
.br
.ti -1c
.RI "\fBlines\fP"
.br
.ti -1c
.RI "\fBfiles\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def cpp\&.CppParser\&.__init__ ( self,  path = \fC''\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def cpp\&.CppParser\&.parse ( self)"

.SS "def cpp\&.CppParser\&.read ( self,  path)"

.SH "Member Data Documentation"
.PP 
.SS "cpp\&.CppParser\&.ast"

.SS "cpp\&.CppParser\&.files"

.SS "cpp\&.CppParser\&.includes"

.SS "cpp\&.CppParser\&.index"

.SS "cpp\&.CppParser\&.lines"

.SS "cpp\&.CppParser\&.path"

.SS "cpp\&.CppParser\&.unit"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
