.TH "CPU" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPU
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CPU\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun_cpuid\fP (uint32_t eax, uint32_t ecx, uint32_t *abcd)"
.br
.ti -1c
.RI "int \fBcheck_xcr0_ymm\fP ()"
.br
.ti -1c
.RI "int \fBcheck_4th_gen_intel_core_features\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcpuid\fP (unsigned *eax, unsigned *ebx, unsigned *ecx, unsigned *edx)"
.br
.ti -1c
.RI "static int \fBcan_use_intel_core_4th_gen_features\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int CPU::can_use_intel_core_4th_gen_features ()\fC [inline]\fP, \fC [static]\fP"

.SS "int CPU::check_4th_gen_intel_core_features ()\fC [inline]\fP"

.SS "int CPU::check_xcr0_ymm ()\fC [inline]\fP"

.SS "static void CPU::cpuid (unsigned * eax, unsigned * ebx, unsigned * ecx, unsigned * edx)\fC [inline]\fP, \fC [static]\fP"

.SS "void CPU::run_cpuid (uint32_t eax, uint32_t ecx, uint32_t * abcd)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
