.TH "csf_data_t" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csf_data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBitype\fP * \fBlevels\fP"
.br
.ti -1c
.RI "\fBitype\fP ** \fBoffsets\fP"
.br
.ti -1c
.RI "\fBitype\fP ** \fBindices\fP"
.br
.ti -1c
.RI "\fBreal\fP * \fBB_prime\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBreal\fP* csf_data_t::B_prime"

.SS "\fBitype\fP** csf_data_t::indices"

.SS "\fBitype\fP* csf_data_t::levels"

.SS "\fBitype\fP** csf_data_t::offsets"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
