.TH "csr_data_t" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csr_data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBN_R\fP"
.br
.ti -1c
.RI "int \fBN_C\fP"
.br
.ti -1c
.RI "int \fBNNZ\fP"
.br
.ti -1c
.RI "\fBreal\fP * \fBA\fP"
.br
.ti -1c
.RI "\fBitype\fP * \fBcol\fP"
.br
.ti -1c
.RI "\fBitype\fP * \fBindex\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBreal\fP* csr_data_t::A"

.SS "\fBitype\fP* csr_data_t::col"

.SS "\fBitype\fP* csr_data_t::index"

.SS "int csr_data_t::N_C"

.SS "unsigned csr_data_t::N_R"

.SS "int csr_data_t::NNZ"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
