.TH "cuda_t" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuda_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuda_funcs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBndevices\fP"
.br
.ti -1c
.RI "int \fBdevid\fP"
.br
.ti -1c
.RI "struct cudaDeviceProp \fBprops\fP"
.br
.ti -1c
.RI "cudaEvent_t \fBstart\fP"
.br
.ti -1c
.RI "cudaEvent_t \fBstop\fP"
.br
.ti -1c
.RI "void * \fBdataptr\fP"
.br
.ti -1c
.RI "size_t \fBdatasize\fP"
.br
.ti -1c
.RI "int \fBmanaged\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* cuda_t::dataptr"

.SS "size_t cuda_t::datasize"

.SS "int cuda_t::devid"

.SS "int cuda_t::managed"

.SS "int cuda_t::ndevices"

.SS "struct cudaDeviceProp cuda_t::props"

.SS "cudaEvent_t cuda_t::start"

.SS "cudaEvent_t cuda_t::stop"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
