.TH "lib/chill/omega/omega_lib/include/omega/omega_core/debugging.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include/omega/omega_core/debugging.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBomega::negation_control\fP { \fBomega::any_negation\fP, \fBomega::one_geq_or_eq\fP, \fBomega::one_geq_or_stride\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBomega::omega_core_debug\fP = 0"
.br
.ti -1c
.RI "int \fBomega::pres_debug\fP =0"
.br
.ti -1c
.RI "int \fBomega::relation_debug\fP =0"
.br
.ti -1c
.RI "int \fBomega::closure_presburger_debug\fP = 0"
.br
.ti -1c
.RI "int \fBomega::hull_debug\fP = 0"
.br
.ti -1c
.RI "int \fBomega::farkas_debug\fP = 0"
.br
.ti -1c
.RI "negation_control \fBomega::pres_legal_negations\fP = any_negation"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
