.TH "doc/debug.txt" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doc/debug.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Bad \fB__pad1__\fP"
.br
.ti -1c
.RI "Bad \fBN\fP"
.br
.ti -1c
.RI "Bad \fBP\fP"
.br
.ti -1c
.RI "gemm \fB__pad2__\fP"
.br
.ti -1c
.RI "gemm \fBj\fP"
.br
.ti -1c
.RI "gemm \fBk\fP"
.br
.ti -1c
.RI "\fBr0\fP \fB__pad3__\fP"
.br
.ti -1c
.RI "\fBr1\fP \fB__pad4__\fP"
.br
.ti -1c
.RI "\fBcodegen\fP \fBr0\fP"
.br
.ti -1c
.RI "\fBcodegen\fP \fBr1\fP"
.br
.ti -1c
.RI "Good \fB__pad5__\fP"
.br
.ti -1c
.RI "\fBinit\fP \fB__pad6__\fP"
.br
.ti -1c
.RI "gemm \fB__pad7__\fP"
.br
.ti -1c
.RI "\fBr0\fP \fB__pad8__\fP"
.br
.ti -1c
.RI "\fBr1\fP \fB__pad9__\fP"
.br
.ti -1c
.RI "\fBopts\fP [SPLATT_OPTION_REGULARIZE] = 0\&."
.br
.ti -1c
.RI "\fBDEFAULT_TOL\fP"
.br
.ti -1c
.RI "\fBpt\fP"
.br
.ti -1c
.RI "c2p \fB__pad10__\fP"
.br
.ti -1c
.RI "c2p \fBx\fP"
.br
.ti -1c
.RI "wsb \fB__pad11__\fP"
.br
.ti -1c
.RI "\fBabs\fP \fB__pad12__\fP"
.br
.ti -1c
.RI "\fBr0\fP \fB__pad13__\fP"
.br
.ti -1c
.RI "\fBr1\fP \fB__pad14__\fP"
.br
.ti -1c
.RI "\fBr2\fP \fB__pad15__\fP"
.br
.ti -1c
.RI "\fBcodegen\fP \fBr2\fP"
.br
.ti -1c
.RI "lap \fB__pad16__\fP"
.br
.ti -1c
.RI "lap \fBy\fP"
.br
.ti -1c
.RI "inc \fB__pad17__\fP"
.br
.ti -1c
.RI "il1 \fB__pad18__\fP"
.br
.ti -1c
.RI "ih1 \fB__pad19__\fP"
.br
.ti -1c
.RI "\fBr0\fP \fB__pad20__\fP"
.br
.ti -1c
.RI "\fBr1\fP \fB__pad21__\fP"
.br
.ti -1c
.RI "\fBr2\fP \fB__pad22__\fP"
.br
.ti -1c
.RI "\fBr3\fP \fB__pad23__\fP"
.br
.ti -1c
.RI "\fBcodegen\fP \fBr3\fP"
.br
.ti -1c
.RI "flap \fB__pad24__\fP"
.br
.ti -1c
.RI "finc \fB__pad25__\fP"
.br
.ti -1c
.RI "fdiv \fB__pad26__\fP"
.br
.ti -1c
.RI "rinc \fB__pad27__\fP"
.br
.ti -1c
.RI "\fBr0\fP \fB__pad28__\fP"
.br
.ti -1c
.RI "\fBr1\fP \fB__pad29__\fP"
.br
.ti -1c
.RI "\fBr2\fP \fB__pad30__\fP"
.br
.ti -1c
.RI "\fBr3\fP \fB__pad31__\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "c2p __pad10__"

.SS "wsb __pad11__"

.SS "\fBabs\fP __pad12__"

.SS "\fBr0\fP __pad13__"

.SS "\fBr1\fP __pad14__"

.SS "\fBr2\fP __pad15__"

.SS "lap __pad16__"

.SS "inc __pad17__"

.SS "il1 __pad18__"

.SS "ih1 __pad19__"

.SS "Bad __pad1__"

.SS "\fBr0\fP __pad20__"

.SS "\fBr1\fP __pad21__"

.SS "\fBr2\fP __pad22__"

.SS "\fBr3\fP __pad23__"

.SS "flap __pad24__"

.SS "finc __pad25__"

.SS "fdiv __pad26__"

.SS "rinc __pad27__"

.SS "\fBr0\fP __pad28__"

.SS "\fBr1\fP __pad29__"

.SS "gemm __pad2__"

.SS "\fBr2\fP __pad30__"

.SS "\fBr3\fP __pad31__"

.SS "\fBr0\fP __pad3__"

.SS "\fBr1\fP __pad4__"

.SS "Good __pad5__"

.SS "\fBinit\fP __pad6__"

.SS "gemm __pad7__"

.SS "\fBr0\fP __pad8__"

.SS "\fBr1\fP __pad9__"

.SS "DEFAULT_TOL"
\fBInitial value:\fP
.PP
.nf
= 1e-5
  DEFAULT_ITS = 50


Euler Debug:

consToPrim:
ypos=0
.fi
.SS "\fBs10\fP j"

.SS "\fBcodegen\fP k"

.SS "Good N"

.SS "opts[SPLATT_OPTION_NITER] = 0\&."

.SS "Good P"

.SS "pt"
\fBInitial value:\fP
.PP
.nf
=(-4,-4)
xpos=0
U=(1\&.29546,0\&.458016,0\&.458016,2\&.40059,)
W=(1\&.29546,0\&.353553,0\&.353553,0\&.895464,)


Cori Modules:
module load cmake/3\&.14\&.0

Euler Fusion:

symbolic N
.fi
.SS "\fBcodegen\fP r0"

.SS "\fBcodegen\fP r1"

.SS "\fBcodegen\fP r2"

.SS "\fBcodegen\fP r3"

.SS "Original Expected x"

.SS "Original Expected y"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
