.TH "Declaration_Site" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Declaration_Site
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AST\&.hh>\fP
.PP
Inherited by \fBGlobal_Declaration_Site\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeclaration_Site\fP ()"
.br
.ti -1c
.RI "\fBDeclaration_Site\fP (\fBstd::set\fP< char * > *v)"
.br
.ti -1c
.RI "virtual \fBVariable_Ref\fP * \fBextend\fP (char *s)"
.br
.ti -1c
.RI "virtual \fBVariable_Ref\fP * \fBextend\fP (char *s, \fBomega::Argument_Tuple\fP, int)"
.br
.ti -1c
.RI "virtual \fB~Declaration_Site\fP ()"
.br
.ti -1c
.RI "\fBVariable_Ref\fP * \fBextend\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDeclaration_Site\fP * \fBprevious\fP"
.br
.ti -1c
.RI "\fBstd::set\fP< \fBVariable_Ref\fP * > \fBdeclarations\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Declaration_Site::Declaration_Site ()"

.SS "Declaration_Site::Declaration_Site (\fBstd::set\fP< char * > * v)"

.SS "Declaration_Site::~Declaration_Site ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBVariable_Ref\fP * Declaration_Site::extend ()"

.SS "\fBVariable_Ref\fP * Declaration_Site::extend (char * s)\fC [virtual]\fP"

.PP
Reimplemented in \fBGlobal_Declaration_Site\fP\&.
.SS "\fBVariable_Ref\fP * Declaration_Site::extend (char * s, \fBomega::Argument_Tuple\fP of, int pos)\fC [virtual]\fP"

.PP
Reimplemented in \fBGlobal_Declaration_Site\fP\&.
.SS "void Declaration_Site::print ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::set\fP<\fBVariable_Ref\fP *> Declaration_Site::declarations"

.SS "\fBDeclaration_Site\fP* Declaration_Site::previous"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
