.TH "DFGVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DFGVisitor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Visitor\&.hpp>\fP
.SH "Detailed Description"
.PP 
(Note, this needs exactly one 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
