.TH "EnvironmentTest" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnvironmentTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void EnvironmentTest::SetUp ()\fC [inline]\fP, \fC [protected]\fP"

.SS "void EnvironmentTest::TearDown ()\fC [inline]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
