.TH "lib/gmp/errno.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/errno.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'gmp\&.h'\fP
.br
\fC#include 'gmp\-impl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__gmp_exception\fP (int error_bit)"
.br
.ti -1c
.RI "void \fB__gmp_sqrt_of_negative\fP (void)"
.br
.ti -1c
.RI "void \fB__gmp_divide_by_zero\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBgmp_errno\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void __gmp_divide_by_zero (void)"

.SS "void __gmp_exception (int error_bit)"

.SS "void __gmp_sqrt_of_negative (void)"

.SH "Variable Documentation"
.PP 
.SS "int gmp_errno = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
