.TH "lib/iegenlib/src/set_relation/expression.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/set_relation/expression.cc \- Implementations of the expression classes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'expression\&.h'\fP
.br
\fC#include 'TupleDecl\&.h'\fP
.br
\fC#include 'set_relation\&.h'\fP
.br
\fC#include 'Visitor\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBiegenlib\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementations of the expression classes\&. 


.PP
\fBAuthors\fP
.RS 4
Michelle Strout and Joe Strout
.RE
.PP
Copyright (c) 2012, Colorado State University 
.br
 Copyright (c) 2015, University of Arizona 
.br
 All rights reserved\&. 
.br
 See \&.\&./\&.\&./COPYING for details\&. 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
