.TH "ExpTest" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBroot_dir\fP"
.br
.ti -1c
.RI "std::string \fBdot_data\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ExpTest::SetUp ()\fC [protected]\fP"

.SS "void ExpTest::TearDown ()\fC [inline]\fP, \fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string ExpTest::dot_data"

.SS "std::string ExpTest::root_dir"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
