.TH "lib/gmp/extract-dbl.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/extract-dbl.c
.SH SYNOPSIS
.br
.PP
\fC#include 'gmp\&.h'\fP
.br
\fC#include 'gmp\-impl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBITS_PER_PART\fP   \fBGMP_LIMB_BITS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fB__gmp_extract_double\fP (\fBmp_ptr\fP \fBrp\fP, double d)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BITS_PER_PART   \fBGMP_LIMB_BITS\fP"

.SH "Function Documentation"
.PP 
.SS "int __gmp_extract_double (\fBmp_ptr\fP rp, double d)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
