.TH "factor_t" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
factor_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdivisor\fP"
.br
.ti -1c
.RI "\fBmpz_t\fP \fBinverse\fP"
.br
.ti -1c
.RI "\fBmpz_t\fP \fBmask\fP"
.br
.ti -1c
.RI "double \fBfraction\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int factor_t::divisor"

.SS "double factor_t::fraction"

.SS "\fBmpz_t\fP factor_t::inverse"

.SS "\fBmpz_t\fP factor_t::mask"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
