.TH "factory.IEGenFactory" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
factory.IEGenFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfactory\&.SetFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBinstance\fP (cls)"
.br
.ti -1c
.RI "def \fBconstants\fP (self)"
.br
.ti -1c
.RI "def \fBconstants\fP (self, constants)"
.br
.ti -1c
.RI "def \fBset\fP (self, setstr, \fBname\fP='')"
.br
.ti -1c
.RI "def \fBmap\fP (self, mapstr, \fBname\fP='')"
.br
.ti -1c
.RI "def \fBcodegen\fP (self, schedule, statements=())"
.br
.ti -1c
.RI "def \fBreformat\fP (self, schedule, code, statements=())"
.br
.ti -1c
.RI "def \fBrestoreConsts\fP (self, code)"
.br
.ti -1c
.RI "def \fBrestoreUFs\fP (self, code)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def factory\&.IEGenFactory\&.__init__ ( self)"

.PP
Reimplemented from \fBfactory\&.SetFactory\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def factory\&.IEGenFactory\&.codegen ( self,  schedule,  statements = \fC()\fP)"

.SS "def factory\&.IEGenFactory\&.constants ( self)"

.SS "def factory\&.IEGenFactory\&.constants ( self,  constants)"

.SS "def factory\&.IEGenFactory\&.instance ( cls)"

.SS "def factory\&.IEGenFactory\&.map ( self,  mapstr,  name = \fC''\fP)"

.PP
Reimplemented from \fBfactory\&.SetFactory\fP\&.
.SS "def factory\&.IEGenFactory\&.reformat ( self,  schedule,  code,  statements = \fC()\fP)"

.SS "def factory\&.IEGenFactory\&.restoreConsts ( self,  code)"

.SS "def factory\&.IEGenFactory\&.restoreUFs ( self,  code)"

.SS "def factory\&.IEGenFactory\&.set ( self,  setstr,  name = \fC''\fP)"

.PP
Reimplemented from \fBfactory\&.SetFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
