.TH "factory.SetFactory" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
factory.SetFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBfactory\&.IEGenFactory\fP, and \fBfactory\&.ISLFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBset\fP (self, setstr, \fBname\fP='')"
.br
.ti -1c
.RI "def \fBmap\fP (self, mapstr, \fBname\fP='')"
.br
.ti -1c
.RI "def \fBcodegen\fP (self, schedule)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def factory\&.SetFactory\&.__init__ ( self)"

.PP
Reimplemented in \fBfactory\&.IEGenFactory\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def factory\&.SetFactory\&.codegen ( self,  schedule)"

.PP
Reimplemented in \fBfactory\&.ISLFactory\fP\&.
.SS "def factory\&.SetFactory\&.map ( self,  mapstr,  name = \fC''\fP)"

.PP
Reimplemented in \fBfactory\&.IEGenFactory\fP, and \fBfactory\&.ISLFactory\fP\&.
.SS "def factory\&.SetFactory\&.set ( self,  setstr,  name = \fC''\fP)"

.PP
Reimplemented in \fBfactory\&.IEGenFactory\fP, and \fBfactory\&.ISLFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
