.TH "fft_table_nk" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fft_table_nk
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmp\-impl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgmp_uint_least32_t\fP \fBn\fP:27"
.br
.ti -1c
.RI "\fBgmp_uint_least32_t\fP \fBk\fP:5"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBgmp_uint_least32_t\fP fft_table_nk::k"

.SS "\fBgmp_uint_least32_t\fP fft_table_nk::n"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
