.TH "scripts/tools/files.py" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/tools/files.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBfiles\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBfiles\&.exists\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.getSize\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.accTime\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.modTime\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.creationTime\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.copy\fP (src, dst)"
.br
.ti -1c
.RI "def \fBfiles\&.move\fP (src, dst)"
.br
.ti -1c
.RI "def \fBfiles\&.remove\fP (file)"
.br
.ti -1c
.RI "def \fBfiles\&.isDir\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.zip\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.list\fP (dir, pattern='')"
.br
.ti -1c
.RI "def \fBfiles\&.getDir\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.getName\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.getExt\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.getPathWithoutExt\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.getNameWithoutExt\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.read\fP (path)"
.br
.ti -1c
.RI "def \fBfiles\&.readCSV\fP (path, delim=',', asDict=False)"
.br
.ti -1c
.RI "def \fBfiles\&.write\fP (path, lines)"
.br
.ti -1c
.RI "def \fBfiles\&.writeCSV\fP (path, rows)"
.br
.ti -1c
.RI "def \fBfiles\&.append\fP (path, lines)"
.br
.ti -1c
.RI "def \fBfiles\&.makedir\fP (newDir)"
.br
.ti -1c
.RI "def \fBfiles\&.chmod\fP (path, mode='')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
