.TH "src/pdfg/FlowGraph.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pdfg/FlowGraph.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <initializer_list>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <pdfg/Digraph\&.hpp>\fP
.br
\fC#include <util/Strings\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpdfg::GraphItem\fP"
.br
.ti -1c
.RI "struct \fBpdfg::Node\fP"
.br
.ti -1c
.RI "struct \fBpdfg::Edge\fP"
.br
.ti -1c
.RI "struct \fBpdfg::DataNode\fP"
.br
.ti -1c
.RI "struct \fBpdfg::CompNode\fP"
.br
.ti -1c
.RI "struct \fBpdfg::RelNode\fP"
.br
.ti -1c
.RI "struct \fBpdfg::FlowGraph\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpdfg\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBpdfg::MemAlloc\fP { \fBpdfg::NONE\fP, \fBpdfg::AUTO\fP, \fBpdfg::STATIC\fP, \fBpdfg::DYNAMIC\fP, \fBpdfg::STRUCT\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBpdfg::operator<<\fP (ostream &os, \fBconst\fP Expr &expr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
