.TH "gcdext_ctx" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gcdext_ctx
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmp\-impl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmp_ptr\fP \fBgp\fP"
.br
.ti -1c
.RI "\fBmp_size_t\fP \fBgn\fP"
.br
.ti -1c
.RI "\fBmp_ptr\fP \fBup\fP"
.br
.ti -1c
.RI "\fBmp_size_t\fP * \fBusize\fP"
.br
.ti -1c
.RI "\fBmp_size_t\fP \fBun\fP"
.br
.ti -1c
.RI "\fBmp_ptr\fP \fBu0\fP"
.br
.ti -1c
.RI "\fBmp_ptr\fP \fBu1\fP"
.br
.ti -1c
.RI "\fBmp_ptr\fP \fBtp\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmp_size_t\fP gcdext_ctx::gn"

.SS "\fBmp_ptr\fP gcdext_ctx::gp"

.SS "\fBmp_ptr\fP gcdext_ctx::tp"

.SS "\fBmp_ptr\fP gcdext_ctx::u0"

.SS "\fBmp_ptr\fP gcdext_ctx::u1"

.SS "\fBmp_size_t\fP gcdext_ctx::un"

.SS "\fBmp_ptr\fP gcdext_ctx::up"

.SS "\fBmp_size_t\fP* gcdext_ctx::usize"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
