.TH "lib/gmp/gen-jacobitab.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/gen-jacobitab.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBJACOBI_A\fP(bits)   (decode_table[(bits)>>1]\&.\fBa\fP)"
.br
.ti -1c
.RI "#define \fBJACOBI_B\fP(bits)   (decode_table[(bits)>>1]\&.\fBb\fP)"
.br
.ti -1c
.RI "#define \fBJACOBI_E\fP(bits)   ((bits) & 1)"
.br
.ti -1c
.RI "#define \fBJACOBI_D\fP(bits)   (((bits)>>1) == 7) /* Gives 0 for don'\fBt\fP care states\&. */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define JACOBI_A(bits)   (decode_table[(bits)>>1]\&.\fBa\fP)"

.SS "#define JACOBI_B(bits)   (decode_table[(bits)>>1]\&.\fBb\fP)"

.SS "#define JACOBI_D(bits)   (((bits)>>1) == 7) /* Gives 0 for don'\fBt\fP care states\&. */"

.SS "#define JACOBI_E(bits)   ((bits) & 1)"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Variable Documentation"
.PP 
.SS "unsigned char a"

.SS "unsigned char b"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
