.TH "lib/gmp/gen-bases.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/gen-bases.c
.SH SYNOPSIS
.br
.PP
\fC#include 'bootstrap\&.c'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPOW2_P\fP(\fBn\fP)   (((\fBn\fP) & ((\fBn\fP) \- 1)) == 0)"
.br
.ti -1c
.RI "#define \fBEXTRA\fP   16"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBulog2\fP (unsigned int \fBx\fP)"
.br
.ti -1c
.RI "void \fBgenerate\fP (int \fBlimb_bits\fP, int nail_bits, int base)"
.br
.ti -1c
.RI "void \fBheader\fP (int \fBlimb_bits\fP, int nail_bits)"
.br
.ti -1c
.RI "void \fBmp_2logb\fP (\fBmpz_t\fP r, int bi, int prec)"
.br
.ti -1c
.RI "void \fBtable\fP (int \fBlimb_bits\fP, int nail_bits)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBchars_per_limb\fP"
.br
.ti -1c
.RI "\fBmpz_t\fP \fBbig_base\fP"
.br
.ti -1c
.RI "int \fBnormalization_steps\fP"
.br
.ti -1c
.RI "\fBmpz_t\fP \fBbig_base_inverted\fP"
.br
.ti -1c
.RI "\fBmpz_t\fP \fBt\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EXTRA   16"

.SS "#define POW2_P(\fBn\fP)   (((\fBn\fP) & ((\fBn\fP) \- 1)) == 0)"

.SH "Function Documentation"
.PP 
.SS "void generate (int limb_bits, int nail_bits, int base)"

.SS "void header (int limb_bits, int nail_bits)"

.SS "int main (int argc, char ** argv)"

.SS "void mp_2logb (\fBmpz_t\fP r, int bi, int prec)"

.SS "void table (int limb_bits, int nail_bits)"

.SS "unsigned int ulog2 (unsigned int x)"

.SH "Variable Documentation"
.PP 
.SS "\fBmpz_t\fP big_base"

.SS "\fBmpz_t\fP big_base_inverted"

.SS "int chars_per_limb"

.SS "int normalization_steps"

.SS "\fBmpz_t\fP t"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
