.TH "lib/isl/gitversion.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/gitversion.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGIT_HEAD_ID\fP   'isl\-0\&.16\&.1'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GIT_HEAD_ID   'isl\-0\&.16\&.1'"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
