.TH "Global_Declaration_Site" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Global_Declaration_Site
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AST\&.hh>\fP
.PP
Inherits \fBDeclaration_Site\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBVariable_Ref\fP * \fBextend\fP (char *s)"
.br
.ti -1c
.RI "virtual \fBVariable_Ref\fP * \fBextend\fP ()"
.br
.ti -1c
.RI "virtual \fBVariable_Ref\fP * \fBextend\fP (char *s, \fBomega::Argument_Tuple\fP in_of, int in_arity)"
.br
.ti -1c
.RI "void \fBextend_both_tuples\fP (char *s, int arity)"
.br
.ti -1c
.RI "virtual \fB~Global_Declaration_Site\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Global_Declaration_Site::~Global_Declaration_Site ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBVariable_Ref\fP* Global_Declaration_Site::extend ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "\fBVariable_Ref\fP * Global_Declaration_Site::extend (char * s)\fC [virtual]\fP"

.PP
Reimplemented from \fBDeclaration_Site\fP\&.
.SS "virtual \fBVariable_Ref\fP* Global_Declaration_Site::extend (char * s, \fBomega::Argument_Tuple\fP in_of, int in_arity)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBDeclaration_Site\fP\&.
.SS "void Global_Declaration_Site::extend_both_tuples (char * s, int arity)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
