.TH "gmp_randfnptr_t" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gmp_randfnptr_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmp\-impl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBrandseed_fn\fP )(\fBgmp_randstate_t\fP, \fBmpz_srcptr\fP)"
.br
.ti -1c
.RI "void(* \fBrandget_fn\fP )(\fBgmp_randstate_t\fP, \fBmp_ptr\fP, unsigned long int)"
.br
.ti -1c
.RI "void(* \fBrandclear_fn\fP )(\fBgmp_randstate_t\fP)"
.br
.ti -1c
.RI "void(* \fBrandiset_fn\fP )(\fBgmp_randstate_ptr\fP, \fBgmp_randstate_srcptr\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void(* gmp_randfnptr_t::randclear_fn) (\fBgmp_randstate_t\fP)"

.SS "void(* gmp_randfnptr_t::randget_fn) (\fBgmp_randstate_t\fP, \fBmp_ptr\fP, unsigned long int)"

.SS "void(* gmp_randfnptr_t::randiset_fn) (\fBgmp_randstate_ptr\fP, \fBgmp_randstate_srcptr\fP)"

.SS "void(* gmp_randfnptr_t::randseed_fn) (\fBgmp_randstate_t\fP, \fBmpz_srcptr\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
