.TH "graph2isl" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph2isl
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgen_jacobi\fP ()"
.br
.ti -1c
.RI "def \fBgen_mfd\fP ()"
.br
.ti -1c
.RI "def \fBgen_csr_spmv\fP ()"
.br
.ti -1c
.RI "def \fBgen_bsr_spmv\fP ()"
.br
.ti -1c
.RI "def \fBgen_csrtobsr\fP (nblocks=8)"
.br
.ti -1c
.RI "def \fBgsl_test\fP ()"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def graph2isl\&.gen_bsr_spmv ()"

.SS "def graph2isl\&.gen_csr_spmv ()"

.SS "def graph2isl\&.gen_csrtobsr ( nblocks = \fC8\fP)"

.SS "def graph2isl\&.gen_jacobi ()"

.SS "def graph2isl\&.gen_mfd ()"

.SS "def graph2isl\&.gsl_test ()"

.SS "def graph2isl\&.main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
