.TH "scripts/graph2isl.py" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/graph2isl.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgraph2isl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgraph2isl\&.gen_jacobi\fP ()"
.br
.ti -1c
.RI "def \fBgraph2isl\&.gen_mfd\fP ()"
.br
.ti -1c
.RI "def \fBgraph2isl\&.gen_csr_spmv\fP ()"
.br
.ti -1c
.RI "def \fBgraph2isl\&.gen_bsr_spmv\fP ()"
.br
.ti -1c
.RI "def \fBgraph2isl\&.gen_csrtobsr\fP (nblocks=8)"
.br
.ti -1c
.RI "def \fBgraph2isl\&.gsl_test\fP ()"
.br
.ti -1c
.RI "def \fBgraph2isl\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
