.TH "lib/gtest/src/gtest-filepath.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gtest/src/gtest-filepath.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\-message\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-filepath\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <climits>\fP
.br
\fC#include 'gtest/internal/gtest\-string\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGTEST_PATH_MAX_\fP   _POSIX_PATH_MAX"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP char \fBtesting::internal::kPathSeparator\fP = '/'"
.br
.ti -1c
.RI "\fBconst\fP char \fBtesting::internal::kCurrentDirectoryString\fP [] = '\&./'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GTEST_PATH_MAX_   _POSIX_PATH_MAX"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
