.TH "lib/gtest/src/gtest-printers.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gtest/src/gtest-printers.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\-printers\&.h'\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <cwchar>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal2\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtesting::internal::CharFormat\fP { \fBtesting::internal::kAsIs\fP, \fBtesting::internal::kHexEscape\fP, \fBtesting::internal::kSpecialEscape\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtesting::internal2::PrintBytesInObjectTo\fP (\fBconst\fP unsigned char *obj_bytes, size_t \fBcount\fP, ostream *os)"
.br
.ti -1c
.RI "bool \fBtesting::internal::IsPrintableAscii\fP (wchar_t \fBc\fP)"
.br
.ti -1c
.RI "template<typename UnsignedChar , typename Char > void \fBtesting::internal::PrintCharAndCodeTo\fP (Char \fBc\fP, ostream *os)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP void \fBtesting::internal::PrintTo\fP (unsigned char \fBc\fP, ::std::ostream *os)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP void \fBtesting::internal::PrintTo\fP (signed char \fBc\fP, ::std::ostream *os)"
.br
.ti -1c
.RI "void \fBtesting::internal::PrintTo\fP (wchar_t wc, ostream *os)"
.br
.ti -1c
.RI "void \fBtesting::internal::UniversalPrintArray\fP (\fBconst\fP char *begin, size_t len, ostream *os)"
.br
.ti -1c
.RI "void \fBtesting::internal::UniversalPrintArray\fP (\fBconst\fP wchar_t *begin, size_t len, ostream *os)"
.br
.ti -1c
.RI "void \fBtesting::internal::PrintTo\fP (\fBconst\fP char *s, ostream *os)"
.br
.ti -1c
.RI "void \fBtesting::internal::PrintTo\fP (\fBconst\fP wchar_t *s, ostream *os)"
.br
.ti -1c
.RI "void \fBtesting::internal::PrintStringTo\fP (\fBconst\fP ::std::string &s, ostream *os)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
