.TH "helpers.VarHelper" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
helpers.VarHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBreplaceChars\fP (formula)"
.br
.ti -1c
.RI "def \fBrestoreChars\fP (formula)"
.br
.ti -1c
.RI "def \fBreplaceIterators\fP (formula, newiters=())"
.br
.ti -1c
.RI "def \fBlistVars\fP (sets)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def helpers\&.VarHelper\&.listVars ( sets)\fC [static]\fP"

.SS "def helpers\&.VarHelper\&.replaceChars ( formula)\fC [static]\fP"

.SS "def helpers\&.VarHelper\&.replaceIterators ( formula,  newiters = \fC()\fP)\fC [static]\fP"

.SS "def helpers\&.VarHelper\&.restoreChars ( formula)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
