.TH "helpers.DotHelper" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
helpers.DotHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBformatLabel\fP (label)"
.br
.ti -1c
.RI "def \fBparseAttrs\fP (attrs)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def helpers\&.DotHelper\&.formatLabel ( label)\fC [static]\fP"

.SS "def helpers\&.DotHelper\&.parseAttrs ( attrs)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
