.TH "hgcd_matrix1" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hgcd_matrix1
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmp\-impl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmp_limb_t\fP \fBu\fP [2][2]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmp_limb_t\fP hgcd_matrix1::u[2][2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
