.TH "hgcd_matrix" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hgcd_matrix
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmp\-impl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmp_size_t\fP \fBalloc\fP"
.br
.ti -1c
.RI "\fBmp_size_t\fP \fBn\fP"
.br
.ti -1c
.RI "\fBmp_ptr\fP \fBp\fP [2][2]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmp_size_t\fP hgcd_matrix::alloc"

.SS "\fBmp_size_t\fP hgcd_matrix::n"

.SS "\fBmp_ptr\fP hgcd_matrix::p[2][2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
