.TH "lib/chill/omega/omega_lib/src/hull_legacy.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/src/hull_legacy.cc
.SH SYNOPSIS
.br
.PP
\fC#include <omega\&.h>\fP
.br
\fC#include <omega/farkas\&.h>\fP
.br
\fC#include <omega/hull\&.h>\fP
.br
\fC#include <basic/Bag\&.h>\fP
.br
\fC#include <basic/omega_error\&.h>\fP
.br
\fC#include <list>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <set>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Relation \fBomega::ConvexHull\fP (\fBNOT_CONST\fP Relation &\fBR\fP)"
.br
.RI "Calculate the Convex Hull of R using the convex combination\&. "
.ti -1c
.RI "Relation \fBomega::DecoupledConvexHull\fP (\fBNOT_CONST\fP Relation &\fBR\fP)"
.br
.RI "Calculate the DecoupledConvex Hull of R\&. "
.ti -1c
.RI "Relation \fBomega::AffineHull\fP (\fBNOT_CONST\fP Relation &\fBR\fP)"
.br
.RI "Calculate the Affine Hull using affine combination\&. "
.ti -1c
.RI "Relation \fBomega::LinearHull\fP (\fBNOT_CONST\fP Relation &\fBR\fP)"
.br
.RI "Calculate the Linear Hull using linear combination\&. "
.ti -1c
.RI "Relation \fBomega::ConicHull\fP (\fBNOT_CONST\fP Relation &\fBR\fP)"
.br
.RI "Calculate the Conic Hull using conic combination\&. "
.ti -1c
.RI "Relation \fBomega::FastTightHull\fP (\fBNOT_CONST\fP Relation &input_R, \fBNOT_CONST\fP Relation &input_H)"
.br
.ti -1c
.RI "Relation \fBomega::QuickHull\fP (Relation &\fBR\fP)"
.br
.ti -1c
.RI "Relation \fBomega::QuickHull\fP (Tuple< Relation > &Rs)"
.br
.ti -1c
.RI "Relation \fBomega::BetterHull\fP (Tuple< Relation > &Rs, bool stridesAllowed, bool checkSubsets, \fBNOT_CONST\fP Relation &input_knownHull=Relation::Null())"
.br
.ti -1c
.RI "Relation \fBomega::Hull\fP (\fBNOT_CONST\fP Relation &\fBR\fP, bool stridesAllowed=false, int effort=1, \fBNOT_CONST\fP Relation &knownHull=Relation::Null())"
.br
.ti -1c
.RI "Relation \fBomega::Hull\fP (Tuple< Relation > &Rs, \fBconst\fP std::vector< bool > &validMask, int effort=1, bool stridesAllowed=false, \fBNOT_CONST\fP Relation &knownHull=Relation::Null())"
.br
.ti -1c
.RI "Relation \fBomega::CheckForConvexRepresentation\fP (\fBNOT_CONST\fP Relation &R_In)"
.br
.ti -1c
.RI "Relation \fBomega::CheckForConvexPairs\fP (\fBNOT_CONST\fP Relation &\fBS\fP)"
.br
.ti -1c
.RI "Relation \fBomega::ConvexRepresentation\fP (\fBNOT_CONST\fP Relation &\fBR\fP)"
.br
.RI "Simplify a union of sets/relations to a minimal (may not be optimal) number of convex regions\&. "
.ti -1c
.RI "Relation \fBomega::RectHull\fP (\fBNOT_CONST\fP Relation &Rel)"
.br
.RI "Calculate the Rect Hull\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "bool change"

.SS "coef_t lb"

.SS "coef_t modulo"

.SS "std::list<std::pair<Relation, Relation> >::iterator pos"

.SS "coef_t size"

.SS "coef_t start"

.SS "coef_t ub"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
