.TH "iegen::IEGenLib" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iegen::IEGenLib
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IEGenLib\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~IEGenLib\fP ()"
.br
.ti -1c
.RI "string \fBadd\fP (\fBconst\fP string &constStr)"
.br
.ti -1c
.RI "string \fBget\fP (\fBconst\fP string &\fBname\fP)"
.br
.ti -1c
.RI "string \fBnewSet\fP (\fBconst\fP string &setStr)"
.br
.ti -1c
.RI "string \fBnewRelation\fP (\fBconst\fP string &relStr)"
.br
.ti -1c
.RI "string \fBapply\fP (\fBconst\fP string &relName, \fBconst\fP string &setName, \fBconst\fP string &resName='')"
.br
.ti -1c
.RI "string \fBdomain\fP (\fBconst\fP string &\fBname\fP)"
.br
.ti -1c
.RI "string \fBinverse\fP (\fBconst\fP string &relName)"
.br
.ti -1c
.RI "string \fBunion_\fP (\fBconst\fP string &lhsName, \fBconst\fP string &rhsName)"
.br
.ti -1c
.RI "string \fBcompose\fP (\fBconst\fP string &lhsName, \fBconst\fP string &rhsName)"
.br
.ti -1c
.RI "string \fBcodegen\fP (\fBconst\fP string &setName)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "iegen::IEGenLib::~IEGenLib ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "string iegen::IEGenLib::add (\fBconst\fP string & constStr)\fC [inline]\fP"
add Add a relation or set\&. 
.SS "string iegen::IEGenLib::apply (\fBconst\fP string & relName, \fBconst\fP string & setName, \fBconst\fP string & resName = \fC''\fP)\fC [inline]\fP"
apply Apply a relation to a set\&. 
.SS "string iegen::IEGenLib::codegen (\fBconst\fP string & setName)\fC [inline]\fP"

.SS "string iegen::IEGenLib::compose (\fBconst\fP string & lhsName, \fBconst\fP string & rhsName)\fC [inline]\fP"
compose Compose two relations\&. 
.SS "string iegen::IEGenLib::domain (\fBconst\fP string & name)\fC [inline]\fP"
domain Return the domain of a set or relation\&. 
.SS "string iegen::IEGenLib::get (\fBconst\fP string & name)\fC [inline]\fP"
get Get a relation or set\&. 
.SS "string iegen::IEGenLib::inverse (\fBconst\fP string & relName)\fC [inline]\fP"
inverse Perform inverse of a relation\&. 
.SS "string iegen::IEGenLib::newRelation (\fBconst\fP string & relStr)\fC [inline]\fP"
newRelation Create a new relation\&. 
.SS "string iegen::IEGenLib::newSet (\fBconst\fP string & setStr)\fC [inline]\fP"
newSet Create a new set\&. 
.SS "string iegen::IEGenLib::union_ (\fBconst\fP string & lhsName, \fBconst\fP string & rhsName)\fC [inline]\fP"
union_ Perform union of two sets or relations\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
