.TH "src/iegenlib/IEGenLib.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/iegenlib/IEGenLib.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <locale>\fP
.br
\fC#include <map>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iegenlib\&.h>\fP
.br
\fC#include <util/Strings\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBiegen::IEGenLib\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBiegen\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCATCH_EXCEPTIONS\fP   1"
.br
.ti -1c
.RI "#define \fBASN_OP\fP   ':='"
.br
.ti -1c
.RI "#define \fBRLT_OP\fP   '\->'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASN_OP   ':='"

.SS "#define CATCH_EXCEPTIONS   1"

.SS "#define RLT_OP   '\->'"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
