.TH "iegenlib::StringIterator" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iegenlib::StringIterator \- An ordered iterator over strings\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringIterator\fP (std::list< std::string > aList)"
.br
.ti -1c
.RI "\fBStringIterator\fP (\fBstd::set\fP< std::string > aSet)"
.br
.ti -1c
.RI "std::string \fBnext\fP ()"
.br
.RI "Returns a pointer to the next string\&. "
.ti -1c
.RI "bool \fBhasNext\fP ()"
.br
.RI "Returns true if there is another string in the iteration\&. "
.in -1c
.SH "Detailed Description"
.PP 
An ordered iterator over strings\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "iegenlib::StringIterator::StringIterator (std::list< std::string > aList)"

.SS "iegenlib::StringIterator::StringIterator (\fBstd::set\fP< std::string > aSet)"

.SH "Member Function Documentation"
.PP 
.SS "bool iegenlib::StringIterator::hasNext ()"

.PP
Returns true if there is another string in the iteration\&. Returns true if there is another symbol in the iteration\&. 
.SS "std::string iegenlib::StringIterator::next ()"

.PP
Returns a pointer to the next string\&. Returns a pointer to the next symbol\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
