.TH "iegenlib.IERel" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iegenlib.IERel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBiegenlib\&.IEObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBformula\fP, \fBname\fP='')"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def iegenlib\&.IERel\&.__init__ ( self,  formula,  name = \fC''\fP)"

.PP
Reimplemented from \fBiegenlib\&.IEObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
