.TH "iegen_to_omega" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iegen_to_omega
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBto_omega\fP (relation, res_id='\fBD\fP')"
.br
.ti -1c
.RI "def \fBisknown\fP (cond, iters, exists, \fBkeywords\fP)"
.br
.ti -1c
.RI "def \fBwrite_macros\fP (ufuncs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBkeywords\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def iegen_to_omega\&.isknown ( cond,  iters,  exists,  keywords)"

.SS "def iegen_to_omega\&.to_omega ( relation,  res_id = \fC'\fBD\fP'\fP)"

.SS "def iegen_to_omega\&.write_macros ( ufuncs)"

.SH "Variable Documentation"
.PP 
.SS "list iegen_to_omega\&.keywords"
\fBInitial value:\fP
.PP
.nf
1 =  ['exists', 'union', 'intersection', 'complement', 'compose', 'inverse', 'domain', 'range',
2             'hull', 'codegen', 'farkas', 'forall', 'given', 'and', 'or', 'not', 'within', 'subsetof',
3             'supersetof', 'symbolic']
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
