.TH "iegenlib.IEObject" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iegenlib.IEObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBiegenlib\&.IERel\fP, and \fBiegenlib\&.IESet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBformula\fP, \fBname\fP='')"
.br
.ti -1c
.RI "def \fB__contains__\fP (self, item)"
.br
.ti -1c
.RI "def \fB__getitem__\fP (self, \fBpos\fP)"
.br
.ti -1c
.RI "def \fB__len__\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.ti -1c
.RI "def \fBfind\fP (self, item)"
.br
.ti -1c
.RI "def \fBformula\fP (self)"
.br
.ti -1c
.RI "def \fBformula\fP (self, formula)"
.br
.ti -1c
.RI "def \fBname\fP (self)"
.br
.ti -1c
.RI "def \fBname\fP (self, name)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def iegenlib\&.IEObject\&.__init__ ( self,  formula,  name = \fC''\fP)"

.PP
Reimplemented in \fBiegenlib\&.IERel\fP, and \fBiegenlib\&.IESet\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def iegenlib\&.IEObject\&.__contains__ ( self,  item)"

.SS "def iegenlib\&.IEObject\&.__getitem__ ( self,  pos)"

.SS "def iegenlib\&.IEObject\&.__len__ ( self)"

.SS "def iegenlib\&.IEObject\&.__repr__ ( self)"

.SS "def iegenlib\&.IEObject\&.__str__ ( self)"

.SS "def iegenlib\&.IEObject\&.find ( self,  item)"

.SS "def iegenlib\&.IEObject\&.formula ( self)"

.SS "def iegenlib\&.IEObject\&.formula ( self,  formula)"

.SS "def iegenlib\&.IEObject\&.name ( self)"

.SS "def iegenlib\&.IEObject\&.name ( self,  name)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
