.TH "iegenlib.IEGenLib" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iegenlib.IEGenLib
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fB__contains__\fP (self, \fBkey\fP)"
.br
.ti -1c
.RI "def \fB__getitem__\fP (self, \fBkey\fP)"
.br
.ti -1c
.RI "def \fB__setitem__\fP (self, \fBkey\fP, \fBval\fP)"
.br
.ti -1c
.RI "def \fBrelations\fP (self)"
.br
.ti -1c
.RI "def \fBsets\fP (self)"
.br
.ti -1c
.RI "def \fBufuncs\fP (self)"
.br
.ti -1c
.RI "def \fBadd\fP (self, rel_or_set, \fBname\fP='')"
.br
.ti -1c
.RI "def \fBapply\fP (self, relname, setname, resname='')"
.br
.ti -1c
.RI "def \fBunion\fP (self, name1, name2, resname='')"
.br
.ti -1c
.RI "def \fBcompose\fP (self, name1, name2, resname='')"
.br
.ti -1c
.RI "def \fBinverse\fP (self, relname, resname='')"
.br
.ti -1c
.RI "def \fBnew_set\fP (self, setstr)"
.br
.ti -1c
.RI "def \fBnew_relation\fP (self, relstr)"
.br
.ti -1c
.RI "def \fBto_omega\fP (self, res_id)"
.br
.ti -1c
.RI "def \fBisknown\fP (self, cond, iters, exists, keywords)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def iegenlib\&.IEGenLib\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def iegenlib\&.IEGenLib\&.__contains__ ( self,  key)"

.SS "def iegenlib\&.IEGenLib\&.__getitem__ ( self,  key)"

.SS "def iegenlib\&.IEGenLib\&.__setitem__ ( self,  key,  val)"

.SS "def iegenlib\&.IEGenLib\&.add ( self,  rel_or_set,  name = \fC''\fP)"

.SS "def iegenlib\&.IEGenLib\&.apply ( self,  relname,  setname,  resname = \fC''\fP)"

.SS "def iegenlib\&.IEGenLib\&.compose ( self,  name1,  name2,  resname = \fC''\fP)"

.SS "def iegenlib\&.IEGenLib\&.inverse ( self,  relname,  resname = \fC''\fP)"

.SS "def iegenlib\&.IEGenLib\&.isknown ( self,  cond,  iters,  exists,  keywords)"

.SS "def iegenlib\&.IEGenLib\&.new_relation ( self,  relstr)"

.SS "def iegenlib\&.IEGenLib\&.new_set ( self,  setstr)"

.SS "def iegenlib\&.IEGenLib\&.relations ( self)"

.SS "def iegenlib\&.IEGenLib\&.sets ( self)"

.SS "def iegenlib\&.IEGenLib\&.to_omega ( self,  res_id)"

.SS "def iegenlib\&.IEGenLib\&.ufuncs ( self)"

.SS "def iegenlib\&.IEGenLib\&.union ( self,  name1,  name2,  resname = \fC''\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
