.TH "iegenlib::assert_exception" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iegenlib::assert_exception
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <util\&.h>\fP
.PP
Inherits logic_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBassert_exception\fP (\fBconst\fP string &error_message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception used when we would normally use an assert\&. We expect certain conditions to apply and when they don't, we throw one of these\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "iegenlib::assert_exception::assert_exception (\fBconst\fP string & error_message)\fC [inline]\fP, \fC [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
