.TH "iegenlib::VisitorIsUFCallParam" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iegenlib::VisitorIsUFCallParam
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisitorIsUFCallParam\fP (int tupleID)"
.br
.ti -1c
.RI "virtual \fB~VisitorIsUFCallParam\fP ()"
.br
.ti -1c
.RI "bool \fBreturnResult\fP ()"
.br
.ti -1c
.RI "void \fBpreVisitTupleVarTerm\fP (\fBiegenlib::TupleVarTerm\fP *t)"
.br
.ti -1c
.RI "void \fBpreVisitExp\fP (\fBiegenlib::Exp\fP *\fBe\fP)"
.br
.ti -1c
.RI "void \fBpostVisitExp\fP (\fBiegenlib::Exp\fP *\fBe\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "iegenlib::VisitorIsUFCallParam::VisitorIsUFCallParam (int tupleID)\fC [inline]\fP"

.SS "virtual iegenlib::VisitorIsUFCallParam::~VisitorIsUFCallParam ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void iegenlib::VisitorIsUFCallParam::postVisitExp (\fBiegenlib::Exp\fP * e)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void iegenlib::VisitorIsUFCallParam::preVisitExp (\fBiegenlib::Exp\fP * e)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void iegenlib::VisitorIsUFCallParam::preVisitTupleVarTerm (\fBiegenlib::TupleVarTerm\fP * t)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "bool iegenlib::VisitorIsUFCallParam::returnResult ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
