.TH "lib/isl/include/isl/ilp.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/ilp.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/aff_type\&.h>\fP
.br
\fC#include <isl/set_type\&.h>\fP
.br
\fC#include <isl/val\&.h>\fP
.br
\fC#include <isl/vec\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_basic_set_max_val\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_set_min_val\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_set_max_val\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_val\fP* isl_basic_set_max_val (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_set_max_val (\fB__isl_keep\fP \fBisl_set\fP * set, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_set_min_val (\fB__isl_keep\fP \fBisl_set\fP * set, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
