.TH "lib/isl/include/isl/deprecated/ilp_int.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/deprecated/ilp_int.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/deprecated/int\&.h>\fP
.br
\fC#include <isl/lp\&.h>\fP
.br
\fC#include <isl/ilp\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_basic_set_max\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fB__isl_keep\fP \fBisl_aff\fP *obj, \fBisl_int\fP *opt)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_set_min\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj, \fBisl_int\fP *opt)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_set_max\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj, \fBisl_int\fP *opt)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "enum \fBisl_lp_result\fP isl_basic_set_max (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fB__isl_keep\fP \fBisl_aff\fP * obj, \fBisl_int\fP * opt)"

.SS "enum \fBisl_lp_result\fP isl_set_max (\fB__isl_keep\fP \fBisl_set\fP * set, \fB__isl_keep\fP \fBisl_aff\fP * obj, \fBisl_int\fP * opt)"

.SS "enum \fBisl_lp_result\fP isl_set_min (\fB__isl_keep\fP \fBisl_set\fP * set, \fB__isl_keep\fP \fBisl_aff\fP * obj, \fBisl_int\fP * opt)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
