.TH "ineq_cmp_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ineq_cmp_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBlen\fP"
.br
.ti -1c
.RI "\fBisl_int\fP * \fBp\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned ineq_cmp_data::len"

.SS "\fBisl_int\fP* ineq_cmp_data::p"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
