.TH "IR_ArrayRef" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_ArrayRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_code\&.hh>\fP
.PP
Inherits \fBIR_Ref\fP\&.
.PP
Inherited by \fBIR_chillArrayRef\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IR_ArrayRef\fP ()"
.br
.ti -1c
.RI "int \fBn_dim\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual \fBomega::CG_outputRepr\fP * \fBindex\fP (int \fBdim\fP) \fBconst\fP =0"
.br
.ti -1c
.RI "virtual \fBIR_ArraySymbol\fP * \fBsymbol\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual std::string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual int \fBelem_size\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual \fBIR_ARRAY_LAYOUT_TYPE\fP \fBlayout_type\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual void \fBDump\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IR_ArrayRef::~IR_ArrayRef ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void IR_ArrayRef::Dump () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIR_Ref\fP\&.
.PP
Reimplemented in \fBIR_chillArrayRef\fP\&.
.SS "virtual int IR_ArrayRef::elem_size () const\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual \fBomega::CG_outputRepr\fP* IR_ArrayRef::index (int dim) const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillArrayRef\fP\&.
.SS "virtual \fBIR_ARRAY_LAYOUT_TYPE\fP IR_ArrayRef::layout_type () const\fC [inline]\fP, \fC [virtual]\fP"

.SS "int IR_ArrayRef::n_dim () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "virtual std::string IR_ArrayRef::name () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.PP
Reimplemented in \fBIR_chillArrayRef\fP\&.
.SS "virtual \fBIR_ArraySymbol\fP* IR_ArrayRef::symbol () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillArrayRef\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
