.TH "lib/chill/ir_chill.hh" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/ir_chill.hh
.SH SYNOPSIS
.br
.PP
\fC#include <omega\&.h>\fP
.br
\fC#include 'ir_code\&.hh'\fP
.br
\fC#include 'chill_error\&.hh'\fP
.br
\fC#include 'chill_ast\&.hh'\fP
.br
\fC#include 'chill_io\&.hh'\fP
.br
\fC#include 'parser\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIR_chillScalarSymbol\fP"
.br
.ti -1c
.RI "struct \fBIR_chillFunctionSymbol\fP"
.br
.ti -1c
.RI "struct \fBIR_chillArraySymbol\fP"
.br
.ti -1c
.RI "struct \fBIR_chillConstantRef\fP"
.br
.ti -1c
.RI "struct \fBIR_chillScalarRef\fP"
.br
.ti -1c
.RI "struct \fBIR_chillFunctionRef\fP"
.br
.ti -1c
.RI "struct \fBIR_chillArrayRef\fP"
.br
.ti -1c
.RI "struct \fBIR_chillPointerArrayRef\fP"
.br
.ti -1c
.RI "struct \fBIR_chillLoop\fP"
.br
.ti -1c
.RI "struct \fBIR_chillBlock\fP"
.br
.ti -1c
.RI "struct \fBIR_chillIf\fP"
.br
.ti -1c
.RI "struct \fBIR_chillPointerSymbol\fP"
.br
.ti -1c
.RI "class \fBIR_chillCode\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOP_LEFT\fP   \fBOP_DEST\fP"
.br
.ti -1c
.RI "#define \fBOP_RIGHT\fP   \fBOP_SRC\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBOP_POSITION\fP { \fBOP_DEST\fP =-1, \fBOP_UNKNOWN\fP, \fBOP_SRC\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfindmanually\fP (\fBchillAST_node\fP *node, char *procname, vector< \fBchillAST_node\fP * > &procs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "vector< \fBchillAST_VarDecl\fP * > \fBVariableDeclarations\fP"
.br
.ti -1c
.RI "vector< \fBchillAST_FunctionDecl\fP * > \fBFunctionDeclarations\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OP_LEFT   \fBOP_DEST\fP"

.SS "#define OP_RIGHT   \fBOP_SRC\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBOP_POSITION\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOP_DEST \fP\fP
.TP
\fB\fIOP_UNKNOWN \fP\fP
.TP
\fB\fIOP_SRC \fP\fP
.SH "Function Documentation"
.PP 
.SS "void findmanually (\fBchillAST_node\fP * node, char * procname, vector< \fBchillAST_node\fP * > & procs)"

.SH "Variable Documentation"
.PP 
.SS "vector<\fBchillAST_FunctionDecl\fP *> FunctionDeclarations"

.SS "vector<\fBchillAST_VarDecl\fP *> VariableDeclarations"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
