.TH "IR_chillLoop" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_chillLoop
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_chill\&.hh>\fP
.PP
Inherits \fBIR_Loop\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR_chillLoop\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_ForStmt\fP *forstmt)"
.br
.ti -1c
.RI "\fB~IR_chillLoop\fP ()"
.br
.ti -1c
.RI "\fBIR_ScalarSymbol\fP * \fBindex\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBlower_bound\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBupper_bound\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_CONDITION_TYPE\fP \fBstop_cond\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_Block\fP * \fBbody\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBstep_size\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_Control\fP * \fBclone\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_Block\fP * \fBconvert\fP ()"
.br
.ti -1c
.RI "virtual void \fBdump\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstep_size_\fP"
.br
.ti -1c
.RI "\fBchillAST_DeclRefExpr\fP * \fBchillindex\fP"
.br
.ti -1c
.RI "\fBchillAST_ForStmt\fP * \fBchillforstmt\fP"
.br
.ti -1c
.RI "\fBchillAST_node\fP * \fBchilllowerbound\fP"
.br
.ti -1c
.RI "\fBchillAST_node\fP * \fBchillupperbound\fP"
.br
.ti -1c
.RI "\fBchillAST_node\fP * \fBchillbody\fP"
.br
.ti -1c
.RI "\fBIR_CONDITION_TYPE\fP \fBconditionoperator\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IR_chillLoop::IR_chillLoop (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_ForStmt\fP * forstmt)"

.SS "IR_chillLoop::~IR_chillLoop ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBIR_Block\fP * IR_chillLoop::body () const\fC [virtual]\fP"

.PP
Implements \fBIR_Loop\fP\&.
.SS "\fBIR_Control\fP * IR_chillLoop::clone () const\fC [virtual]\fP"

.PP
Implements \fBIR_Control\fP\&.
.SS "\fBIR_Block\fP * IR_chillLoop::convert ()\fC [virtual]\fP"

.PP
Implements \fBIR_Control\fP\&.
.SS "void IR_chillLoop::dump () const\fC [virtual]\fP"

.SS "\fBIR_ScalarSymbol\fP* IR_chillLoop::index () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Loop\fP\&.
.SS "\fBCG_outputRepr\fP * IR_chillLoop::lower_bound () const\fC [virtual]\fP"

.PP
Implements \fBIR_Loop\fP\&.
.SS "int IR_chillLoop::step_size () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Loop\fP\&.
.SS "\fBIR_CONDITION_TYPE\fP IR_chillLoop::stop_cond () const\fC [virtual]\fP"

.PP
Implements \fBIR_Loop\fP\&.
.SS "\fBCG_outputRepr\fP * IR_chillLoop::upper_bound () const\fC [virtual]\fP"

.PP
Implements \fBIR_Loop\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBchillAST_node\fP* IR_chillLoop::chillbody"

.SS "\fBchillAST_ForStmt\fP* IR_chillLoop::chillforstmt"

.SS "\fBchillAST_DeclRefExpr\fP* IR_chillLoop::chillindex"

.SS "\fBchillAST_node\fP* IR_chillLoop::chilllowerbound"

.SS "\fBchillAST_node\fP* IR_chillLoop::chillupperbound"

.SS "\fBIR_CONDITION_TYPE\fP IR_chillLoop::conditionoperator"

.SS "int IR_chillLoop::step_size_"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
