.TH "IR_chillFunctionRef" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_chillFunctionRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_chill\&.hh>\fP
.PP
Inherits \fBIR_FunctionRef\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR_chillFunctionRef\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_DeclRefExpr\fP *ins)"
.br
.ti -1c
.RI "bool \fBis_write\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_FunctionSymbol\fP * \fBsymbol\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBIR_Ref\fP &that) \fBconst\fP"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBconvert\fP ()"
.br
.ti -1c
.RI "\fBIR_Ref\fP * \fBclone\fP () \fBconst\fP"
.br
.RI "shallow copy "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchillAST_DeclRefExpr\fP * \fBvs_\fP"
.br
.ti -1c
.RI "int \fBis_write_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IR_chillFunctionRef::IR_chillFunctionRef (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_DeclRefExpr\fP * ins)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBIR_Ref\fP * IR_chillFunctionRef::clone () const\fC [virtual]\fP"

.PP
shallow copy 
.PP
Implements \fBIR_Ref\fP\&.
.SS "\fBomega::CG_outputRepr\fP * IR_chillFunctionRef::convert ()\fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "bool IR_chillFunctionRef::is_write () const\fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "bool IR_chillFunctionRef::operator== (\fBconst\fP \fBIR_Ref\fP & that) const\fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "\fBIR_FunctionSymbol\fP * IR_chillFunctionRef::symbol () const\fC [virtual]\fP"

.PP
Implements \fBIR_FunctionRef\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int IR_chillFunctionRef::is_write_"

.SS "\fBchillAST_DeclRefExpr\fP* IR_chillFunctionRef::vs_"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
