.TH "IR_chillBlock" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_chillBlock
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_chill\&.hh>\fP
.PP
Inherits \fBIR_Block\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR_chillBlock\fP ()"
.br
.ti -1c
.RI "\fBIR_chillBlock\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_node\fP *ast)"
.br
.ti -1c
.RI "\fBIR_chillBlock\fP (\fBconst\fP \fBIR_Code\fP *ir)"
.br
.ti -1c
.RI "\fBIR_chillBlock\fP (\fBconst\fP \fBIR_chillBlock\fP *CB)"
.br
.ti -1c
.RI "\fB~IR_chillBlock\fP ()"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBextract\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBoriginal\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_Control\fP * \fBclone\fP () \fBconst\fP"
.br
.ti -1c
.RI "vector< \fBchillAST_node\fP * > \fBgetStmtList\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBnumstatements\fP ()"
.br
.ti -1c
.RI "void \fBaddStatement\fP (\fBchillAST_node\fP *s)"
.br
.ti -1c
.RI "void \fBdump\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBchillAST_node\fP * > \fBstatements\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IR_chillBlock::IR_chillBlock ()\fC [inline]\fP"

.SS "IR_chillBlock::IR_chillBlock (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_node\fP * ast)\fC [inline]\fP"

.SS "IR_chillBlock::IR_chillBlock (\fBconst\fP \fBIR_Code\fP * ir)\fC [inline]\fP"

.SS "IR_chillBlock::IR_chillBlock (\fBconst\fP \fBIR_chillBlock\fP * CB)\fC [inline]\fP"

.SS "IR_chillBlock::~IR_chillBlock ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void IR_chillBlock::addStatement (\fBchillAST_node\fP * s)"

.SS "\fBIR_Control\fP * IR_chillBlock::clone () const\fC [virtual]\fP"

.PP
Implements \fBIR_Control\fP\&.
.SS "void IR_chillBlock::dump () const"

.SS "\fBCG_outputRepr\fP * IR_chillBlock::extract () const\fC [virtual]\fP"

.PP
Implements \fBIR_Block\fP\&.
.SS "vector< \fBchillAST_node\fP * > IR_chillBlock::getStmtList () const"

.SS "int IR_chillBlock::numstatements ()\fC [inline]\fP"

.SS "\fBCG_outputRepr\fP * IR_chillBlock::original () const\fC [virtual]\fP"

.PP
Implements \fBIR_Block\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBchillAST_node\fP *> IR_chillBlock::statements"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
