.TH "IR_chillPointerSymbol" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_chillPointerSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_chill\&.hh>\fP
.PP
Inherits \fBIR_PointerSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR_chillPointerSymbol\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_VarDecl\fP *v)"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBn_dim\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBIR_Symbol\fP &that) \fBconst\fP"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBsize\fP (int \fBdim\fP) \fBconst\fP"
.br
.ti -1c
.RI "void \fBset_size\fP (int \fBdim\fP, \fBomega::CG_outputRepr\fP *)"
.br
.ti -1c
.RI "\fBIR_Symbol\fP * \fBclone\fP () \fBconst\fP"
.br
.RI "shallow copy "
.ti -1c
.RI "\fBIR_CONSTANT_TYPE\fP \fBelem_type\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchillAST_VarDecl\fP * \fBchillvd\fP"
.br
.ti -1c
.RI "std::string \fBname_\fP"
.br
.ti -1c
.RI "int \fBdim_\fP"
.br
.ti -1c
.RI "std::vector< \fBomega::CG_outputRepr\fP * > \fBdims\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IR_chillPointerSymbol::IR_chillPointerSymbol (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_VarDecl\fP * v)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBIR_Symbol\fP * IR_chillPointerSymbol::clone () const\fC [virtual]\fP"

.PP
shallow copy 
.PP
Implements \fBIR_Symbol\fP\&.
.SS "\fBIR_CONSTANT_TYPE\fP IR_chillPointerSymbol::elem_type () const\fC [virtual]\fP"

.PP
Implements \fBIR_PointerSymbol\fP\&.
.SS "int IR_chillPointerSymbol::n_dim () const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "std::string IR_chillPointerSymbol::name () const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "bool IR_chillPointerSymbol::operator== (\fBconst\fP \fBIR_Symbol\fP & that) const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "void IR_chillPointerSymbol::set_size (int dim, \fBomega::CG_outputRepr\fP *)\fC [virtual]\fP"

.PP
Implements \fBIR_PointerSymbol\fP\&.
.SS "\fBomega::CG_outputRepr\fP * IR_chillPointerSymbol::size (int dim) const\fC [virtual]\fP"

.PP
Implements \fBIR_PointerSymbol\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBchillAST_VarDecl\fP* IR_chillPointerSymbol::chillvd"

.SS "int IR_chillPointerSymbol::dim_"

.SS "std::vector<\fBomega::CG_outputRepr\fP *> IR_chillPointerSymbol::dims"

.SS "std::string IR_chillPointerSymbol::name_"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
