.TH "IR_chillScalarSymbol" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_chillScalarSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_chill\&.hh>\fP
.PP
Inherits \fBIR_ScalarSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR_chillScalarSymbol\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_VarDecl\fP *vd)"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBIR_Symbol\fP &that) \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_Symbol\fP * \fBclone\fP () \fBconst\fP"
.br
.RI "shallow copy "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchillAST_VarDecl\fP * \fBchillvd\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IR_chillScalarSymbol::IR_chillScalarSymbol (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_VarDecl\fP * vd)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBIR_Symbol\fP * IR_chillScalarSymbol::clone () const\fC [virtual]\fP"

.PP
shallow copy 
.PP
Implements \fBIR_Symbol\fP\&.
.SS "string IR_chillScalarSymbol::name () const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "bool IR_chillScalarSymbol::operator== (\fBconst\fP \fBIR_Symbol\fP & that) const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "int IR_chillScalarSymbol::size () const\fC [virtual]\fP"

.PP
Implements \fBIR_ScalarSymbol\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBchillAST_VarDecl\fP* IR_chillScalarSymbol::chillvd"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
