.TH "IR_chillFunctionSymbol" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_chillFunctionSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_chill\&.hh>\fP
.PP
Inherits \fBIR_FunctionSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR_chillFunctionSymbol\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_DeclRefExpr\fP *fs)"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBIR_Symbol\fP &that) \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_Symbol\fP * \fBclone\fP () \fBconst\fP"
.br
.RI "shallow copy "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchillAST_DeclRefExpr\fP * \fBfs_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IR_chillFunctionSymbol::IR_chillFunctionSymbol (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_DeclRefExpr\fP * fs)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBIR_Symbol\fP * IR_chillFunctionSymbol::clone () const\fC [virtual]\fP"

.PP
shallow copy 
.PP
Implements \fBIR_Symbol\fP\&.
.SS "std::string IR_chillFunctionSymbol::name () const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "bool IR_chillFunctionSymbol::operator== (\fBconst\fP \fBIR_Symbol\fP & that) const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBchillAST_DeclRefExpr\fP* IR_chillFunctionSymbol::fs_"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
