.TH "IR_chillConstantRef" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_chillConstantRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_chill\&.hh>\fP
.PP
Inherits \fBIR_ConstantRef\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR_chillConstantRef\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBomega::coef_t\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBIR_chillConstantRef\fP (\fBconst\fP \fBIR_Code\fP *ir, double \fBf\fP)"
.br
.ti -1c
.RI "\fBomega::coef_t\fP \fBinteger\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBIR_Ref\fP &that) \fBconst\fP"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBconvert\fP ()"
.br
.ti -1c
.RI "\fBIR_Ref\fP * \fBclone\fP () \fBconst\fP"
.br
.RI "shallow copy "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBomega::coef_t\fP \fBi_\fP"
.br
.ti -1c
.RI "   double \fBf_\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IR_chillConstantRef::IR_chillConstantRef (\fBconst\fP \fBIR_Code\fP * ir, \fBomega::coef_t\fP i)\fC [inline]\fP"

.SS "IR_chillConstantRef::IR_chillConstantRef (\fBconst\fP \fBIR_Code\fP * ir, double f)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBIR_Ref\fP * IR_chillConstantRef::clone () const\fC [virtual]\fP"

.PP
shallow copy 
.PP
Implements \fBIR_Ref\fP\&.
.SS "\fBCG_outputRepr\fP * IR_chillConstantRef::convert ()\fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "\fBomega::coef_t\fP IR_chillConstantRef::integer () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_ConstantRef\fP\&.
.SS "bool IR_chillConstantRef::operator== (\fBconst\fP \fBIR_Ref\fP & that) const\fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "union { \&.\&.\&. } "

.SS "double IR_chillConstantRef::f_"

.SS "\fBomega::coef_t\fP IR_chillConstantRef::i_"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
