.TH "lib/chill/ir_chill.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/ir_chill.cc
.SH SYNOPSIS
.br
.PP
\fC#include <typeinfo>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'ir_chill\&.hh'\fP
.br
\fC#include 'loop\&.hh'\fP
.br
\fC#include 'chill_error\&.hh'\fP
.br
\fC#include 'code_gen/CG_chillRepr\&.h'\fP
.br
\fC#include 'code_gen/CG_chillBuilder\&.h'\fP
.br
\fC#include 'chill_ast\&.hh'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDUMPFUNC\fP(\fBx\fP,  \fBy\fP)   cerr << 'In function ' << x << '\\n'; y\->dump();"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfindmanually\fP (\fBchillAST_node\fP *node, char *procname, vector< \fBchillAST_node\fP * > &procs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "vector< \fBchillAST_VarDecl\fP * > \fBVariableDeclarations\fP"
.br
.ti -1c
.RI "vector< \fBchillAST_FunctionDecl\fP * > \fBFunctionDeclarations\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DUMPFUNC(\fBx\fP, \fBy\fP)   cerr << 'In function ' << x << '\\n'; y\->dump();"

.SH "Function Documentation"
.PP 
.SS "void findmanually (\fBchillAST_node\fP * node, char * procname, vector< \fBchillAST_node\fP * > & procs)"

.SH "Variable Documentation"
.PP 
.SS "vector<\fBchillAST_FunctionDecl\fP *> FunctionDeclarations"

.SS "vector< \fBchillAST_VarDecl\fP * > VariableDeclarations"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
