.TH "IR_chillArrayRef" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_chillArrayRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_chill\&.hh>\fP
.PP
Inherits \fBIR_ArrayRef\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR_chillArrayRef\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_ArraySubscriptExpr\fP *ase, int \fBwrite\fP)"
.br
.ti -1c
.RI "\fBIR_chillArrayRef\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_ArraySubscriptExpr\fP *ase, \fBconst\fP char *printname, int \fBwrite\fP)"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBis_write\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBindex\fP (int \fBdim\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_ArraySymbol\fP * \fBsymbol\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBconst\fP \fBIR_Ref\fP &that) \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBIR_Ref\fP &that) \fBconst\fP"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBconvert\fP ()"
.br
.ti -1c
.RI "\fBIR_Ref\fP * \fBclone\fP () \fBconst\fP"
.br
.RI "shallow copy "
.ti -1c
.RI "virtual void \fBDump\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchillAST_ArraySubscriptExpr\fP * \fBchillASE\fP"
.br
.ti -1c
.RI "char * \fBprintable\fP"
.br
.ti -1c
.RI "int \fBiswrite\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IR_chillArrayRef::IR_chillArrayRef (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_ArraySubscriptExpr\fP * ase, int write)\fC [inline]\fP"

.SS "IR_chillArrayRef::IR_chillArrayRef (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_ArraySubscriptExpr\fP * ase, \fBconst\fP char * printname, int write)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBIR_Ref\fP * IR_chillArrayRef::clone () const\fC [virtual]\fP"

.PP
shallow copy 
.PP
Implements \fBIR_Ref\fP\&.
.SS "\fBCG_outputRepr\fP * IR_chillArrayRef::convert ()\fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "void IR_chillArrayRef::Dump () const\fC [virtual]\fP"

.PP
Reimplemented from \fBIR_ArrayRef\fP\&.
.SS "\fBCG_outputRepr\fP * IR_chillArrayRef::index (int dim) const\fC [virtual]\fP"

.PP
Implements \fBIR_ArrayRef\fP\&.
.SS "bool IR_chillArrayRef::is_write () const\fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "string IR_chillArrayRef::name () const\fC [virtual]\fP"

.PP
Reimplemented from \fBIR_ArrayRef\fP\&.
.SS "bool IR_chillArrayRef::operator!= (\fBconst\fP \fBIR_Ref\fP & that) const\fC [virtual]\fP"

.PP
Reimplemented from \fBIR_Ref\fP\&.
.SS "bool IR_chillArrayRef::operator== (\fBconst\fP \fBIR_Ref\fP & that) const\fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "\fBIR_ArraySymbol\fP * IR_chillArrayRef::symbol () const\fC [virtual]\fP"

.PP
Implements \fBIR_ArrayRef\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBchillAST_ArraySubscriptExpr\fP* IR_chillArrayRef::chillASE"

.SS "int IR_chillArrayRef::iswrite"

.SS "char* IR_chillArrayRef::printable"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
