.TH "IR_chillArraySymbol" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_chillArraySymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_chill\&.hh>\fP
.PP
Inherits \fBIR_ArraySymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR_chillArraySymbol\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_VarDecl\fP *vd, int \fBoffset\fP=0)"
.br
.ti -1c
.RI "\fBIR_chillArraySymbol\fP (\fBconst\fP \fBIR_Code\fP *ir, \fBchillAST_node\fP *\fBn\fP, int \fBoffset\fP=0)"
.br
.ti -1c
.RI "\fBIR_ARRAY_LAYOUT_TYPE\fP \fBlayout_type\fP () \fBconst\fP"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBelem_size\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_CONSTANT_TYPE\fP \fBelem_type\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBn_dim\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBsize\fP (int \fBdim\fP) \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBconst\fP \fBIR_Symbol\fP &that) \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBIR_Symbol\fP &that) \fBconst\fP"
.br
.ti -1c
.RI "\fBIR_Symbol\fP * \fBclone\fP () \fBconst\fP"
.br
.RI "shallow copy "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBoffset_\fP"
.br
.ti -1c
.RI "\fBchillAST_node\fP * \fBbase\fP"
.br
.ti -1c
.RI "\fBchillAST_VarDecl\fP * \fBchillvd\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IR_chillArraySymbol::IR_chillArraySymbol (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_VarDecl\fP * vd, int offset = \fC0\fP)\fC [inline]\fP"

.SS "IR_chillArraySymbol::IR_chillArraySymbol (\fBconst\fP \fBIR_Code\fP * ir, \fBchillAST_node\fP * n, int offset = \fC0\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBIR_Symbol\fP * IR_chillArraySymbol::clone () const\fC [virtual]\fP"

.PP
shallow copy 
.PP
Implements \fBIR_Symbol\fP\&.
.SS "int IR_chillArraySymbol::elem_size () const\fC [virtual]\fP"

.PP
Implements \fBIR_ArraySymbol\fP\&.
.SS "\fBIR_CONSTANT_TYPE\fP IR_chillArraySymbol::elem_type () const\fC [virtual]\fP"

.PP
Implements \fBIR_ArraySymbol\fP\&.
.SS "\fBIR_ARRAY_LAYOUT_TYPE\fP IR_chillArraySymbol::layout_type () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_ArraySymbol\fP\&.
.SS "int IR_chillArraySymbol::n_dim () const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "string IR_chillArraySymbol::name () const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "bool IR_chillArraySymbol::operator!= (\fBconst\fP \fBIR_Symbol\fP & that) const\fC [virtual]\fP"

.PP
Reimplemented from \fBIR_Symbol\fP\&.
.SS "bool IR_chillArraySymbol::operator== (\fBconst\fP \fBIR_Symbol\fP & that) const\fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "\fBCG_outputRepr\fP * IR_chillArraySymbol::size (int dim) const\fC [virtual]\fP"

.PP
Implements \fBIR_ArraySymbol\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBchillAST_node\fP* IR_chillArraySymbol::base"

.SS "\fBchillAST_VarDecl\fP* IR_chillArraySymbol::chillvd"

.SS "int IR_chillArraySymbol::offset_"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
