.TH "IR_ConstantRef" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_ConstantRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_code\&.hh>\fP
.PP
Inherits \fBIR_Ref\fP\&.
.PP
Inherited by \fBIR_chillConstantRef\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IR_ConstantRef\fP ()"
.br
.ti -1c
.RI "int \fBn_dim\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBis_write\fP () \fBconst\fP"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual bool \fBis_integer\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual \fBomega::coef_t\fP \fBinteger\fP () \fBconst\fP =0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIR_CONSTANT_TYPE\fP \fBtype_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IR_ConstantRef::~IR_ConstantRef ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBomega::coef_t\fP IR_ConstantRef::integer () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillConstantRef\fP\&.
.SS "virtual bool IR_ConstantRef::is_integer () const\fC [inline]\fP, \fC [virtual]\fP"

.SS "bool IR_ConstantRef::is_write () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "int IR_ConstantRef::n_dim () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "std::string IR_ConstantRef::name () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBIR_CONSTANT_TYPE\fP IR_ConstantRef::type_"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
