.TH "ir_exp_error" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ir_exp_error \- specific for expression to presburger math translation problem  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chill_error\&.hh>\fP
.PP
Inherits \fBir_error\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBir_exp_error\fP (\fBconst\fP std::string &msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
specific for expression to presburger math translation problem 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ir_exp_error::ir_exp_error (\fBconst\fP std::string & msg)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
