.TH "ir_error" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ir_error \- for generic compiler intermediate code handling problem  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chill_error\&.hh>\fP
.PP
Inherits runtime_error\&.
.PP
Inherited by \fBir_exp_error\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBir_error\fP (\fBconst\fP std::string &msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
for generic compiler intermediate code handling problem 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ir_error::ir_error (\fBconst\fP std::string & msg)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
