.TH "IR_FunctionRef" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_FunctionRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_code\&.hh>\fP
.PP
Inherits \fBIR_Ref\fP\&.
.PP
Inherited by \fBIR_chillFunctionRef\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IR_FunctionRef\fP ()"
.br
.ti -1c
.RI "int \fBn_dim\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual \fBIR_FunctionSymbol\fP * \fBsymbol\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IR_FunctionRef::~IR_FunctionRef ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int IR_FunctionRef::n_dim () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "std::string IR_FunctionRef::name () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "virtual \fBIR_FunctionSymbol\fP* IR_FunctionRef::symbol () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillFunctionRef\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
