.TH "IR_Loop" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_Loop
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_code\&.hh>\fP
.PP
Inherits \fBIR_Control\fP\&.
.PP
Inherited by \fBIR_chillLoop\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IR_Loop\fP ()"
.br
.ti -1c
.RI "virtual \fBIR_ScalarSymbol\fP * \fBindex\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual \fBomega::CG_outputRepr\fP * \fBlower_bound\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual \fBomega::CG_outputRepr\fP * \fBupper_bound\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual \fBIR_CONDITION_TYPE\fP \fBstop_cond\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual \fBIR_Block\fP * \fBbody\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual int \fBstep_size\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBIR_CONTROL_TYPE\fP \fBtype\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IR_Loop::~IR_Loop ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBIR_Block\fP* IR_Loop::body () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillLoop\fP\&.
.SS "virtual \fBIR_ScalarSymbol\fP* IR_Loop::index () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillLoop\fP\&.
.SS "virtual \fBomega::CG_outputRepr\fP* IR_Loop::lower_bound () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillLoop\fP\&.
.SS "virtual int IR_Loop::step_size () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillLoop\fP\&.
.SS "virtual \fBIR_CONDITION_TYPE\fP IR_Loop::stop_cond () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillLoop\fP\&.
.SS "\fBIR_CONTROL_TYPE\fP IR_Loop::type () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Control\fP\&.
.SS "virtual \fBomega::CG_outputRepr\fP* IR_Loop::upper_bound () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillLoop\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
