.TH "IR_PointerSymbol" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_PointerSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_code\&.hh>\fP
.PP
Inherits \fBIR_Symbol\fP\&.
.PP
Inherited by \fBIR_chillPointerSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IR_PointerSymbol\fP ()"
.br
.ti -1c
.RI "virtual \fBomega::CG_outputRepr\fP * \fBsize\fP (int \fBdim\fP) \fBconst\fP =0"
.br
.ti -1c
.RI "virtual void \fBset_size\fP (int \fBdim\fP, \fBomega::CG_outputRepr\fP *)=0"
.br
.ti -1c
.RI "virtual \fBIR_CONSTANT_TYPE\fP \fBelem_type\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "bool \fBisPointer\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IR_PointerSymbol::~IR_PointerSymbol ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBIR_CONSTANT_TYPE\fP IR_PointerSymbol::elem_type () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillPointerSymbol\fP\&.
.SS "bool IR_PointerSymbol::isPointer () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIR_Symbol\fP\&.
.SS "virtual void IR_PointerSymbol::set_size (int dim, \fBomega::CG_outputRepr\fP *)\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillPointerSymbol\fP\&.
.SS "virtual \fBomega::CG_outputRepr\fP* IR_PointerSymbol::size (int dim) const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillPointerSymbol\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
