.TH "IR_PointerArrayRef" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_PointerArrayRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_code\&.hh>\fP
.PP
Inherits \fBIR_Ref\fP\&.
.PP
Inherited by \fBIR_chillPointerArrayRef\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IR_PointerArrayRef\fP ()"
.br
.ti -1c
.RI "int \fBn_dim\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual \fBomega::CG_outputRepr\fP * \fBindex\fP (int \fBdim\fP) \fBconst\fP =0"
.br
.ti -1c
.RI "virtual \fBIR_PointerSymbol\fP * \fBsymbol\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBIR_Code\fP * \fBir_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IR_PointerArrayRef::~IR_PointerArrayRef ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBomega::CG_outputRepr\fP* IR_PointerArrayRef::index (int dim) const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillPointerArrayRef\fP\&.
.SS "int IR_PointerArrayRef::n_dim () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "std::string IR_PointerArrayRef::name () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "virtual \fBIR_PointerSymbol\fP* IR_PointerArrayRef::symbol () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillPointerArrayRef\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP \fBIR_Code\fP* IR_PointerArrayRef::ir_"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
