.TH "IR_ScalarSymbol" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_ScalarSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_code\&.hh>\fP
.PP
Inherits \fBIR_Symbol\fP\&.
.PP
Inherited by \fBIR_chillScalarSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IR_ScalarSymbol\fP ()"
.br
.ti -1c
.RI "int \fBn_dim\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual int \fBsize\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "bool \fBisScalar\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IR_ScalarSymbol::~IR_ScalarSymbol ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool IR_ScalarSymbol::isScalar () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBIR_Symbol\fP\&.
.SS "int IR_ScalarSymbol::n_dim () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Symbol\fP\&.
.SS "virtual int IR_ScalarSymbol::size () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillScalarSymbol\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
