.TH "IR_ScalarRef" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR_ScalarRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ir_code\&.hh>\fP
.PP
Inherits \fBIR_Ref\fP\&.
.PP
Inherited by \fBIR_chillScalarRef\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IR_ScalarRef\fP ()"
.br
.ti -1c
.RI "int \fBn_dim\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual \fBIR_ScalarSymbol\fP * \fBsymbol\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "std::string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual int \fBsize\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IR_ScalarRef::~IR_ScalarRef ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int IR_ScalarRef::n_dim () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "std::string IR_ScalarRef::name () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIR_Ref\fP\&.
.SS "virtual int IR_ScalarRef::size () const\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual \fBIR_ScalarSymbol\fP* IR_ScalarRef::symbol () const\fC [pure virtual]\fP"

.PP
Implemented in \fBIR_chillScalarRef\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
