.TH "isl_band" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_band
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_band_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int * \fBcoincident\fP"
.br
.ti -1c
.RI "\fBisl_union_pw_multi_aff\fP * \fBpma\fP"
.br
.ti -1c
.RI "\fBisl_schedule\fP * \fBschedule\fP"
.br
.ti -1c
.RI "\fBisl_band\fP * \fBparent\fP"
.br
.ti -1c
.RI "isl_band_list * \fBchildren\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "isl_band_list* isl_band::children"

.SS "int* isl_band::coincident"

.SS "int isl_band::n"

.SS "\fBisl_band\fP* isl_band::parent"

.SS "\fBisl_union_pw_multi_aff\fP* isl_band::pma"

.SS "int isl_band::ref"

.SS "\fBisl_schedule\fP* isl_band::schedule"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
