.TH "isl_ctx" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_ctx
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_ctx_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "struct \fBisl_stats\fP * \fBstats\fP"
.br
.ti -1c
.RI "int \fBopt_allocated\fP"
.br
.ti -1c
.RI "struct \fBisl_options\fP * \fBopt\fP"
.br
.ti -1c
.RI "void * \fBuser_opt\fP"
.br
.ti -1c
.RI "struct \fBisl_args\fP * \fBuser_args\fP"
.br
.ti -1c
.RI "\fBisl_int\fP \fBzero\fP"
.br
.ti -1c
.RI "\fBisl_int\fP \fBone\fP"
.br
.ti -1c
.RI "\fBisl_int\fP \fBtwo\fP"
.br
.ti -1c
.RI "\fBisl_int\fP \fBnegone\fP"
.br
.ti -1c
.RI "\fBisl_int\fP \fBnormalize_gcd\fP"
.br
.ti -1c
.RI "int \fBn_cached\fP"
.br
.ti -1c
.RI "int \fBn_miss\fP"
.br
.ti -1c
.RI "struct \fBisl_blk\fP \fBcache\fP [\fBISL_BLK_CACHE_SIZE\fP]"
.br
.ti -1c
.RI "struct \fBisl_hash_table\fP \fBid_table\fP"
.br
.ti -1c
.RI "enum \fBisl_error\fP \fBerror\fP"
.br
.ti -1c
.RI "int \fBabort\fP"
.br
.ti -1c
.RI "unsigned long \fBoperations\fP"
.br
.ti -1c
.RI "unsigned long \fBmax_operations\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_ctx::abort"

.SS "struct \fBisl_blk\fP isl_ctx::cache[\fBISL_BLK_CACHE_SIZE\fP]"

.SS "enum \fBisl_error\fP isl_ctx::error"

.SS "struct \fBisl_hash_table\fP isl_ctx::id_table"

.SS "unsigned long isl_ctx::max_operations"

.SS "int isl_ctx::n_cached"

.SS "int isl_ctx::n_miss"

.SS "\fBisl_int\fP isl_ctx::negone"

.SS "\fBisl_int\fP isl_ctx::normalize_gcd"

.SS "\fBisl_int\fP isl_ctx::one"

.SS "unsigned long isl_ctx::operations"

.SS "struct \fBisl_options\fP* isl_ctx::opt"

.SS "int isl_ctx::opt_allocated"

.SS "int isl_ctx::ref"

.SS "struct \fBisl_stats\fP* isl_ctx::stats"

.SS "\fBisl_int\fP isl_ctx::two"

.SS "struct \fBisl_args\fP* isl_ctx::user_args"

.SS "void* isl_ctx::user_opt"

.SS "\fBisl_int\fP isl_ctx::zero"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
