.TH "isl_args" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBoptions_size\fP"
.br
.ti -1c
.RI "struct \fBisl_arg\fP * \fBargs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_arg\fP* isl_args::args"

.SS "size_t isl_args::options_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
