.TH "lib/isl/isl_vec_private.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_vec_private.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl_blk\&.h>\fP
.br
\fC#include <isl/vec\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_vec\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vec\fP * \fBisl_vec_cow\fP (\fB__isl_take\fP \fBisl_vec\fP *vec)"
.br
.ti -1c
.RI "void \fBisl_vec_lcm\fP (struct \fBisl_vec\fP *vec, \fBisl_int\fP *\fBlcm\fP)"
.br
.ti -1c
.RI "int \fBisl_vec_get_element\fP (\fB__isl_keep\fP \fBisl_vec\fP *vec, int \fBpos\fP, \fBisl_int\fP *v)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vec\fP * \fBisl_vec_set\fP (\fB__isl_take\fP \fBisl_vec\fP *vec, \fBisl_int\fP v)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_vec\fP* isl_vec_cow (\fB__isl_take\fP \fBisl_vec\fP * vec)"

.SS "int isl_vec_get_element (\fB__isl_keep\fP \fBisl_vec\fP * vec, int pos, \fBisl_int\fP * v)"

.SS "void isl_vec_lcm (struct \fBisl_vec\fP * vec, \fBisl_int\fP * lcm)"

.SS "\fB__isl_give\fP \fBisl_vec\fP* isl_vec_set (\fB__isl_take\fP \fBisl_vec\fP * vec, \fBisl_int\fP v)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
