.TH "lib/isl/isl_basis_reduction.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_basis_reduction.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/set\&.h>\fP
.br
\fC#include <isl_mat_private\&.h>\fP
.br
\fC#include 'isl_tab\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBisl_tab\fP * \fBisl_tab_compute_reduced_basis\fP (struct \fBisl_tab\fP *tab)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBisl_tab\fP* isl_tab_compute_reduced_basis (struct \fBisl_tab\fP * tab)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
