.TH "isl_term" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_term
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_polynomial_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_int\fP \fBn\fP"
.br
.ti -1c
.RI "\fBisl_int\fP \fBd\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.ti -1c
.RI "struct \fBisl_mat\fP * \fBdiv\fP"
.br
.ti -1c
.RI "int \fBpow\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_int\fP isl_term::d"

.SS "\fBisl_space\fP* isl_term::dim"

.SS "struct \fBisl_mat\fP* isl_term::div"

.SS "\fBisl_int\fP isl_term::n"

.SS "int isl_term::pow[1]"

.SS "int isl_term::ref"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
