.TH "isl_aff_split" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_aff_split
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_basic_map\fP * \fBaff\fP"
.br
.ti -1c
.RI "\fBisl_map\fP * \fBmap\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_basic_map\fP* isl_aff_split::aff"

.SS "\fBisl_map\fP* isl_aff_split::map"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
