.TH "isl_schedule_node_get_filter_prefix_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_schedule_node_get_filter_prefix_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBinitialized\fP"
.br
.ti -1c
.RI "int \fBuniverse_domain\fP"
.br
.ti -1c
.RI "int \fBuniverse_filter\fP"
.br
.ti -1c
.RI "int \fBcollect_prefix\fP"
.br
.ti -1c
.RI "\fBisl_union_set\fP * \fBfilter\fP"
.br
.ti -1c
.RI "\fBisl_multi_union_pw_aff\fP * \fBprefix\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_schedule_node_get_filter_prefix_data::collect_prefix"

.SS "\fBisl_union_set\fP* isl_schedule_node_get_filter_prefix_data::filter"

.SS "int isl_schedule_node_get_filter_prefix_data::initialized"

.SS "\fBisl_multi_union_pw_aff\fP* isl_schedule_node_get_filter_prefix_data::prefix"

.SS "int isl_schedule_node_get_filter_prefix_data::universe_domain"

.SS "int isl_schedule_node_get_filter_prefix_data::universe_filter"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
