.TH "isl_check_scaled_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_check_scaled_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "\fBisl_val\fP * \fBm\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_check_scaled_data::depth"

.SS "\fBisl_val\fP* isl_check_scaled_data::m"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
