.TH "isl_tarjan_graph" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_tarjan_graph
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_tarjan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "struct \fBisl_tarjan_node\fP * \fBnode\fP"
.br
.ti -1c
.RI "int * \fBstack\fP"
.br
.ti -1c
.RI "int \fBsp\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int * \fBorder\fP"
.br
.ti -1c
.RI "int \fBop\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_tarjan_graph::index"

.SS "int isl_tarjan_graph::len"

.SS "struct \fBisl_tarjan_node\fP* isl_tarjan_graph::node"

.SS "int isl_tarjan_graph::op"

.SS "int* isl_tarjan_graph::order"

.SS "int isl_tarjan_graph::sp"

.SS "int* isl_tarjan_graph::stack"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
