.TH "isl_compute_flow_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_compute_flow_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_union_map\fP * \fBmust_source\fP"
.br
.ti -1c
.RI "\fBisl_union_map\fP * \fBmay_source\fP"
.br
.ti -1c
.RI "\fBisl_union_flow\fP * \fBflow\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBmust\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.ti -1c
.RI "struct \fBisl_sched_info\fP * \fBsink_info\fP"
.br
.ti -1c
.RI "struct \fBisl_sched_info\fP ** \fBsource_info\fP"
.br
.ti -1c
.RI "\fBisl_access_info\fP * \fBaccesses\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_access_info\fP* isl_compute_flow_data::accesses"

.SS "int isl_compute_flow_data::count"

.SS "\fBisl_space\fP* isl_compute_flow_data::dim"

.SS "\fBisl_union_flow\fP* isl_compute_flow_data::flow"

.SS "\fBisl_union_map\fP* isl_compute_flow_data::may_source"

.SS "int isl_compute_flow_data::must"

.SS "\fBisl_union_map\fP* isl_compute_flow_data::must_source"

.SS "struct \fBisl_sched_info\fP* isl_compute_flow_data::sink_info"

.SS "struct \fBisl_sched_info\fP** isl_compute_flow_data::source_info"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
