.TH "isl_forall_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_forall_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_bool\fP \fBres\fP"
.br
.ti -1c
.RI "\fBisl_bool\fP(* \fBfn\fP )(\fB__isl_keep\fP \fBisl_map\fP *\fBmap\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_bool\fP(* isl_forall_data::fn) (\fB__isl_keep\fP \fBisl_map\fP *\fBmap\fP)"

.SS "\fBisl_bool\fP isl_forall_data::res"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
