.TH "isl_from_pw_aff_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_from_pw_aff_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_ast_build\fP * \fBbuild\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "\fBisl_ast_expr\fP ** \fBnext\fP"
.br
.ti -1c
.RI "\fBisl_set\fP * \fBdom\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_ast_build\fP* isl_from_pw_aff_data::build"

.SS "\fBisl_set\fP* isl_from_pw_aff_data::dom"

.SS "int isl_from_pw_aff_data::n"

.SS "\fBisl_ast_expr\fP** isl_from_pw_aff_data::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
