.TH "isl_tab_var" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_tab_var
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_tab\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "unsigned \fBis_row\fP: 1"
.br
.ti -1c
.RI "unsigned \fBis_nonneg\fP: 1"
.br
.ti -1c
.RI "unsigned \fBis_zero\fP: 1"
.br
.ti -1c
.RI "unsigned \fBis_redundant\fP: 1"
.br
.ti -1c
.RI "unsigned \fBmarked\fP: 1"
.br
.ti -1c
.RI "unsigned \fBfrozen\fP: 1"
.br
.ti -1c
.RI "unsigned \fBnegated\fP: 1"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned isl_tab_var::frozen"

.SS "int isl_tab_var::index"

.SS "unsigned isl_tab_var::is_nonneg"

.SS "unsigned isl_tab_var::is_redundant"

.SS "unsigned isl_tab_var::is_row"

.SS "unsigned isl_tab_var::is_zero"

.SS "unsigned isl_tab_var::marked"

.SS "unsigned isl_tab_var::negated"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
