.TH "isl_token" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_token
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_stream_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "unsigned int \fBon_new_line\fP: 1"
.br
.ti -1c
.RI "unsigned \fBis_keyword\fP: 1"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "int \fBcol\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBisl_int\fP \fBv\fP"
.br
.ti -1c
.RI "   char * \fBs\fP"
.br
.ti -1c
.RI "   \fBisl_map\fP * \fBmap\fP"
.br
.ti -1c
.RI "   \fBisl_pw_aff\fP * \fBpwaff\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_token::col"

.SS "unsigned isl_token::is_keyword"

.SS "int isl_token::line"

.SS "\fBisl_map\fP* isl_token::map"

.SS "unsigned int isl_token::on_new_line"

.SS "\fBisl_pw_aff\fP* isl_token::pwaff"

.SS "char* isl_token::s"

.SS "int isl_token::type"

.SS "union { \&.\&.\&. }  isl_token::u"

.SS "\fBisl_int\fP isl_token::v"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
