.TH "isl_qpolynomial" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_qpolynomial
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_polynomial_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.ti -1c
.RI "struct \fBisl_mat\fP * \fBdiv\fP"
.br
.ti -1c
.RI "struct \fBisl_upoly\fP * \fBupoly\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_space\fP* isl_qpolynomial::dim"

.SS "struct \fBisl_mat\fP* isl_qpolynomial::div"

.SS "int isl_qpolynomial::ref"

.SS "struct \fBisl_upoly\fP* isl_qpolynomial::upoly"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
