.TH "isl_external_vertex" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_external_vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_vertices_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_vertices\fP * \fBvertices\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_external_vertex::id"

.SS "\fBisl_vertices\fP* isl_external_vertex::vertices"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
