.TH "isl_ast_expr" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_ast_expr
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_ast_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_ctx\fP * \fBctx\fP"
.br
.ti -1c
.RI "enum \fBisl_ast_expr_type\fP \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBisl_val\fP * \fBv\fP"
.br
.ti -1c
.RI "   \fBisl_id\fP * \fBid\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      enum \fBisl_ast_op_type\fP \fBop\fP"
.br
.ti -1c
.RI "      unsigned \fBn_arg\fP"
.br
.ti -1c
.RI "      \fBisl_ast_expr\fP ** \fBargs\fP"
.br
.ti -1c
.RI "   } \fBop\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_ast_expr\fP** isl_ast_expr::args"

.SS "\fBisl_ctx\fP* isl_ast_expr::ctx"

.SS "\fBisl_id\fP* isl_ast_expr::id"

.SS "unsigned isl_ast_expr::n_arg"

.SS "enum \fBisl_ast_op_type\fP isl_ast_expr::op"

.SS "struct { \&.\&.\&. }  isl_ast_expr::op"

.SS "int isl_ast_expr::ref"

.SS "enum \fBisl_ast_expr_type\fP isl_ast_expr::type"

.SS "union { \&.\&.\&. }  isl_ast_expr::u"

.SS "\fBisl_val\fP* isl_ast_expr::v"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
