.TH "lib/isl/isl_sort.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_sort.c
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <isl_sort\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMID\fP(lo,  hi)   (lo + ((hi \- lo) >> 1))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_sort\fP (void *\fBconst\fP pbase, size_t total_elems, size_t \fBsize\fP, int(*\fBcmp\fP)(\fBconst\fP void *, \fBconst\fP void *, void *\fBarg\fP), void *\fBarg\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MID(lo, hi)   (lo + ((hi \- lo) >> 1))"

.SH "Function Documentation"
.PP 
.SS "int isl_sort (void *\fBconst\fP pbase, size_t total_elems, size_t size, int(*)(\fBconst\fP void *, \fBconst\fP void *, void *\fBarg\fP) cmp, void * arg)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
