.TH "isl_pw_aff_piece" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_pw_aff_piece
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_aff_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_set\fP * \fBset\fP"
.br
.ti -1c
.RI "struct \fBisl_aff\fP * \fBaff\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_aff\fP* isl_pw_aff_piece::aff"

.SS "struct \fBisl_set\fP* isl_pw_aff_piece::set"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
