.TH "lib/isl/isl_union_single.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_union_single.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl_hash_private\&.h>\fP
.br
\fC#include <isl_union_macro\&.h>\fP
.br
\fC#include <isl_union_templ\&.c>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBUNION\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBFN\fP (FN(\fBUNION\fP, \fBn\fP), \fBPARTS\fP)"
.br
.ti -1c
.RI "\fBS\fP (\fBUNION\fP, foreach_data)"
.br
.ti -1c
.RI "\fBisl_stat\fP \fBFN\fP (FN(\fBUNION\fP, \fBforeach\fP), \fBPARTS\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBisl_stat\fP FN (FN(\fBUNION\fP, \fBforeach\fP), \fBPARTS\fP)"

.SS "int FN (FN(\fBUNION\fP, \fBn\fP), \fBPARTS\fP)"

.SS "S (\fBUNION\fP, foreach_data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
