.TH "lib/isl/isl_config.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_config.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl_config_post\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGCC_WARN_UNUSED_RESULT\fP   \fB__attribute__\fP((__warn_unused_result__))"
.br
.ti -1c
.RI "#define \fBHAVE_DECL_FFS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DECL_SNPRINTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DECL_STRCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DECL_STRNCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DECL__BITSCANFORWARD\fP   0"
.br
.ti -1c
.RI "#define \fBHAVE_DECL__SNPRINTF\fP   0"
.br
.ti -1c
.RI "#define \fBHAVE_DECL__STRICMP\fP   0"
.br
.ti -1c
.RI "#define \fBHAVE_DECL__STRNICMP\fP   0"
.br
.ti -1c
.RI "#define \fBHAVE_DECL___BUILTIN_FFS\fP   0"
.br
.ti -1c
.RI "#define \fBHAVE_DLFCN_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_STAT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE___ATTRIBUTE__\fP   1"
.br
.ti -1c
.RI "#define \fBLT_OBJDIR\fP   '\&.libs/'"
.br
.ti -1c
.RI "#define \fBPACKAGE\fP   'isl'"
.br
.ti -1c
.RI "#define \fBPACKAGE_BUGREPORT\fP   'isl\-development@googlegroups\&.com'"
.br
.ti -1c
.RI "#define \fBPACKAGE_NAME\fP   'isl'"
.br
.ti -1c
.RI "#define \fBPACKAGE_STRING\fP   'isl 0\&.16\&.1'"
.br
.ti -1c
.RI "#define \fBPACKAGE_TARNAME\fP   'isl'"
.br
.ti -1c
.RI "#define \fBPACKAGE_URL\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_VERSION\fP   '0\&.16\&.1'"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBUSE_IMATH_FOR_MP\fP"
.br
.ti -1c
.RI "#define \fBUSE_SMALL_INT_OPT\fP"
.br
.ti -1c
.RI "#define \fBVERSION\fP   '0\&.16\&.1'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GCC_WARN_UNUSED_RESULT   \fB__attribute__\fP((__warn_unused_result__))"

.SS "#define HAVE___ATTRIBUTE__   1"

.SS "#define HAVE_DECL___BUILTIN_FFS   0"

.SS "#define HAVE_DECL__BITSCANFORWARD   0"

.SS "#define HAVE_DECL__SNPRINTF   0"

.SS "#define HAVE_DECL__STRICMP   0"

.SS "#define HAVE_DECL__STRNICMP   0"

.SS "#define HAVE_DECL_FFS   1"

.SS "#define HAVE_DECL_SNPRINTF   1"

.SS "#define HAVE_DECL_STRCASECMP   1"

.SS "#define HAVE_DECL_STRNCASECMP   1"

.SS "#define HAVE_DLFCN_H   1"

.SS "#define HAVE_INTTYPES_H   1"

.SS "#define HAVE_MEMORY_H   1"

.SS "#define HAVE_STDINT_H   1"

.SS "#define HAVE_STDLIB_H   1"

.SS "#define HAVE_STRING_H   1"

.SS "#define HAVE_STRINGS_H   1"

.SS "#define HAVE_SYS_STAT_H   1"

.SS "#define HAVE_SYS_TYPES_H   1"

.SS "#define HAVE_UNISTD_H   1"

.SS "#define LT_OBJDIR   '\&.libs/'"

.SS "#define PACKAGE   'isl'"

.SS "#define PACKAGE_BUGREPORT   'isl\-development@googlegroups\&.com'"

.SS "#define PACKAGE_NAME   'isl'"

.SS "#define PACKAGE_STRING   'isl 0\&.16\&.1'"

.SS "#define PACKAGE_TARNAME   'isl'"

.SS "#define PACKAGE_URL   ''"

.SS "#define PACKAGE_VERSION   '0\&.16\&.1'"

.SS "#define STDC_HEADERS   1"

.SS "#define USE_IMATH_FOR_MP"

.SS "#define USE_SMALL_INT_OPT"

.SS "#define VERSION   '0\&.16\&.1'"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
