.TH "isl_lex_res" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_lex_res
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBp\fP"
.br
.ti -1c
.RI "\fBisl_map\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBisl_pw_multi_aff\fP * \fBpma\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_map\fP* isl_lex_res::map"

.SS "void* isl_lex_res::p"

.SS "\fBisl_pw_multi_aff\fP* isl_lex_res::pma"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
