.TH "isl_map" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_map
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_map_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.ti -1c
.RI "struct \fBisl_ctx\fP * \fBctx\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "struct \fBisl_basic_map\fP * \fBp\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_ctx\fP* isl_map::ctx"

.SS "\fBisl_space\fP* isl_map::dim"

.SS "unsigned isl_map::flags"

.SS "int isl_map::n"

.SS "struct \fBisl_basic_map\fP* isl_map::p[1]"

.SS "int isl_map::ref"

.SS "size_t isl_map::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
