.TH "isl_vertices" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_vertices
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_vertices_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_basic_set\fP * \fBbset\fP"
.br
.ti -1c
.RI "int \fBn_vertices\fP"
.br
.ti -1c
.RI "struct \fBisl_vertex\fP * \fBv\fP"
.br
.ti -1c
.RI "int \fBn_chambers\fP"
.br
.ti -1c
.RI "struct \fBisl_chamber\fP * \fBc\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_basic_set\fP* isl_vertices::bset"

.SS "struct \fBisl_chamber\fP* isl_vertices::c"

.SS "int isl_vertices::n_chambers"

.SS "int isl_vertices::n_vertices"

.SS "int isl_vertices::ref"

.SS "struct \fBisl_vertex\fP* isl_vertices::v"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
