.TH "isl_pw_qpolynomial" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_pw_qpolynomial
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_polynomial_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "struct \fBisl_pw_qpolynomial_piece\fP \fBp\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_space\fP* isl_pw_qpolynomial::dim"

.SS "int isl_pw_qpolynomial::n"

.SS "struct \fBisl_pw_qpolynomial_piece\fP isl_pw_qpolynomial::p[1]"

.SS "int isl_pw_qpolynomial::ref"

.SS "size_t isl_pw_qpolynomial::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
