.TH "isl_tc_follows_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_tc_follows_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_basic_map\fP ** \fBlist\fP"
.br
.ti -1c
.RI "int \fBcheck_closed\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_tc_follows_data::check_closed"

.SS "\fBisl_basic_map\fP** isl_tc_follows_data::list"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
