.TH "lib/isl/isl_reordering.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_reordering.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl_ctx_private\&.h>\fP
.br
\fC#include <isl_space_private\&.h>\fP
.br
\fC#include <isl_reordering\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_reordering\fP * \fBisl_reordering_alloc\fP (\fBisl_ctx\fP *ctx, int len)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_reordering\fP * \fBisl_reordering_copy\fP (\fB__isl_keep\fP \fBisl_reordering\fP *exp)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_reordering\fP * \fBisl_reordering_dup\fP (\fB__isl_keep\fP \fBisl_reordering\fP *r)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_reordering\fP * \fBisl_reordering_cow\fP (\fB__isl_take\fP \fBisl_reordering\fP *r)"
.br
.ti -1c
.RI "void * \fBisl_reordering_free\fP (\fB__isl_take\fP \fBisl_reordering\fP *exp)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_reordering\fP * \fBisl_parameter_alignment_reordering\fP (\fB__isl_keep\fP \fBisl_space\fP *alignee, \fB__isl_keep\fP \fBisl_space\fP *aligner)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_reordering\fP * \fBisl_reordering_extend\fP (\fB__isl_take\fP \fBisl_reordering\fP *exp, unsigned extra)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_reordering\fP * \fBisl_reordering_extend_space\fP (\fB__isl_take\fP \fBisl_reordering\fP *exp, \fB__isl_take\fP \fBisl_space\fP *\fBdim\fP)"
.br
.ti -1c
.RI "void \fBisl_reordering_dump\fP (\fB__isl_keep\fP \fBisl_reordering\fP *exp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_reordering\fP* isl_parameter_alignment_reordering (\fB__isl_keep\fP \fBisl_space\fP * alignee, \fB__isl_keep\fP \fBisl_space\fP * aligner)"

.SS "\fB__isl_give\fP \fBisl_reordering\fP* isl_reordering_alloc (\fBisl_ctx\fP * ctx, int len)"

.SS "\fB__isl_give\fP \fBisl_reordering\fP* isl_reordering_copy (\fB__isl_keep\fP \fBisl_reordering\fP * exp)"

.SS "\fB__isl_give\fP \fBisl_reordering\fP* isl_reordering_cow (\fB__isl_take\fP \fBisl_reordering\fP * r)"

.SS "void isl_reordering_dump (\fB__isl_keep\fP \fBisl_reordering\fP * exp)"

.SS "\fB__isl_give\fP \fBisl_reordering\fP* isl_reordering_dup (\fB__isl_keep\fP \fBisl_reordering\fP * r)"

.SS "\fB__isl_give\fP \fBisl_reordering\fP* isl_reordering_extend (\fB__isl_take\fP \fBisl_reordering\fP * exp, unsigned extra)"

.SS "\fB__isl_give\fP \fBisl_reordering\fP* isl_reordering_extend_space (\fB__isl_take\fP \fBisl_reordering\fP * exp, \fB__isl_take\fP \fBisl_space\fP * dim)"

.SS "void* isl_reordering_free (\fB__isl_take\fP \fBisl_reordering\fP * exp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
