.TH "isl_union_map_match_bin_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_union_map_match_bin_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_union_map\fP * \fBumap2\fP"
.br
.ti -1c
.RI "\fBisl_union_map\fP * \fBres\fP"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_map\fP *(* \fBfn\fP )(\fB__isl_take\fP \fBisl_map\fP *, \fB__isl_take\fP \fBisl_map\fP *)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_map\fP*(* isl_union_map_match_bin_data::fn) (\fB__isl_take\fP \fBisl_map\fP *, \fB__isl_take\fP \fBisl_map\fP *)"

.SS "\fBisl_union_map\fP* isl_union_map_match_bin_data::res"

.SS "\fBisl_union_map\fP* isl_union_map_match_bin_data::umap2"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
