.TH "lib/isl/isl_sample.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_sample.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl_ctx_private\&.h>\fP
.br
\fC#include <isl_map_private\&.h>\fP
.br
\fC#include 'isl_sample\&.h'\fP
.br
\fC#include <isl/vec\&.h>\fP
.br
\fC#include <isl/mat\&.h>\fP
.br
\fC#include <isl_seq\&.h>\fP
.br
\fC#include 'isl_equalities\&.h'\fP
.br
\fC#include 'isl_tab\&.h'\fP
.br
\fC#include 'isl_basis_reduction\&.h'\fP
.br
\fC#include <isl_factorization\&.h>\fP
.br
\fC#include <isl_point_private\&.h>\fP
.br
\fC#include <isl_options_private\&.h>\fP
.br
\fC#include <isl_vec_private\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBisl_vec\fP * \fBisl_tab_sample\fP (struct \fBisl_tab\fP *tab)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vec\fP * \fBisl_basic_set_sample_with_cone\fP (\fB__isl_take\fP \fBisl_basic_set\fP *bset, \fB__isl_take\fP \fBisl_basic_set\fP *cone)"
.br
.ti -1c
.RI "int \fBisl_tab_set_initial_basis_with_cone\fP (struct \fBisl_tab\fP *tab, struct \fBisl_tab\fP *tab_cone)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vec\fP * \fBisl_basic_set_sample_vec\fP (\fB__isl_take\fP \fBisl_basic_set\fP *bset)"
.br
.ti -1c
.RI "struct \fBisl_vec\fP * \fBisl_basic_set_sample_bounded\fP (struct \fBisl_basic_set\fP *bset)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_basic_set\fP * \fBisl_basic_set_from_vec\fP (\fB__isl_take\fP \fBisl_vec\fP *vec)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_basic_map\fP * \fBisl_basic_map_sample\fP (\fB__isl_take\fP \fBisl_basic_map\fP *\fBbmap\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_basic_set\fP * \fBisl_basic_set_sample\fP (\fB__isl_take\fP \fBisl_basic_set\fP *bset)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_basic_map\fP * \fBisl_map_sample\fP (\fB__isl_take\fP \fBisl_map\fP *\fBmap\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_basic_set\fP * \fBisl_set_sample\fP (\fB__isl_take\fP \fBisl_set\fP *\fBset\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_point\fP * \fBisl_basic_set_sample_point\fP (\fB__isl_take\fP \fBisl_basic_set\fP *bset)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_point\fP * \fBisl_set_sample_point\fP (\fB__isl_take\fP \fBisl_set\fP *\fBset\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_basic_map\fP* isl_basic_map_sample (\fB__isl_take\fP \fBisl_basic_map\fP * bmap)"

.SS "\fB__isl_give\fP \fBisl_basic_set\fP* isl_basic_set_from_vec (\fB__isl_take\fP \fBisl_vec\fP * vec)"

.SS "\fB__isl_give\fP \fBisl_basic_set\fP* isl_basic_set_sample (\fB__isl_take\fP \fBisl_basic_set\fP * bset)"

.SS "struct \fBisl_vec\fP* isl_basic_set_sample_bounded (struct \fBisl_basic_set\fP * bset)"

.SS "\fB__isl_give\fP \fBisl_point\fP* isl_basic_set_sample_point (\fB__isl_take\fP \fBisl_basic_set\fP * bset)"

.SS "\fB__isl_give\fP \fBisl_vec\fP* isl_basic_set_sample_vec (\fB__isl_take\fP \fBisl_basic_set\fP * bset)"

.SS "\fB__isl_give\fP \fBisl_vec\fP* isl_basic_set_sample_with_cone (\fB__isl_take\fP \fBisl_basic_set\fP * bset, \fB__isl_take\fP \fBisl_basic_set\fP * cone)"

.SS "\fB__isl_give\fP \fBisl_basic_map\fP* isl_map_sample (\fB__isl_take\fP \fBisl_map\fP * map)"

.SS "\fB__isl_give\fP \fBisl_basic_set\fP* isl_set_sample (\fB__isl_take\fP \fBisl_set\fP * set)"

.SS "\fB__isl_give\fP \fBisl_point\fP* isl_set_sample_point (\fB__isl_take\fP \fBisl_set\fP * set)"

.SS "struct \fBisl_vec\fP* isl_tab_sample (struct \fBisl_tab\fP * tab)"

.SS "int isl_tab_set_initial_basis_with_cone (struct \fBisl_tab\fP * tab, struct \fBisl_tab\fP * tab_cone)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
