.TH "isl_facet_todo" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_facet_todo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_tab\fP * \fBtab\fP"
.br
.ti -1c
.RI "\fBisl_basic_set\fP * \fBbset\fP"
.br
.ti -1c
.RI "\fBisl_vec\fP * \fBconstraint\fP"
.br
.ti -1c
.RI "struct \fBisl_facet_todo\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_basic_set\fP* isl_facet_todo::bset"

.SS "\fBisl_vec\fP* isl_facet_todo::constraint"

.SS "struct \fBisl_facet_todo\fP* isl_facet_todo::next"

.SS "struct \fBisl_tab\fP* isl_facet_todo::tab"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
