.TH "isl_labeled_map" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_labeled_map
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_map\fP * \fBmap\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "int \fBmust\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* isl_labeled_map::data"

.SS "struct \fBisl_map\fP* isl_labeled_map::map"

.SS "int isl_labeled_map::must"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
