.TH "isl_constraint_equal_info" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_constraint_equal_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_basic_map\fP * \fBbmap\fP"
.br
.ti -1c
.RI "unsigned \fBn_in\fP"
.br
.ti -1c
.RI "unsigned \fBn_out\fP"
.br
.ti -1c
.RI "\fBisl_int\fP * \fBval\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_basic_map\fP* isl_constraint_equal_info::bmap"

.SS "unsigned isl_constraint_equal_info::n_in"

.SS "unsigned isl_constraint_equal_info::n_out"

.SS "\fBisl_int\fP* isl_constraint_equal_info::val"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
