.TH "isl_region" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_region
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_tab\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpos\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_region::len"

.SS "int isl_region::pos"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
