.TH "lib/isl/isl_map_to_basic_set.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_map_to_basic_set.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl/map_to_basic_set\&.h>\fP
.br
\fC#include <isl/map\&.h>\fP
.br
\fC#include <isl/set\&.h>\fP
.br
\fC#include <isl_hmap_templ\&.c>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKEY_BASE\fP   \fBmap\fP"
.br
.ti -1c
.RI "#define \fBKEY_EQUAL\fP   \fBisl_map_plain_is_equal\fP"
.br
.ti -1c
.RI "#define \fBVAL_BASE\fP   basic_set"
.br
.ti -1c
.RI "#define \fBVAL_EQUAL\fP   \fBisl_basic_set_plain_is_equal\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KEY_BASE   \fBmap\fP"

.SS "#define KEY_EQUAL   \fBisl_map_plain_is_equal\fP"

.SS "#define VAL_BASE   basic_set"

.SS "#define VAL_EQUAL   \fBisl_basic_set_plain_is_equal\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
