.TH "isl_printer" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_printer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_printer_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_ctx\fP * \fBctx\fP"
.br
.ti -1c
.RI "struct \fBisl_printer_ops\fP * \fBops\fP"
.br
.ti -1c
.RI "FILE * \fBfile\fP"
.br
.ti -1c
.RI "int \fBbuf_n\fP"
.br
.ti -1c
.RI "int \fBbuf_size\fP"
.br
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "int \fBindent\fP"
.br
.ti -1c
.RI "int \fBoutput_format\fP"
.br
.ti -1c
.RI "int \fBdump\fP"
.br
.ti -1c
.RI "char * \fBindent_prefix\fP"
.br
.ti -1c
.RI "char * \fBprefix\fP"
.br
.ti -1c
.RI "char * \fBsuffix\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fByaml_style\fP"
.br
.ti -1c
.RI "int \fByaml_depth\fP"
.br
.ti -1c
.RI "int \fByaml_size\fP"
.br
.ti -1c
.RI "enum \fBisl_yaml_state\fP * \fByaml_state\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* isl_printer::buf"

.SS "int isl_printer::buf_n"

.SS "int isl_printer::buf_size"

.SS "struct \fBisl_ctx\fP* isl_printer::ctx"

.SS "int isl_printer::dump"

.SS "FILE* isl_printer::file"

.SS "int isl_printer::indent"

.SS "char* isl_printer::indent_prefix"

.SS "struct \fBisl_printer_ops\fP* isl_printer::ops"

.SS "int isl_printer::output_format"

.SS "char* isl_printer::prefix"

.SS "char* isl_printer::suffix"

.SS "int isl_printer::width"

.SS "int isl_printer::yaml_depth"

.SS "int isl_printer::yaml_size"

.SS "enum \fBisl_yaml_state\fP* isl_printer::yaml_state"

.SS "int isl_printer::yaml_style"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
