.TH "isl_reordering" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_reordering
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_reordering\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.ti -1c
.RI "unsigned \fBlen\fP"
.br
.ti -1c
.RI "int \fBpos\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_space\fP* isl_reordering::dim"

.SS "unsigned isl_reordering::len"

.SS "int isl_reordering::pos[1]"

.SS "int isl_reordering::ref"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
