.TH "isl_is_empty_diff_collector" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_is_empty_diff_collector
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_diff_collector\fP \fBdc\fP"
.br
.ti -1c
.RI "\fBisl_bool\fP \fBempty\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_diff_collector\fP isl_is_empty_diff_collector::dc"

.SS "\fBisl_bool\fP isl_is_empty_diff_collector::empty"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
