.TH "isl_union_map_is_disjoint_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_union_map_is_disjoint_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_union_map\fP * \fBumap2\fP"
.br
.ti -1c
.RI "\fBisl_bool\fP \fBis_disjoint\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_bool\fP isl_union_map_is_disjoint_data::is_disjoint"

.SS "\fBisl_union_map\fP* isl_union_map_is_disjoint_data::umap2"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
