.TH "isl_ast_count_constraints_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_ast_count_constraints_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpos\fP"
.br
.ti -1c
.RI "int \fBn_indep\fP"
.br
.ti -1c
.RI "int \fBn_lower\fP"
.br
.ti -1c
.RI "int \fBn_upper\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_ast_count_constraints_data::n_indep"

.SS "int isl_ast_count_constraints_data::n_lower"

.SS "int isl_ast_count_constraints_data::n_upper"

.SS "int isl_ast_count_constraints_data::pos"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
