.TH "lib/isl/isl_deprecated.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_deprecated.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl/constraint\&.h>\fP
.br
\fC#include <isl/set\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_basic_set\fP * \fBisl_basic_set_add\fP (\fB__isl_take\fP \fBisl_basic_set\fP *bset, enum \fBisl_dim_type\fP type, unsigned \fBn\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_constraint\fP * \fBisl_equality_alloc\fP (\fB__isl_take\fP \fBisl_local_space\fP *ls)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_constraint\fP * \fBisl_inequality_alloc\fP (\fB__isl_take\fP \fBisl_local_space\fP *ls)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_basic_set\fP* isl_basic_set_add (\fB__isl_take\fP \fBisl_basic_set\fP * bset, enum \fBisl_dim_type\fP type, unsigned n)"

.SS "\fB__isl_give\fP \fBisl_constraint\fP* isl_equality_alloc (\fB__isl_take\fP \fBisl_local_space\fP * ls)"

.SS "\fB__isl_give\fP \fBisl_constraint\fP* isl_inequality_alloc (\fB__isl_take\fP \fBisl_local_space\fP * ls)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
