.TH "lib/isl/isl_multi_templ.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_multi_templ.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/space\&.h>\fP
.br
\fC#include <isl_multi_macro\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBMULTI\fP (\fBBASE\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fB_alloc\fP (\fB__isl_take\fP \fBisl_space\fP *space)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP _alloc (\fB__isl_take\fP \fBisl_space\fP * space)"

.SS "struct MULTI (\fBBASE\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
