.TH "lib/isl/isl_lp.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_lp.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl_ctx_private\&.h>\fP
.br
\fC#include <isl_map_private\&.h>\fP
.br
\fC#include <isl/lp\&.h>\fP
.br
\fC#include <isl_seq\&.h>\fP
.br
\fC#include 'isl_tab\&.h'\fP
.br
\fC#include <isl_options_private\&.h>\fP
.br
\fC#include <isl_local_space_private\&.h>\fP
.br
\fC#include <isl_aff_private\&.h>\fP
.br
\fC#include <isl_mat_private\&.h>\fP
.br
\fC#include <isl_val_private\&.h>\fP
.br
\fC#include <isl_vec_private\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_tab_solve_lp\fP (struct \fBisl_basic_map\fP *\fBbmap\fP, int maximize, \fBisl_int\fP *\fBf\fP, \fBisl_int\fP denom, \fBisl_int\fP *opt, \fBisl_int\fP *opt_denom, struct \fBisl_vec\fP **sol)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_basic_map_solve_lp\fP (struct \fBisl_basic_map\fP *\fBbmap\fP, int \fBmax\fP, \fBisl_int\fP *\fBf\fP, \fBisl_int\fP d, \fBisl_int\fP *opt, \fBisl_int\fP *opt_denom, struct \fBisl_vec\fP **sol)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_basic_set_solve_lp\fP (struct \fBisl_basic_set\fP *bset, int \fBmax\fP, \fBisl_int\fP *\fBf\fP, \fBisl_int\fP d, \fBisl_int\fP *opt, \fBisl_int\fP *opt_denom, struct \fBisl_vec\fP **sol)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_map_solve_lp\fP (\fB__isl_keep\fP \fBisl_map\fP *\fBmap\fP, int \fBmax\fP, \fBisl_int\fP *\fBf\fP, \fBisl_int\fP d, \fBisl_int\fP *opt, \fBisl_int\fP *opt_denom, struct \fBisl_vec\fP **sol)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_set_solve_lp\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, int \fBmax\fP, \fBisl_int\fP *\fBf\fP, \fBisl_int\fP d, \fBisl_int\fP *opt, \fBisl_int\fP *opt_denom, struct \fBisl_vec\fP **sol)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_basic_set_min_lp_val\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_basic_set_max_lp_val\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "enum \fBisl_lp_result\fP isl_basic_map_solve_lp (struct \fBisl_basic_map\fP * bmap, int max, \fBisl_int\fP * f, \fBisl_int\fP d, \fBisl_int\fP * opt, \fBisl_int\fP * opt_denom, struct \fBisl_vec\fP ** sol)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_basic_set_max_lp_val (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_basic_set_min_lp_val (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SS "enum \fBisl_lp_result\fP isl_basic_set_solve_lp (struct \fBisl_basic_set\fP * bset, int max, \fBisl_int\fP * f, \fBisl_int\fP d, \fBisl_int\fP * opt, \fBisl_int\fP * opt_denom, struct \fBisl_vec\fP ** sol)"

.SS "enum \fBisl_lp_result\fP isl_map_solve_lp (\fB__isl_keep\fP \fBisl_map\fP * map, int max, \fBisl_int\fP * f, \fBisl_int\fP d, \fBisl_int\fP * opt, \fBisl_int\fP * opt_denom, struct \fBisl_vec\fP ** sol)"

.SS "enum \fBisl_lp_result\fP isl_set_solve_lp (\fB__isl_keep\fP \fBisl_set\fP * set, int max, \fBisl_int\fP * f, \fBisl_int\fP d, \fBisl_int\fP * opt, \fBisl_int\fP * opt_denom, struct \fBisl_vec\fP ** sol)"

.SS "enum \fBisl_lp_result\fP isl_tab_solve_lp (struct \fBisl_basic_map\fP * bmap, int maximize, \fBisl_int\fP * f, \fBisl_int\fP denom, \fBisl_int\fP * opt, \fBisl_int\fP * opt_denom, struct \fBisl_vec\fP ** sol)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
