.TH "isl_union_power" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_union_power
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_union_map\fP * \fBpow\fP"
.br
.ti -1c
.RI "int * \fBexact\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int* isl_union_power::exact"

.SS "\fBisl_union_map\fP* isl_union_power::pow"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
