.TH "lib/isl/isl_factorization.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_factorization.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl_map_private\&.h>\fP
.br
\fC#include <isl_factorization\&.h>\fP
.br
\fC#include <isl_space_private\&.h>\fP
.br
\fC#include <isl_mat_private\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_factor_groups\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBisl_factorizer_free\fP (\fB__isl_take\fP \fBisl_factorizer\fP *\fBf\fP)"
.br
.ti -1c
.RI "void \fBisl_factorizer_dump\fP (\fB__isl_take\fP \fBisl_factorizer\fP *\fBf\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_factorizer\fP * \fBisl_factorizer_identity\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_factorizer\fP * \fBisl_factorizer_groups\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fB__isl_take\fP \fBisl_mat\fP *Q, \fB__isl_take\fP \fBisl_mat\fP *\fBU\fP, int \fBn\fP, int *len)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_factorizer\fP * \fBisl_basic_set_factorizer\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_factorizer\fP* isl_basic_set_factorizer (\fB__isl_keep\fP \fBisl_basic_set\fP * bset)"

.SS "void isl_factorizer_dump (\fB__isl_take\fP \fBisl_factorizer\fP * f)"

.SS "void isl_factorizer_free (\fB__isl_take\fP \fBisl_factorizer\fP * f)"

.SS "\fB__isl_give\fP \fBisl_factorizer\fP* isl_factorizer_groups (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fB__isl_take\fP \fBisl_mat\fP * Q, \fB__isl_take\fP \fBisl_mat\fP * U, int n, int * len)"

.SS "\fB__isl_give\fP \fBisl_factorizer\fP* isl_factorizer_identity (\fB__isl_keep\fP \fBisl_basic_set\fP * bset)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
