.TH "isl_union_bound_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_union_bound_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBisl_fold\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBtight\fP"
.br
.ti -1c
.RI "\fBisl_union_pw_qpolynomial_fold\fP * \fBres\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_union_pw_qpolynomial_fold\fP* isl_union_bound_data::res"

.SS "int isl_union_bound_data::tight"

.SS "enum \fBisl_fold\fP isl_union_bound_data::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
