.TH "lib/isl/isl_sample.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_sample.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/set\&.h>\fP
.br
\fC#include <isl_tab\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vec\fP * \fBisl_basic_set_sample_vec\fP (\fB__isl_take\fP \fBisl_basic_set\fP *bset)"
.br
.ti -1c
.RI "struct \fBisl_vec\fP * \fBisl_basic_set_sample_bounded\fP (struct \fBisl_basic_set\fP *bset)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vec\fP * \fBisl_basic_set_sample_with_cone\fP (\fB__isl_take\fP \fBisl_basic_set\fP *bset, \fB__isl_take\fP \fBisl_basic_set\fP *cone)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_basic_set\fP * \fBisl_basic_set_from_vec\fP (\fB__isl_take\fP \fBisl_vec\fP *vec)"
.br
.ti -1c
.RI "int \fBisl_tab_set_initial_basis_with_cone\fP (struct \fBisl_tab\fP *tab, struct \fBisl_tab\fP *tab_cone)"
.br
.ti -1c
.RI "struct \fBisl_vec\fP * \fBisl_tab_sample\fP (struct \fBisl_tab\fP *tab)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_basic_set\fP* isl_basic_set_from_vec (\fB__isl_take\fP \fBisl_vec\fP * vec)"

.SS "struct \fBisl_vec\fP* isl_basic_set_sample_bounded (struct \fBisl_basic_set\fP * bset)"

.SS "\fB__isl_give\fP \fBisl_vec\fP* isl_basic_set_sample_vec (\fB__isl_take\fP \fBisl_basic_set\fP * bset)"

.SS "\fB__isl_give\fP \fBisl_vec\fP* isl_basic_set_sample_with_cone (\fB__isl_take\fP \fBisl_basic_set\fP * bset, \fB__isl_take\fP \fBisl_basic_set\fP * cone)"

.SS "struct \fBisl_vec\fP* isl_tab_sample (struct \fBisl_tab\fP * tab)"

.SS "int isl_tab_set_initial_basis_with_cone (struct \fBisl_tab\fP * tab, struct \fBisl_tab\fP * tab_cone)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
