.TH "lib/isl/isl_union_map_private.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_union_map_private.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/union_map\&.h>\fP
.br
\fC#include <isl/union_set\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_union_map\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBisl_union_set_list\fP   isl_union_map_list"
.br
.ti -1c
.RI "#define \fBisl_union_set\fP   \fBisl_union_map\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_union_map\fP * \fBisl_union_map_reset_range_space\fP (\fB__isl_take\fP \fBisl_union_map\fP *umap, \fB__isl_take\fP \fBisl_space\fP *space)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "struct \fB__isl_export\fP \fBisl_union_set\fP   \fBisl_union_map\fP"

.SS "#define isl_union_set_list   isl_union_map_list"

.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_union_map\fP* isl_union_map_reset_range_space (\fB__isl_take\fP \fBisl_union_map\fP * umap, \fB__isl_take\fP \fBisl_space\fP * space)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
