.TH "isl_union_map_gen_bin_set_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_union_map_gen_bin_set_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_set\fP * \fBset\fP"
.br
.ti -1c
.RI "\fBisl_union_map\fP * \fBres\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_union_map\fP* isl_union_map_gen_bin_set_data::res"

.SS "\fBisl_set\fP* isl_union_map_gen_bin_set_data::set"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
