.TH "lib/isl/isl_list_templ.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_list_templ.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBxFN\fP(\fBTYPE\fP,  NAME)   \fBTYPE\fP ## _ ## NAME"
.br
.ti -1c
.RI "#define \fBFN\fP(\fBTYPE\fP,  NAME)   \fBxFN\fP(\fBTYPE\fP,NAME)"
.br
.ti -1c
.RI "#define \fBxLIST\fP(\fBEL\fP)   \fBEL\fP ## _list"
.br
.ti -1c
.RI "#define \fBLIST\fP(\fBEL\fP)   \fBxLIST\fP(\fBEL\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBdup\fP (\fB__isl_keep\fP \fBLIST\fP(\fBEL\fP) *list)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FN(\fBTYPE\fP, NAME)   \fBxFN\fP(\fBTYPE\fP,NAME)"

.SS "#define LIST(\fBEL\fP)   \fBxLIST\fP(\fBEL\fP)"

.SS "#define xFN(\fBTYPE\fP, NAME)   \fBTYPE\fP ## _ ## NAME"

.SS "#define xLIST(\fBEL\fP)   \fBEL\fP ## _list"

.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP dup (\fB__isl_keep\fP \fBLIST\fP(\fBEL\fP) * list)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
