.TH "isl_access_info" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_access_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_map\fP * \fBdomain_map\fP"
.br
.ti -1c
.RI "struct \fBisl_labeled_map\fP \fBsink\fP"
.br
.ti -1c
.RI "\fBisl_access_level_before\fP \fBlevel_before\fP"
.br
.ti -1c
.RI "\fBisl_access_restrict\fP \fBrestrict_fn\fP"
.br
.ti -1c
.RI "void * \fBrestrict_user\fP"
.br
.ti -1c
.RI "int \fBmax_source\fP"
.br
.ti -1c
.RI "int \fBn_must\fP"
.br
.ti -1c
.RI "int \fBn_may\fP"
.br
.ti -1c
.RI "struct \fBisl_labeled_map\fP \fBsource\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_map\fP* isl_access_info::domain_map"

.SS "\fBisl_access_level_before\fP isl_access_info::level_before"

.SS "int isl_access_info::max_source"

.SS "int isl_access_info::n_may"

.SS "int isl_access_info::n_must"

.SS "\fBisl_access_restrict\fP isl_access_info::restrict_fn"

.SS "void* isl_access_info::restrict_user"

.SS "struct \fBisl_labeled_map\fP isl_access_info::sink"

.SS "struct \fBisl_labeled_map\fP isl_access_info::source[1]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
