.TH "isl_to_poly_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_to_poly_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsign\fP"
.br
.ti -1c
.RI "\fBisl_pw_qpolynomial\fP * \fBres\fP"
.br
.ti -1c
.RI "\fBisl_qpolynomial\fP * \fBqp\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_qpolynomial\fP* isl_to_poly_data::qp"

.SS "\fBisl_pw_qpolynomial\fP* isl_to_poly_data::res"

.SS "int isl_to_poly_data::sign"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
