.TH "isl_foreach_point" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_foreach_point
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_scan_callback\fP \fBcallback\fP"
.br
.ti -1c
.RI "\fBisl_stat\fP(* \fBfn\fP )(\fB__isl_take\fP \fBisl_point\fP *pnt, void *\fBuser\fP)"
.br
.ti -1c
.RI "void * \fBuser\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_scan_callback\fP isl_foreach_point::callback"

.SS "\fBisl_space\fP* isl_foreach_point::dim"

.SS "\fBisl_stat\fP(* isl_foreach_point::fn) (\fB__isl_take\fP \fBisl_point\fP *pnt, void *\fBuser\fP)"

.SS "void* isl_foreach_point::user"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
