.TH "isl_obj_vtable" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_obj_vtable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <obj\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void *(* \fBcopy\fP )(void *v1)"
.br
.ti -1c
.RI "void *(* \fBadd\fP )(void *v1, void *v2)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_printer\fP *(* \fBprint\fP )(\fB__isl_take\fP \fBisl_printer\fP *\fBp\fP, void *v)"
.br
.ti -1c
.RI "void(* \fBfree\fP )(void *v)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void*(* isl_obj_vtable::add) (void *v1, void *v2)"

.SS "void*(* isl_obj_vtable::copy) (void *v1)"

.SS "void(* isl_obj_vtable::free) (void *v)"

.SS "\fB__isl_give\fP \fBisl_printer\fP*(* isl_obj_vtable::print) (\fB__isl_take\fP \fBisl_printer\fP *\fBp\fP, void *v)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
