.TH "lib/isl/isl_point_private.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_point_private.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/space\&.h>\fP
.br
\fC#include <isl/point\&.h>\fP
.br
\fC#include <isl/vec\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_point\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_point\fP * \fBisl_point_alloc\fP (\fB__isl_take\fP \fBisl_space\fP *\fBdim\fP, \fB__isl_take\fP \fBisl_vec\fP *vec)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_point\fP* isl_point_alloc (\fB__isl_take\fP \fBisl_space\fP * dim, \fB__isl_take\fP \fBisl_vec\fP * vec)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
