.TH "lib/isl/isl_options.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_options.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <isl/ctx\&.h>\fP
.br
\fC#include <isl_options_private\&.h>\fP
.br
\fC#include <isl/ast_build\&.h>\fP
.br
\fC#include <isl/schedule\&.h>\fP
.br
\fC#include <isl/version\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBISL_SCHEDULE_FUSE_MAX\fP   0"
.br
.ti -1c
.RI "#define \fBISL_SCHEDULE_FUSE_MIN\fP   1"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBisl_arg_choice\fP \fBisl_pip_context_choice\fP []"
.br
.ti -1c
.RI "struct \fBisl_arg_choice\fP \fBisl_gbr_choice\fP []"
.br
.ti -1c
.RI "struct \fBisl_arg_choice\fP \fBisl_closure_choice\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ISL_SCHEDULE_FUSE_MAX   0"

.SS "#define ISL_SCHEDULE_FUSE_MIN   1"

.SH "Variable Documentation"
.PP 
.SS "struct \fBisl_arg_choice\fP isl_closure_choice[]"
\fBInitial value:\fP
.PP
.nf
= {
    {"isl",     ISL_CLOSURE_ISL},
    {"box",     ISL_CLOSURE_BOX},
    {0}
}
.fi
.SS "struct \fBisl_arg_choice\fP isl_gbr_choice[]"
\fBInitial value:\fP
.PP
.nf
= {
    {"never",   ISL_GBR_NEVER},
    {"once",    ISL_GBR_ONCE},
    {"always",  ISL_GBR_ALWAYS},
    {0}
}
.fi
.SS "struct \fBisl_arg_choice\fP isl_pip_context_choice[]"
\fBInitial value:\fP
.PP
.nf
= {
    {"gbr",     ISL_CONTEXT_GBR},
    {"lexmin",  ISL_CONTEXT_LEXMIN},
    {0}
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
