.TH "isl_bound" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_bound
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_bound\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcheck_tight\fP"
.br
.ti -1c
.RI "int \fBwrapping\fP"
.br
.ti -1c
.RI "enum \fBisl_fold\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.ti -1c
.RI "\fBisl_basic_set\fP * \fBbset\fP"
.br
.ti -1c
.RI "\fBisl_qpolynomial_fold\fP * \fBfold\fP"
.br
.ti -1c
.RI "\fBisl_pw_qpolynomial_fold\fP * \fBpwf\fP"
.br
.ti -1c
.RI "\fBisl_pw_qpolynomial_fold\fP * \fBpwf_tight\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_basic_set\fP* isl_bound::bset"

.SS "int isl_bound::check_tight"

.SS "\fBisl_space\fP* isl_bound::dim"

.SS "\fBisl_qpolynomial_fold\fP* isl_bound::fold"

.SS "\fBisl_pw_qpolynomial_fold\fP* isl_bound::pwf"

.SS "\fBisl_pw_qpolynomial_fold\fP* isl_bound::pwf_tight"

.SS "enum \fBisl_fold\fP isl_bound::type"

.SS "int isl_bound::wrapping"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
