.TH "isl_qpolynomial_fold" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_qpolynomial_fold
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_polynomial_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "enum \fBisl_fold\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "struct \fBisl_qpolynomial\fP * \fBqp\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_space\fP* isl_qpolynomial_fold::dim"

.SS "int isl_qpolynomial_fold::n"

.SS "struct \fBisl_qpolynomial\fP* isl_qpolynomial_fold::qp[1]"

.SS "int isl_qpolynomial_fold::ref"

.SS "size_t isl_qpolynomial_fold::size"

.SS "enum \fBisl_fold\fP isl_qpolynomial_fold::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
