.TH "isl_union_align" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_union_align
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_reordering\fP * \fBexp\fP"
.br
.ti -1c
.RI "\fBisl_union_map\fP * \fBres\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_reordering\fP* isl_union_align::exp"

.SS "\fBisl_union_map\fP* isl_union_align::res"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
