.TH "isl_split_periods_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_split_periods_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmax_periods\fP"
.br
.ti -1c
.RI "\fBisl_pw_qpolynomial\fP * \fBres\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_split_periods_data::max_periods"

.SS "\fBisl_pw_qpolynomial\fP* isl_split_periods_data::res"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
