.TH "isl_scheduled_access" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_scheduled_access
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_map\fP * \fBaccess\fP"
.br
.ti -1c
.RI "int \fBmust\fP"
.br
.ti -1c
.RI "\fBisl_schedule_node\fP * \fBnode\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_map\fP* isl_scheduled_access::access"

.SS "int isl_scheduled_access::must"

.SS "\fBisl_schedule_node\fP* isl_scheduled_access::node"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
