.TH "lib/isl/isl_coalesce.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_coalesce.c
.SH SYNOPSIS
.br
.PP
\fC#include 'isl_map_private\&.h'\fP
.br
\fC#include <isl_seq\&.h>\fP
.br
\fC#include <isl/options\&.h>\fP
.br
\fC#include 'isl_tab\&.h'\fP
.br
\fC#include <isl_mat_private\&.h>\fP
.br
\fC#include <isl_local_space_private\&.h>\fP
.br
\fC#include <isl_vec_private\&.h>\fP
.br
\fC#include <isl_aff_private\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_coalesce_info\fP"
.br
.ti -1c
.RI "struct \fBisl_wraps\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTATUS_ERROR\fP   \-1"
.br
.ti -1c
.RI "#define \fBSTATUS_REDUNDANT\fP   1"
.br
.ti -1c
.RI "#define \fBSTATUS_VALID\fP   2"
.br
.ti -1c
.RI "#define \fBSTATUS_SEPARATE\fP   3"
.br
.ti -1c
.RI "#define \fBSTATUS_CUT\fP   4"
.br
.ti -1c
.RI "#define \fBSTATUS_ADJ_EQ\fP   5"
.br
.ti -1c
.RI "#define \fBSTATUS_ADJ_INEQ\fP   6"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBisl_change\fP { \fBisl_change_error\fP = -1, \fBisl_change_none\fP = 0, \fBisl_change_drop_first\fP, \fBisl_change_drop_second\fP, \fBisl_change_fuse\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBisl_map\fP * \fBisl_map_coalesce\fP (struct \fBisl_map\fP *\fBmap\fP)"
.br
.ti -1c
.RI "struct \fBisl_set\fP * \fBisl_set_coalesce\fP (struct \fBisl_set\fP *\fBset\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STATUS_ADJ_EQ   5"

.SS "#define STATUS_ADJ_INEQ   6"

.SS "#define STATUS_CUT   4"

.SS "#define STATUS_ERROR   \-1"

.SS "#define STATUS_REDUNDANT   1"

.SS "#define STATUS_SEPARATE   3"

.SS "#define STATUS_VALID   2"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBisl_change\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIisl_change_error \fP\fP
.TP
\fB\fIisl_change_none \fP\fP
.TP
\fB\fIisl_change_drop_first \fP\fP
.TP
\fB\fIisl_change_drop_second \fP\fP
.TP
\fB\fIisl_change_fuse \fP\fP
.SH "Function Documentation"
.PP 
.SS "struct \fBisl_map\fP* isl_map_coalesce (struct \fBisl_map\fP * map)"

.SS "struct \fBisl_set\fP* isl_set_coalesce (struct \fBisl_set\fP * set)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
