.TH "isl_vertices_test_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_vertices_test_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP char * \fBset\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBvertex\fP [2]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_vertices_test_data::n"

.SS "\fBconst\fP char* isl_vertices_test_data::set"

.SS "\fBconst\fP char* isl_vertices_test_data::vertex[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
