.TH "isl_fixed_sign_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_fixed_sign_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int * \fBsigns\fP"
.br
.ti -1c
.RI "int \fBsign\fP"
.br
.ti -1c
.RI "\fBisl_qpolynomial\fP * \fBpoly\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_qpolynomial\fP* isl_fixed_sign_data::poly"

.SS "int isl_fixed_sign_data::sign"

.SS "int* isl_fixed_sign_data::signs"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
