.TH "lib/isl/isl_scan.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_scan.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl_ctx_private\&.h>\fP
.br
\fC#include <isl_map_private\&.h>\fP
.br
\fC#include 'isl_basis_reduction\&.h'\fP
.br
\fC#include 'isl_scan\&.h'\fP
.br
\fC#include <isl_seq\&.h>\fP
.br
\fC#include 'isl_tab\&.h'\fP
.br
\fC#include <isl_val_private\&.h>\fP
.br
\fC#include <isl_vec_private\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_counter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_basic_set_scan\fP (struct \fBisl_basic_set\fP *bset, struct \fBisl_scan_callback\fP *callback)"
.br
.ti -1c
.RI "int \fBisl_set_scan\fP (\fB__isl_take\fP \fBisl_set\fP *\fBset\fP, struct \fBisl_scan_callback\fP *callback)"
.br
.ti -1c
.RI "int \fBisl_basic_set_count_upto\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fBisl_int\fP \fBmax\fP, \fBisl_int\fP *\fBcount\fP)"
.br
.ti -1c
.RI "int \fBisl_set_count_upto\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fBisl_int\fP \fBmax\fP, \fBisl_int\fP *\fBcount\fP)"
.br
.ti -1c
.RI "int \fBisl_set_count\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fBisl_int\fP *\fBcount\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_set_count_val\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isl_basic_set_count_upto (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fBisl_int\fP max, \fBisl_int\fP * count)"

.SS "int isl_basic_set_scan (struct \fBisl_basic_set\fP * bset, struct \fBisl_scan_callback\fP * callback)"

.SS "int isl_set_count (\fB__isl_keep\fP \fBisl_set\fP * set, \fBisl_int\fP * count)"

.SS "int isl_set_count_upto (\fB__isl_keep\fP \fBisl_set\fP * set, \fBisl_int\fP max, \fBisl_int\fP * count)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_set_count_val (\fB__isl_keep\fP \fBisl_set\fP * set)"

.SS "int isl_set_scan (\fB__isl_take\fP \fBisl_set\fP * set, struct \fBisl_scan_callback\fP * callback)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
