.TH "lib/isl/isl_union_macro.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_union_macro.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBxFN\fP(\fBTYPE\fP,  NAME)   \fBTYPE\fP ## _ ## NAME"
.br
.ti -1c
.RI "#define \fBFN\fP(\fBTYPE\fP,  NAME)   \fBxFN\fP(\fBTYPE\fP,NAME)"
.br
.ti -1c
.RI "#define \fBxS\fP(\fBTYPE\fP,  NAME)   struct \fBTYPE\fP ## _ ## NAME"
.br
.ti -1c
.RI "#define \fBS\fP(\fBTYPE\fP,  NAME)   \fBxS\fP(\fBTYPE\fP,NAME)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FN(\fBTYPE\fP, NAME)   \fBxFN\fP(\fBTYPE\fP,NAME)"

.SS "#define S(\fBTYPE\fP, NAME)   \fBxS\fP(\fBTYPE\fP,NAME)"

.SS "#define xFN(\fBTYPE\fP, NAME)   \fBTYPE\fP ## _ ## NAME"

.SS "#define xS(\fBTYPE\fP, NAME)   struct \fBTYPE\fP ## _ ## NAME"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
