.TH "lib/iegenlib/src/set_relation/isl_str_manipulation_test.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/set_relation/isl_str_manipulation_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'isl_str_manipulation\&.h'\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (islStrManipulationTest, revertISLTupDeclToOrig)"
.br
.ti -1c
.RI "\fBTEST\fP (islStrManipulationTest, projectOutStrCorrection)"
.br
.ti -1c
.RI "\fBTEST\fP (islStrManipulationTest, setStr2RelationStrTEST)"
.br
.ti -1c
.RI "\fBTEST\fP (islStrManipulationTest, relationStr2SetStrStrTEST)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (islStrManipulationTest, projectOutStrCorrection)"

.SS "TEST (islStrManipulationTest, relationStr2SetStrStrTEST)"

.SS "TEST (islStrManipulationTest, revertISLTupDeclToOrig)"

.SS "TEST (islStrManipulationTest, setStr2RelationStrTEST)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
