.TH "isl_prefixes" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_prefixes
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBprefix\fP [10]"
.br
.ti -1c
.RI "size_t \fBlen\fP [10]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t isl_prefixes::len[10]"

.SS "int isl_prefixes::n"

.SS "\fBconst\fP char* isl_prefixes::prefix[10]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
