.TH "isl_union_pw_aff_reset_params_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_union_pw_aff_reset_params_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_space\fP * \fBspace\fP"
.br
.ti -1c
.RI "\fBisl_union_pw_aff\fP * \fBres\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_union_pw_aff\fP* isl_union_pw_aff_reset_params_data::res"

.SS "\fBisl_space\fP* isl_union_pw_aff_reset_params_data::space"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
