.TH "lib/isl/isl_id_to_pw_aff.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_id_to_pw_aff.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl/id_to_pw_aff\&.h>\fP
.br
\fC#include <isl/aff\&.h>\fP
.br
\fC#include <isl_hmap_templ\&.c>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBisl_id_is_equal\fP(id1,  id2)   id1 == id2"
.br
.ti -1c
.RI "#define \fBKEY_BASE\fP   id"
.br
.ti -1c
.RI "#define \fBKEY_EQUAL\fP   \fBisl_id_is_equal\fP"
.br
.ti -1c
.RI "#define \fBVAL_BASE\fP   pw_aff"
.br
.ti -1c
.RI "#define \fBVAL_EQUAL\fP   \fBisl_pw_aff_plain_is_equal\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define isl_id_is_equal(id1, id2)   id1 == id2"

.SS "#define KEY_BASE   id"

.SS "#define KEY_EQUAL   \fBisl_id_is_equal\fP"

.SS "#define VAL_BASE   pw_aff"

.SS "#define VAL_EQUAL   \fBisl_pw_aff_plain_is_equal\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
