.TH "lib/isl/isl_band_private.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_band_private.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/aff\&.h>\fP
.br
\fC#include <isl/band\&.h>\fP
.br
\fC#include <isl/list\&.h>\fP
.br
\fC#include <isl/schedule\&.h>\fP
.br
\fC#include <isl_list_templ\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_band\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEL\fP   \fBisl_band\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_band\fP * \fBisl_band_alloc\fP (\fBisl_ctx\fP *ctx)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_union_map\fP * \fBisl_band_list_get_suffix_schedule\fP (\fB__isl_keep\fP isl_band_list *list)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EL   \fBisl_band\fP"

.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_band\fP* isl_band_alloc (\fBisl_ctx\fP * ctx)"

.SS "\fB__isl_give\fP \fBisl_union_map\fP* isl_band_list_get_suffix_schedule (\fB__isl_keep\fP isl_band_list * list)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
