.TH "lib/isl/isl_imath.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_imath.h
.SH SYNOPSIS
.br
.PP
\fC#include <imath\&.h>\fP
.br
\fC#include <gmp_compat\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBisl_imath_hash\fP (\fBmp_int\fP v, uint32_t hash)"
.br
.ti -1c
.RI "int \fBisl_imath_fits_ulong_p\fP (\fBmp_int\fP \fBop\fP)"
.br
.ti -1c
.RI "int \fBisl_imath_fits_slong_p\fP (\fBmp_int\fP \fBop\fP)"
.br
.ti -1c
.RI "void \fBisl_imath_addmul_ui\fP (\fBmp_int\fP rop, \fBmp_int\fP op1, unsigned long op2)"
.br
.ti -1c
.RI "void \fBisl_imath_submul_ui\fP (\fBmp_int\fP rop, \fBmp_int\fP op1, unsigned long op2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void isl_imath_addmul_ui (\fBmp_int\fP rop, \fBmp_int\fP op1, unsigned long op2)"

.SS "int isl_imath_fits_slong_p (\fBmp_int\fP op)"

.SS "int isl_imath_fits_ulong_p (\fBmp_int\fP op)"

.SS "uint32_t isl_imath_hash (\fBmp_int\fP v, uint32_t hash)"

.SS "void isl_imath_submul_ui (\fBmp_int\fP rop, \fBmp_int\fP op1, unsigned long op2)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
