.TH "isl_add_nodes_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_add_nodes_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_union_map\fP * \fBexecuted\fP"
.br
.ti -1c
.RI "\fBisl_ast_build\fP * \fBbuild\fP"
.br
.ti -1c
.RI "isl_ast_graft_list * \fBlist\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_ast_build\fP* isl_add_nodes_data::build"

.SS "\fBisl_union_map\fP* isl_add_nodes_data::executed"

.SS "isl_ast_graft_list* isl_add_nodes_data::list"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
