.TH "isl_schedule_constraints" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_schedule_constraints
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_union_set\fP * \fBdomain\fP"
.br
.ti -1c
.RI "\fBisl_set\fP * \fBcontext\fP"
.br
.ti -1c
.RI "\fBisl_union_map\fP * \fBconstraint\fP [\fBisl_edge_last\fP+1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_union_map\fP* isl_schedule_constraints::constraint[\fBisl_edge_last\fP+1]"

.SS "\fBisl_set\fP* isl_schedule_constraints::context"

.SS "\fBisl_union_set\fP* isl_schedule_constraints::domain"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
