.TH "isl_tarjan_node" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_tarjan_node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_tarjan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBmin_index\fP"
.br
.ti -1c
.RI "int \fBon_stack\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_tarjan_node::index"

.SS "int isl_tarjan_node::min_index"

.SS "int isl_tarjan_node::on_stack"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
