.TH "lib/isl/isl_ctx_private.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_ctx_private.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/ctx\&.h>\fP
.br
\fC#include <isl_blk\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_ctx\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_ctx_next_operation\fP (\fBisl_ctx\fP *ctx)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isl_ctx_next_operation (\fBisl_ctx\fP * ctx)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
