.TH "lib/isl/isl_ast_int.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_ast_int.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl/deprecated/ast_int\&.h>\fP
.br
\fC#include <isl/deprecated/val_int\&.h>\fP
.br
\fC#include <isl_ast_private\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_ast_expr_get_int\fP (\fB__isl_keep\fP \fBisl_ast_expr\fP *expr, \fBisl_int\fP *v)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isl_ast_expr_get_int (\fB__isl_keep\fP \fBisl_ast_expr\fP * expr, \fBisl_int\fP * v)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
