.TH "isl_id" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_id
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_id_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_ctx\fP * \fBctx\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBname\fP"
.br
.ti -1c
.RI "void * \fBuser\fP"
.br
.ti -1c
.RI "uint32_t \fBhash\fP"
.br
.ti -1c
.RI "\fB__isl_give\fP void(* \fBfree_user\fP )(void *\fBuser\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_ctx\fP* isl_id::ctx"

.SS "\fB__isl_give\fP void(* isl_id::free_user) (void *\fBuser\fP)"

.SS "uint32_t isl_id::hash"

.SS "\fBconst\fP char* isl_id::name"

.SS "int isl_id::ref"

.SS "void* isl_id::user"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
