.TH "lib/isl/isl_arg.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_arg.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <isl/arg\&.h>\fP
.br
\fC#include <isl/ctx\&.h>\fP
.br
\fC#include <isl_config\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_prefixes\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBisl_args_set_defaults\fP (struct \fBisl_args\fP *args, void *opt)"
.br
.ti -1c
.RI "void \fBisl_args_free\fP (struct \fBisl_args\fP *args, void *opt)"
.br
.ti -1c
.RI "\fBconst\fP void * \fBisl_memrchr\fP (\fBconst\fP void *s, int \fBc\fP, size_t \fBn\fP)"
.br
.ti -1c
.RI "int \fBisl_args_parse\fP (struct \fBisl_args\fP *args, int argc, char **argv, void *opt, unsigned flags)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void isl_args_free (struct \fBisl_args\fP * args, void * opt)"

.SS "int isl_args_parse (struct \fBisl_args\fP * args, int argc, char ** argv, void * opt, unsigned flags)"

.SS "void isl_args_set_defaults (struct \fBisl_args\fP * args, void * opt)"

.SS "\fBconst\fP void* isl_memrchr (\fBconst\fP void * s, int c, size_t n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
