.TH "isl_dim_map" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_dim_map
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBlen\fP"
.br
.ti -1c
.RI "struct \fBisl_dim_map_entry\fP \fBm\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned isl_dim_map::len"

.SS "struct \fBisl_dim_map_entry\fP isl_dim_map::m[1]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
