.TH "lib/isl/isl_bernstein.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_bernstein.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl_bound\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_qpolynomial_bound_on_domain_bernstein\fP (\fB__isl_take\fP \fBisl_basic_set\fP *bset, \fB__isl_take\fP \fBisl_qpolynomial\fP *poly, struct \fBisl_bound\fP *bound)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isl_qpolynomial_bound_on_domain_bernstein (\fB__isl_take\fP \fBisl_basic_set\fP * bset, \fB__isl_take\fP \fBisl_qpolynomial\fP * poly, struct \fBisl_bound\fP * bound)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
