.TH "isl_sched_edge" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_sched_edge
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_map\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBisl_union_map\fP * \fBtagged_condition\fP"
.br
.ti -1c
.RI "\fBisl_union_map\fP * \fBtagged_validity\fP"
.br
.ti -1c
.RI "struct \fBisl_sched_node\fP * \fBsrc\fP"
.br
.ti -1c
.RI "struct \fBisl_sched_node\fP * \fBdst\fP"
.br
.ti -1c
.RI "unsigned \fBtypes\fP"
.br
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int \fBend\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_sched_node\fP* isl_sched_edge::dst"

.SS "int isl_sched_edge::end"

.SS "\fBisl_map\fP* isl_sched_edge::map"

.SS "struct \fBisl_sched_node\fP* isl_sched_edge::src"

.SS "int isl_sched_edge::start"

.SS "\fBisl_union_map\fP* isl_sched_edge::tagged_condition"

.SS "\fBisl_union_map\fP* isl_sched_edge::tagged_validity"

.SS "unsigned isl_sched_edge::types"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
