.TH "isl_div_sort_info" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_div_sort_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_mat\fP * \fBdiv\fP"
.br
.ti -1c
.RI "int \fBrow\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_mat\fP* isl_div_sort_info::div"

.SS "int isl_div_sort_info::row"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
