.TH "isl_print_space_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_print_space_data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_output_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlatex\fP"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_printer\fP *(* \fBprint_dim\fP )(\fB__isl_take\fP \fBisl_printer\fP *\fBp\fP, struct \fBisl_print_space_data\fP *data, unsigned \fBpos\fP)"
.br
.ti -1c
.RI "void * \fBuser\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBspace\fP"
.br
.ti -1c
.RI "enum \fBisl_dim_type\fP \fBtype\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_print_space_data::latex"

.SS "\fB__isl_give\fP \fBisl_printer\fP*(* isl_print_space_data::print_dim) (\fB__isl_take\fP \fBisl_printer\fP *\fBp\fP, struct \fBisl_print_space_data\fP *data, unsigned \fBpos\fP)"

.SS "\fBisl_space\fP* isl_print_space_data::space"

.SS "enum \fBisl_dim_type\fP isl_print_space_data::type"

.SS "void* isl_print_space_data::user"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
