.TH "isl_morph" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_morph
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_morph\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_basic_set\fP * \fBdom\fP"
.br
.ti -1c
.RI "\fBisl_basic_set\fP * \fBran\fP"
.br
.ti -1c
.RI "\fBisl_mat\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBisl_mat\fP * \fBinv\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_basic_set\fP* isl_morph::dom"

.SS "\fBisl_mat\fP* isl_morph::inv"

.SS "\fBisl_mat\fP* isl_morph::map"

.SS "\fBisl_basic_set\fP* isl_morph::ran"

.SS "int isl_morph::ref"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
