.TH "lib/isl/isl_ilp_private.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_ilp_private.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl_int\&.h>\fP
.br
\fC#include <isl/lp\&.h>\fP
.br
\fC#include <isl/set\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_basic_set_solve_ilp\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, int \fBmax\fP, \fBisl_int\fP *\fBf\fP, \fBisl_int\fP *opt, \fB__isl_give\fP \fBisl_vec\fP **sol_p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "enum \fBisl_lp_result\fP isl_basic_set_solve_ilp (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, int max, \fBisl_int\fP * f, \fBisl_int\fP * opt, \fB__isl_give\fP \fBisl_vec\fP ** sol_p)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
