.TH "lib/isl/isl_union_templ.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_union_templ.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBisl_ctx\fP *FN(\fBUNION\fP, cow)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_space\fP * \fBFN\fP (\fBUNION\fP, get_space)"
.br
.ti -1c
.RI "unsigned \fBFN\fP (\fBUNION\fP, \fBdim\fP)"
.br
.ti -1c
.RI "int \fBFN\fP (\fBUNION\fP, find_dim_by_name)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, \fBZERO\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, \fBcopy\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBPART\fP * \fBFN\fP (FN(\fBUNION\fP, \fBextract\fP), \fBPARTS\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (FN(\fBUNION\fP, \fBadd\fP), \fBPARTS\fP)"
.br
.ti -1c
.RI "\fBS\fP (\fBUNION\fP, transform_data)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, \fBdup\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, cow)"
.br
.ti -1c
.RI "\fB__isl_null\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, \fBfree\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, align_params)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (FN(\fBUNION\fP, from), \fBPARTS\fP)"
.br
.ti -1c
.RI "\fBS\fP (\fBUNION\fP, match_bin_data)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, \fBadd\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, \fBsub\fP)"
.br
.ti -1c
.RI "\fBS\fP (\fBUNION\fP, any_set_data)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, intersect_params)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, gist_params)"
.br
.ti -1c
.RI "\fBS\fP (\fBUNION\fP, match_domain_data)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, intersect_domain)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, subtract_domain)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, \fBgist\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, coalesce)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_union_set\fP * \fBFN\fP (\fBUNION\fP, \fBdomain\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, mul_isl_int)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, scale_val)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, scale_down_val)"
.br
.ti -1c
.RI "\fBS\fP (\fBUNION\fP, plain_is_equal_data)"
.br
.ti -1c
.RI "\fBisl_bool\fP \fBFN\fP (\fBUNION\fP, plain_is_equal)"
.br
.ti -1c
.RI "\fBS\fP (\fBUNION\fP, drop_dims_data)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, drop_dims)"
.br
.ti -1c
.RI "\fBS\fP (\fBUNION\fP, set_dim_name_data)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, set_dim_name)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, reset_user)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBUNION\fP* FN (FN(\fBUNION\fP, \fBadd\fP), \fBPARTS\fP)"

.SS "\fB__isl_give\fP \fBPART\fP* FN (FN(\fBUNION\fP, \fBextract\fP), \fBPARTS\fP)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (FN(\fBUNION\fP, from), \fBPARTS\fP)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBisl_ctx\fP *FN( UNION, cow)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, \fBadd\fP)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, align_params)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, coalesce)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, \fBcopy\fP)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, cow)"

.SS "unsigned FN (\fBUNION\fP, \fBdim\fP)"

.SS "\fB__isl_give\fP \fBisl_union_set\fP* FN (\fBUNION\fP, \fBdomain\fP)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, drop_dims)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, \fBdup\fP)"

.SS "int FN (\fBUNION\fP, find_dim_by_name)"

.SS "\fB__isl_null\fP \fBUNION\fP* FN (\fBUNION\fP, \fBfree\fP)"

.SS "\fB__isl_give\fP \fBisl_space\fP* FN (\fBUNION\fP, get_space)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, \fBgist\fP)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, gist_params)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, intersect_domain)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, intersect_params)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, mul_isl_int)"

.SS "\fBisl_bool\fP FN (\fBUNION\fP, plain_is_equal)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, reset_user)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, scale_down_val)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, scale_val)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, set_dim_name)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, \fBsub\fP)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, subtract_domain)"

.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, \fBZERO\fP)"

.SS "S (\fBUNION\fP, any_set_data)"

.SS "S (\fBUNION\fP, drop_dims_data)"

.SS "S (\fBUNION\fP, match_bin_data)"

.SS "S (\fBUNION\fP, match_domain_data)"

.SS "S (\fBUNION\fP, plain_is_equal_data)"

.SS "S (\fBUNION\fP, set_dim_name_data)"

.SS "S (\fBUNION\fP, transform_data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
