.TH "isl_union_map" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_union_map
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_union_map_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBdim\fP"
.br
.ti -1c
.RI "struct \fBisl_hash_table\fP \fBtable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_space\fP* isl_union_map::dim"

.SS "int isl_union_map::ref"

.SS "struct \fBisl_hash_table\fP isl_union_map::table"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
