.TH "lib/isl/isl_sort.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_sort.h
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_sort\fP (void *\fBconst\fP pbase, size_t total_elems, size_t \fBsize\fP, int(*\fBcmp\fP)(\fBconst\fP void *, \fBconst\fP void *, void *\fBarg\fP), void *\fBarg\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isl_sort (void *\fBconst\fP pbase, size_t total_elems, size_t size, int(*)(\fBconst\fP void *, \fBconst\fP void *, void *\fBarg\fP) cmp, void * arg)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
