.TH "isl_sol_pma" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_sol_pma
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_sol\fP \fBsol\fP"
.br
.ti -1c
.RI "\fBisl_pw_multi_aff\fP * \fBpma\fP"
.br
.ti -1c
.RI "\fBisl_set\fP * \fBempty\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_set\fP* isl_sol_pma::empty"

.SS "\fBisl_pw_multi_aff\fP* isl_sol_pma::pma"

.SS "struct \fBisl_sol\fP isl_sol_pma::sol"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
