.TH "lib/isl/isl_vertices_private.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_vertices_private.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/set\&.h>\fP
.br
\fC#include <isl/vertices\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_vertex\fP"
.br
.ti -1c
.RI "struct \fBisl_chamber\fP"
.br
.ti -1c
.RI "struct \fBisl_vertices\fP"
.br
.ti -1c
.RI "struct \fBisl_cell\fP"
.br
.ti -1c
.RI "struct \fBisl_external_vertex\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_vertices_foreach_disjoint_cell\fP (\fB__isl_keep\fP \fBisl_vertices\fP *vertices, int(*\fBfn\fP)(\fB__isl_take\fP \fBisl_cell\fP *cell, void *\fBuser\fP), void *\fBuser\fP)"
.br
.ti -1c
.RI "int \fBisl_cell_foreach_simplex\fP (\fB__isl_take\fP \fBisl_cell\fP *cell, int(*\fBfn\fP)(\fB__isl_take\fP \fBisl_cell\fP *simplex, void *\fBuser\fP), void *\fBuser\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vertices\fP * \fBisl_morph_vertices\fP (\fB__isl_take\fP struct \fBisl_morph\fP *morph, \fB__isl_take\fP \fBisl_vertices\fP *vertices)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isl_cell_foreach_simplex (\fB__isl_take\fP \fBisl_cell\fP * cell, int(*)(\fB__isl_take\fP \fBisl_cell\fP *simplex, void *\fBuser\fP) fn, void * user)"

.SS "\fB__isl_give\fP \fBisl_vertices\fP* isl_morph_vertices (\fB__isl_take\fP struct \fBisl_morph\fP * morph, \fB__isl_take\fP \fBisl_vertices\fP * vertices)"

.SS "int isl_vertices_foreach_disjoint_cell (\fB__isl_keep\fP \fBisl_vertices\fP * vertices, int(*)(\fB__isl_take\fP \fBisl_cell\fP *cell, void *\fBuser\fP) fn, void * user)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
