.TH "lib/isl/isl_union_neg.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_union_neg.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl_union_macro\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBUNION\fP * \fBFN\fP (\fBUNION\fP, \fBneg\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBUNION\fP* FN (\fBUNION\fP, \fBneg\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
