.TH "isl_apply_fold_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_apply_fold_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_union_pw_qpolynomial_fold\fP * \fBupwf\fP"
.br
.ti -1c
.RI "\fBisl_union_pw_qpolynomial_fold\fP * \fBres\fP"
.br
.ti -1c
.RI "\fBisl_map\fP * \fBmap\fP"
.br
.ti -1c
.RI "int \fBtight\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_map\fP* isl_apply_fold_data::map"

.SS "\fBisl_union_pw_qpolynomial_fold\fP* isl_apply_fold_data::res"

.SS "int isl_apply_fold_data::tight"

.SS "\fBisl_union_pw_qpolynomial_fold\fP* isl_apply_fold_data::upwf"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
