.TH "isl_chamber" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_chamber
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_vertices_private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn_vertices\fP"
.br
.ti -1c
.RI "int * \fBvertices\fP"
.br
.ti -1c
.RI "\fBisl_basic_set\fP * \fBdom\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_basic_set\fP* isl_chamber::dom"

.SS "int isl_chamber::n_vertices"

.SS "int* isl_chamber::vertices"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
