.TH "lib/isl/isl_ilp.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_ilp.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl_ctx_private\&.h>\fP
.br
\fC#include <isl_map_private\&.h>\fP
.br
\fC#include <isl/ilp\&.h>\fP
.br
\fC#include 'isl_sample\&.h'\fP
.br
\fC#include <isl_seq\&.h>\fP
.br
\fC#include 'isl_equalities\&.h'\fP
.br
\fC#include <isl_aff_private\&.h>\fP
.br
\fC#include <isl_local_space_private\&.h>\fP
.br
\fC#include <isl_mat_private\&.h>\fP
.br
\fC#include <isl_val_private\&.h>\fP
.br
\fC#include <isl_vec_private\&.h>\fP
.br
\fC#include <isl_lp_private\&.h>\fP
.br
\fC#include <isl_ilp_private\&.h>\fP
.br
\fC#include <isl/deprecated/ilp_int\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_basic_set_solve_ilp\fP (struct \fBisl_basic_set\fP *bset, int \fBmax\fP, \fBisl_int\fP *\fBf\fP, \fBisl_int\fP *opt, struct \fBisl_vec\fP **sol_p)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_basic_set_opt\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, int \fBmax\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj, \fBisl_int\fP *opt)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_set_opt\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, int \fBmax\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj, \fBisl_int\fP *opt)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_basic_set_max\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fB__isl_keep\fP \fBisl_aff\fP *obj, \fBisl_int\fP *opt)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_set_max\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj, \fBisl_int\fP *opt)"
.br
.ti -1c
.RI "enum \fBisl_lp_result\fP \fBisl_set_min\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj, \fBisl_int\fP *opt)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_basic_set_opt_val\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, int \fBmax\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_basic_set_max_val\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_set_opt_val\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, int \fBmax\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_set_min_val\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_set_max_val\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "enum \fBisl_lp_result\fP isl_basic_set_max (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fB__isl_keep\fP \fBisl_aff\fP * obj, \fBisl_int\fP * opt)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_basic_set_max_val (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SS "enum \fBisl_lp_result\fP isl_basic_set_opt (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, int max, \fB__isl_keep\fP \fBisl_aff\fP * obj, \fBisl_int\fP * opt)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_basic_set_opt_val (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, int max, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SS "enum \fBisl_lp_result\fP isl_basic_set_solve_ilp (struct \fBisl_basic_set\fP * bset, int max, \fBisl_int\fP * f, \fBisl_int\fP * opt, struct \fBisl_vec\fP ** sol_p)"

.SS "enum \fBisl_lp_result\fP isl_set_max (\fB__isl_keep\fP \fBisl_set\fP * set, \fB__isl_keep\fP \fBisl_aff\fP * obj, \fBisl_int\fP * opt)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_set_max_val (\fB__isl_keep\fP \fBisl_set\fP * set, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SS "enum \fBisl_lp_result\fP isl_set_min (\fB__isl_keep\fP \fBisl_set\fP * set, \fB__isl_keep\fP \fBisl_aff\fP * obj, \fBisl_int\fP * opt)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_set_min_val (\fB__isl_keep\fP \fBisl_set\fP * set, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SS "enum \fBisl_lp_result\fP isl_set_opt (\fB__isl_keep\fP \fBisl_set\fP * set, int max, \fB__isl_keep\fP \fBisl_aff\fP * obj, \fBisl_int\fP * opt)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_set_opt_val (\fB__isl_keep\fP \fBisl_set\fP * set, int max, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
