.TH "isl_detect_stride_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_detect_stride_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_ast_build\fP * \fBbuild\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_ast_build\fP* isl_detect_stride_data::build"

.SS "int isl_detect_stride_data::pos"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
