.TH "isl_node_gist_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_node_gist_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn_expansion\fP"
.br
.ti -1c
.RI "\fBisl_union_set_list\fP * \fBfilters\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_union_set_list\fP* isl_node_gist_data::filters"

.SS "int isl_node_gist_data::n_expansion"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
