.TH "isl_sched_node" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_sched_node
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_space\fP * \fBspace\fP"
.br
.ti -1c
.RI "int \fBcompressed\fP"
.br
.ti -1c
.RI "\fBisl_set\fP * \fBhull\fP"
.br
.ti -1c
.RI "\fBisl_multi_aff\fP * \fBcompress\fP"
.br
.ti -1c
.RI "\fBisl_multi_aff\fP * \fBdecompress\fP"
.br
.ti -1c
.RI "\fBisl_mat\fP * \fBsched\fP"
.br
.ti -1c
.RI "\fBisl_map\fP * \fBsched_map\fP"
.br
.ti -1c
.RI "int \fBrank\fP"
.br
.ti -1c
.RI "\fBisl_mat\fP * \fBcmap\fP"
.br
.ti -1c
.RI "\fBisl_mat\fP * \fBcinv\fP"
.br
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int \fBnvar\fP"
.br
.ti -1c
.RI "int \fBnparam\fP"
.br
.ti -1c
.RI "int \fBscc\fP"
.br
.ti -1c
.RI "int * \fBcoincident\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_mat\fP* isl_sched_node::cinv"

.SS "\fBisl_mat\fP* isl_sched_node::cmap"

.SS "int* isl_sched_node::coincident"

.SS "\fBisl_multi_aff\fP* isl_sched_node::compress"

.SS "int isl_sched_node::compressed"

.SS "\fBisl_multi_aff\fP* isl_sched_node::decompress"

.SS "\fBisl_set\fP* isl_sched_node::hull"

.SS "int isl_sched_node::nparam"

.SS "int isl_sched_node::nvar"

.SS "int isl_sched_node::rank"

.SS "int isl_sched_node::scc"

.SS "\fBisl_mat\fP* isl_sched_node::sched"

.SS "\fBisl_map\fP* isl_sched_node::sched_map"

.SS "\fBisl_space\fP* isl_sched_node::space"

.SS "int isl_sched_node::start"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
