.TH "isl_scan_callback" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_scan_callback
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_scan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_stat\fP(* \fBadd\fP )(struct \fBisl_scan_callback\fP *cb, \fB__isl_take\fP \fBisl_vec\fP *sample)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_stat\fP(* isl_scan_callback::add) (struct \fBisl_scan_callback\fP *cb, \fB__isl_take\fP \fBisl_vec\fP *sample)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
