.TH "isl_scan_pip" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_scan_pip
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_scan_callback\fP \fBcallback\fP"
.br
.ti -1c
.RI "\fBisl_basic_set\fP * \fBbset\fP"
.br
.ti -1c
.RI "\fBisl_set\fP * \fBsol\fP"
.br
.ti -1c
.RI "\fBisl_set\fP * \fBempty\fP"
.br
.ti -1c
.RI "int \fBstride\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_basic_set\fP* isl_scan_pip::bset"

.SS "struct \fBisl_scan_callback\fP isl_scan_pip::callback"

.SS "\fBisl_set\fP* isl_scan_pip::empty"

.SS "int isl_scan_pip::max"

.SS "int isl_scan_pip::n"

.SS "\fBisl_set\fP* isl_scan_pip::sol"

.SS "int isl_scan_pip::stride"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
