.TH "isl_factor_groups" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_factor_groups
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int * \fBpos\fP"
.br
.ti -1c
.RI "int * \fBgroup\fP"
.br
.ti -1c
.RI "int * \fBcnt\fP"
.br
.ti -1c
.RI "int * \fBrowgroup\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int* isl_factor_groups::cnt"

.SS "int* isl_factor_groups::group"

.SS "int* isl_factor_groups::pos"

.SS "int* isl_factor_groups::rowgroup"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
