.TH "isl_partial_sol" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_partial_sol
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "struct \fBisl_basic_set\fP * \fBdom\fP"
.br
.ti -1c
.RI "struct \fBisl_mat\fP * \fBM\fP"
.br
.ti -1c
.RI "struct \fBisl_partial_sol\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_basic_set\fP* isl_partial_sol::dom"

.SS "int isl_partial_sol::level"

.SS "struct \fBisl_mat\fP* isl_partial_sol::M"

.SS "struct \fBisl_partial_sol\fP* isl_partial_sol::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
