.TH "lib/isl/isl_ast_build_expr.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_ast_build_expr.c
.SH SYNOPSIS
.br
.PP
\fC#include <isl/constraint\&.h>\fP
.br
\fC#include <isl/ilp\&.h>\fP
.br
\fC#include <isl_ast_build_expr\&.h>\fP
.br
\fC#include <isl_ast_private\&.h>\fP
.br
\fC#include <isl_ast_build_private\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_ast_add_term_data\fP"
.br
.ti -1c
.RI "struct \fBisl_extract_mod_data\fP"
.br
.ti -1c
.RI "struct \fBisl_from_pw_aff_data\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_expr_from_aff\fP (\fB__isl_take\fP \fBisl_aff\fP *aff, \fB__isl_keep\fP \fBisl_ast_build\fP *build)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_build_expr_from_basic_set\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_basic_set\fP *bset)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_build_expr_from_set_internal\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_set\fP *\fBset\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_build_expr_from_set\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_set\fP *\fBset\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_build_expr_from_pw_aff_internal\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_pw_aff\fP *pa)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_build_expr_from_pw_aff\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_pw_aff\fP *pa)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_build_call_from_multi_pw_aff\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_multi_pw_aff\fP *mpa)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_build_access_from_multi_pw_aff\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_multi_pw_aff\fP *mpa)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_build_call_from_pw_multi_aff\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_pw_multi_aff\fP *pma)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_expr\fP * \fBisl_ast_build_access_from_pw_multi_aff\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_pw_multi_aff\fP *pma)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_ast_node\fP * \fBisl_ast_build_call_from_executed\fP (\fB__isl_keep\fP \fBisl_ast_build\fP *build, \fB__isl_take\fP \fBisl_map\fP *executed)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_build_access_from_multi_pw_aff (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_multi_pw_aff\fP * mpa)"

.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_build_access_from_pw_multi_aff (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_pw_multi_aff\fP * pma)"

.SS "\fB__isl_give\fP \fBisl_ast_node\fP* isl_ast_build_call_from_executed (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_map\fP * executed)"

.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_build_call_from_multi_pw_aff (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_multi_pw_aff\fP * mpa)"

.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_build_call_from_pw_multi_aff (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_pw_multi_aff\fP * pma)"

.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_build_expr_from_basic_set (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_basic_set\fP * bset)"

.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_build_expr_from_pw_aff (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_pw_aff\fP * pa)"

.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_build_expr_from_pw_aff_internal (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_pw_aff\fP * pa)"

.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_build_expr_from_set (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_set\fP * set)"

.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_build_expr_from_set_internal (\fB__isl_keep\fP \fBisl_ast_build\fP * build, \fB__isl_take\fP \fBisl_set\fP * set)"

.SS "\fB__isl_give\fP \fBisl_ast_expr\fP* isl_ast_expr_from_aff (\fB__isl_take\fP \fBisl_aff\fP * aff, \fB__isl_keep\fP \fBisl_ast_build\fP * build)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
