.TH "isl_wraps" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_wraps
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBbound\fP"
.br
.ti -1c
.RI "\fBisl_mat\fP * \fBmat\fP"
.br
.ti -1c
.RI "\fBisl_int\fP \fBmax\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_wraps::bound"

.SS "\fBisl_mat\fP* isl_wraps::mat"

.SS "\fBisl_int\fP isl_wraps::max"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
