.TH "lib/isl/isl_output_private.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_output_private.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/space\&.h>\fP
.br
\fC#include <isl/printer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_print_space_data\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_printer\fP * \fBisl_print_space\fP (\fB__isl_keep\fP \fBisl_space\fP *space, \fB__isl_take\fP \fBisl_printer\fP *\fBp\fP, int rational, struct \fBisl_print_space_data\fP *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_printer\fP* isl_print_space (\fB__isl_keep\fP \fBisl_space\fP * space, \fB__isl_take\fP \fBisl_printer\fP * p, int rational, struct \fBisl_print_space_data\fP * data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
