.TH "lib/isl/isl_blk.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/isl_blk.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl_int\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBisl_blk\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBISL_BLK_CACHE_SIZE\fP   20"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBisl_blk\fP \fBisl_blk_alloc\fP (struct \fBisl_ctx\fP *ctx, size_t \fBn\fP)"
.br
.ti -1c
.RI "struct \fBisl_blk\fP \fBisl_blk_empty\fP (void)"
.br
.ti -1c
.RI "int \fBisl_blk_is_error\fP (struct \fBisl_blk\fP block)"
.br
.ti -1c
.RI "struct \fBisl_blk\fP \fBisl_blk_extend\fP (struct \fBisl_ctx\fP *ctx, struct \fBisl_blk\fP block, size_t new_n)"
.br
.ti -1c
.RI "void \fBisl_blk_free\fP (struct \fBisl_ctx\fP *ctx, struct \fBisl_blk\fP block)"
.br
.ti -1c
.RI "void \fBisl_blk_clear_cache\fP (struct \fBisl_ctx\fP *ctx)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ISL_BLK_CACHE_SIZE   20"

.SH "Function Documentation"
.PP 
.SS "struct \fBisl_blk\fP isl_blk_alloc (struct \fBisl_ctx\fP * ctx, size_t n)"

.SS "void isl_blk_clear_cache (struct \fBisl_ctx\fP * ctx)"

.SS "struct \fBisl_blk\fP isl_blk_empty (void)"

.SS "struct \fBisl_blk\fP isl_blk_extend (struct \fBisl_ctx\fP * ctx, struct \fBisl_blk\fP block, size_t new_n)"

.SS "void isl_blk_free (struct \fBisl_ctx\fP * ctx, struct \fBisl_blk\fP block)"

.SS "int isl_blk_is_error (struct \fBisl_blk\fP block)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
