.TH "isl_schedule_node_postorder_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_schedule_node_postorder_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_schedule_node\fP *(* \fBfn\fP )(\fB__isl_take\fP \fBisl_schedule_node\fP *node, void *\fBuser\fP)"
.br
.ti -1c
.RI "void * \fBuser\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_schedule_node\fP*(* isl_schedule_node_postorder_data::fn) (\fB__isl_take\fP \fBisl_schedule_node\fP *node, void *\fBuser\fP)"

.SS "void* isl_schedule_node_postorder_data::user"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
