.TH "isl_opt_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_opt_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_qpolynomial\fP * \fBqp\fP"
.br
.ti -1c
.RI "int \fBfirst\fP"
.br
.ti -1c
.RI "\fBisl_val\fP * \fBopt\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_opt_data::first"

.SS "int isl_opt_data::max"

.SS "\fBisl_val\fP* isl_opt_data::opt"

.SS "\fBisl_qpolynomial\fP* isl_opt_data::qp"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
