.TH "isl_set_map_pair" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_set_map_pair
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_set\fP * \fBset\fP"
.br
.ti -1c
.RI "\fBisl_map\fP * \fBmap\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_map\fP* isl_set_map_pair::map"

.SS "\fBisl_set\fP* isl_set_map_pair::set"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
