.TH "isl_tab_callback" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_tab_callback
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isl_tab\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBrun\fP )(struct \fBisl_tab_callback\fP *cb)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int(* isl_tab_callback::run) (struct \fBisl_tab_callback\fP *cb)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
