.TH "isl_ast_build_involves_data" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isl_ast_build_involves_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "int \fBinvolves\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int isl_ast_build_involves_data::depth"

.SS "int isl_ast_build_involves_data::involves"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
