.TH "test/JacobiTest.cpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/JacobiTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <Eigen/Sparse>\fP
.br
\fC#include <Eigen/SparseExtra>\fP
.br
\fC#include <Eigen/IterativeLinearSolvers>\fP
.br
\fC#include <util/MatrixIO\&.hpp>\fP
.br
\fC#include 'InspExecTest\&.hpp'\fP
.br
\fC#include 'jacobi\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest::JacobiTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtest\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_JacobiTest_HPP_\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Eigen::Triplet< double > \fBTriple\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _JacobiTest_HPP_"

.SH "Typedef Documentation"
.PP 
.SS "typedef Eigen::Triplet<double> \fBTriple\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
