.TH "jsoncons::json_type_traits< JsonT, long long >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::json_type_traits< JsonT, long long >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_type_traits\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBis\fP (\fBconst\fP JsonT &\fBrhs\fP) \fBJSONCONS_NOEXCEPT\fP"
.br
.ti -1c
.RI "static long long \fBas\fP (\fBconst\fP JsonT &\fBrhs\fP)"
.br
.ti -1c
.RI "static void \fBassign\fP (JsonT &\fBlhs\fP, long long \fBrhs\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class JsonT > static long long \fBjsoncons::json_type_traits\fP< JsonT, long long >::as (\fBconst\fP JsonT & rhs)\fC [inline]\fP, \fC [static]\fP"

.SS "template<class JsonT > static void \fBjsoncons::json_type_traits\fP< JsonT, long long >::assign (JsonT & lhs, long long rhs)\fC [inline]\fP, \fC [static]\fP"

.SS "template<class JsonT > static bool \fBjsoncons::json_type_traits\fP< JsonT, long long >::is (\fBconst\fP JsonT & rhs)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
