.TH "jsoncons::basic_parse_error_handler< CharT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::basic_parse_error_handler< CharT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherited by \fBjsoncons::basic_default_parse_error_handler< CharT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~basic_parse_error_handler\fP ()"
.br
.ti -1c
.RI "void \fBwarning\fP (std::error_code ec, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)  throw (parse_exception)"
.br
.ti -1c
.RI "void \fBerror\fP (std::error_code ec, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)  throw (parse_exception)"
.br
.ti -1c
.RI "void \fBfatal_error\fP (std::error_code ec, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)  throw (parse_exception)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CharT > virtual \fBjsoncons::basic_parse_error_handler\fP< CharT >::~\fBbasic_parse_error_handler\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename CharT > void \fBjsoncons::basic_parse_error_handler\fP< CharT >::error (std::error_code ec, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fBparse_exception\fP\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_parse_error_handler\fP< CharT >::fatal_error (std::error_code ec, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fBparse_exception\fP\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_parse_error_handler\fP< CharT >::warning (std::error_code ec, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fBparse_exception\fP\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
