.TH "jsoncons::json_type_traits< JsonT, std::vector< T > >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::json_type_traits< JsonT, std::vector< T > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_type_traits\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBis\fP (\fBconst\fP JsonT &\fBrhs\fP) \fBJSONCONS_NOEXCEPT\fP"
.br
.ti -1c
.RI "static std::vector< \fBT\fP > \fBas\fP (\fBconst\fP JsonT &\fBrhs\fP)"
.br
.ti -1c
.RI "static void \fBassign\fP (JsonT &\fBlhs\fP, \fBconst\fP std::vector< \fBT\fP > &\fBrhs\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class JsonT , typename T > static std::vector<\fBT\fP> \fBjsoncons::json_type_traits\fP< JsonT, std::vector< \fBT\fP > >::as (\fBconst\fP JsonT & rhs)\fC [inline]\fP, \fC [static]\fP"

.SS "template<class JsonT , typename T > static void \fBjsoncons::json_type_traits\fP< JsonT, std::vector< \fBT\fP > >::assign (JsonT & lhs, \fBconst\fP std::vector< \fBT\fP > & rhs)\fC [inline]\fP, \fC [static]\fP"

.SS "template<class JsonT , typename T > static bool \fBjsoncons::json_type_traits\fP< JsonT, std::vector< \fBT\fP > >::is (\fBconst\fP JsonT & rhs)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
