.TH "jsoncons::json_printable< JsonT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::json_printable< JsonT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef JsonT::char_type \fBchar_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBjson_printable\fP (\fBconst\fP JsonT &o, bool is_pretty_print)"
.br
.ti -1c
.RI "\fBjson_printable\fP (\fBconst\fP JsonT &o, bool is_pretty_print, \fBconst\fP \fBbasic_output_format\fP< \fBchar_type\fP > &format)"
.br
.ti -1c
.RI "void \fBto_stream\fP (std::basic_ostream< \fBchar_type\fP > &os) \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP JsonT * \fBo_\fP"
.br
.ti -1c
.RI "bool \fBis_pretty_print_\fP"
.br
.ti -1c
.RI "\fBbasic_output_format\fP< \fBchar_type\fP > \fBformat_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::basic_ostream< \fBchar_type\fP > & \fBoperator<<\fP (std::basic_ostream< \fBchar_type\fP > &os, \fBconst\fP \fBjson_printable\fP< JsonT > &o)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename JsonT > typedef JsonT::char_type \fBjsoncons::json_printable\fP< JsonT >::\fBchar_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename JsonT > \fBjsoncons::json_printable\fP< JsonT >::\fBjson_printable\fP (\fBconst\fP JsonT & o, bool is_pretty_print)\fC [inline]\fP"

.SS "template<typename JsonT > \fBjsoncons::json_printable\fP< JsonT >::\fBjson_printable\fP (\fBconst\fP JsonT & o, bool is_pretty_print, \fBconst\fP \fBbasic_output_format\fP< \fBchar_type\fP > & format)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename JsonT > void \fBjsoncons::json_printable\fP< JsonT >::to_stream (std::basic_ostream< \fBchar_type\fP > & os) const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename JsonT > std::basic_ostream<\fBchar_type\fP>& operator<< (std::basic_ostream< \fBchar_type\fP > & os, \fBconst\fP \fBjson_printable\fP< JsonT > & o)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename JsonT > \fBbasic_output_format\fP<\fBchar_type\fP> \fBjsoncons::json_printable\fP< JsonT >::format_"

.SS "template<typename JsonT > bool \fBjsoncons::json_printable\fP< JsonT >::is_pretty_print_"

.SS "template<typename JsonT > \fBconst\fP JsonT* \fBjsoncons::json_printable\fP< JsonT >::o_"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
