.TH "jsoncons::float_printer< CharT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::float_printer< CharT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jsoncons_io\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfloat_printer\fP (uint8_t precision)"
.br
.ti -1c
.RI "void \fBprint\fP (double \fBval\fP, uint8_t precision, \fBbuffered_ostream\fP< CharT > &os)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CharT > \fBjsoncons::float_printer\fP< CharT >::\fBfloat_printer\fP (uint8_t precision)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename CharT > void \fBjsoncons::float_printer\fP< CharT >::print (double val, uint8_t precision, \fBbuffered_ostream\fP< CharT > & os)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
