.TH "jsoncons::serializable_any< CharT, Alloc >::any_handle" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::serializable_any< CharT, Alloc >::any_handle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherited by \fBjsoncons::serializable_any< CharT, Alloc >::any_handle_impl< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~any_handle\fP ()"
.br
.ti -1c
.RI "virtual \fBany_handle\fP * \fBclone\fP (\fBconst\fP Alloc &allocator) \fBconst\fP =0"
.br
.ti -1c
.RI "virtual void \fBto_stream\fP (\fBbasic_json_output_handler\fP< CharT > &os) \fBconst\fP =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CharT , class Alloc > virtual \fBjsoncons::serializable_any\fP< CharT, Alloc >::any_handle::~any_handle ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename CharT , class Alloc > virtual \fBany_handle\fP* \fBjsoncons::serializable_any\fP< CharT, Alloc >::any_handle::clone (\fBconst\fP Alloc & allocator) const\fC [pure virtual]\fP"

.PP
Implemented in \fBjsoncons::serializable_any< CharT, Alloc >::any_handle_impl< T >\fP\&.
.SS "template<typename CharT , class Alloc > virtual void \fBjsoncons::serializable_any\fP< CharT, Alloc >::any_handle::to_stream (\fBbasic_json_output_handler\fP< CharT > & os) const\fC [pure virtual]\fP"

.PP
Implemented in \fBjsoncons::serializable_any< CharT, Alloc >::any_handle_impl< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
