.TH "jsoncons::basic_ovectorstream< CharT, CharTraits >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::basic_ovectorstream< CharT, CharTraits >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ovectorstream\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::basic_ios< CharT, CharTraits >::\fBchar_type\fP \fBchar_type\fP"
.br
.ti -1c
.RI "typedef std::basic_ios< \fBchar_type\fP, CharTraits >::\fBint_type\fP \fBint_type\fP"
.br
.ti -1c
.RI "typedef std::basic_ios< \fBchar_type\fP, CharTraits >::\fBpos_type\fP \fBpos_type\fP"
.br
.ti -1c
.RI "typedef std::basic_ios< \fBchar_type\fP, CharTraits >::\fBoff_type\fP \fBoff_type\fP"
.br
.ti -1c
.RI "typedef std::basic_ios< \fBchar_type\fP, CharTraits >::\fBtraits_type\fP \fBtraits_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbasic_ovectorstream\fP (std::size_t \fBlength\fP) \fBJSONCONS_NOEXCEPT\fP"
.br
.ti -1c
.RI "\fB~basic_ovectorstream\fP ()"
.br
.ti -1c
.RI "size_t \fBlength\fP ()"
.br
.ti -1c
.RI "void \fBset_locale\fP (\fBconst\fP std::locale &\fBloc\fP)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "\fBconst\fP CharT * \fBdata\fP () \fBconst\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<class CharT , class CharTraits > typedef std::basic_ios<CharT, CharTraits>::\fBchar_type\fP \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::\fBchar_type\fP"

.SS "template<class CharT , class CharTraits > typedef std::basic_ios<\fBchar_type\fP, CharTraits>::\fBint_type\fP \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::\fBint_type\fP"

.SS "template<class CharT , class CharTraits > typedef std::basic_ios<\fBchar_type\fP, CharTraits>::\fBoff_type\fP \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::\fBoff_type\fP"

.SS "template<class CharT , class CharTraits > typedef std::basic_ios<\fBchar_type\fP, CharTraits>::\fBpos_type\fP \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::\fBpos_type\fP"

.SS "template<class CharT , class CharTraits > typedef std::basic_ios<\fBchar_type\fP, CharTraits>::\fBtraits_type\fP \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::\fBtraits_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class CharT , class CharTraits > \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::\fBbasic_ovectorstream\fP (std::size_t length)\fC [inline]\fP"

.SS "template<class CharT , class CharTraits > \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::~\fBbasic_ovectorstream\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class CharT , class CharTraits > \fBconst\fP CharT* \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::data () const\fC [inline]\fP"

.SS "template<class CharT , class CharTraits > size_t \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::length ()\fC [inline]\fP"

.SS "template<class CharT , class CharTraits > void \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::reset ()\fC [inline]\fP"

.SS "template<class CharT , class CharTraits > void \fBjsoncons::basic_ovectorstream\fP< CharT, CharTraits >::set_locale (\fBconst\fP std::locale & loc)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
