.TH "jsoncons::basic_json_output_handler< CharT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::basic_json_output_handler< CharT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_output_handler\&.hpp>\fP
.PP
Inherited by \fBjsoncons::basic_json_output_input_adapter< CharT >\fP, \fBjsoncons::basic_json_serializer< CharT >\fP, and \fBjsoncons::null_json_output_handler_impl< CharT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~basic_json_output_handler\fP ()"
.br
.ti -1c
.RI "void \fBbegin_json\fP ()"
.br
.ti -1c
.RI "void \fBend_json\fP ()"
.br
.ti -1c
.RI "void \fBbegin_object\fP ()"
.br
.ti -1c
.RI "void \fBend_object\fP ()"
.br
.ti -1c
.RI "void \fBbegin_array\fP ()"
.br
.ti -1c
.RI "void \fBend_array\fP ()"
.br
.ti -1c
.RI "void \fBname\fP (\fBconst\fP std::basic_string< CharT > &name)"
.br
.ti -1c
.RI "void \fBname\fP (\fBconst\fP CharT *\fBp\fP, size_t length)"
.br
.ti -1c
.RI "void \fBvalue\fP (\fBconst\fP std::basic_string< CharT > &value)"
.br
.ti -1c
.RI "void \fBvalue\fP (\fBconst\fP CharT *\fBp\fP, size_t length)"
.br
.ti -1c
.RI "void \fBvalue\fP (\fBconst\fP CharT *\fBp\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (int value)"
.br
.ti -1c
.RI "void \fBvalue\fP (long value)"
.br
.ti -1c
.RI "void \fBvalue\fP (long long value)"
.br
.ti -1c
.RI "void \fBvalue\fP (unsigned int value)"
.br
.ti -1c
.RI "void \fBvalue\fP (unsigned long value)"
.br
.ti -1c
.RI "void \fBvalue\fP (unsigned long long value)"
.br
.ti -1c
.RI "void \fBvalue\fP (double value, uint8_t precision=0)"
.br
.ti -1c
.RI "void \fBvalue\fP (bool value)"
.br
.ti -1c
.RI "void \fBvalue\fP (\fBnull_type\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CharT > virtual \fBjsoncons::basic_json_output_handler\fP< CharT >::~\fBbasic_json_output_handler\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::begin_array ()\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::begin_json ()\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::begin_object ()\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::end_array ()\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::end_json ()\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::end_object ()\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::name (\fBconst\fP CharT * p, size_t length)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::name (\fBconst\fP std::basic_string< CharT > & name)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (bool value)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (\fBconst\fP CharT * p)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (\fBconst\fP CharT * p, size_t length)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (\fBconst\fP std::basic_string< CharT > & value)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (double value, uint8_t precision = \fC0\fP)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (int value)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (long long value)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (long value)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (\fBnull_type\fP)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (unsigned int value)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (unsigned long long value)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_output_handler\fP< CharT >::value (unsigned long value)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
