.TH "jsoncons::basic_json< CharT, Alloc >::variant::string_dataA" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::basic_json< CharT, Alloc >::variant::string_dataA
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstring_data\fP \fBdata\fP"
.br
.ti -1c
.RI "\fBchar_type\fP \fBc\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename CharT , typename Alloc  = std::allocator<CharT>> \fBchar_type\fP \fBjsoncons::basic_json\fP< CharT, Alloc >::variant::string_dataA::c[1]"

.SS "template<typename CharT , typename Alloc  = std::allocator<CharT>> \fBstring_data\fP \fBjsoncons::basic_json\fP< CharT, Alloc >::variant::string_dataA::data"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
