.TH "json" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBparseFile\fP (jsonFile)"
.br
.ti -1c
.RI "def \fBparse\fP (jsonStr)"
.br
.ti -1c
.RI "def \fBwriteFile\fP (jsonFile, jsonData)"
.br
.ti -1c
.RI "def \fBwrite\fP (jsonData)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def json\&.parse ( jsonStr)"

.SS "def json\&.parseFile ( jsonFile)"

.SS "def json\&.write ( jsonData)"

.SS "def json\&.writeFile ( jsonFile,  jsonData)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
