.TH "jsoncons::json_exception" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::json_exception
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jsoncons\&.hpp>\fP
.PP
Inherited by \fBjsoncons::json_exception_0< Base >\fP\fC [virtual]\fP, \fBjsoncons::json_exception_1< Base >\fP\fC [virtual]\fP, and \fBjsoncons::parse_exception\fP\fC [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBconst\fP char * \fBwhat\fP () \fBconst\fP \fBJSONCONS_NOEXCEPT\fP=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBconst\fP char* jsoncons::json_exception::what () const\fC [pure virtual]\fP"

.PP
Implemented in \fBjsoncons::json_exception_1< Base >\fP, \fBjsoncons::json_exception_0< Base >\fP, and \fBjsoncons::parse_exception\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
