.TH "lib/iegenlib/src/parser/jsoncons/json_input_handler.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/parser/jsoncons/json_input_handler.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'jsoncons\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjsoncons::basic_parsing_context< CharT >\fP"
.br
.ti -1c
.RI "class \fBjsoncons::basic_json_input_handler< CharT >\fP"
.br
.ti -1c
.RI "class \fBjsoncons::basic_empty_json_input_handler< CharT >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjsoncons\fP"
.br
.RI "Copyright 2013 Daniel Parker\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef basic_json_input_handler< char > \fBjsoncons::json_input_handler\fP"
.br
.ti -1c
.RI "typedef basic_json_input_handler< wchar_t > \fBjsoncons::wjson_input_handler\fP"
.br
.ti -1c
.RI "typedef basic_empty_json_input_handler< char > \fBjsoncons::empty_json_input_handler\fP"
.br
.ti -1c
.RI "typedef basic_empty_json_input_handler< wchar_t > \fBjsoncons::wempty_json_input_handler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename CharT > uint64_t \fBjsoncons::string_to_uinteger\fP (\fBconst\fP CharT *s, size_t length)  throw (std::overflow_error)"
.br
.ti -1c
.RI "template<typename CharT > int64_t \fBjsoncons::string_to_integer\fP (bool has_neg, \fBconst\fP CharT *s, size_t length)  throw (std::overflow_error)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
