.TH "jsoncons::json_error_category_impl" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::json_error_category_impl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_error_category\&.hpp>\fP
.PP
Inherits error_category\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBconst\fP char * \fBname\fP () \fBconst\fP \fBJSONCONS_NOEXCEPT\fP"
.br
.ti -1c
.RI "virtual std::string \fBmessage\fP (int ev) \fBconst\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string jsoncons::json_error_category_impl::message (int ev) const\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual \fBconst\fP char* jsoncons::json_error_category_impl::name () const\fC [inline]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
