.TH "jsoncons::member_lt_string< ValueT, CharT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::member_lt_string< ValueT, CharT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_structures\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmember_lt_string\fP (size_t length)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (\fBconst\fP ValueT &\fBa\fP, \fBconst\fP CharT *\fBb\fP) \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ValueT , typename CharT > \fBjsoncons::member_lt_string\fP< ValueT, CharT >::\fBmember_lt_string\fP (size_t length)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class ValueT , typename CharT > bool \fBjsoncons::member_lt_string\fP< ValueT, CharT >::operator() (\fBconst\fP ValueT & a, \fBconst\fP CharT * b) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
