.TH "jsoncons::parse_exception" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::parse_exception
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parse_error_handler\&.hpp>\fP
.PP
Inherits exception, and \fBjsoncons::json_exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBparse_exception\fP (std::error_code ec, size_t line, size_t column)"
.br
.ti -1c
.RI "\fBparse_exception\fP (\fBconst\fP \fBparse_exception\fP &other)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBwhat\fP () \fBconst\fP \fBJSONCONS_NOEXCEPT\fP"
.br
.ti -1c
.RI "\fBconst\fP std::error_code \fBcode\fP () \fBconst\fP"
.br
.ti -1c
.RI "size_t \fBline_number\fP () \fBconst\fP"
.br
.ti -1c
.RI "size_t \fBcolumn_number\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jsoncons::parse_exception::parse_exception (std::error_code ec, size_t line, size_t column)\fC [inline]\fP"

.SS "jsoncons::parse_exception::parse_exception (\fBconst\fP \fBparse_exception\fP & other)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP std::error_code jsoncons::parse_exception::code () const\fC [inline]\fP"

.SS "size_t jsoncons::parse_exception::column_number () const\fC [inline]\fP"

.SS "size_t jsoncons::parse_exception::line_number () const\fC [inline]\fP"

.SS "\fBconst\fP char* jsoncons::parse_exception::what () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBjsoncons::json_exception\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
