.TH "jsoncons::basic_json_input_handler< CharT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::basic_json_input_handler< CharT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_input_handler\&.hpp>\fP
.PP
Inherited by \fBjsoncons::basic_empty_json_input_handler< CharT >\fP, \fBjsoncons::basic_json_filter< CharT >\fP, and \fBjsoncons::basic_json_input_output_adapter< CharT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~basic_json_input_handler\fP ()"
.br
.ti -1c
.RI "void \fBbegin_json\fP ()"
.br
.ti -1c
.RI "void \fBend_json\fP ()"
.br
.ti -1c
.RI "void \fBbegin_object\fP (\fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBend_object\fP (\fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBbegin_array\fP (\fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBend_array\fP (\fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBname\fP (\fBconst\fP std::basic_string< CharT > &name, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBname\fP (\fBconst\fP CharT *\fBp\fP, size_t length, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (\fBconst\fP std::basic_string< CharT > &value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (\fBconst\fP CharT *\fBp\fP, size_t length, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (\fBconst\fP CharT *\fBp\fP, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (int value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (long value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (long long value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (unsigned int value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (unsigned long value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (unsigned long long value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (float value, uint8_t precision, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (double value, uint8_t precision, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (bool value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.ti -1c
.RI "void \fBvalue\fP (\fBnull_type\fP, \fBconst\fP \fBbasic_parsing_context\fP< CharT > &\fBcontext\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CharT > virtual \fBjsoncons::basic_json_input_handler\fP< CharT >::~\fBbasic_json_input_handler\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::begin_array (\fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::begin_json ()\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::begin_object (\fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::end_array (\fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::end_json ()\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::end_object (\fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::name (\fBconst\fP CharT * p, size_t length, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::name (\fBconst\fP std::basic_string< CharT > & name, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (bool value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (\fBconst\fP CharT * p, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (\fBconst\fP CharT * p, size_t length, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (\fBconst\fP std::basic_string< CharT > & value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (double value, uint8_t precision, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (float value, uint8_t precision, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (int value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (long long value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (long value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (\fBnull_type\fP, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (unsigned int value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (unsigned long long value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_input_handler\fP< CharT >::value (unsigned long value, \fBconst\fP \fBbasic_parsing_context\fP< CharT > & context)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
