.TH "jsoncons::float_reader" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::float_reader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jsoncons_io\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfloat_reader\fP ()"
.br
.ti -1c
.RI "double \fBread\fP (\fBconst\fP char *s, size_t length)"
.br
.ti -1c
.RI "\fBfloat_reader\fP (\fBconst\fP \fBfloat_reader\fP &fr)=delete"
.br
.ti -1c
.RI "\fBfloat_reader\fP & \fBoperator=\fP (\fBconst\fP \fBfloat_reader\fP &fr)=delete"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jsoncons::float_reader::float_reader ()\fC [inline]\fP"

.SS "jsoncons::float_reader::float_reader (\fBconst\fP \fBfloat_reader\fP & fr)\fC [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBfloat_reader\fP& jsoncons::float_reader::operator= (\fBconst\fP \fBfloat_reader\fP & fr)\fC [delete]\fP"

.SS "double jsoncons::float_reader::read (\fBconst\fP char * s, size_t length)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
