.TH "jsoncons::basic_json_reader< CharT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::basic_json_reader< CharT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_reader\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbasic_json_reader\fP (std::basic_istream< CharT > &is, \fBbasic_json_input_handler\fP< CharT > &handler)"
.br
.ti -1c
.RI "\fBbasic_json_reader\fP (std::basic_istream< CharT > &is, \fBbasic_json_input_handler\fP< CharT > &handler, \fBbasic_parse_error_handler\fP< CharT > &err_handler)"
.br
.ti -1c
.RI "size_t \fBbuffer_capacity\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBbuffer_capacity\fP (size_t capacity)"
.br
.ti -1c
.RI "size_t \fBmax_nesting_depth\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBmax_nesting_depth\fP (size_t depth)"
.br
.ti -1c
.RI "void \fBread_next\fP ()"
.br
.ti -1c
.RI "void \fBcheck_done\fP ()"
.br
.ti -1c
.RI "bool \fBeof\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "size_t \fBmax_depth\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBmax_depth\fP (size_t depth)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CharT > \fBjsoncons::basic_json_reader\fP< CharT >::\fBbasic_json_reader\fP (std::basic_istream< CharT > & is, \fBbasic_json_input_handler\fP< CharT > & handler)\fC [inline]\fP"

.SS "template<typename CharT > \fBjsoncons::basic_json_reader\fP< CharT >::\fBbasic_json_reader\fP (std::basic_istream< CharT > & is, \fBbasic_json_input_handler\fP< CharT > & handler, \fBbasic_parse_error_handler\fP< CharT > & err_handler)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename CharT > size_t \fBjsoncons::basic_json_reader\fP< CharT >::buffer_capacity () const\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_reader\fP< CharT >::buffer_capacity (size_t capacity)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_reader\fP< CharT >::check_done ()\fC [inline]\fP"

.SS "template<typename CharT > bool \fBjsoncons::basic_json_reader\fP< CharT >::eof () const\fC [inline]\fP"

.SS "template<typename CharT > size_t \fBjsoncons::basic_json_reader\fP< CharT >::max_depth () const\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_reader\fP< CharT >::max_depth (size_t depth)\fC [inline]\fP"

.SS "template<typename CharT > size_t \fBjsoncons::basic_json_reader\fP< CharT >::max_nesting_depth () const\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_reader\fP< CharT >::max_nesting_depth (size_t depth)\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_reader\fP< CharT >::read ()\fC [inline]\fP"

.SS "template<typename CharT > void \fBjsoncons::basic_json_reader\fP< CharT >::read_next ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
