.TH "lib/iegenlib/src/parser/jsoncons/json_reader.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/parser/jsoncons/json_reader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <istream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <system_error>\fP
.br
\fC#include 'jsoncons\&.hpp'\fP
.br
\fC#include 'json_input_handler\&.hpp'\fP
.br
\fC#include 'parse_error_handler\&.hpp'\fP
.br
\fC#include 'json_parser\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjsoncons::basic_json_reader< CharT >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjsoncons\fP"
.br
.RI "Copyright 2013 Daniel Parker\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef basic_json_reader< char > \fBjsoncons::json_reader\fP"
.br
.ti -1c
.RI "typedef basic_json_reader< wchar_t > \fBjsoncons::wjson_reader\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
