.TH "jsoncons::json_literals< char >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::json_literals< char >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jsoncons\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::pair< \fBconst\fP char *, size_t > \fBnull_literal\fP ()"
.br
.ti -1c
.RI "static std::pair< \fBconst\fP char *, size_t > \fBtrue_literal\fP ()"
.br
.ti -1c
.RI "static std::pair< \fBconst\fP char *, size_t > \fBfalse_literal\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static std::pair<\fBconst\fP char*,size_t> \fBjsoncons::json_literals\fP< char >::false_literal ()\fC [inline]\fP, \fC [static]\fP"

.SS "static std::pair<\fBconst\fP char*,size_t> \fBjsoncons::json_literals\fP< char >::null_literal ()\fC [inline]\fP, \fC [static]\fP"

.SS "static std::pair<\fBconst\fP char*,size_t> \fBjsoncons::json_literals\fP< char >::true_literal ()\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
