.TH "jsoncons::basic_parsing_context< CharT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::basic_parsing_context< CharT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_input_handler\&.hpp>\fP
.PP
Inherited by \fBjsoncons::basic_json_parser< CharT >\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~basic_parsing_context\fP ()"
.br
.ti -1c
.RI "size_t \fBline_number\fP () \fBconst\fP"
.br
.ti -1c
.RI "size_t \fBcolumn_number\fP () \fBconst\fP"
.br
.ti -1c
.RI "CharT \fBcurrent_char\fP () \fBconst\fP"
.br
.ti -1c
.RI "CharT \fBlast_char\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CharT > virtual \fBjsoncons::basic_parsing_context\fP< CharT >::~\fBbasic_parsing_context\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename CharT > size_t \fBjsoncons::basic_parsing_context\fP< CharT >::column_number () const\fC [inline]\fP"

.SS "template<typename CharT > CharT \fBjsoncons::basic_parsing_context\fP< CharT >::current_char () const\fC [inline]\fP"

.SS "template<typename CharT > CharT \fBjsoncons::basic_parsing_context\fP< CharT >::last_char () const\fC [inline]\fP"

.SS "template<typename CharT > size_t \fBjsoncons::basic_parsing_context\fP< CharT >::line_number () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
