.TH "jsoncons::type_wrapper< T & >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::type_wrapper< T & >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jsoncons\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP * \fBpointer_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP & \fBreference\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP typedef \fBT\fP * \fBconst_pointer_type\fP"
.br
.ti -1c
.RI "\fBconst\fP typedef \fBT\fP & \fBconst_reference\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef \fBT\fP* \fBjsoncons::type_wrapper\fP< \fBT\fP & >::\fBpointer_type\fP"

.SS "template<typename T > typedef \fBT\fP& \fBjsoncons::type_wrapper\fP< \fBT\fP & >::\fBreference\fP"

.SS "template<typename T > typedef \fBT\fP \fBjsoncons::type_wrapper\fP< \fBT\fP & >::\fBvalue_type\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > \fBconst\fP typedef \fBT\fP* \fBjsoncons::type_wrapper\fP< \fBT\fP & >::const_pointer_type"

.SS "template<typename T > \fBconst\fP typedef \fBT\fP& \fBjsoncons::type_wrapper\fP< \fBT\fP & >::const_reference"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
