.TH "jsoncons::basic_ovectorbuf< CharT, CharTraits >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::basic_ovectorbuf< CharT, CharTraits >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ovectorstream\&.hpp>\fP
.PP
Inherits basic_streambuf< CharT, CharTraits >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef CharT \fBchar_type\fP"
.br
.ti -1c
.RI "typedef CharTraits::int_type \fBint_type\fP"
.br
.ti -1c
.RI "typedef CharTraits::pos_type \fBpos_type\fP"
.br
.ti -1c
.RI "typedef CharTraits::off_type \fBoff_type\fP"
.br
.ti -1c
.RI "typedef CharTraits \fBtraits_type\fP"
.br
.ti -1c
.RI "typedef std::basic_streambuf< \fBchar_type\fP, \fBtraits_type\fP > \fBbase_streambuf\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbasic_ovectorbuf\fP (std::size_t length) \fBJSONCONS_NOEXCEPT\fP"
.br
.ti -1c
.RI "virtual \fB~basic_ovectorbuf\fP ()"
.br
.ti -1c
.RI "\fBconst\fP CharT * \fBdata\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBint_type\fP \fBunderflow\fP () override"
.br
.ti -1c
.RI "\fBint_type\fP \fBpbackfail\fP (\fBint_type\fP \fBc\fP=CharTraits::eof()) override"
.br
.ti -1c
.RI "\fBint_type\fP \fBoverflow\fP (\fBint_type\fP \fBc\fP=CharTraits::eof()) override"
.br
.ti -1c
.RI "\fBpos_type\fP \fBseekoff\fP (\fBoff_type\fP off, std::ios_base::seekdir dir, std::ios_base::openmode mode=std::ios_base::out) override"
.br
.ti -1c
.RI "\fBpos_type\fP \fBseekoff_beg\fP (\fBoff_type\fP off)"
.br
.ti -1c
.RI "\fBpos_type\fP \fBseekpos\fP (\fBpos_type\fP \fBpos\fP, std::ios_base::openmode mode=std::ios_base::out) override"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<class CharT , class CharTraits > typedef std::basic_streambuf<\fBchar_type\fP, \fBtraits_type\fP> \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::\fBbase_streambuf\fP"

.SS "template<class CharT , class CharTraits > typedef CharT \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::\fBchar_type\fP"

.SS "template<class CharT , class CharTraits > typedef CharTraits::int_type \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::\fBint_type\fP"

.SS "template<class CharT , class CharTraits > typedef CharTraits::off_type \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::\fBoff_type\fP"

.SS "template<class CharT , class CharTraits > typedef CharTraits::pos_type \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::\fBpos_type\fP"

.SS "template<class CharT , class CharTraits > typedef CharTraits \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::\fBtraits_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class CharT , class CharTraits > \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::\fBbasic_ovectorbuf\fP (std::size_t length)\fC [inline]\fP, \fC [explicit]\fP"

.SS "template<class CharT , class CharTraits > virtual \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::~\fBbasic_ovectorbuf\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class CharT , class CharTraits > \fBconst\fP CharT* \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::data () const\fC [inline]\fP"

.SS "template<class CharT , class CharTraits > \fBint_type\fP \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::overflow (\fBint_type\fP c = \fCCharTraits::eof()\fP)\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP"

.SS "template<class CharT , class CharTraits > \fBint_type\fP \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::pbackfail (\fBint_type\fP c = \fCCharTraits::eof()\fP)\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP"

.SS "template<class CharT , class CharTraits > \fBpos_type\fP \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::seekoff (\fBoff_type\fP off, std::ios_base::seekdir dir, std::ios_base::openmode mode = \fCstd::ios_base::out\fP)\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP"

.SS "template<class CharT , class CharTraits > \fBpos_type\fP \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::seekoff_beg (\fBoff_type\fP off)\fC [inline]\fP, \fC [protected]\fP"

.SS "template<class CharT , class CharTraits > \fBpos_type\fP \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::seekpos (\fBpos_type\fP pos, std::ios_base::openmode mode = \fCstd::ios_base::out\fP)\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP"

.SS "template<class CharT , class CharTraits > \fBint_type\fP \fBjsoncons::basic_ovectorbuf\fP< CharT, CharTraits >::underflow ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
