.TH "jsoncons::member_lt_member< ValueT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsoncons::member_lt_member< ValueT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_structures\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBconst\fP ValueT &\fBa\fP, \fBconst\fP ValueT &\fBb\fP) \fBconst\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class ValueT > bool \fBjsoncons::member_lt_member\fP< ValueT >::operator() (\fBconst\fP ValueT & a, \fBconst\fP ValueT & b) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
