.TH "src/util/LIKWID.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/LIKWID.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLIKWID_MARKER_INIT\fP"
.br
.ti -1c
.RI "#define \fBLIKWID_MARKER_THREADINIT\fP"
.br
.ti -1c
.RI "#define \fBLIKWID_MARKER_SWITCH\fP"
.br
.ti -1c
.RI "#define \fBLIKWID_MARKER_REGISTER\fP(regionTag)"
.br
.ti -1c
.RI "#define \fBLIKWID_MARKER_START\fP(regionTag)"
.br
.ti -1c
.RI "#define \fBLIKWID_MARKER_STOP\fP(regionTag)"
.br
.ti -1c
.RI "#define \fBLIKWID_MARKER_CLOSE\fP"
.br
.ti -1c
.RI "#define \fBLIKWID_MARKER_GET\fP(regionTag,  nevents,  events,  time,  \fBcount\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LIKWID_MARKER_CLOSE"

.SS "#define LIKWID_MARKER_GET(regionTag, nevents, events, time, \fBcount\fP)"

.SS "#define LIKWID_MARKER_INIT"

.SS "#define LIKWID_MARKER_REGISTER(regionTag)"

.SS "#define LIKWID_MARKER_START(regionTag)"

.SS "#define LIKWID_MARKER_STOP(regionTag)"

.SS "#define LIKWID_MARKER_SWITCH"

.SS "#define LIKWID_MARKER_THREADINIT"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
