.TH "CMakeFiles/polylib.dir/link.txt" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeFiles/polylib.dir/link.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "usr bin \fBc\fP fPIC fPIC DPIC Xpreprocessor ftree vectorize funroll all \fBloops\fP \fBstd\fP =\fBc\fP++11 \-g \-O3 \-g \-O3 \-Wno\-deprecated \-Wno\-deprecated\-declarations \-Wno\-format\-overflow \-shared \-Wl"
.br
.ti -1c
.RI "usr bin \fBc\fP fPIC fPIC DPIC Xpreprocessor ftree vectorize funroll all \fBloops\fP \fBsoname\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "usr bin \fBc\fP fPIC fPIC DPIC Xpreprocessor ftree vectorize funroll all \fBloops\fP soname"

.SS "usr bin \fBc\fP fPIC fPIC DPIC Xpreprocessor ftree vectorize funroll all \fBloops\fP std =\fBc\fP++11 \-g \-O3 \-g \-O3 \-Wno\-deprecated \-Wno\-deprecated\-declarations \-Wno\-format\-overflow \-shared \-Wl"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
