.TH "Lists" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lists
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Lists\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > static vector< \fBT\fP > \fBinitListToVec\fP (\fBconst\fP initializer_list< \fBT\fP > list)"
.br
.ti -1c
.RI "template<typename K , typename V > static vector< K > \fBkeys\fP (\fBconst\fP \fBmap\fP< K, \fBV\fP > &inmap)"
.br
.ti -1c
.RI "template<typename K , typename V > static vector< K > \fBvalues\fP (\fBconst\fP \fBmap\fP< K, \fBV\fP > &inmap)"
.br
.ti -1c
.RI "template<typename T > static int \fBindex\fP (\fBconst\fP vector< \fBT\fP > &in, \fBT\fP item, int \fBstart\fP=0)"
.br
.ti -1c
.RI "template<typename T > static vector< \fBT\fP > \fBslice\fP (\fBconst\fP vector< \fBT\fP > &in, int \fBstart\fP, int stop=\-1)"
.br
.ti -1c
.RI "template<typename T > static bool \fBequal\fP (\fBconst\fP vector< \fBT\fP > &\fBlhs\fP, \fBconst\fP vector< \fBT\fP > &\fBrhs\fP, unsigned \fBsize\fP)"
.br
.ti -1c
.RI "template<typename T > static vector< \fBT\fP > \fBappend\fP (\fBconst\fP vector< \fBT\fP > &\fBlhs\fP, \fBconst\fP vector< \fBT\fP > &\fBrhs\fP)"
.br
.ti -1c
.RI "template<typename T > static vector< \fBT\fP > \fBmatch\fP (\fBconst\fP vector< \fBT\fP > &vec, \fBT\fP item)"
.br
.ti -1c
.RI "template<typename T > static bool \fBmatch\fP (\fBconst\fP vector< \fBT\fP > &\fBlhs\fP, \fBconst\fP vector< \fBT\fP > &\fBrhs\fP, unsigned \fBsize\fP=string::npos)"
.br
.ti -1c
.RI "template<typename T > static void \fBread\fP (vector< \fBT\fP > &elems, \fBconst\fP string &file, \fBconst\fP char delim=',')"
.br
.ti -1c
.RI "static void \fBwrite\fP (vector< int > &elems, \fBconst\fP string &file, \fBconst\fP char delim=',')"
.br
.ti -1c
.RI "static void \fBwrite\fP (vector< unsigned > &elems, \fBconst\fP string &file, \fBconst\fP char delim=',')"
.br
.ti -1c
.RI "static void \fBwrite\fP (vector< float > &elems, \fBconst\fP string &file, \fBconst\fP char delim=',')"
.br
.ti -1c
.RI "static void \fBwrite\fP (vector< double > &elems, \fBconst\fP string &file, \fBconst\fP char delim=',')"
.br
.ti -1c
.RI "template<typename T > static void \fBwrite\fP (\fBconst\fP vector< \fBT\fP > &elems, \fBconst\fP string &file='', \fBconst\fP char delim=',', \fBconst\fP string pattern='%s')"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static vector<\fBT\fP> Lists::append (\fBconst\fP vector< \fBT\fP > & lhs, \fBconst\fP vector< \fBT\fP > & rhs)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static bool Lists::equal (\fBconst\fP vector< \fBT\fP > & lhs, \fBconst\fP vector< \fBT\fP > & rhs, unsigned size)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static int Lists::index (\fBconst\fP vector< \fBT\fP > & in, \fBT\fP item, int start = \fC0\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static vector<\fBT\fP> Lists::initListToVec (\fBconst\fP initializer_list< \fBT\fP > list)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename K , typename V > static vector<K> Lists::keys (\fBconst\fP \fBmap\fP< K, \fBV\fP > & inmap)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static bool Lists::match (\fBconst\fP vector< \fBT\fP > & lhs, \fBconst\fP vector< \fBT\fP > & rhs, unsigned size = \fCstring::npos\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static vector<\fBT\fP> Lists::match (\fBconst\fP vector< \fBT\fP > & vec, \fBT\fP item)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static void Lists::read (vector< \fBT\fP > & elems, \fBconst\fP string & file, \fBconst\fP char delim = \fC','\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static vector<\fBT\fP> Lists::slice (\fBconst\fP vector< \fBT\fP > & in, int start, int stop = \fC\-1\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename K , typename V > static vector<K> Lists::values (\fBconst\fP \fBmap\fP< K, \fBV\fP > & inmap)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static void Lists::write (\fBconst\fP vector< \fBT\fP > & elems, \fBconst\fP string & file = \fC''\fP, \fBconst\fP char delim = \fC','\fP, \fBconst\fP string pattern = \fC'%s'\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static void Lists::write (vector< double > & elems, \fBconst\fP string & file, \fBconst\fP char delim = \fC','\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static void Lists::write (vector< float > & elems, \fBconst\fP string & file, \fBconst\fP char delim = \fC','\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static void Lists::write (vector< int > & elems, \fBconst\fP string & file, \fBconst\fP char delim = \fC','\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static void Lists::write (vector< unsigned > & elems, \fBconst\fP string & file, \fBconst\fP char delim = \fC','\fP)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
