.TH "llvm_test.Tokenizer" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm_test.Tokenizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, line)"
.br
.ti -1c
.RI "def \fB__next__\fP (self)"
.br
.ti -1c
.RI "def \fB__iter__\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def llvm_test\&.Tokenizer\&.__init__ ( self,  line)"

.SH "Member Function Documentation"
.PP 
.SS "def llvm_test\&.Tokenizer\&.__iter__ ( self)"

.SS "def llvm_test\&.Tokenizer\&.__next__ ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
