.TH "Logger" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Logger\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogger\fP (\fBconst\fP string &\fBfile\fP='')"
.br
.ti -1c
.RI "virtual \fB~Logger\fP ()"
.br
.ti -1c
.RI "string \fBfile\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBfile\fP (\fBconst\fP string &file)"
.br
.ti -1c
.RI "void \fBenable\fP ()"
.br
.ti -1c
.RI "void \fBdisable\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBtrace\fP (\fBconst\fP string &msg)"
.br
.ti -1c
.RI "void \fBdebug\fP (\fBconst\fP string &msg)"
.br
.ti -1c
.RI "void \fBinfo\fP (\fBconst\fP string &msg)"
.br
.ti -1c
.RI "void \fBwarn\fP (\fBconst\fP string &msg)"
.br
.ti -1c
.RI "void \fBerror\fP (\fBconst\fP string &msg)"
.br
.ti -1c
.RI "void \fBfatal\fP (\fBconst\fP string &msg)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Logger::Logger (\fBconst\fP string & file = \fC''\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "virtual Logger::~Logger ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Logger::clear ()\fC [inline]\fP"

.SS "void Logger::debug (\fBconst\fP string & msg)\fC [inline]\fP"

.SS "void Logger::disable ()\fC [inline]\fP"

.SS "void Logger::enable ()\fC [inline]\fP"

.SS "void Logger::error (\fBconst\fP string & msg)\fC [inline]\fP"

.SS "void Logger::fatal (\fBconst\fP string & msg)\fC [inline]\fP"

.SS "string Logger::file () const\fC [inline]\fP"

.SS "void Logger::file (\fBconst\fP string & file)\fC [inline]\fP"

.SS "void Logger::info (\fBconst\fP string & msg)\fC [inline]\fP"

.SS "void Logger::trace (\fBconst\fP string & msg)\fC [inline]\fP"

.SS "void Logger::warn (\fBconst\fP string & msg)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
