.TH "lib/chill/loop_cuda_chill.hh" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/loop_cuda_chill.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'chill_ast\&.hh'\fP
.br
\fC#include 'chill_io\&.hh'\fP
.br
\fC#include 'loop\&.hh'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <code_gen/CG_chillRepr\&.h>\fP
.br
\fC#include <code_gen/CG_chillBuilder\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCudaIOVardef\fP"
.br
.ti -1c
.RI "class \fBLoopCuda\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENUMMEMORYMODE\fP"
.br
.ti -1c
.RI "#define \fBCUDAVARDEFS\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMemoryMode\fP { \fBGlobalMem\fP, \fBSharedMem\fP, \fBTexMem\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBchillAST_VarDecl\fP * \fBaddBuiltin\fP (char *nameofbuiltin, char *typeOfBuiltin, \fBchillAST_node\fP *somecode)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CUDAVARDEFS"

.SS "#define ENUMMEMORYMODE"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMemoryMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGlobalMem \fP\fP
.TP
\fB\fISharedMem \fP\fP
.TP
\fB\fITexMem \fP\fP
.SH "Function Documentation"
.PP 
.SS "\fBchillAST_VarDecl\fP* addBuiltin (char * nameofbuiltin, char * typeOfBuiltin, \fBchillAST_node\fP * somecode)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
