.TH "lib/chill/loop_sparse.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/loop_sparse.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'loop\&.hh'\fP
.br
\fC#include <iegenlib\&.h>\fP
.br
\fC#include <code_gen/CG_utils\&.h>\fP
.br
\fC#include 'omegatools\&.hh'\fP
.br
\fC#include <sstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBomega::Relation\fP \fBflip_var_exclusive\fP (\fBomega::Relation\fP &\fBr1\fP, \fBVariable_ID\fP &v1)"
.br
.ti -1c
.RI "\fBomega::Relation\fP \fBflip_var\fP (\fBomega::Relation\fP &\fBr1\fP, \fBVariable_ID\fP &v1)"
.br
.ti -1c
.RI "\fBomega::Relation\fP \fBparseISLStringToOmegaRelation\fP (std::string s, \fBconst\fP \fBomega::Relation\fP &\fBr1\fP, \fBconst\fP \fBomega::Relation\fP &\fBr2\fP, \fBstd::map\fP< std::string, std::string > &unin, std::vector< \fBomega::Free_Var_Decl\fP * > &freevar, \fBIR_Code\fP *ir)"
.br
.ti -1c
.RI "bool \fBcheckIfEqual\fP (\fBomega::Relation\fP &r, \fBomega::Relation\fP s)"
.br
.ti -1c
.RI "\fBstd::map\fP< int, \fBomega::Relation\fP > \fBremoveRedundantConstraints\fP (\fBstd::map\fP< int, \fBomega::Relation\fP > &rels)"
.br
.ti -1c
.RI "std::string \fBget_lb_string\fP (\fBomega::Relation\fP &result, \fBVariable_ID\fP &v2, bool range=true)"
.br
.ti -1c
.RI "std::string \fBget_ub_string\fP (\fBomega::Relation\fP &result, \fBVariable_ID\fP &v2, bool range=true)"
.br
.ti -1c
.RI "std::pair< std::vector< std::string >, std::pair< std::vector< std::pair< bool, std::pair< std::string, std::string > > >, std::vector< std::pair< bool, std::pair< std::string, std::string > > > > > \fBdetermineUFsForIegen\fP (\fBomega::Relation\fP &result, \fBIR_Code\fP *ir, std::vector< \fBFree_Var_Decl\fP * > freevar)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool checkIfEqual (\fBomega::Relation\fP & r, \fBomega::Relation\fP s)"

.SS "std::pair<std::vector<std::string>, std::pair< std::vector<std::pair<bool, std::pair<std::string, std::string> > >, std::vector<std::pair<bool, std::pair<std::string, std::string> > > > > determineUFsForIegen (\fBomega::Relation\fP & result, \fBIR_Code\fP * ir, std::vector< \fBFree_Var_Decl\fP * > freevar)"

.SS "\fBomega::Relation\fP flip_var (\fBomega::Relation\fP & r1, \fBVariable_ID\fP & v1)"

.SS "\fBomega::Relation\fP flip_var_exclusive (\fBomega::Relation\fP & r1, \fBVariable_ID\fP & v1)"

.SS "std::string get_lb_string (\fBomega::Relation\fP & result, \fBVariable_ID\fP & v2, bool range = \fCtrue\fP)"

.SS "std::string get_ub_string (\fBomega::Relation\fP & result, \fBVariable_ID\fP & v2, bool range = \fCtrue\fP)"

.SS "\fBomega::Relation\fP parseISLStringToOmegaRelation (std::string s, \fBconst\fP \fBomega::Relation\fP & r1, \fBconst\fP \fBomega::Relation\fP & r2, \fBstd::map\fP< std::string, std::string > & unin, std::vector< \fBomega::Free_Var_Decl\fP * > & freevar, \fBIR_Code\fP * ir)"

.SS "\fBstd::map\fP<int, \fBomega::Relation\fP> removeRedundantConstraints (\fBstd::map\fP< int, \fBomega::Relation\fP > & rels)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
