.TH "lib/chill/loop_ghostcells.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/loop_ghostcells.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'loop\&.hh'\fP
.br
\fC#include 'chill_error\&.hh'\fP
.br
\fC#include <omega\&.h>\fP
.br
\fC#include 'omegatools\&.hh'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <code_gen/CG_outputRepr\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBis_in\fP (int \fBn\fP, std::vector< int > v_)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool is_in (int n, std::vector< int > v_)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
