.TH "lib/isl/include/isl/lp.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/lp.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/aff\&.h>\fP
.br
\fC#include <isl/val\&.h>\fP
.br
\fC#include <isl/set_type\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBisl_lp_result\fP { \fBisl_lp_error\fP = -1, \fBisl_lp_ok\fP = 0, \fBisl_lp_unbounded\fP, \fBisl_lp_empty\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_basic_set_min_lp_val\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_basic_set_max_lp_val\fP (\fB__isl_keep\fP \fBisl_basic_set\fP *bset, \fB__isl_keep\fP \fBisl_aff\fP *obj)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBisl_lp_result\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIisl_lp_error \fP\fP
.TP
\fB\fIisl_lp_ok \fP\fP
.TP
\fB\fIisl_lp_unbounded \fP\fP
.TP
\fB\fIisl_lp_empty \fP\fP
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_val\fP* isl_basic_set_max_lp_val (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_basic_set_min_lp_val (\fB__isl_keep\fP \fBisl_basic_set\fP * bset, \fB__isl_keep\fP \fBisl_aff\fP * obj)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
