.TH "lib/isl/include/isl/map_to_basic_set.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/map_to_basic_set.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/set_type\&.h>\fP
.br
\fC#include <isl/map_type\&.h>\fP
.br
\fC#include <isl/hmap\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBISL_KEY_BASE\fP   \fBmap\fP"
.br
.ti -1c
.RI "#define \fBISL_VAL_BASE\fP   basic_set"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ISL_KEY_BASE   \fBmap\fP"

.SS "#define ISL_VAL_BASE   basic_set"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
