.TH "lib/isl/include/isl/deprecated/mat_int.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/deprecated/mat_int.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/deprecated/int\&.h>\fP
.br
\fC#include <isl/mat\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_mat_get_element\fP (\fB__isl_keep\fP \fBisl_mat\fP *mat, int \fBrow\fP, int \fBcol\fP, \fBisl_int\fP *v)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_mat\fP * \fBisl_mat_set_element\fP (\fB__isl_take\fP \fBisl_mat\fP *mat, int \fBrow\fP, int \fBcol\fP, \fBisl_int\fP v)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isl_mat_get_element (\fB__isl_keep\fP \fBisl_mat\fP * mat, int row, int col, \fBisl_int\fP * v)"

.SS "\fB__isl_give\fP \fBisl_mat\fP* isl_mat_set_element (\fB__isl_take\fP \fBisl_mat\fP * mat, int row, int col, \fBisl_int\fP v)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
