.TH "artifact/src/chill/matrix_io.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
artifact/src/chill/matrix_io.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'matrix_io\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBload_sparse_matrix\fP (char *filename, struct \fBsparse_matrix\fP *\fBA\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void load_sparse_matrix (char * filename, struct \fBsparse_matrix\fP * A)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
