.TH "max_constraint" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
max_constraint
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_mat\fP * \fBc\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBineq\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_mat\fP* max_constraint::c"

.SS "int max_constraint::count"

.SS "int max_constraint::ineq"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
