.TH "lib/gmp/memory.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/memory.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'gmp\&.h'\fP
.br
\fC#include 'gmp\-impl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fB__gmp_default_allocate\fP (size_t \fBsize\fP)"
.br
.ti -1c
.RI "void * \fB__gmp_default_reallocate\fP (void *oldptr, size_t old_size, size_t new_size)"
.br
.ti -1c
.RI "void \fB__gmp_default_free\fP (void *blk_ptr, size_t blk_size)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void *(* \fB__gmp_allocate_func\fP )(size_t) = \fB__gmp_default_allocate\fP"
.br
.ti -1c
.RI "void *(* \fB__gmp_reallocate_func\fP )(void *, size_t, size_t) = \fB__gmp_default_reallocate\fP"
.br
.ti -1c
.RI "void(* \fB__gmp_free_func\fP )(void *, size_t) = \fB__gmp_default_free\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* __gmp_default_allocate (size_t size)"

.SS "void __gmp_default_free (void * blk_ptr, size_t blk_size)"

.SS "void* __gmp_default_reallocate (void * oldptr, size_t old_size, size_t new_size)"

.SH "Variable Documentation"
.PP 
.SS "void*(* __gmp_allocate_func) (size_t) = \fB__gmp_default_allocate\fP"

.SS "void(* __gmp_free_func) (void *, size_t) = \fB__gmp_default_free\fP"

.SS "void*(* __gmp_reallocate_func) (void *, size_t, size_t) = \fB__gmp_default_reallocate\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
