.TH "mfd-graph-dot" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mfd-graph-dot
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBinit_digraph\fP ()"
.br
.ti -1c
.RI "def \fBstatement\fP (label, node_name='')"
.br
.ti -1c
.RI "def \fBdata\fP (label, node_name='')"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdot\fP = None"
.br
.ti -1c
.RI "string \fBOUTPUT\fP = 'm2dfg'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def mfd\-graph\-dot\&.data ( label,  node_name = \fC''\fP)"

.SS "def mfd\-graph\-dot\&.init_digraph ()"

.SS "def mfd\-graph\-dot\&.main ()"

.SS "def mfd\-graph\-dot\&.statement ( label,  node_name = \fC''\fP)"

.SH "Variable Documentation"
.PP 
.SS "mfd\-graph\-dot\&.dot = None"

.SS "string mfd\-graph\-dot\&.OUTPUT = 'm2dfg'"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
