.TH "scripts/mfd-graph-dot.py" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/mfd-graph-dot.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmfd\-graph\-dot\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmfd\-graph\-dot\&.init_digraph\fP ()"
.br
.ti -1c
.RI "def \fBmfd\-graph\-dot\&.statement\fP (label, node_name='')"
.br
.ti -1c
.RI "def \fBmfd\-graph\-dot\&.data\fP (label, node_name='')"
.br
.ti -1c
.RI "def \fBmfd\-graph\-dot\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmfd\-graph\-dot\&.dot\fP = None"
.br
.ti -1c
.RI "string \fBmfd\-graph\-dot\&.OUTPUT\fP = 'm2dfg'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
