.TH "mk" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mk
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBa_list\fP * \fBptr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBa_list\fP* mk::ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
