.TH "lib/gmp/mp_clz_tab.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/mp_clz_tab.c
.SH SYNOPSIS
.br
.PP
\fC#include 'gmp\&.h'\fP
.br
\fC#include 'gmp\-impl\&.h'\fP
.br
\fC#include 'longlong\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP unsigned char \fB__clz_tab\fP [129]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBconst\fP unsigned char __clz_tab[129]"
\fBInitial value:\fP
.PP
.nf
=
{
  1,2,3,3,4,4,4,4,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
  7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
  8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
  8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
  9
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
