.TH "lib/gmp/mp_dv_tab.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/mp_dv_tab.c
.SH SYNOPSIS
.br
.PP
\fC#include 'gmp\&.h'\fP
.br
\fC#include 'gmp\-impl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBX\fP   0xff"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP unsigned char \fB__gmp_digit_value_tab\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define X   0xff"

.SH "Variable Documentation"
.PP 
.SS "\fBconst\fP unsigned char __gmp_digit_value_tab[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
