.TH "mpq" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpq
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imrat\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmpz_t\fP \fBnum\fP"
.br
.ti -1c
.RI "\fBmpz_t\fP \fBden\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmpz_t\fP mpq::den"

.SS "\fBmpz_t\fP mpq::num"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
