.TH "mtx2csr" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtx2csr
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmtx2csr\fP (mtxfile)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def mtx2csr\&.main ()"

.SS "def mtx2csr\&.mtx2csr ( mtxfile)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
