.TH "artifact/py/mtx2csr.py" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
artifact/py/mtx2csr.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtx2csr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmtx2csr\&.mtx2csr\fP (mtxfile)"
.br
.ti -1c
.RI "def \fBmtx2csr\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
