.TH "must_may" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
must_may
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBisl_map\fP * \fBmust\fP"
.br
.ti -1c
.RI "\fBisl_map\fP * \fBmay\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_map\fP* must_may::may"

.SS "\fBisl_map\fP* must_may::must"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
