.TH "lib/gmp/nextprime.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/nextprime.c
.SH SYNOPSIS
.br
.PP
\fC#include 'gmp\&.h'\fP
.br
\fC#include 'gmp\-impl\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned long int \fBgmp_nextprime\fP (\fBgmp_primesieve_t\fP *ps)"
.br
.ti -1c
.RI "void \fBgmp_init_primesieve\fP (\fBgmp_primesieve_t\fP *ps)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gmp_init_primesieve (\fBgmp_primesieve_t\fP * ps)"

.SS "unsigned long int gmp_nextprime (\fBgmp_primesieve_t\fP * ps)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
