.TH "lib/iegenlib/src/set_relation/normalization_test.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/set_relation/normalization_test.cc \- Normalization tests on Sets and Relations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'set_relation\&.h'\fP
.br
\fC#include 'expression\&.h'\fP
.br
\fC#include <util/util\&.h>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <isl/set\&.h>\fP
.br
\fC#include <isl/map\&.h>\fP
.br
\fC#include <util/UnionFindUniverse\&.h>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNormalizationTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, SimpleEqualities)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, SimpleEqOutOfOrder)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, SimpleEqOutOfOrderRelation)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, EqUFParamRelation)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, EqUFParamRelation2)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, EqUFSignatureRelation)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, NestedUFCalls1D1D1D)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, NestedUFCalls1D2D1D)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, NestedUFCallsEqUFCalls)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, EqUFSignatureEqParams)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, AffineExpWithUFCall)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, EqAffineExpParamForUFCalls)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, boundTupleExpRange)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, boundTupleExpDomain)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBNormalizationTest\fP, buildingNormalize)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Normalization tests on Sets and Relations\&. 

This file is to begin to test the Set and Relation classes, along with the related Conjunction class, for normal form to facilitate equality testing\&.
.PP
\fBDate\fP
.RS 4
Started: 6/24/13
.RE
.PP
\fBAuthors\fP
.RS 4
Barbara Kreaseck and Michelle Strout
.RE
.PP
Copyright (c) 2016, University of Arizona 
.br
 Copyright (c) 2012, Colorado State University 
.br
 All rights reserved\&. 
.br
 See \&.\&./\&.\&./COPYING for details\&. 
.br
 
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBNormalizationTest\fP, AffineExpWithUFCall)"

.SS "TEST_F (\fBNormalizationTest\fP, boundTupleExpDomain)"

.SS "TEST_F (\fBNormalizationTest\fP, boundTupleExpRange)"

.SS "TEST_F (\fBNormalizationTest\fP, buildingNormalize)"

.SS "TEST_F (\fBNormalizationTest\fP, EqAffineExpParamForUFCalls)"

.SS "TEST_F (\fBNormalizationTest\fP, EqUFParamRelation)"

.SS "TEST_F (\fBNormalizationTest\fP, EqUFParamRelation2)"

.SS "TEST_F (\fBNormalizationTest\fP, EqUFSignatureEqParams)"

.SS "TEST_F (\fBNormalizationTest\fP, EqUFSignatureRelation)"

.SS "TEST_F (\fBNormalizationTest\fP, NestedUFCalls1D1D1D)"

.SS "TEST_F (\fBNormalizationTest\fP, NestedUFCalls1D2D1D)"

.SS "TEST_F (\fBNormalizationTest\fP, NestedUFCallsEqUFCalls)"

.SS "TEST_F (\fBNormalizationTest\fP, SimpleEqOutOfOrder)"

.SS "TEST_F (\fBNormalizationTest\fP, SimpleEqOutOfOrderRelation)"

.SS "TEST_F (\fBNormalizationTest\fP, SimpleEqualities)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
