.TH "doc/notes.txt" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doc/notes.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBI_N\fP ()"
.br
.ti -1c
.RI "symbolic \fBrow\fP (1)"
.br
.ti -1c
.RI "symbolic \fBrp\fP (2)"
.br
.ti -1c
.RI "\fBcodegen\fP (\fBI_rp\fP) given"
.br
.ti -1c
.RI "\fBI_rp\fP (\fBn\fP, \fBi\fP)"
.br
.ti -1c
.RI "\fBrp1\fP (2)"
.br
.ti -1c
.RI "\fBcodegen\fP (I_rp2) given"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "symbolic \fBNNZ\fP"
.br
.ti -1c
.RI "\fBI_rp\fP \fB__pad32__\fP"
.br
.ti -1c
.RI "\fBI_rp\fP \fBi\fP =0&&\fBNNZ\fP\-1>=0&&\-\fBn\fP+\fBNNZ\fP\-1>=0}"
.br
.ti -1c
.RI "I_rp2 \fB__pad33__\fP"
.br
.ti -1c
.RI "I_rp2 \fBm\fP"
.br
.ti -1c
.RI "symbolic \fBn\fP"
.br
.ti -1c
.RI "i10 \fB__pad34__\fP"
.br
.ti -1c
.RI "i20 \fB__pad35__\fP"
.br
.ti -1c
.RI "i20 \fBj\fP"
.br
.ti -1c
.RI "i30 \fB__pad36__\fP"
.br
.ti -1c
.RI "\fBs10\fP \fB__pad37__\fP"
.br
.ti -1c
.RI "\fBs10\fP \fBs20\fP"
.br
.ti -1c
.RI "\fBs30\fP \fB__pad38__\fP"
.br
.ti -1c
.RI "\fBs30\fP \fBcodegen\fP \fBs10\fP"
.br
.ti -1c
.RI "s30 \fBcodegen\fP \fBs30\fP"
.br
.ti -1c
.RI "Irp \fB__pad39__\fP"
.br
.ti -1c
.RI "Irp2 \fB__pad40__\fP"
.br
.ti -1c
.RI "\fBSrp\fP \fB__pad41__\fP"
.br
.ti -1c
.RI "\fBSrp2\fP \fB__pad42__\fP"
.br
.ti -1c
.RI "\fBcodegen\fP \fBSrp\fP"
.br
.ti -1c
.RI "\fBcodegen\fP \fBSrp2\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "codegen (\fBI_rp\fP)"

.SS "codegen (I_rp2)"

.SS "I_N ()"

.SS "I_rp (\fBn\fP, \fBi\fP)"

.SS "symbolic row (1)"

.SS "symbolic rp (2)"

.SS "symbolic rp1 (2)"

.SH "Variable Documentation"
.PP 
.SS "\fBI_rp\fP __pad32__"

.SS "I_rp2 __pad33__"

.SS "i10 __pad34__"

.SS "i20 __pad35__"

.SS "i30 __pad36__"

.SS "\fBs10\fP __pad37__"

.SS "\fBs30\fP __pad38__"

.SS "Irp __pad39__"

.SS "Irp2 __pad40__"

.SS "\fBSrp\fP __pad41__"

.SS "\fBSrp2\fP __pad42__"

.SS "\fBcodegen\fP i =0&&\fBNNZ\fP\-1>=0&&\-\fBn\fP+\fBNNZ\fP\-1>=0}"

.SS "\fBs10\fP j[1, j, 0, \fBi\fP]"

.SS "\fBcodegen\fP m"

.SS "symbolic n"

.SS "symbolic NNZ"

.SS "\fBs30\fP \fBcodegen\fP s10"

.SS "\fBs30\fP \fBcodegen\fP s20"

.SS "s30 \fBcodegen\fP s30"

.SS "\fBcodegen\fP Srp"

.SS "\fBcodegen\fP Srp2"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
