.TH "lib/chill/omega/omega_lib/src/omega_core/oc_global.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/src/omega_core/oc_global.cc
.SH SYNOPSIS
.br
.PP
\fC#include <omega/omega_core/oc_i\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
