.TH "omega::Collection< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Collection< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Collection\&.h>\fP
.PP
Inherited by \fBomega::Bag< T >\fP, and \fBomega::Sequence< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBIterator\fP< \fBT\fP > * \fBnew_iterator\fP ()=0"
.br
.ti -1c
.RI "virtual \fBAny_Iterator\fP< \fBT\fP > \fBany_iterator\fP ()"
.br
.ti -1c
.RI "virtual int \fBsize\fP () \fBconst\fP =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class T > virtual \fBAny_Iterator\fP<\fBT\fP> \fBomega::Collection\fP< \fBT\fP >::any_iterator ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class T > virtual \fBIterator\fP<\fBT\fP>* \fBomega::Collection\fP< \fBT\fP >::new_iterator ()\fC [pure virtual]\fP"

.PP
Implemented in \fBomega::Tuple< T >\fP, \fBomega::Tuple< omega::Const_String >\fP, \fBomega::Tuple< std::string >\fP, \fBomega::Tuple< Variable_ID >\fP, \fBomega::Tuple< omega::Tuple< omega::Relation > >\fP, \fBomega::Tuple< int >\fP, \fBomega::Tuple< omega::Relation >\fP, \fBomega::List< T >\fP, \fBomega::List< omega::Formula * >\fP, \fBomega::List< omega::Conjunct * >\fP, \fBomega::Simple_List< T >\fP, \fBomega::Bag< T >\fP, and \fBomega::Section< T >\fP\&.
.SS "template<class T > virtual int \fBomega::Collection\fP< \fBT\fP >::size () const\fC [pure virtual]\fP"

.PP
Implemented in \fBomega::List< T >\fP, \fBomega::List< omega::Formula * >\fP, \fBomega::List< omega::Conjunct * >\fP, \fBomega::Simple_List< T >\fP, \fBomega::Bag< T >\fP, \fBomega::Tuple< T >\fP, \fBomega::Tuple< omega::Const_String >\fP, \fBomega::Tuple< std::string >\fP, \fBomega::Tuple< Variable_ID >\fP, \fBomega::Tuple< omega::Tuple< omega::Relation > >\fP, \fBomega::Tuple< int >\fP, \fBomega::Tuple< omega::Relation >\fP, and \fBomega::Section< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
