.TH "omega::Polyhedra" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Polyhedra
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <code_gen\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolyhedra\fP (\fBconst\fP \fBTuple\fP< \fBRelation\fP > &\fBT\fP, \fBconst\fP \fBTuple\fP< \fBRelation\fP > &old_IS, \fBconst\fP \fBRelation\fP &\fBknown\fP=\fBRelation::Null\fP())"
.br
.ti -1c
.RI "\fB~Polyhedra\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlast_level\fP"
.br
.ti -1c
.RI "\fBTuple\fP< \fBRelation\fP > \fBtransformations\fP"
.br
.ti -1c
.RI "\fBRelation\fP \fBknown\fP"
.br
.ti -1c
.RI "\fBTuple\fP< int > \fBremap\fP"
.br
.ti -1c
.RI "\fBTuple\fP< \fBTuple\fP< \fBRelation\fP > > \fBprojected_nIS\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::Polyhedra::Polyhedra (\fBconst\fP \fBTuple\fP< \fBRelation\fP > & T, \fBconst\fP \fBTuple\fP< \fBRelation\fP > & old_IS, \fBconst\fP \fBRelation\fP & known = \fC\fBRelation::Null\fP()\fP)"

.SS "omega::Polyhedra::~Polyhedra ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBRelation\fP omega::Polyhedra::known"

.SS "int omega::Polyhedra::last_level"

.SS "\fBTuple\fP<\fBTuple\fP<\fBRelation\fP> > omega::Polyhedra::projected_nIS"

.SS "\fBTuple\fP<int> omega::Polyhedra::remap"

.SS "\fBTuple\fP<\fBRelation\fP> omega::Polyhedra::transformations"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
