.TH "omega::Comp_Constraints" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Comp_Constraints
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_cmpr\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComp_Constraints\fP (\fBeqn\fP *constrs, int no_constrs, int no_vars)"
.br
.ti -1c
.RI "void \fBUncompressConstr\fP (\fBeqn\fP *constrs, short &pn_constrs)"
.br
.ti -1c
.RI "\fB~Comp_Constraints\fP ()"
.br
.ti -1c
.RI "bool \fBno_constraints\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBn_constraints\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "int \fBcoef_index\fP (int \fBe\fP, int v)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::Comp_Constraints::Comp_Constraints (\fBeqn\fP * constrs, int no_constrs, int no_vars)"

.SS "omega::Comp_Constraints::~Comp_Constraints ()"

.SH "Member Function Documentation"
.PP 
.SS "int omega::Comp_Constraints::coef_index (int e, int v)\fC [inline]\fP, \fC [protected]\fP"

.SS "int omega::Comp_Constraints::n_constraints () const\fC [inline]\fP"

.SS "bool omega::Comp_Constraints::no_constraints () const\fC [inline]\fP"

.SS "void omega::Comp_Constraints::UncompressConstr (\fBeqn\fP * constrs, short & pn_constrs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
