.TH "omega::Dynamic_Array< T, d >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Dynamic_Array< T, d >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dynamic_Array\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDynamic_Array\fP (\fBDynamic_Array\fP< \fBT\fP, d > &\fBD\fP)"
.br
.ti -1c
.RI "\fB~Dynamic_Array\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDynamic_Array\fP ()"
.br
.ti -1c
.RI "void \fBdo_constr\fP ()"
.br
.ti -1c
.RI "void \fBdo_destruct\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBpartial\fP"
.br
.ti -1c
.RI "int * \fBbounds\fP"
.br
.ti -1c
.RI "\fBT\fP * \fBelements\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T , int d> \fBomega::Dynamic_Array\fP< \fBT\fP, d >::\fBDynamic_Array\fP (\fBDynamic_Array\fP< \fBT\fP, d > & D)"

.SS "template<class T , int d> \fBomega::Dynamic_Array\fP< \fBT\fP, d >::~\fBDynamic_Array\fP"

.SS "template<class T , int d> \fBomega::Dynamic_Array\fP< \fBT\fP, d >::\fBDynamic_Array\fP\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T , int d> void \fBomega::Dynamic_Array\fP< \fBT\fP, d >::do_constr\fC [protected]\fP"

.SS "template<class T , int d> void \fBomega::Dynamic_Array\fP< \fBT\fP, d >::do_destruct\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<class T , int d> int* \fBomega::Dynamic_Array\fP< \fBT\fP, d >::bounds\fC [protected]\fP"

.SS "template<class T , int d> \fBT\fP* \fBomega::Dynamic_Array\fP< \fBT\fP, d >::elements\fC [protected]\fP"

.SS "template<class T , int d> bool \fBomega::Dynamic_Array\fP< \fBT\fP, d >::partial\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
