.TH "omega::EQ_Iterator" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::EQ_Iterator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_cnstr\&.h>\fP
.PP
Inherits \fBomega::Generator< EQ_Handle >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEQ_Iterator\fP (\fBConjunct\fP *)"
.br
.RI "Get the EQs in a conjunct\&. "
.ti -1c
.RI "int \fBlive\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBoperator++\fP (int)"
.br
.ti -1c
.RI "void \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBEQ_Handle\fP \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fBEQ_Handle\fP \fBoperator*\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::EQ_Iterator::EQ_Iterator (\fBConjunct\fP * _c)"

.PP
Get the EQs in a conjunct\&. 
.SH "Member Function Documentation"
.PP 
.SS "int omega::EQ_Iterator::live () const"

.SS "\fBEQ_Handle\fP omega::EQ_Iterator::operator* ()\fC [virtual]\fP"

.PP
Implements \fBomega::Generator< EQ_Handle >\fP\&.
.SS "\fBEQ_Handle\fP omega::EQ_Iterator::operator* () const"

.SS "void omega::EQ_Iterator::operator++ ()\fC [virtual]\fP"

.PP
Implements \fBomega::Generator< EQ_Handle >\fP\&.
.SS "void omega::EQ_Iterator::operator++ (int)\fC [virtual]\fP"

.PP
Implements \fBomega::Generator< EQ_Handle >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
