.TH "omega::MMPrefetchInsertion" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::MMPrefetchInsertion
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rose_attributes\&.h>\fP
.PP
Inherits \fBomega::CodeInsertion\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMMPrefetchInsertion\fP (int \fBloop_level\fP, \fBconst\fP std::string &arr, int hint)"
.br
.ti -1c
.RI "\fB~MMPrefetchInsertion\fP ()"
.br
.ti -1c
.RI "virtual SgStatement * \fBgetStatement\fP (SgScopeStatement *scopeStmt=\fBNULL\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::MMPrefetchInsertion::MMPrefetchInsertion (int loop_level, \fBconst\fP std::string & arr, int hint)\fC [inline]\fP"

.SS "omega::MMPrefetchInsertion::~MMPrefetchInsertion ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual SgStatement* omega::MMPrefetchInsertion::getStatement (SgScopeStatement * scopeStmt = \fC\fBNULL\fP\fP)\fC [virtual]\fP"

.PP
Implements \fBomega::CodeInsertion\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
