.TH "src/omega/OmegaLib.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/omega/OmegaLib.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <locale>\fP
.br
\fC#include <map>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <util/Lists\&.hpp>\fP
.br
\fC#include <util/Strings\&.hpp>\fP
.br
\fC#include <util/OS\&.hpp>\fP
.br
\fC#include <basic/Dynamic_Array\&.h>\fP
.br
\fC#include <basic/Iterator\&.h>\fP
.br
\fC#include <omega/parser/AST\&.hh>\fP
.br
\fC#include <omega/hull\&.h>\fP
.br
\fC#include <omega/closure\&.h>\fP
.br
\fC#include <omega/reach\&.h>\fP
.br
\fC#include <codegen\&.h>\fP
.br
\fC#include <omega/parser/parser\&.tab\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBomglib::UninterpFunc\fP"
.br
.ti -1c
.RI "struct \fBomglib::OmegaLib\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomglib\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBASN_OP\fP   ':='"
.br
.ti -1c
.RI "#define \fBPROMPT\fP   '>>>'"
.br
.ti -1c
.RI "#define \fBIN\fP(cont,  item)   (find((cont)\&.begin(),(cont)\&.end(),(item))!=(cont)\&.end())"
.br
.ti -1c
.RI "#define \fBLEN\fP(cont)   ((unsigned)(cont)\&.\fBsize\fP())"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBomega_run\fP (std::istream *is, std::ostream *os)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASN_OP   ':='"

.SS "#define IN(cont, item)   (find((cont)\&.begin(),(cont)\&.end(),(item))!=(cont)\&.end())"

.SS "#define LEN(cont)   ((unsigned)(cont)\&.\fBsize\fP())"

.SS "#define PROMPT   '>>>'"

.SH "Function Documentation"
.PP 
.SS "int omega_run (std::istream * is, std::ostream * os)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
