.TH "omega::SubstituteOldVar" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::SubstituteOldVar
.SH SYNOPSIS
.br
.PP
.PP
Inherits Scanner< const char *, chillAST_node *, CG_chillRepr *, chillAST_node *& >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SubstituteOldVar\fP ()=default"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBerrorRun\fP (\fBchillAST_node\fP *n, \fBconst\fP char *oldvar, \fBchillAST_node\fP *parent, \fBCG_chillRepr\fP *newvar, \fBchillAST_node\fP *&newnode)"
.br
.ti -1c
.RI "virtual void \fBrunS\fP (\fBchillAST_DeclRefExpr\fP *n, \fBconst\fP char *oldvar, \fBchillAST_node\fP *parent, \fBCG_chillRepr\fP *newvar, \fBchillAST_node\fP *&newnode)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual omega::SubstituteOldVar::~SubstituteOldVar ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void omega::SubstituteOldVar::errorRun (\fBchillAST_node\fP * n, \fBconst\fP char * oldvar, \fBchillAST_node\fP * parent, \fBCG_chillRepr\fP * newvar, \fBchillAST_node\fP *& newnode)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.SS "virtual void omega::SubstituteOldVar::runS (\fBchillAST_DeclRefExpr\fP * n, \fBconst\fP char * oldvar, \fBchillAST_node\fP * parent, \fBCG_chillRepr\fP * newvar, \fBchillAST_node\fP *& newnode)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
