.TH "omega::Const_String" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Const_String
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConstString\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConst_String\fP ()"
.br
.ti -1c
.RI "\fBConst_String\fP (\fBconst\fP char *t)"
.br
.ti -1c
.RI "\fBConst_String\fP (\fBconst\fP std::string &s)"
.br
.ti -1c
.RI "\fBConst_String\fP (\fBconst\fP \fBConst_String\fP &t)"
.br
.ti -1c
.RI "\fBoperator int\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBnull\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator const char *\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator std::string\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBoperator++\fP (int)"
.br
.ti -1c
.RI "int \fBoperator++\fP ()"
.br
.ti -1c
.RI "int \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "int \fBoperator\-\-\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "int \fBoperator==\fP (\fBconst\fP \fBConst_String\fP &\fBx\fP, \fBconst\fP \fBConst_String\fP &\fBy\fP)"
.br
.ti -1c
.RI "int \fBoperator!=\fP (\fBconst\fP \fBConst_String\fP &\fBx\fP, \fBconst\fP \fBConst_String\fP &\fBy\fP)"
.br
.ti -1c
.RI "int \fBoperator<\fP (\fBconst\fP \fBConst_String\fP &\fBx\fP, \fBconst\fP \fBConst_String\fP &\fBy\fP)"
.br
.ti -1c
.RI "int \fBoperator>\fP (\fBconst\fP \fBConst_String\fP &\fBx\fP, \fBconst\fP \fBConst_String\fP &\fBy\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::Const_String::Const_String ()"

.SS "omega::Const_String::Const_String (\fBconst\fP char * t)"

.SS "omega::Const_String::Const_String (\fBconst\fP std::string & s)"

.SS "omega::Const_String::Const_String (\fBconst\fP \fBConst_String\fP & t)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int omega::Const_String::null () const"

.SS "omega::Const_String::operator \fBconst\fP char * () const"

.SS "omega::Const_String::operator int () const"

.SS "omega::Const_String::operator std::string () const"

.SS "int omega::Const_String::operator++ ()"

.SS "int omega::Const_String::operator++ (int)"

.SS "int omega::Const_String::operator\-\- ()"

.SS "int omega::Const_String::operator\-\- (int)"

.SH "Friends And Related Function Documentation"
.PP 
.SS "int operator!= (\fBconst\fP \fBConst_String\fP & x, \fBconst\fP \fBConst_String\fP & y)\fC [friend]\fP"

.SS "int operator< (\fBconst\fP \fBConst_String\fP & x, \fBconst\fP \fBConst_String\fP & y)\fC [friend]\fP"

.SS "int operator== (\fBconst\fP \fBConst_String\fP & x, \fBconst\fP \fBConst_String\fP & y)\fC [friend]\fP"

.SS "int operator> (\fBconst\fP \fBConst_String\fP & x, \fBconst\fP \fBConst_String\fP & y)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
