.TH "omega::EQ_Handle" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::EQ_Handle \- Handle to access EQ constraints\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_cnstr\&.h>\fP
.PP
Inherits \fBomega::Constraint_Handle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEQ_Handle\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBprint_to_string\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual std::string \fBprint_term_to_string\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBConstraint_Handle\fP &that)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBConjunct\fP"
.br
.ti -1c
.RI "class \fBEQ_Iterator\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Handle to access EQ constraints\&. 

Represent constraints in the form \[\sum_i a_ix_i + a_0 = 0\]
.PP
Note that a stride constraint( $(\sum a_ix_i+a_0) \% s = 0$) is the same as \[\exists k, \sum_i a_ix_i + a_0 = ks\] 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::EQ_Handle::EQ_Handle ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool omega::EQ_Handle::operator== (\fBconst\fP \fBConstraint_Handle\fP & that)"

.SS "std::string omega::EQ_Handle::print_term_to_string () const\fC [virtual]\fP"

.PP
Reimplemented from \fBomega::Constraint_Handle\fP\&.
.SS "std::string omega::EQ_Handle::print_to_string () const\fC [virtual]\fP"

.PP
Reimplemented from \fBomega::Constraint_Handle\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBConjunct\fP\fC [friend]\fP"

.SS "friend class \fBEQ_Iterator\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
