.TH "omega::Global_Var_Decl" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Global_Var_Decl \- Abstract data type for Global Variable declarations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_var\&.h>\fP
.PP
Inherited by \fBomega::Coef_Var_Decl\fP, and \fBomega::Free_Var_Decl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlobal_Var_Decl\fP (\fBConst_String\fP baseName)"
.br
.ti -1c
.RI "virtual \fBConst_String\fP \fBbase_name\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual void \fBset_base_name\fP (\fBConst_String\fP newName)"
.br
.ti -1c
.RI "virtual int \fBarity\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual Omega_Var * \fBreally_omega_var\fP ()"
.br
.ti -1c
.RI "virtual \fBCoef_Var_Decl\fP * \fBreally_coef_var\fP ()"
.br
.ti -1c
.RI "virtual \fBGlobal_Kind\fP \fBkind\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBinstance\fP"
.br
.RI "Wild card instance number\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBRel_Body\fP"
.br
.ti -1c
.RI "class \fBVar_Decl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract data type for Global Variable declarations\&. 

Supports the following operations:
.IP "\(bu" 2
create global variable,
.IP "\(bu" 2
find the arity of the variable, (default = 0, for symbolic consts)
.IP "\(bu" 2
get the name of global variable,
.IP "\(bu" 2
tell if two variables are the same (if they are the same object) 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::Global_Var_Decl::Global_Var_Decl (\fBConst_String\fP baseName)"

.SH "Member Function Documentation"
.PP 
.SS "virtual int omega::Global_Var_Decl::arity () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBomega::Free_Var_Decl\fP\&.
.SS "virtual \fBConst_String\fP omega::Global_Var_Decl::base_name () const\fC [inline]\fP, \fC [virtual]\fP"

.SS "\fBGlobal_Kind\fP omega::Global_Var_Decl::kind () const\fC [virtual]\fP"

.PP
Reimplemented in \fBomega::Free_Var_Decl\fP, and \fBomega::Coef_Var_Decl\fP\&.
.SS "\fBCoef_Var_Decl\fP * omega::Global_Var_Decl::really_coef_var ()\fC [virtual]\fP"

.PP
Reimplemented in \fBomega::Coef_Var_Decl\fP\&.
.SS "Omega_Var * omega::Global_Var_Decl::really_omega_var ()\fC [virtual]\fP"

.SS "virtual void omega::Global_Var_Decl::set_base_name (\fBConst_String\fP newName)\fC [inline]\fP, \fC [virtual]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBRel_Body\fP\fC [friend]\fP"

.SS "friend class \fBVar_Decl\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int omega::Global_Var_Decl::instance"

.PP
Wild card instance number\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
