.TH "omega::Sub_Iterator" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Sub_Iterator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_subs\&.h>\fP
.PP
Inherits \fBomega::Generator< Sub_Handle >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSub_Iterator\fP (\fBSubstitutions\fP *input_s)"
.br
.ti -1c
.RI "int \fBlive\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBoperator++\fP (int)"
.br
.ti -1c
.RI "void \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBSub_Handle\fP \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fBSub_Handle\fP \fBoperator*\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::Sub_Iterator::Sub_Iterator (\fBSubstitutions\fP * input_s)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int omega::Sub_Iterator::live () const"

.SS "\fBSub_Handle\fP omega::Sub_Iterator::operator* ()\fC [virtual]\fP"

.PP
Implements \fBomega::Generator< Sub_Handle >\fP\&.
.SS "\fBSub_Handle\fP omega::Sub_Iterator::operator* () const"

.SS "void omega::Sub_Iterator::operator++ ()\fC [virtual]\fP"

.PP
Implements \fBomega::Generator< Sub_Handle >\fP\&.
.SS "void omega::Sub_Iterator::operator++ (int)\fC [virtual]\fP"

.PP
Implements \fBomega::Generator< Sub_Handle >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
