.TH "omega::CodeInsertionVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::CodeInsertionVisitor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rose_attributes\&.h>\fP
.PP
Inherits AstPrePostProcessing\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "virtual void \fBpreOrderVisit\fP (SgNode *n)"
.br
.ti -1c
.RI "virtual void \fBpostOrderVisit\fP (SgNode *n)"
.br
.ti -1c
.RI "void \fBinsertCode\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void omega::CodeInsertionVisitor::initialize ()"

.SS "void omega::CodeInsertionVisitor::insertCode ()"

.SS "virtual void omega::CodeInsertionVisitor::postOrderVisit (SgNode * n)\fC [virtual]\fP"

.SS "virtual void omega::CodeInsertionVisitor::preOrderVisit (SgNode * n)\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
