.TH "omega::CodeInsertionAttribute" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::CodeInsertionAttribute
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rose_attributes\&.h>\fP
.PP
Inherits AstAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCodeInsertionAttribute\fP ()"
.br
.ti -1c
.RI "\fB~CodeInsertionAttribute\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBCodeInsertion\fP *ci)"
.br
.ti -1c
.RI "\fBCodeInsertionPtrListItr\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBCodeInsertionPtrListItr\fP \fBend\fP ()"
.br
.ti -1c
.RI "void \fBremove\fP (\fBCodeInsertion\fP *ci)"
.br
.ti -1c
.RI "int \fBcountCodeInsertions\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::CodeInsertionAttribute::CodeInsertionAttribute ()\fC [inline]\fP"

.SS "omega::CodeInsertionAttribute::~CodeInsertionAttribute ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void omega::CodeInsertionAttribute::add (\fBCodeInsertion\fP * ci)\fC [inline]\fP"

.SS "\fBCodeInsertionPtrListItr\fP omega::CodeInsertionAttribute::begin ()\fC [inline]\fP"

.SS "int omega::CodeInsertionAttribute::countCodeInsertions ()\fC [inline]\fP"

.SS "\fBCodeInsertionPtrListItr\fP omega::CodeInsertionAttribute::end ()\fC [inline]\fP"

.SS "void omega::CodeInsertionAttribute::remove (\fBCodeInsertion\fP * ci)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
