.TH "omega::CodeInsertionMark" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::CodeInsertionMark
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rose_attributes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SgStatement * \fBstmt\fP"
.br
.ti -1c
.RI "\fBCodeInsertion\fP * \fBci\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBCodeInsertion\fP* omega::CodeInsertionMark::ci"

.SS "SgStatement* omega::CodeInsertionMark::stmt"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
