.TH "omega::Section< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Section< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Section\&.h>\fP
.PP
Inherits \fBomega::Sequence< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSection\fP (\fBSequence\fP< \fBT\fP > *, int start, int length)"
.br
.ti -1c
.RI "\fBIterator\fP< \fBT\fP > * \fBnew_iterator\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBT\fP & \fBoperator[]\fP (int) \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator[]\fP (int)"
.br
.ti -1c
.RI "int \fBindex\fP (\fBconst\fP \fBT\fP &) \fBconst\fP"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSection_Iterator< T >\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBomega::Section\fP< \fBT\fP >::\fBSection\fP (\fBSequence\fP< \fBT\fP > * s, int start, int length)"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > int \fBomega::Section\fP< \fBT\fP >::index (\fBconst\fP \fBT\fP & var) const\fC [virtual]\fP"

.PP
Implements \fBomega::Sequence< T >\fP\&.
.SS "template<class T > \fBIterator\fP< \fBT\fP > * \fBomega::Section\fP< \fBT\fP >::new_iterator\fC [virtual]\fP"

.PP
Implements \fBomega::Collection< T >\fP\&.
.SS "template<class T > \fBT\fP & \fBomega::Section\fP< \fBT\fP >::operator[] (int i)\fC [virtual]\fP"

.PP
Implements \fBomega::Sequence< T >\fP\&.
.SS "template<class T > \fBconst\fP \fBT\fP & \fBomega::Section\fP< \fBT\fP >::operator[] (int i) const\fC [virtual]\fP"

.PP
Implements \fBomega::Sequence< T >\fP\&.
.SS "template<class T > int \fBomega::Section\fP< \fBT\fP >::size\fC [virtual]\fP"

.PP
Implements \fBomega::Collection< T >\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T > friend class \fBSection_Iterator\fP< \fBT\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
