.TH "omega::Dynamic_Array1< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Dynamic_Array1< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dynamic_Array\&.h>\fP
.PP
Inherits \fBomega::Dynamic_Array< T, 1 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDynamic_Array1\fP (\fBconst\fP char *\fBs0\fP=0)"
.br
.ti -1c
.RI "\fBDynamic_Array1\fP (int d0)"
.br
.ti -1c
.RI "void \fBresize\fP (int d0)"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator[]\fP (int d)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBDynamic_Array2< T >\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBomega::Dynamic_Array1\fP< \fBT\fP >::\fBDynamic_Array1\fP (\fBconst\fP char * s0 = \fC0\fP)"

.SS "template<class T > \fBomega::Dynamic_Array1\fP< \fBT\fP >::\fBDynamic_Array1\fP (int d0)"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > \fBT\fP & \fBomega::Dynamic_Array1\fP< \fBT\fP >::operator[] (int d)"

.SS "template<class T > void \fBomega::Dynamic_Array1\fP< \fBT\fP >::resize (int d0)"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T > friend class \fBDynamic_Array2\fP< \fBT\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
