.TH "omega::Sequence< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Sequence< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Collection\&.h>\fP
.PP
Inherits \fBomega::Collection< T >\fP\&.
.PP
Inherited by \fBomega::List< T >\fP, \fBomega::Section< T >\fP, \fBomega::Simple_List< T >\fP, and \fBomega::Tuple< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBconst\fP \fBT\fP & \fBoperator[]\fP (int) \fBconst\fP =0"
.br
.ti -1c
.RI "virtual \fBT\fP & \fBoperator[]\fP (int)=0"
.br
.ti -1c
.RI "virtual int \fBindex\fP (\fBconst\fP \fBT\fP &) \fBconst\fP =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class T > virtual int \fBomega::Sequence\fP< \fBT\fP >::index (\fBconst\fP \fBT\fP &) const\fC [pure virtual]\fP"

.PP
Implemented in \fBomega::Tuple< Variable_ID >\fP, \fBomega::Simple_List< T >\fP, \fBomega::Tuple< T >\fP, \fBomega::List< T >\fP, \fBomega::Section< T >\fP, \fBomega::Tuple< std::string >\fP, \fBomega::Tuple< omega::Tuple< omega::Relation > >\fP, \fBomega::Tuple< omega::Relation >\fP, \fBomega::List< omega::Formula * >\fP, \fBomega::Tuple< omega::Const_String >\fP, \fBomega::List< omega::Conjunct * >\fP, and \fBomega::Tuple< int >\fP\&.
.SS "template<class T > virtual \fBconst\fP \fBT\fP& \fBomega::Sequence\fP< \fBT\fP >::operator[] (int) const\fC [pure virtual]\fP"

.PP
Implemented in \fBomega::List< T >\fP, \fBomega::List< omega::Formula * >\fP, \fBomega::List< omega::Conjunct * >\fP, \fBomega::Simple_List< T >\fP, \fBomega::Section< T >\fP, \fBomega::Global_Input_Output_Tuple\fP, \fBomega::Tuple< T >\fP, \fBomega::Tuple< omega::Const_String >\fP, \fBomega::Tuple< std::string >\fP, \fBomega::Tuple< Variable_ID >\fP, \fBomega::Tuple< omega::Tuple< omega::Relation > >\fP, \fBomega::Tuple< int >\fP, and \fBomega::Tuple< omega::Relation >\fP\&.
.SS "template<class T > virtual \fBT\fP& \fBomega::Sequence\fP< \fBT\fP >::operator[] (int)\fC [pure virtual]\fP"

.PP
Implemented in \fBomega::List< T >\fP, \fBomega::List< omega::Formula * >\fP, \fBomega::List< omega::Conjunct * >\fP, \fBomega::Simple_List< T >\fP, \fBomega::Section< T >\fP, \fBomega::Global_Input_Output_Tuple\fP, \fBomega::Tuple< T >\fP, \fBomega::Tuple< omega::Const_String >\fP, \fBomega::Tuple< std::string >\fP, \fBomega::Tuple< Variable_ID >\fP, \fBomega::Tuple< omega::Tuple< omega::Relation > >\fP, \fBomega::Tuple< int >\fP, and \fBomega::Tuple< omega::Relation >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
