.TH "omega::List< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::List< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <List\&.h>\fP
.PP
Inherits \fBomega::Sequence< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBList\fP (\fBconst\fP \fBList\fP< \fBT\fP > &l)"
.br
.ti -1c
.RI "\fBList\fP ()"
.br
.ti -1c
.RI "virtual \fB~List\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP< \fBT\fP > * \fBnew_iterator\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBT\fP & \fBoperator[]\fP (int) \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator[]\fP (int)"
.br
.ti -1c
.RI "int \fBindex\fP (\fBconst\fP \fBT\fP &) \fBconst\fP"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBlength\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBempty\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP & \fBfront\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP \fBremove_front\fP ()"
.br
.ti -1c
.RI "void \fBprepend\fP (\fBconst\fP \fBT\fP &item)"
.br
.ti -1c
.RI "void \fBappend\fP (\fBconst\fP \fBT\fP &item)"
.br
.ti -1c
.RI "void \fBins_after\fP (\fBList_Iterator\fP< \fBT\fP > \fBi\fP, \fBconst\fP \fBT\fP &item)"
.br
.ti -1c
.RI "void \fBdel_front\fP ()"
.br
.ti -1c
.RI "void \fBdel_after\fP (\fBList_Iterator\fP< \fBT\fP > \fBi\fP)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBjoin\fP (\fBList\fP< \fBT\fP > &consumed)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBList_Iterator< T >\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBomega::List\fP< \fBT\fP >::\fBList\fP (\fBconst\fP \fBList\fP< \fBT\fP > & l)\fC [inline]\fP"

.SS "template<class T > \fBomega::List\fP< \fBT\fP >::\fBList\fP ()\fC [inline]\fP"

.SS "template<class T > virtual \fBomega::List\fP< \fBT\fP >::~\fBList\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > void \fBomega::List\fP< \fBT\fP >::append (\fBconst\fP \fBT\fP & item)"

.SS "template<class T > void \fBomega::List\fP< \fBT\fP >::clear"

.SS "template<class T > void \fBomega::List\fP< \fBT\fP >::del_after (\fBList_Iterator\fP< \fBT\fP > i)"

.SS "template<class T > void \fBomega::List\fP< \fBT\fP >::del_front"

.SS "template<class T > bool \fBomega::List\fP< \fBT\fP >::empty () const\fC [inline]\fP"

.SS "template<class T > \fBT\fP & \fBomega::List\fP< \fBT\fP >::front"

.SS "template<class T > int \fBomega::List\fP< \fBT\fP >::index (\fBconst\fP \fBT\fP & item) const\fC [virtual]\fP"

.PP
Implements \fBomega::Sequence< T >\fP\&.
.SS "template<class T > void \fBomega::List\fP< \fBT\fP >::ins_after (\fBList_Iterator\fP< \fBT\fP > i, \fBconst\fP \fBT\fP & item)"

.SS "template<class T > void \fBomega::List\fP< \fBT\fP >::join (\fBList\fP< \fBT\fP > & consumed)"

.SS "template<class T > int \fBomega::List\fP< \fBT\fP >::length () const\fC [inline]\fP"

.SS "template<class T > \fBIterator\fP< \fBT\fP > * \fBomega::List\fP< \fBT\fP >::new_iterator\fC [virtual]\fP"

.PP
Implements \fBomega::Collection< T >\fP\&.
.SS "template<class T > \fBT\fP & \fBomega::List\fP< \fBT\fP >::operator[] (int i)\fC [virtual]\fP"

.PP
Implements \fBomega::Sequence< T >\fP\&.
.SS "template<class T > \fBconst\fP \fBT\fP & \fBomega::List\fP< \fBT\fP >::operator[] (int i) const\fC [virtual]\fP"

.PP
Implements \fBomega::Sequence< T >\fP\&.
.SS "template<class T > void \fBomega::List\fP< \fBT\fP >::prepend (\fBconst\fP \fBT\fP & item)"

.SS "template<class T > \fBT\fP \fBomega::List\fP< \fBT\fP >::remove_front"

.SS "template<class T > int \fBomega::List\fP< \fBT\fP >::size\fC [virtual]\fP"

.PP
Implements \fBomega::Collection< T >\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T > friend class \fBList_Iterator\fP< \fBT\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
