.TH "omega::Dynamic_Array4< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Dynamic_Array4< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dynamic_Array\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDynamic_Array4\fP (\fBconst\fP char *\fBs0\fP=0, \fBconst\fP char *\fBs1\fP=0, \fBconst\fP char *\fBs2\fP=0, \fBconst\fP char *\fBs3\fP=0)"
.br
.ti -1c
.RI "\fBDynamic_Array4\fP (int d0, int d1, int d2, int d3)"
.br
.ti -1c
.RI "void \fBresize\fP (int d0, int d1, int d2, int d3)"
.br
.ti -1c
.RI "\fBDynamic_Array3\fP< \fBT\fP > \fBoperator[]\fP (int d)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBomega::Dynamic_Array4\fP< \fBT\fP >::\fBDynamic_Array4\fP (\fBconst\fP char * s0 = \fC0\fP, \fBconst\fP char * s1 = \fC0\fP, \fBconst\fP char * s2 = \fC0\fP, \fBconst\fP char * s3 = \fC0\fP)"

.SS "template<class T > \fBomega::Dynamic_Array4\fP< \fBT\fP >::\fBDynamic_Array4\fP (int d0, int d1, int d2, int d3)"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > \fBDynamic_Array3\fP< \fBT\fP > \fBomega::Dynamic_Array4\fP< \fBT\fP >::operator[] (int d)"

.SS "template<class T > void \fBomega::Dynamic_Array4\fP< \fBT\fP >::resize (int d0, int d1, int d2, int d3)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
