.TH "omega::Constr_Vars_Iter" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Constr_Vars_Iter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_cnstr\&.h>\fP
.PP
Inherits \fBomega::Generator< Variable_Info >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstr_Vars_Iter\fP (\fBconst\fP \fBConstraint_Handle\fP &ch, bool _wild_only=false)"
.br
.ti -1c
.RI "int \fBlive\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBoperator++\fP (int)"
.br
.ti -1c
.RI "void \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBVariable_Info\fP \fBoperator*\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBVariable_ID\fP \fBcurr_var\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBcoef_t\fP \fBcurr_coef\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::Constr_Vars_Iter::Constr_Vars_Iter (\fBconst\fP \fBConstraint_Handle\fP & ch, bool _wild_only = \fCfalse\fP)"

.SH "Member Function Documentation"
.PP 
.SS "\fBcoef_t\fP omega::Constr_Vars_Iter::curr_coef () const"

.SS "\fBVariable_ID\fP omega::Constr_Vars_Iter::curr_var () const"

.SS "int omega::Constr_Vars_Iter::live () const"

.SS "\fBVariable_Info\fP omega::Constr_Vars_Iter::operator* () const"

.SS "void omega::Constr_Vars_Iter::operator++ ()\fC [virtual]\fP"

.PP
Implements \fBomega::Generator< Variable_Info >\fP\&.
.SS "void omega::Constr_Vars_Iter::operator++ (int)\fC [virtual]\fP"

.PP
Implements \fBomega::Generator< Variable_Info >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
