.TH "omega::F_Or" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::F_Or \- Represents the logical disjunction of its children nodes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_logic\&.h>\fP
.PP
Inherits \fBomega::Formula\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode_Type\fP \fBnode_type\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBFormula\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents the logical disjunction of its children nodes\&. 

It is 'False' if it has no children 
.SH "Member Function Documentation"
.PP 
.SS "\fBNode_Type\fP omega::F_Or::node_type ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBomega::Formula\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBFormula\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
