.TH "omega::CodeInsertion" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::CodeInsertion
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rose_attributes\&.h>\fP
.PP
Inherited by \fBomega::MMPrefetchInsertion\fP, and \fBomega::PragmaInsertion\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCodeInsertion\fP (int looplevel)"
.br
.ti -1c
.RI "\fB~CodeInsertion\fP ()"
.br
.ti -1c
.RI "virtual SgStatement * \fBgetStatement\fP (SgScopeStatement *scopeStmt=\fBNULL\fP)=0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBloop_level\fP"
.br
.ti -1c
.RI "bool \fBmarked\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::CodeInsertion::CodeInsertion (int looplevel)\fC [inline]\fP"

.SS "omega::CodeInsertion::~CodeInsertion ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual SgStatement* omega::CodeInsertion::getStatement (SgScopeStatement * scopeStmt = \fC\fBNULL\fP\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBomega::MMPrefetchInsertion\fP, and \fBomega::PragmaInsertion\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int omega::CodeInsertion::loop_level"

.SS "bool omega::CodeInsertion::marked"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
