.TH "omega::Comp_Problem" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Comp_Problem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_cmpr\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComp_Problem\fP (\fBProblem\fP *problem)"
.br
.ti -1c
.RI "\fBProblem\fP * \fBUncompressProblem\fP ()"
.br
.ti -1c
.RI "bool \fBno_constraints\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::Comp_Problem::Comp_Problem (\fBProblem\fP * problem)"

.SH "Member Function Documentation"
.PP 
.SS "bool omega::Comp_Problem::no_constraints () const\fC [inline]\fP"

.SS "\fBProblem\fP * omega::Comp_Problem::UncompressProblem ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
