.TH "omega::Substitutions" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Substitutions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_subs\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubstitutions\fP (\fBRelation\fP &input_R, \fBConjunct\fP *input_c)"
.br
.ti -1c
.RI "\fB~Substitutions\fP ()"
.br
.ti -1c
.RI "\fBSub_Handle\fP \fBget_sub\fP (\fBVariable_ID\fP v)"
.br
.ti -1c
.RI "bool \fBsubstituted\fP (\fBVariable_ID\fP v)"
.br
.ti -1c
.RI "bool \fBsub_involves\fP (\fBVariable_ID\fP v, \fBVar_Kind\fP kind)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSub_Iterator\fP"
.br
.ti -1c
.RI "class \fBSub_Handle\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::Substitutions::Substitutions (\fBRelation\fP & input_R, \fBConjunct\fP * input_c)"

.SS "omega::Substitutions::~Substitutions ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBSub_Handle\fP omega::Substitutions::get_sub (\fBVariable_ID\fP v)"

.SS "bool omega::Substitutions::sub_involves (\fBVariable_ID\fP v, \fBVar_Kind\fP kind)"

.SS "bool omega::Substitutions::substituted (\fBVariable_ID\fP v)"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSub_Handle\fP\fC [friend]\fP"

.SS "friend class \fBSub_Iterator\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
