.TH "omega::reachable_information" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::reachable_information \- Reachability of a graph\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reach\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTuple\fP< std::string > \fBnode_names\fP"
.br
.ti -1c
.RI "\fBTuple\fP< int > \fBnode_arity\fP"
.br
.ti -1c
.RI "\fBDynamic_Array1\fP< \fBRelation\fP > \fBstart_nodes\fP"
.br
.ti -1c
.RI "\fBDynamic_Array2\fP< \fBRelation\fP > \fBtransitions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reachability of a graph\&. 

Given a tuple set for each node representing starting states at each node\&. The library can compute which node are reachable and values the tuples can take on\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBTuple\fP<int> omega::reachable_information::node_arity"

.SS "\fBTuple\fP<std::string> omega::reachable_information::node_names"

.SS "\fBDynamic_Array1\fP<\fBRelation\fP> omega::reachable_information::start_nodes"

.SS "\fBDynamic_Array2\fP<\fBRelation\fP> omega::reachable_information::transitions"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
