.TH "omega::Set< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Set< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bag\&.h>\fP
.PP
Inherits \fBomega::Ordered_Bag< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSet\fP ()"
.br
.ti -1c
.RI "\fBSet\fP (\fBT\fP)"
.br
.ti -1c
.RI "\fBSet\fP (\fBconst\fP \fBSet\fP< \fBT\fP > &\fBS\fP)"
.br
.ti -1c
.RI "bool \fBcontains\fP (\fBconst\fP \fBSet\fP< \fBT\fP > &\fBb\fP) \fBconst\fP"
.br
.ti -1c
.RI "bool \fBcontains\fP (\fBT\fP t) \fBconst\fP"
.br
.ti -1c
.RI "virtual void \fBoperator|=\fP (\fBconst\fP \fBSet\fP< \fBT\fP > &\fBb\fP)"
.br
.ti -1c
.RI "void \fBoperator|=\fP (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > &\fBb\fP)"
.br
.ti -1c
.RI "void \fBoperator|=\fP (\fBconst\fP \fBBag\fP< \fBT\fP > &\fBb\fP)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (\fBconst\fP \fBSet\fP< \fBT\fP > &\fBb\fP)"
.br
.ti -1c
.RI "void \fBoperator&=\fP (\fBconst\fP \fBSet\fP< \fBT\fP > &\fBb\fP)"
.br
.ti -1c
.RI "bool \fBoperator&\fP (\fBconst\fP \fBSet\fP< \fBT\fP > &) \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBomega::Set\fP< \fBT\fP >::\fBSet\fP"

.SS "template<class T > \fBomega::Set\fP< \fBT\fP >::\fBSet\fP (\fBT\fP e)"

.SS "template<class T > \fBomega::Set\fP< \fBT\fP >::\fBSet\fP (\fBconst\fP \fBSet\fP< \fBT\fP > & S)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > bool \fBomega::Set\fP< \fBT\fP >::contains (\fBconst\fP \fBSet\fP< \fBT\fP > & b) const"

.SS "template<class T > bool \fBomega::Set\fP< \fBT\fP >::contains (\fBT\fP t) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBomega::Ordered_Bag< T >\fP\&.
.SS "template<class T > bool \fBomega::Set\fP< \fBT\fP >::operator& (\fBconst\fP \fBSet\fP< \fBT\fP > & b) const"

.SS "template<class T > void \fBomega::Set\fP< \fBT\fP >::operator&= (\fBconst\fP \fBSet\fP< \fBT\fP > & b)"

.SS "template<class T > void \fBomega::Set\fP< \fBT\fP >::operator\-= (\fBconst\fP \fBSet\fP< \fBT\fP > & b)"

.SS "template<class T > void \fBomega::Set\fP< \fBT\fP >::operator|= (\fBconst\fP \fBBag\fP< \fBT\fP > & b)\fC [virtual]\fP"

.PP
Reimplemented from \fBomega::Ordered_Bag< T >\fP\&.
.SS "template<class T > void \fBomega::Set\fP< \fBT\fP >::operator|= (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > & b)\fC [virtual]\fP"

.PP
Reimplemented from \fBomega::Ordered_Bag< T >\fP\&.
.SS "template<class T > void \fBomega::Set\fP< \fBT\fP >::operator|= (\fBconst\fP \fBSet\fP< \fBT\fP > & b)\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
