.TH "omega::BoolSet< T >::iterator" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::BoolSet< T >::iterator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <boolset\&.h>\fP
.PP
Inherits iterator< std::forward_iterator_tag, T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~iterator\fP ()"
.br
.ti -1c
.RI "\fBBoolSet\fP< \fBT\fP >::\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBBoolSet\fP< \fBT\fP >::\fBiterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBBoolSet\fP< \fBT\fP >::\fBiterator\fP \fBoperator+\fP (int) \fBconst\fP"
.br
.ti -1c
.RI "unsigned int \fBoperator*\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBBoolSet\fP< \fBT\fP >::\fBiterator\fP &) \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBconst\fP \fBBoolSet\fP< \fBT\fP >::\fBiterator\fP &) \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator typename BoolSet< T >::const_iterator\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (\fBBoolSet\fP< \fBT\fP > *s, unsigned int \fBpos\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBBoolSet\fP< \fBT\fP > * \fBs_\fP"
.br
.ti -1c
.RI "unsigned int \fBpos_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBBoolSet< T >\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T  = unsigned int> \fBomega::BoolSet\fP< \fBT\fP >::iterator::iterator (\fBBoolSet\fP< \fBT\fP > * s, unsigned int pos)\fC [inline]\fP, \fC [protected]\fP"

.SS "template<typename T  = unsigned int> \fBomega::BoolSet\fP< \fBT\fP >::iterator::~iterator ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBomega::BoolSet\fP< \fBT\fP >::iterator::operator typename \fBBoolSet\fP< \fBT\fP >::\fBconst_iterator\fP"

.SS "template<typename T > bool \fBomega::BoolSet\fP< \fBT\fP >::iterator::operator!= (\fBconst\fP \fBBoolSet\fP< \fBT\fP >::\fBiterator\fP & other) const"

.SS "template<typename T > unsigned int \fBomega::BoolSet\fP< \fBT\fP >::iterator::operator*"

.SS "template<typename T > \fBBoolSet\fP< \fBT\fP >::\fBiterator\fP \fBomega::BoolSet\fP< \fBT\fP >::iterator::operator+ (int n) const"

.SS "template<typename T > \fBBoolSet\fP< \fBT\fP >::\fBiterator\fP & \fBomega::BoolSet\fP< \fBT\fP >::iterator::operator++"

.SS "template<typename T > \fBBoolSet\fP< \fBT\fP >::\fBiterator\fP \fBomega::BoolSet\fP< \fBT\fP >::iterator::operator++ (int)"

.SS "template<typename T > bool \fBomega::BoolSet\fP< \fBT\fP >::iterator::operator== (\fBconst\fP \fBBoolSet\fP< \fBT\fP >::\fBiterator\fP & other) const"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename T  = unsigned int> friend class \fBBoolSet\fP< \fBT\fP >\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T  = unsigned int> unsigned int \fBomega::BoolSet\fP< \fBT\fP >::iterator::pos_\fC [protected]\fP"

.SS "template<typename T  = unsigned int> \fBBoolSet\fP<\fBT\fP>* \fBomega::BoolSet\fP< \fBT\fP >::iterator::s_\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
