.TH "omega::F_Exists" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::F_Exists \- Existential qualifier\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_quant\&.h>\fP
.PP
Inherits \fBomega::F_Declaration\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode_Type\fP \fBnode_type\fP ()"
.br
.ti -1c
.RI "\fBVariable_ID\fP \fBdeclare\fP (\fBConst_String\fP s)"
.br
.RI "add a new variable to this declaration node "
.ti -1c
.RI "\fBVariable_ID\fP \fBdeclare\fP ()"
.br
.ti -1c
.RI "\fBVariable_ID\fP \fBdeclare\fP (\fBVariable_ID\fP v)"
.br
.ti -1c
.RI "virtual void \fBpush_exists\fP (\fBVariable_ID_Tuple\fP &\fBS\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBF_Exists\fP (\fBFormula\fP *, \fBRel_Body\fP *)"
.br
.ti -1c
.RI "\fBF_Exists\fP (\fBFormula\fP *, \fBRel_Body\fP *, \fBVariable_ID_Tuple\fP &)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBFormula\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Existential qualifier\&. 

This associates with one or more variables\&. These variables are existentially qualified in the formula represented by its single child node\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::F_Exists::F_Exists (\fBFormula\fP * p, \fBRel_Body\fP * r)\fC [protected]\fP"

.SS "omega::F_Exists::F_Exists (\fBFormula\fP * p, \fBRel_Body\fP * r, \fBVariable_ID_Tuple\fP & S)\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBVariable_ID\fP omega::F_Exists::declare ()\fC [virtual]\fP"

.PP
Implements \fBomega::F_Declaration\fP\&.
.SS "\fBVariable_ID\fP omega::F_Exists::declare (\fBConst_String\fP s)\fC [virtual]\fP"

.PP
add a new variable to this declaration node 
.PP
Implements \fBomega::F_Declaration\fP\&.
.SS "\fBVariable_ID\fP omega::F_Exists::declare (\fBVariable_ID\fP v)\fC [virtual]\fP"

.PP
Implements \fBomega::F_Declaration\fP\&.
.SS "\fBNode_Type\fP omega::F_Exists::node_type ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBomega::Formula\fP\&.
.SS "void omega::F_Exists::push_exists (\fBVariable_ID_Tuple\fP & S)\fC [virtual]\fP"

.PP
Reimplemented from \fBomega::Formula\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBFormula\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
