.TH "omega::eqn" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::eqn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <oc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEqnKey\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBcoef_t\fP \fBtouched\fP"
.br
.ti -1c
.RI "int \fBcolor\fP"
.br
.ti -1c
.RI "int \fBessential\fP"
.br
.ti -1c
.RI "int \fBvarCount\fP"
.br
.ti -1c
.RI "\fBcoef_t\fP \fBcoef\fP [\fBmaxVars\fP+1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBcoef_t\fP omega::eqn::coef[\fBmaxVars\fP+1]"

.SS "int omega::eqn::color"

.SS "int omega::eqn::essential"

.SS "\fBEqnKey\fP omega::eqn::key"

.SS "\fBcoef_t\fP omega::eqn::touched"

.SS "int omega::eqn::varCount"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
