.TH "omega::DNF_Iterator" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::DNF_Iterator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pres_dnf\&.h>\fP
.PP
Inherits \fBomega::List_Iterator< Conjunct * >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDNF_Iterator\fP (\fBDNF\fP *dnf)"
.br
.ti -1c
.RI "\fBDNF_Iterator\fP ()"
.br
.ti -1c
.RI "void \fBcurr_set\fP (\fBConjunct\fP *\fBc\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omega::DNF_Iterator::DNF_Iterator (\fBDNF\fP * dnf)\fC [inline]\fP"

.SS "omega::DNF_Iterator::DNF_Iterator ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void omega::DNF_Iterator::curr_set (\fBConjunct\fP * c)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
