.TH "omega::Ordered_Bag< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::Ordered_Bag< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bag\&.h>\fP
.PP
Inherits \fBomega::Bag< T >\fP\&.
.PP
Inherited by \fBomega::Set< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrdered_Bag\fP ()"
.br
.ti -1c
.RI "\fBOrdered_Bag\fP (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > &\fBB\fP)"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBT\fP)"
.br
.ti -1c
.RI "virtual void \fBoperator|=\fP (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > &\fBb\fP)"
.br
.ti -1c
.RI "void \fBoperator|=\fP (\fBconst\fP \fBBag\fP< \fBT\fP > &\fBb\fP)"
.br
.ti -1c
.RI "bool \fBcontains\fP (\fBT\fP) \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > &) \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > &) \fBconst\fP"
.br
.ti -1c
.RI "bool \fBoperator<\fP (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > &) \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBomega::Ordered_Bag\fP< \fBT\fP >::\fBOrdered_Bag\fP"

.SS "template<class T > \fBomega::Ordered_Bag\fP< \fBT\fP >::\fBOrdered_Bag\fP (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > & B)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > bool \fBomega::Ordered_Bag\fP< \fBT\fP >::contains (\fBT\fP e) const\fC [virtual]\fP"

.PP
Reimplemented from \fBomega::Bag< T >\fP\&.
.PP
Reimplemented in \fBomega::Set< T >\fP\&.
.SS "template<class T > void \fBomega::Ordered_Bag\fP< \fBT\fP >::insert (\fBT\fP e)\fC [virtual]\fP"

.PP
Reimplemented from \fBomega::Bag< T >\fP\&.
.SS "template<class T > bool \fBomega::Ordered_Bag\fP< \fBT\fP >::operator!= (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > & b) const"

.SS "template<class T > bool \fBomega::Ordered_Bag\fP< \fBT\fP >::operator< (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > & b) const"

.SS "template<class T > bool \fBomega::Ordered_Bag\fP< \fBT\fP >::operator== (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > & b) const"

.SS "template<class T > void \fBomega::Ordered_Bag\fP< \fBT\fP >::operator|= (\fBconst\fP \fBBag\fP< \fBT\fP > & b)\fC [virtual]\fP"

.PP
Reimplemented from \fBomega::Bag< T >\fP\&.
.PP
Reimplemented in \fBomega::Set< T >\fP\&.
.SS "template<class T > void \fBomega::Ordered_Bag\fP< \fBT\fP >::operator|= (\fBconst\fP \fBOrdered_Bag\fP< \fBT\fP > & b)\fC [virtual]\fP"

.PP
Reimplemented in \fBomega::Set< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
