.TH "omega::List_Iterator< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omega::List_Iterator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <List\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBList_Iterator\fP (\fBList\fP< \fBT\fP > &l)"
.br
.ti -1c
.RI "\fBList_Iterator\fP (\fBconst\fP \fBList\fP< \fBT\fP > &l)"
.br
.ti -1c
.RI "\fBList_Iterator\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBList< T >\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBomega::List_Iterator\fP< \fBT\fP >::\fBList_Iterator\fP (\fBList\fP< \fBT\fP > & l)"

.SS "template<class T > \fBomega::List_Iterator\fP< \fBT\fP >::\fBList_Iterator\fP (\fBconst\fP \fBList\fP< \fBT\fP > & l)"

.SS "template<class T > \fBomega::List_Iterator\fP< \fBT\fP >::\fBList_Iterator\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T > friend class \fBList\fP< \fBT\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
