.TH "omglib::UninterpFunc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
omglib::UninterpFunc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OmegaLib\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUninterpFunc\fP (\fBconst\fP string &\fBname\fP='', unsigned \fBarity\fP=1, unsigned \fBorder\fP=0)"
.br
.ti -1c
.RI "\fBUninterpFunc\fP (\fBconst\fP \fBUninterpFunc\fP &other)"
.br
.ti -1c
.RI "unsigned \fBnum_args\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBadd_arg\fP (\fBconst\fP string &\fBarg\fP)"
.br
.ti -1c
.RI "string \fBto_string\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "vector< string > \fBargs\fP"
.br
.ti -1c
.RI "unsigned \fBarity\fP"
.br
.ti -1c
.RI "unsigned \fBorder\fP"
.br
.ti -1c
.RI "string \fBoldName\fP"
.br
.ti -1c
.RI "vector< string > \fBoldArgs\fP"
.br
.ti -1c
.RI "int \fBoldArity\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "omglib::UninterpFunc::UninterpFunc (\fBconst\fP string & name = \fC''\fP, unsigned arity = \fC1\fP, unsigned order = \fC0\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "omglib::UninterpFunc::UninterpFunc (\fBconst\fP \fBUninterpFunc\fP & other)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void omglib::UninterpFunc::add_arg (\fBconst\fP string & arg)\fC [inline]\fP"

.SS "unsigned omglib::UninterpFunc::num_args () const\fC [inline]\fP"

.SS "string omglib::UninterpFunc::to_string () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "vector<string> omglib::UninterpFunc::args"

.SS "unsigned omglib::UninterpFunc::arity"

.SS "string omglib::UninterpFunc::name"

.SS "vector<string> omglib::UninterpFunc::oldArgs"

.SS "int omglib::UninterpFunc::oldArity"

.SS "string omglib::UninterpFunc::oldName"

.SS "unsigned omglib::UninterpFunc::order"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
