.TH "lib/isl/include/isl/options.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/options.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/arg\&.h>\fP
.br
\fC#include <isl/ctx\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBISL_BOUND_BERNSTEIN\fP   0"
.br
.ti -1c
.RI "#define \fBISL_BOUND_RANGE\fP   1"
.br
.ti -1c
.RI "#define \fBISL_ON_ERROR_WARN\fP   0"
.br
.ti -1c
.RI "#define \fBISL_ON_ERROR_CONTINUE\fP   1"
.br
.ti -1c
.RI "#define \fBISL_ON_ERROR_ABORT\fP   2"
.br
.ti -1c
.RI "#define \fBISL_SCHEDULE_ALGORITHM_ISL\fP   0"
.br
.ti -1c
.RI "#define \fBISL_SCHEDULE_ALGORITHM_FEAUTRIER\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBisl_stat\fP \fBisl_options_set_bound\fP (\fBisl_ctx\fP *ctx, int \fBval\fP)"
.br
.ti -1c
.RI "int \fBisl_options_get_bound\fP (\fBisl_ctx\fP *ctx)"
.br
.ti -1c
.RI "\fBisl_stat\fP \fBisl_options_set_on_error\fP (\fBisl_ctx\fP *ctx, int \fBval\fP)"
.br
.ti -1c
.RI "int \fBisl_options_get_on_error\fP (\fBisl_ctx\fP *ctx)"
.br
.ti -1c
.RI "\fBisl_stat\fP \fBisl_options_set_gbr_only_first\fP (\fBisl_ctx\fP *ctx, int \fBval\fP)"
.br
.ti -1c
.RI "int \fBisl_options_get_gbr_only_first\fP (\fBisl_ctx\fP *ctx)"
.br
.ti -1c
.RI "\fBisl_stat\fP \fBisl_options_set_schedule_algorithm\fP (\fBisl_ctx\fP *ctx, int \fBval\fP)"
.br
.ti -1c
.RI "int \fBisl_options_get_schedule_algorithm\fP (\fBisl_ctx\fP *ctx)"
.br
.ti -1c
.RI "\fBisl_stat\fP \fBisl_options_set_coalesce_bounded_wrapping\fP (\fBisl_ctx\fP *ctx, int \fBval\fP)"
.br
.ti -1c
.RI "int \fBisl_options_get_coalesce_bounded_wrapping\fP (\fBisl_ctx\fP *ctx)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ISL_BOUND_BERNSTEIN   0"

.SS "#define ISL_BOUND_RANGE   1"

.SS "#define ISL_ON_ERROR_ABORT   2"

.SS "#define ISL_ON_ERROR_CONTINUE   1"

.SS "#define ISL_ON_ERROR_WARN   0"

.SS "#define ISL_SCHEDULE_ALGORITHM_FEAUTRIER   1"

.SS "#define ISL_SCHEDULE_ALGORITHM_ISL   0"

.SH "Function Documentation"
.PP 
.SS "int isl_options_get_bound (\fBisl_ctx\fP * ctx)"

.SS "int isl_options_get_coalesce_bounded_wrapping (\fBisl_ctx\fP * ctx)"

.SS "int isl_options_get_gbr_only_first (\fBisl_ctx\fP * ctx)"

.SS "int isl_options_get_on_error (\fBisl_ctx\fP * ctx)"

.SS "int isl_options_get_schedule_algorithm (\fBisl_ctx\fP * ctx)"

.SS "\fBisl_stat\fP isl_options_set_bound (\fBisl_ctx\fP * ctx, int val)"

.SS "\fBisl_stat\fP isl_options_set_coalesce_bounded_wrapping (\fBisl_ctx\fP * ctx, int val)"

.SS "\fBisl_stat\fP isl_options_set_gbr_only_first (\fBisl_ctx\fP * ctx, int val)"

.SS "\fBisl_stat\fP isl_options_set_on_error (\fBisl_ctx\fP * ctx, int val)"

.SS "\fBisl_stat\fP isl_options_set_schedule_algorithm (\fBisl_ctx\fP * ctx, int val)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
