.TH "src/util/OS.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/OS.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fButil::OS\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fButil\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUFFSIZE\fP   1024"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFSIZE   1024"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
