.TH "lib/iegenlib/src/parser/parser.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/parser/parser.cc \- Implementations to methods declared in \fBparser\&.h\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <parser/parser\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBiegenlib\fP"
.br
.ti -1c
.RI " \fBiegenlib::parser\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fByyparse\fP   \fBzzparse\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBzzparse\fP ()"
.br
.ti -1c
.RI "int \fBiegenlib::parser::string_get_next_char\fP ()"
.br
.RI "Used by lexer to obtain each character of input string being parsed\&. "
.ti -1c
.RI "Environment * \fBiegenlib::parser::parse_env\fP (std::string env_string)"
.br
.ti -1c
.RI "Environment * \fBiegenlib::parser::get_parse_env_result\fP ()"
.br
.ti -1c
.RI "void \fBiegenlib::parser::set_parse_env_result\fP (Environment *\fBe\fP)"
.br
.ti -1c
.RI "Set * \fBiegenlib::parser::parse_set\fP (string set_string)"
.br
.ti -1c
.RI "Set \fBiegenlib::parser::get_parse_set_result\fP ()"
.br
.ti -1c
.RI "void \fBiegenlib::parser::set_parse_set_result\fP (Set *s)"
.br
.ti -1c
.RI "Relation * \fBiegenlib::parser::parse_relation\fP (string relation_string)"
.br
.ti -1c
.RI "Relation \fBiegenlib::parser::get_parse_relation_result\fP ()"
.br
.ti -1c
.RI "void \fBiegenlib::parser::set_parse_relation_result\fP (Relation *s)"
.br
.ti -1c
.RI "void \fBiegenlib::parser::set_parse_error\fP (string \fBerror\fP)"
.br
.ti -1c
.RI "bool \fBiegenlib::parser::get_parse_error\fP ()"
.br
.ti -1c
.RI "void \fBiegenlib::parser::clearAll\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBiegenlib::parser::input_buffer\fP"
.br
.ti -1c
.RI "unsigned int \fBiegenlib::parser::input_pos\fP"
.br
.ti -1c
.RI "bool \fBiegenlib::parser::parse_error\fP"
.br
.ti -1c
.RI "string \fBiegenlib::parser::error_message\fP"
.br
.RI "error message for when an error occurs in the parser "
.ti -1c
.RI "Environment * \fBiegenlib::parser::parse_env_result\fP"
.br
.ti -1c
.RI "Relation * \fBiegenlib::parser::parse_relation_result\fP"
.br
.ti -1c
.RI "Set * \fBiegenlib::parser::parse_set_result\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementations to methods declared in \fBparser\&.h\fP\&. 


.PP
\fBDate\fP
.RS 4
Started: 5/17/2010 
.RE
.PP
.SH "$Revision:: 622                $: last committed revision"
.PP
.SH "$Date:: 2013-01-18 13:11:32 -0#$: date of last committed revision"
.PP
.SH "$Author:: cathie               $: author of last committed revision"
.PP
\fBAuthors\fP
.RS 4
Michelle Strout, Alan LaMielle, Nicholas Jeanette
.RE
.PP
Copyright (c) 2009, 2010, 2011, 2012, Colorado State University 
.br
 All rights reserved\&. 
.br
 See \&.\&./\&.\&./COPYING for details\&. 
.br
 
.SH "Macro Definition Documentation"
.PP 
.SS "#define yyparse   \fBzzparse\fP"

.SH "Function Documentation"
.PP 
.SS "int zzparse ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
