.TH "pdfg::Int" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::Int
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphIL\&.hpp>\fP
.PP
Inherits \fBpdfg::Expr\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInt\fP (int \fBval\fP=0)"
.br
.ti -1c
.RI "\fBInt\fP (\fBconst\fP \fBExpr\fP &expr)"
.br
.ti -1c
.RI "\fBInt\fP (\fBconst\fP \fBInt\fP &other)"
.br
.ti -1c
.RI "\fBInt\fP & \fBoperator=\fP (\fBconst\fP \fBExpr\fP &expr) override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcopy\fP (\fBconst\fP \fBInt\fP &other)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_val\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::Int::Int (int val = \fC0\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "pdfg::Int::Int (\fBconst\fP \fBExpr\fP & expr)\fC [inline]\fP, \fC [explicit]\fP"

.SS "pdfg::Int::Int (\fBconst\fP \fBInt\fP & other)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void pdfg::Int::copy (\fBconst\fP \fBInt\fP & other)\fC [inline]\fP, \fC [protected]\fP"

.SS "\fBInt\fP& pdfg::Int::operator= (\fBconst\fP \fBExpr\fP & expr)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::Expr\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int pdfg::Int::_val\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
