.TH "scripts/pdfg/pdfgs.py" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/pdfg/pdfgs.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpdfg\&.pdfgs\&.PDFGParser\fP"
.br
.ti -1c
.RI "class \fBpdfg\&.pdfgs\&.Jacobi1D\fP"
.br
.ti -1c
.RI "class \fBpdfg\&.pdfgs\&.Jacobi2D\fP"
.br
.ti -1c
.RI "class \fBpdfg\&.pdfgs\&.MiniFluxDix\fP"
.br
.ti -1c
.RI "class \fBpdfg\&.pdfgs\&.CSRSpMV\fP"
.br
.ti -1c
.RI "class \fBpdfg\&.pdfgs\&.BSRSpMV\fP"
.br
.ti -1c
.RI "class \fBpdfg\&.pdfgs\&.CSRToBSRGen\fP"
.br
.ti -1c
.RI "class \fBpdfg\&.pdfgs\&.CSRToBSR\fP"
.br
.ti -1c
.RI "class \fBpdfg\&.pdfgs\&.CSRToBSRInsp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpdfg\&.pdfgs\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpdfg\&.pdfgs\&.from_spec\fP (spec)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
