.TH "pdfg.graph.Node" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.graph.Node
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBpdfg\&.graph\&.DataNode\fP, \fBpdfg\&.graph\&.IterNode\fP, and \fBpdfg\&.graph\&.StmtNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBlabel\fP='', \fBname\fP='', \fBattrs\fP={}, \fBgraph\fP=None, \fBdomain\fP='')"
.br
.ti -1c
.RI "def \fB__contains__\fP (self, item)"
.br
.ti -1c
.RI "def \fB__len__\fP (self)"
.br
.ti -1c
.RI "def \fB__getitem__\fP (self, \fBkey\fP)"
.br
.ti -1c
.RI "def \fB__setitem__\fP (self, \fBkey\fP, \fBval\fP)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fBkey\fP (self)"
.br
.ti -1c
.RI "def \fBattrkeys\fP (self)"
.br
.ti -1c
.RI "def \fBdotlabel\fP (self)"
.br
.ti -1c
.RI "def \fBlabel\fP (self)"
.br
.ti -1c
.RI "def \fBlabel\fP (self, label)"
.br
.ti -1c
.RI "def \fBname\fP (self)"
.br
.ti -1c
.RI "def \fBname\fP (self, name)"
.br
.ti -1c
.RI "def \fBdomain\fP (self)"
.br
.ti -1c
.RI "def \fBdomain\fP (self, domain)"
.br
.ti -1c
.RI "def \fBset\fP (self)"
.br
.ti -1c
.RI "def \fBset\fP (self, set)"
.br
.ti -1c
.RI "def \fBattrs\fP (self)"
.br
.ti -1c
.RI "def \fBattrs\fP (self, attrs={})"
.br
.ti -1c
.RI "def \fBgraph\fP (self)"
.br
.ti -1c
.RI "def \fBgraph\fP (self, g)"
.br
.ti -1c
.RI "def \fBdot\fP (self)"
.br
.ti -1c
.RI "def \fBstatement\fP (self)"
.br
.ti -1c
.RI "def \fBaccept\fP (self, visitor)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.graph\&.Node\&.__init__ ( self,  label = \fC''\fP,  name = \fC''\fP,  attrs = \fC{}\fP,  graph = \fCNone\fP,  domain = \fC''\fP)"

.PP
Reimplemented in \fBpdfg\&.graph\&.DataNode\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def pdfg\&.graph\&.Node\&.__contains__ ( self,  item)"

.SS "def pdfg\&.graph\&.Node\&.__getitem__ ( self,  key)"

.SS "def pdfg\&.graph\&.Node\&.__len__ ( self)"

.SS "def pdfg\&.graph\&.Node\&.__setitem__ ( self,  key,  val)"

.SS "def pdfg\&.graph\&.Node\&.__str__ ( self)"

.SS "def pdfg\&.graph\&.Node\&.accept ( self,  visitor)"

.SS "def pdfg\&.graph\&.Node\&.attrkeys ( self)"

.SS "def pdfg\&.graph\&.Node\&.attrs ( self)"

.SS "def pdfg\&.graph\&.Node\&.attrs ( self,  attrs = \fC{}\fP)"

.SS "def pdfg\&.graph\&.Node\&.domain ( self)"

.PP
Reimplemented in \fBpdfg\&.graph\&.DataNode\fP\&.
.SS "def pdfg\&.graph\&.Node\&.domain ( self,  domain)"

.PP
Reimplemented in \fBpdfg\&.graph\&.DataNode\fP\&.
.SS "def pdfg\&.graph\&.Node\&.dot ( self)"

.PP
Reimplemented in \fBpdfg\&.graph\&.DataNode\fP, and \fBpdfg\&.graph\&.StmtNode\fP\&.
.SS "def pdfg\&.graph\&.Node\&.dotlabel ( self)"

.SS "def pdfg\&.graph\&.Node\&.graph ( self)"

.SS "def pdfg\&.graph\&.Node\&.graph ( self,  g)"

.SS "def pdfg\&.graph\&.Node\&.key ( self)"

.SS "def pdfg\&.graph\&.Node\&.label ( self)"

.SS "def pdfg\&.graph\&.Node\&.label ( self,  label)"

.SS "def pdfg\&.graph\&.Node\&.name ( self)"

.SS "def pdfg\&.graph\&.Node\&.name ( self,  name)"

.SS "def pdfg\&.graph\&.Node\&.set ( self)"

.SS "def pdfg\&.graph\&.Node\&.set ( self,  set)"

.SS "def pdfg\&.graph\&.Node\&.statement ( self)"

.PP
Reimplemented in \fBpdfg\&.graph\&.StmtNode\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
