.TH "pdfg::InspGen" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::InspGen
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InspGen\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInspGen\fP (\fBconst\fP \fBSpace\fP &source, \fBconst\fP \fBSpace\fP &dest)"
.br
.ti -1c
.RI "string \fBgen\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::InspGen::InspGen (\fBconst\fP \fBSpace\fP & source, \fBconst\fP \fBSpace\fP & dest)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "string pdfg::InspGen::gen ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
