.TH "pdfg.graph.NodeFactory.__NodeFactory" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.graph.NodeFactory.__NodeFactory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.graph\&.NodeFactory\&.__NodeFactory\&.__init__ ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
