.TH "pdfg.graph.IEGenGraph" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.graph.IEGenGraph
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpdfg\&.graph\&.FlowGraph\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBname\fP='iegen', \fBconstants\fP=(), expressions=(), \fBinput\fP=None)"
.br
.ti -1c
.RI "def \fBinput\fP (self)"
.br
.ti -1c
.RI "def \fBsetup\fP (self)"
.br
.ti -1c
.RI "def \fBexecutor\fP (self)"
.br
.ti -1c
.RI "def \fBinspector\fP (self)"
.br
.ti -1c
.RI "def \fBbuild_sets\fP (self)"
.br
.ti -1c
.RI "def \fBgenerate\fP (self)"
.br
.ti -1c
.RI "def \fBbuild_setup\fP (self)"
.br
.ti -1c
.RI "def \fBbuild_inspector\fP (self)"
.br
.ti -1c
.RI "def \fBbuild_executor\fP (self)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.graph\&.IEGenGraph\&.__init__ ( self,  name = \fC'iegen'\fP,  constants = \fC()\fP,  expressions = \fC()\fP,  input = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def pdfg\&.graph\&.IEGenGraph\&.build_executor ( self)"

.SS "def pdfg\&.graph\&.IEGenGraph\&.build_inspector ( self)"

.SS "def pdfg\&.graph\&.IEGenGraph\&.build_sets ( self)"

.SS "def pdfg\&.graph\&.IEGenGraph\&.build_setup ( self)"

.SS "def pdfg\&.graph\&.IEGenGraph\&.executor ( self)"

.SS "def pdfg\&.graph\&.IEGenGraph\&.generate ( self)"

.SS "def pdfg\&.graph\&.IEGenGraph\&.input ( self)"

.SS "def pdfg\&.graph\&.IEGenGraph\&.inspector ( self)"

.SS "def pdfg\&.graph\&.IEGenGraph\&.setup ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
