.TH "pdfg::RelNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::RelNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FlowGraph\&.hpp>\fP
.PP
Inherits \fBpdfg::Node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRelNode\fP (\fBExpr\fP *rel, \fBconst\fP string &\fBlabel\fP='')"
.br
.ti -1c
.RI "\fBRelNode\fP (\fBconst\fP \fBRelNode\fP &other)"
.br
.ti -1c
.RI "\fBRelNode\fP & \fBoperator=\fP (\fBconst\fP \fBRelNode\fP &other)"
.br
.ti -1c
.RI "\fBRel\fP * \fBrelation\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBrelation\fP (\fBRel\fP *rel)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcopy\fP (\fBconst\fP \fBRelNode\fP &other)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::RelNode::RelNode (\fBExpr\fP * rel, \fBconst\fP string & label = \fC''\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "pdfg::RelNode::RelNode (\fBconst\fP \fBRelNode\fP & other)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void pdfg::RelNode::copy (\fBconst\fP \fBRelNode\fP & other)\fC [inline]\fP, \fC [protected]\fP"

.SS "\fBRelNode\fP& pdfg::RelNode::operator= (\fBconst\fP \fBRelNode\fP & other)\fC [inline]\fP"

.SS "\fBRel\fP* pdfg::RelNode::relation () const\fC [inline]\fP"

.SS "void pdfg::RelNode::relation (\fBRel\fP * rel)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
