.TH "pdfg.pdfgs.CSRToBSRGen" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.pdfgs.CSRToBSRGen
.SH SYNOPSIS
.br
.PP
.PP
Inherits IEGenGraph\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBname\fP='csr_bsr', \fBbsize\fP=8)"
.br
.ti -1c
.RI "def \fBbuild_setup\fP (self)"
.br
.ti -1c
.RI "def \fBbuild_inspector\fP (self)"
.br
.ti -1c
.RI "def \fBbuild_executor\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.pdfgs\&.CSRToBSRGen\&.__init__ ( self,  name = \fC'csr_bsr'\fP,  bsize = \fC8\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def pdfg\&.pdfgs\&.CSRToBSRGen\&.build_executor ( self)"

.SS "def pdfg\&.pdfgs\&.CSRToBSRGen\&.build_inspector ( self)"

.SS "def pdfg\&.pdfgs\&.CSRToBSRGen\&.build_setup ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
