.TH "pdfg::Edge" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::Edge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FlowGraph\&.hpp>\fP
.PP
Inherits \fBpdfg::GraphItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEdge\fP (\fBNode\fP *\fBsource\fP, \fBNode\fP *\fBdest\fP, \fBconst\fP string &\fBlabel\fP='')"
.br
.ti -1c
.RI "\fBEdge\fP (\fBconst\fP \fBEdge\fP &other)"
.br
.ti -1c
.RI "\fBEdge\fP & \fBoperator=\fP (\fBconst\fP \fBEdge\fP &other)"
.br
.ti -1c
.RI "\fBNode\fP * \fBsource\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBdest\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBsource\fP (\fBNode\fP *source)"
.br
.ti -1c
.RI "void \fBdest\fP (\fBNode\fP *dest)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcopy\fP (\fBconst\fP \fBEdge\fP &other)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fB_source\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fB_dest\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, \fBEdge\fP &edge)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::Edge::Edge (\fBNode\fP * source, \fBNode\fP * dest, \fBconst\fP string & label = \fC''\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "pdfg::Edge::Edge (\fBconst\fP \fBEdge\fP & other)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void pdfg::Edge::copy (\fBconst\fP \fBEdge\fP & other)\fC [inline]\fP, \fC [protected]\fP"

.SS "\fBNode\fP* pdfg::Edge::dest () const\fC [inline]\fP"

.SS "void pdfg::Edge::dest (\fBNode\fP * dest)\fC [inline]\fP"

.SS "\fBEdge\fP& pdfg::Edge::operator= (\fBconst\fP \fBEdge\fP & other)\fC [inline]\fP"

.SS "\fBNode\fP* pdfg::Edge::source () const\fC [inline]\fP"

.SS "void pdfg::Edge::source (\fBNode\fP * source)\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, \fBEdge\fP & edge)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* pdfg::Edge::_dest\fC [protected]\fP"

.SS "\fBNode\fP* pdfg::Edge::_source\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
