.TH "pdfg.graph.IterNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.graph.IterNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpdfg\&.graph\&.Node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBlabel\fP='', \fBname\fP='', \fBattrs\fP={})"
.br
.ti -1c
.RI "def \fBrelation\fP (self)"
.br
.ti -1c
.RI "def \fBrelation\fP (self, relation)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.graph\&.IterNode\&.__init__ ( self,  label = \fC''\fP,  name = \fC''\fP,  attrs = \fC{}\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def pdfg\&.graph\&.IterNode\&.relation ( self)"

.SS "def pdfg\&.graph\&.IterNode\&.relation ( self,  relation)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
