.TH "pdfg.graph.StructNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.graph.StructNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpdfg\&.graph\&.DataNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBlabel\fP='', \fBname\fP='', \fBattrs\fP={}, \fBmembers\fP={})"
.br
.ti -1c
.RI "def \fBsuffix\fP (cls)"
.br
.ti -1c
.RI "def \fBmembers\fP (self)"
.br
.ti -1c
.RI "def \fBscalar\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.graph\&.StructNode\&.__init__ ( self,  label = \fC''\fP,  name = \fC''\fP,  attrs = \fC{}\fP,  members = \fC{}\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def pdfg\&.graph\&.StructNode\&.members ( self)"

.SS "def pdfg\&.graph\&.StructNode\&.scalar ( self)"

.PP
Reimplemented from \fBpdfg\&.graph\&.DataNode\fP\&.
.SS "def pdfg\&.graph\&.StructNode\&.suffix ( cls)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
