.TH "pdfg::GraphItem" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::GraphItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FlowGraph\&.hpp>\fP
.PP
Inherited by \fBpdfg::Edge\fP, \fBpdfg::FlowGraph\fP, and \fBpdfg::Node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual string \fBattr\fP (\fBconst\fP string &\fBkey\fP) \fBconst\fP"
.br
.ti -1c
.RI "virtual void \fBattr\fP (\fBconst\fP string &\fBkey\fP, \fBconst\fP string &\fBval\fP)"
.br
.ti -1c
.RI "virtual string \fBlabel\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual void \fBlabel\fP (\fBconst\fP string &label)"
.br
.ti -1c
.RI "virtual void \fBprint_attrs\fP (ostream &os)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fB_label\fP"
.br
.ti -1c
.RI "\fBmap\fP< string, string > \fB_attrs\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual string pdfg::GraphItem::attr (\fBconst\fP string & key) const\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void pdfg::GraphItem::attr (\fBconst\fP string & key, \fBconst\fP string & val)\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual string pdfg::GraphItem::label () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBpdfg::Node\fP\&.
.SS "virtual void pdfg::GraphItem::label (\fBconst\fP string & label)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBpdfg::Node\fP\&.
.SS "virtual void pdfg::GraphItem::print_attrs (ostream & os)\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBmap\fP<string, string> pdfg::GraphItem::_attrs\fC [protected]\fP"

.SS "string pdfg::GraphItem::_label\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
