.TH "pdfg::Condition" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::Condition
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphIL\&.hpp>\fP
.PP
Inherits \fBpdfg::Expr\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCondition\fP (\fBconst\fP \fBConstr\fP &cond, \fBconst\fP \fBExpr\fP &\fBtrue_expr\fP, \fBconst\fP \fBExpr\fP &\fBfalse_expr\fP)"
.br
.ti -1c
.RI "\fBCondition\fP (\fBconst\fP \fBConstr\fP &cond, \fBconst\fP \fBExpr\fP &expr)"
.br
.ti -1c
.RI "\fBConstr\fP \fBcondition\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBExpr\fP \fBtrue_expr\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBExpr\fP \fBfalse_expr\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBconst\fP \fBConstr\fP &cond, \fBconst\fP \fBExpr\fP &\fBtrue_expr\fP, \fBconst\fP \fBExpr\fP &\fBfalse_expr\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBConstr\fP \fB_cond\fP"
.br
.ti -1c
.RI "\fBExpr\fP \fB_true\fP"
.br
.ti -1c
.RI "\fBExpr\fP \fB_false\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::Condition::Condition (\fBconst\fP \fBConstr\fP & cond, \fBconst\fP \fBExpr\fP & true_expr, \fBconst\fP \fBExpr\fP & false_expr)\fC [inline]\fP, \fC [explicit]\fP"

.SS "pdfg::Condition::Condition (\fBconst\fP \fBConstr\fP & cond, \fBconst\fP \fBExpr\fP & expr)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBConstr\fP pdfg::Condition::condition () const\fC [inline]\fP"

.SS "\fBExpr\fP pdfg::Condition::false_expr () const\fC [inline]\fP"

.SS "void pdfg::Condition::init (\fBconst\fP \fBConstr\fP & cond, \fBconst\fP \fBExpr\fP & true_expr, \fBconst\fP \fBExpr\fP & false_expr)\fC [inline]\fP, \fC [protected]\fP"

.SS "\fBExpr\fP pdfg::Condition::true_expr () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBConstr\fP pdfg::Condition::_cond\fC [protected]\fP"

.SS "\fBExpr\fP pdfg::Condition::_false\fC [protected]\fP"

.SS "\fBExpr\fP pdfg::Condition::_true\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
