.TH "pdfg.graph.DataNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.graph.DataNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpdfg\&.graph\&.Node\fP\&.
.PP
Inherited by \fBpdfg\&.graph\&.StructNode\fP, and \fBpdfg\&.graph\&.TempNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBlabel\fP='', \fBname\fP='', \fBattrs\fP={}, \fBcopy\fP=None, \fBdomain\fP='')"
.br
.ti -1c
.RI "def \fBdomain\fP (self)"
.br
.ti -1c
.RI "def \fBdomain\fP (self, domain)"
.br
.ti -1c
.RI "def \fBrange\fP (self)"
.br
.ti -1c
.RI "def \fBrange\fP (self, range)"
.br
.ti -1c
.RI "def \fBsize\fP (self)"
.br
.ti -1c
.RI "def \fBsize\fP (self, size)"
.br
.ti -1c
.RI "def \fBtype\fP (self)"
.br
.ti -1c
.RI "def \fBtype\fP (self, type)"
.br
.ti -1c
.RI "def \fBalloc\fP (self)"
.br
.ti -1c
.RI "def \fBalloc\fP (self, alloc)"
.br
.ti -1c
.RI "def \fBdefval\fP (self)"
.br
.ti -1c
.RI "def \fBdefval\fP (self, defval)"
.br
.ti -1c
.RI "def \fBscalar\fP (self)"
.br
.ti -1c
.RI "def \fBdot\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.graph\&.DataNode\&.__init__ ( self,  label = \fC''\fP,  name = \fC''\fP,  attrs = \fC{}\fP,  copy = \fCNone\fP,  domain = \fC''\fP)"

.PP
Reimplemented from \fBpdfg\&.graph\&.Node\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def pdfg\&.graph\&.DataNode\&.alloc ( self)"

.SS "def pdfg\&.graph\&.DataNode\&.alloc ( self,  alloc)"

.SS "def pdfg\&.graph\&.DataNode\&.defval ( self)"

.SS "def pdfg\&.graph\&.DataNode\&.defval ( self,  defval)"

.SS "def pdfg\&.graph\&.DataNode\&.domain ( self)"

.PP
Reimplemented from \fBpdfg\&.graph\&.Node\fP\&.
.SS "def pdfg\&.graph\&.DataNode\&.domain ( self,  domain)"

.PP
Reimplemented from \fBpdfg\&.graph\&.Node\fP\&.
.SS "def pdfg\&.graph\&.DataNode\&.dot ( self)"

.PP
Reimplemented from \fBpdfg\&.graph\&.Node\fP\&.
.SS "def pdfg\&.graph\&.DataNode\&.range ( self)"

.SS "def pdfg\&.graph\&.DataNode\&.range ( self,  range)"

.SS "def pdfg\&.graph\&.DataNode\&.scalar ( self)"

.PP
Reimplemented in \fBpdfg\&.graph\&.StructNode\fP\&.
.SS "def pdfg\&.graph\&.DataNode\&.size ( self)"

.SS "def pdfg\&.graph\&.DataNode\&.size ( self,  size)"

.SS "def pdfg\&.graph\&.DataNode\&.type ( self)"

.SS "def pdfg\&.graph\&.DataNode\&.type ( self,  type)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
