.TH "pdfg.graph.NodeFactory" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.graph.NodeFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__NodeFactory\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBname\fP)"
.br
.ti -1c
.RI "def \fBget\fP (self, type='', label='', attrs={})"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.graph\&.NodeFactory\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def pdfg\&.graph\&.NodeFactory\&.__getattr__ ( self,  name)"

.SS "def pdfg\&.graph\&.NodeFactory\&.get ( self,  type = \fC''\fP,  label = \fC''\fP,  attrs = \fC{}\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
