.TH "pdfg::Math" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::Math
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphIL\&.hpp>\fP
.PP
Inherits \fBpdfg::Expr\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMath\fP ()"
.br
.ti -1c
.RI "\fBMath\fP (\fBconst\fP \fBExpr\fP &\fBlhs\fP, \fBconst\fP \fBExpr\fP &\fBrhs\fP, \fBconst\fP string &\fBoper\fP)"
.br
.ti -1c
.RI "\fBMath\fP (\fBconst\fP \fBMath\fP &other)"
.br
.ti -1c
.RI "\fBMath\fP (\fBconst\fP \fBExpr\fP &expr)"
.br
.ti -1c
.RI "\fBMath\fP & \fBoperator=\fP (\fBconst\fP \fBExpr\fP &expr) override"
.br
.ti -1c
.RI "\fBMath\fP \fBoperator()\fP (\fBconst\fP \fBExpr\fP &expr)"
.br
.ti -1c
.RI "\fBExpr\fP \fBlhs\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBExpr\fP \fBrhs\fP () \fBconst\fP"
.br
.ti -1c
.RI "string \fBoper\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcopy\fP (\fBconst\fP \fBMath\fP &other)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBExpr\fP \fB_lhs\fP"
.br
.ti -1c
.RI "\fBExpr\fP \fB_rhs\fP"
.br
.ti -1c
.RI "string \fB_oper\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, \fBMath\fP &math)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::Math::Math ()\fC [inline]\fP, \fC [explicit]\fP"

.SS "pdfg::Math::Math (\fBconst\fP \fBExpr\fP & lhs, \fBconst\fP \fBExpr\fP & rhs, \fBconst\fP string & oper)\fC [inline]\fP, \fC [explicit]\fP"

.SS "pdfg::Math::Math (\fBconst\fP \fBMath\fP & other)\fC [inline]\fP"

.SS "pdfg::Math::Math (\fBconst\fP \fBExpr\fP & expr)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void pdfg::Math::copy (\fBconst\fP \fBMath\fP & other)\fC [inline]\fP, \fC [protected]\fP"

.SS "\fBExpr\fP pdfg::Math::lhs () const\fC [inline]\fP"

.SS "string pdfg::Math::oper () const\fC [inline]\fP"

.SS "\fBMath\fP pdfg::Math::operator() (\fBconst\fP \fBExpr\fP & expr)\fC [inline]\fP"

.SS "\fBMath\fP& pdfg::Math::operator= (\fBconst\fP \fBExpr\fP & expr)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::Expr\fP\&.
.SS "\fBExpr\fP pdfg::Math::rhs () const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "istream& operator>> (istream & is, \fBMath\fP & math)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBExpr\fP pdfg::Math::_lhs\fC [protected]\fP"

.SS "string pdfg::Math::_oper\fC [protected]\fP"

.SS "\fBExpr\fP pdfg::Math::_rhs\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
