.TH "pdfg::TransformVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::TransformVisitor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Visitor\&.hpp>\fP
.PP
Inherits \fBpdfg::DFGVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransformVisitor\fP (\fBconst\fP \fBmap\fP< string, \fBConst\fP > &constants={}, initializer_list< string > tile_iters={}, initializer_list< unsigned > tile_sizes={}, initializer_list< initializer_list< string > > fuse_names={}, bool reduce_precision=false)"
.br
.ti -1c
.RI "virtual void \fBsetup\fP (\fBFlowGraph\fP *graph)"
.br
.ti -1c
.RI "virtual void \fBfinish\fP (\fBFlowGraph\fP *graph)"
.br
.ti -1c
.RI "\fBFlowGraph\fP * \fBbest\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBgenerate\fP ()"
.br
.ti -1c
.RI "void \fBprocess\fP (\fBFlowGraph\fP *variant)"
.br
.ti -1c
.RI "void \fBcompare\fP (\fBFlowGraph\fP *variant)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBFlowGraph\fP * \fB_best\fP"
.br
.ti -1c
.RI "bool \fB_reduce_precision\fP"
.br
.ti -1c
.RI "\fBmap\fP< string, \fBConst\fP > \fB_constants\fP"
.br
.ti -1c
.RI "vector< string > \fB_tile_iters\fP"
.br
.ti -1c
.RI "vector< unsigned > \fB_tile_sizes\fP"
.br
.ti -1c
.RI "vector< vector< string > > \fB_fuse_names\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::TransformVisitor::TransformVisitor (\fBconst\fP \fBmap\fP< string, \fBConst\fP > & constants = \fC{}\fP, initializer_list< string > tile_iters = \fC{}\fP, initializer_list< unsigned > tile_sizes = \fC{}\fP, initializer_list< initializer_list< string > > fuse_names = \fC{}\fP, bool reduce_precision = \fCfalse\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBFlowGraph\fP* pdfg::TransformVisitor::best ()\fC [inline]\fP"

.SS "void pdfg::TransformVisitor::compare (\fBFlowGraph\fP * variant)\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual void pdfg::TransformVisitor::finish (\fBFlowGraph\fP * graph)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::DFGVisitor\fP\&.
.SS "void pdfg::TransformVisitor::generate ()\fC [inline]\fP, \fC [protected]\fP"

.SS "void pdfg::TransformVisitor::process (\fBFlowGraph\fP * variant)\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual void pdfg::TransformVisitor::setup (\fBFlowGraph\fP * graph)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::DFGVisitor\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFlowGraph\fP* pdfg::TransformVisitor::_best\fC [protected]\fP"

.SS "\fBmap\fP<string, \fBConst\fP> pdfg::TransformVisitor::_constants\fC [protected]\fP"

.SS "vector<vector<string> > pdfg::TransformVisitor::_fuse_names\fC [protected]\fP"

.SS "bool pdfg::TransformVisitor::_reduce_precision\fC [protected]\fP"

.SS "vector<string> pdfg::TransformVisitor::_tile_iters\fC [protected]\fP"

.SS "vector<unsigned> pdfg::TransformVisitor::_tile_sizes\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
