.TH "pdfg::CudaGenVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::CudaGenVisitor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Visitor\&.hpp>\fP
.PP
Inherits \fBpdfg::CodeGenVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCudaGenVisitor\fP (\fBconst\fP string &\fBpath\fP='', \fBconst\fP string &lang='CU', unsigned niters=15)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "string \fBrestrict\fP () \fBconst\fP override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::CudaGenVisitor::CudaGenVisitor (\fBconst\fP string & path = \fC''\fP, \fBconst\fP string & lang = \fC'CU'\fP, unsigned niters = \fC15\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void pdfg::CudaGenVisitor::init ()\fC [inline]\fP, \fC [protected]\fP"

.SS "string pdfg::CudaGenVisitor::restrict () const\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::CodeGenVisitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
