.TH "pdfg.graph.TempNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.graph.TempNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpdfg\&.graph\&.DataNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBlabel\fP='', \fBname\fP='', \fBattrs\fP={})"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.graph\&.TempNode\&.__init__ ( self,  label = \fC''\fP,  name = \fC''\fP,  attrs = \fC{}\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
