.TH "pdfg::OmpGenVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::OmpGenVisitor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Visitor\&.hpp>\fP
.PP
Inherits \fBpdfg::CodeGenVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOmpGenVisitor\fP (\fBconst\fP string &\fBpath\fP='', \fBconst\fP string &lang='C', unsigned niters=15)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBallocate\fP (\fBDataNode\fP *node) override"
.br
.ti -1c
.RI "void \fBcodegen\fP (\fBCompNode\fP *node, vector< string > &names, \fBmap\fP< string, vector< string >> &statements, \fBmap\fP< string, vector< string >> &guards, \fBmap\fP< string, vector< string >> &schedules) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::OmpGenVisitor::OmpGenVisitor (\fBconst\fP string & path = \fC''\fP, \fBconst\fP string & lang = \fC'C'\fP, unsigned niters = \fC15\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void pdfg::OmpGenVisitor::allocate (\fBDataNode\fP * node)\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::CodeGenVisitor\fP\&.
.SS "void pdfg::OmpGenVisitor::codegen (\fBCompNode\fP * node, vector< string > & names, \fBmap\fP< string, vector< string >> & statements, \fBmap\fP< string, vector< string >> & guards, \fBmap\fP< string, vector< string >> & schedules)\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::CodeGenVisitor\fP\&.
.SS "void pdfg::OmpGenVisitor::init ()\fC [inline]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
