.TH "pdfg::MemTableEntry" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::MemTableEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Visitor\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBsize\fP"
.br
.ti -1c
.RI "unsigned \fBprev_size\fP"
.br
.ti -1c
.RI "bool \fBactive\fP"
.br
.ti -1c
.RI "bool \fBresized\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMemAllocVisitor\fP 
.SH "Member Data Documentation"
.PP 
.SS "bool pdfg::MemTableEntry::active"

.SS "unsigned pdfg::MemTableEntry::prev_size"

.SS "bool pdfg::MemTableEntry::resized"

.SS "unsigned pdfg::MemTableEntry::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
