.TH "pdfg::GroupVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::GroupVisitor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Visitor\&.hpp>\fP
.PP
Inherits \fBpdfg::DFSVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGroupVisitor\fP (\fBconst\fP \fBmap\fP< string, \fBConst\fP > &constants={})"
.br
.ti -1c
.RI "void \fBenter\fP (\fBCompNode\fP *node) override"
.br
.ti -1c
.RI "void \fBnewGroup\fP ()"
.br
.ti -1c
.RI "void \fBfinish\fP (\fBFlowGraph\fP *graph) override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP unsigned \fB_cache_size\fP = 288435456"
.br
.ti -1c
.RI "int \fB_ngroups\fP"
.br
.ti -1c
.RI "unordered_map< string, int > \fB_constants\fP"
.br
.ti -1c
.RI "vector< unsigned > \fB_read_bytes\fP"
.br
.ti -1c
.RI "vector< unsigned > \fB_write_bytes\fP"
.br
.ti -1c
.RI "vector< unsigned > \fB_alloc_bytes\fP"
.br
.ti -1c
.RI "vector< unsigned > \fB_flop_counts\fP"
.br
.ti -1c
.RI "vector< vector< \fBCompNode\fP * > > \fB_groups\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGroupVisitor\fP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::GroupVisitor::GroupVisitor (\fBconst\fP \fBmap\fP< string, \fBConst\fP > & constants = \fC{}\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void pdfg::GroupVisitor::enter (\fBCompNode\fP * node)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::DFGVisitor\fP\&.
.SS "void pdfg::GroupVisitor::finish (\fBFlowGraph\fP * graph)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::DFGVisitor\fP\&.
.SS "void pdfg::GroupVisitor::newGroup ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "vector<unsigned> pdfg::GroupVisitor::_alloc_bytes\fC [protected]\fP"

.SS "\fBconst\fP unsigned pdfg::GroupVisitor::_cache_size = 288435456\fC [protected]\fP"

.SS "unordered_map<string, int> pdfg::GroupVisitor::_constants\fC [protected]\fP"

.SS "vector<unsigned> pdfg::GroupVisitor::_flop_counts\fC [protected]\fP"

.SS "vector<vector<\fBCompNode\fP*> > pdfg::GroupVisitor::_groups\fC [protected]\fP"

.SS "int pdfg::GroupVisitor::_ngroups\fC [protected]\fP"

.SS "vector<unsigned> pdfg::GroupVisitor::_read_bytes\fC [protected]\fP"

.SS "vector<unsigned> pdfg::GroupVisitor::_write_bytes\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
