.TH "pdfg::DataNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::DataNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FlowGraph\&.hpp>\fP
.PP
Inherits \fBpdfg::Node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataNode\fP (\fBExpr\fP *access, \fBconst\fP string &\fBlabel\fP='', \fBExpr\fP *\fBsize\fP=nullptr, \fBconst\fP string &\fBtype\fP='real', const string &\fBdefval\fP='', \fBconst\fP \fBMemAlloc\fP &\fBalloc\fP=\fBDYNAMIC\fP)"
.br
.ti -1c
.RI "\fB~DataNode\fP ()"
.br
.ti -1c
.RI "\fBDataNode\fP (\fBconst\fP \fBDataNode\fP &other)"
.br
.ti -1c
.RI "\fBDataNode\fP & \fBoperator=\fP (\fBconst\fP \fBDataNode\fP &other)"
.br
.ti -1c
.RI "\fBExpr\fP * \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBsize\fP (\fBExpr\fP *size)"
.br
.ti -1c
.RI "string \fBdatatype\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBdatatype\fP (\fBconst\fP string &\fBtype\fP)"
.br
.ti -1c
.RI "bool \fBis_float\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBis_int\fP () \fBconst\fP"
.br
.ti -1c
.RI "unsigned \fBtypesize\fP () \fBconst\fP"
.br
.ti -1c
.RI "string \fBdefval\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBdefval\fP (\fBconst\fP string &\fBval\fP)"
.br
.ti -1c
.RI "\fBMemAlloc\fP \fBalloc\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBalloc\fP (\fBconst\fP \fBMemAlloc\fP &alloc)"
.br
.ti -1c
.RI "bool \fBis_scalar\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcopy\fP (\fBconst\fP \fBDataNode\fP &other)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBExpr\fP * \fB_size\fP"
.br
.ti -1c
.RI "string \fB_datatype\fP"
.br
.ti -1c
.RI "string \fB_defval\fP"
.br
.ti -1c
.RI "\fBMemAlloc\fP \fB_alloc\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, \fBDataNode\fP &node)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::DataNode::DataNode (\fBExpr\fP * access, \fBconst\fP string & label = \fC''\fP, \fBExpr\fP * size = \fCnullptr\fP, \fBconst\fP string & type = \fC'real'\fP, \fBconst\fP string & defval = \fC''\fP, \fBconst\fP \fBMemAlloc\fP & alloc = \fC\fBDYNAMIC\fP\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "pdfg::DataNode::~DataNode ()\fC [inline]\fP"

.SS "pdfg::DataNode::DataNode (\fBconst\fP \fBDataNode\fP & other)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBMemAlloc\fP pdfg::DataNode::alloc () const\fC [inline]\fP"

.SS "void pdfg::DataNode::alloc (\fBconst\fP \fBMemAlloc\fP & alloc)\fC [inline]\fP"

.SS "void pdfg::DataNode::copy (\fBconst\fP \fBDataNode\fP & other)\fC [inline]\fP, \fC [protected]\fP"

.SS "string pdfg::DataNode::datatype () const\fC [inline]\fP"

.SS "void pdfg::DataNode::datatype (\fBconst\fP string & type)\fC [inline]\fP"

.SS "string pdfg::DataNode::defval () const\fC [inline]\fP"

.SS "void pdfg::DataNode::defval (\fBconst\fP string & val)\fC [inline]\fP"

.SS "bool pdfg::DataNode::is_float () const\fC [inline]\fP"

.SS "bool pdfg::DataNode::is_int () const\fC [inline]\fP"

.SS "bool pdfg::DataNode::is_scalar () const\fC [inline]\fP"

.SS "\fBDataNode\fP& pdfg::DataNode::operator= (\fBconst\fP \fBDataNode\fP & other)\fC [inline]\fP"

.SS "\fBExpr\fP* pdfg::DataNode::size () const\fC [inline]\fP"

.SS "void pdfg::DataNode::size (\fBExpr\fP * size)\fC [inline]\fP"

.SS "unsigned pdfg::DataNode::typesize () const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, \fBDataNode\fP & node)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMemAlloc\fP pdfg::DataNode::_alloc\fC [protected]\fP"

.SS "string pdfg::DataNode::_datatype\fC [protected]\fP"

.SS "string pdfg::DataNode::_defval\fC [protected]\fP"

.SS "\fBExpr\fP* pdfg::DataNode::_size\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
