.TH "pdfg::Rel" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::Rel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphIL\&.hpp>\fP
.PP
Inherits \fBpdfg::Expr\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRel\fP (\fBconst\fP string &\fBname\fP='', \fBconst\fP vector< \fBIter\fP > &srcIters={}, \fBconst\fP vector< \fBIter\fP > &destIters={})"
.br
.ti -1c
.RI "\fBRel\fP (\fBconst\fP string &\fBname\fP, initializer_list< \fBIter\fP > srcIters, initializer_list< \fBIter\fP > destIters)"
.br
.ti -1c
.RI "\fBRel\fP (\fBconst\fP string &\fBname\fP, \fBconst\fP \fBSpace\fP &src, \fBconst\fP \fBSpace\fP &\fBdest\fP)"
.br
.ti -1c
.RI "\fBRel\fP (\fBconst\fP \fBRel\fP &other)"
.br
.ti -1c
.RI "\fBRel\fP & \fBoperator=\fP (\fBconst\fP \fBExpr\fP &expr) override"
.br
.ti -1c
.RI "string \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBname\fP (\fBconst\fP string name)"
.br
.ti -1c
.RI "\fBSpace\fP \fBsource\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBsource\fP (\fBconst\fP \fBSpace\fP &src)"
.br
.ti -1c
.RI "\fBSpace\fP \fBdest\fP () \fBconst\fP"
.br
.ti -1c
.RI "void \fBdest\fP (\fBconst\fP \fBSpace\fP &dst)"
.br
.ti -1c
.RI "string \fBto_iset\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcopy\fP (\fBconst\fP \fBRel\fP &other)"
.br
.ti -1c
.RI "void \fBinit\fP (\fBconst\fP string &\fBname\fP, initializer_list< \fBIter\fP > srcIters, initializer_list< \fBIter\fP > destIters)"
.br
.ti -1c
.RI "void \fBinit\fP (\fBconst\fP string &\fBname\fP, \fBconst\fP vector< \fBIter\fP > &srcIters, \fBconst\fP vector< \fBIter\fP > &destIters)"
.br
.ti -1c
.RI "void \fBinit\fP (\fBconst\fP string &\fBname\fP, \fBconst\fP \fBSpace\fP &src, \fBconst\fP \fBSpace\fP &\fBdest\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fB_name\fP"
.br
.ti -1c
.RI "\fBSpace\fP \fB_src\fP"
.br
.ti -1c
.RI "\fBSpace\fP \fB_dest\fP"
.br
.ti -1c
.RI "\fBmap\fP< string, string > \fB_itermap\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::Rel::Rel (\fBconst\fP string & name = \fC''\fP, \fBconst\fP vector< \fBIter\fP > & srcIters = \fC{}\fP, \fBconst\fP vector< \fBIter\fP > & destIters = \fC{}\fP)\fC [inline]\fP, \fC [explicit]\fP"

.SS "pdfg::Rel::Rel (\fBconst\fP string & name, initializer_list< \fBIter\fP > srcIters, initializer_list< \fBIter\fP > destIters)\fC [inline]\fP"

.SS "pdfg::Rel::Rel (\fBconst\fP string & name, \fBconst\fP \fBSpace\fP & src, \fBconst\fP \fBSpace\fP & dest)\fC [inline]\fP"

.SS "pdfg::Rel::Rel (\fBconst\fP \fBRel\fP & other)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void pdfg::Rel::copy (\fBconst\fP \fBRel\fP & other)\fC [inline]\fP, \fC [protected]\fP"

.SS "\fBSpace\fP pdfg::Rel::dest () const\fC [inline]\fP"

.SS "void pdfg::Rel::dest (\fBconst\fP \fBSpace\fP & dst)\fC [inline]\fP"

.SS "void pdfg::Rel::init (\fBconst\fP string & name, \fBconst\fP \fBSpace\fP & src, \fBconst\fP \fBSpace\fP & dest)\fC [inline]\fP, \fC [protected]\fP"

.SS "void pdfg::Rel::init (\fBconst\fP string & name, \fBconst\fP vector< \fBIter\fP > & srcIters, \fBconst\fP vector< \fBIter\fP > & destIters)\fC [inline]\fP, \fC [protected]\fP"

.SS "void pdfg::Rel::init (\fBconst\fP string & name, initializer_list< \fBIter\fP > srcIters, initializer_list< \fBIter\fP > destIters)\fC [inline]\fP, \fC [protected]\fP"

.SS "string pdfg::Rel::name () const\fC [inline]\fP"

.SS "void pdfg::Rel::name (\fBconst\fP string name)\fC [inline]\fP"

.SS "\fBRel\fP& pdfg::Rel::operator= (\fBconst\fP \fBExpr\fP & expr)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::Expr\fP\&.
.SS "\fBSpace\fP pdfg::Rel::source () const\fC [inline]\fP"

.SS "void pdfg::Rel::source (\fBconst\fP \fBSpace\fP & src)\fC [inline]\fP"

.SS "string pdfg::Rel::to_iset () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBSpace\fP pdfg::Rel::_dest\fC [protected]\fP"

.SS "\fBmap\fP<string, string> pdfg::Rel::_itermap\fC [protected]\fP"

.SS "string pdfg::Rel::_name\fC [protected]\fP"

.SS "\fBSpace\fP pdfg::Rel::_src\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
