.TH "pdfg::DFSVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::DFSVisitor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Visitor\&.hpp>\fP
.PP
Inherits \fBpdfg::DFGVisitor\fP\&.
.PP
Inherited by \fBpdfg::GroupVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwalk\fP (\fBFlowGraph\fP *graph)"
.br
.ti -1c
.RI "virtual void \fBvisit\fP (\fBNode\fP *node)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unordered_map< string, bool > \fB_visited\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void pdfg::DFSVisitor::visit (\fBNode\fP * node)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::DFGVisitor\fP\&.
.SS "virtual void pdfg::DFSVisitor::walk (\fBFlowGraph\fP * graph)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBpdfg::DFGVisitor\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unordered_map<string, bool> pdfg::DFSVisitor::_visited\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
