.TH "pdfg::DataReduceVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg::DataReduceVisitor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Visitor\&.hpp>\fP
.PP
Inherits \fBpdfg::DFGVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataReduceVisitor\fP ()"
.br
.ti -1c
.RI "void \fBenter\fP (\fBDataNode\fP *node) override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddIter\fP (\fBconst\fP \fBIter\fP &iter, \fBconst\fP vector< \fBConstr\fP > &constraints, \fBSpace\fP &newspace)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pdfg::DataReduceVisitor::DataReduceVisitor ()\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void pdfg::DataReduceVisitor::addIter (\fBconst\fP \fBIter\fP & iter, \fBconst\fP vector< \fBConstr\fP > & constraints, \fBSpace\fP & newspace)\fC [inline]\fP, \fC [protected]\fP"

.SS "void pdfg::DataReduceVisitor::enter (\fBDataNode\fP * node)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"
producer->comp()->tiled();
.PP
Reimplemented from \fBpdfg::DFGVisitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
