.TH "pdfg.pdfgs.PDFGParser" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdfg.pdfgs.PDFGParser
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, file='', \fBname\fP='')"
.br
.ti -1c
.RI "def \fBparse\fP (self, spec='')"
.br
.ti -1c
.RI "def \fBassign\fP (self, line, \fBpos\fP)"
.br
.ti -1c
.RI "def \fBconstants\fP (self, constlist)"
.br
.ti -1c
.RI "def \fBrelation\fP (self, \fBname\fP, relstr)"
.br
.ti -1c
.RI "def \fBexpression\fP (self, line)"
.br
.ti -1c
.RI "def \fBfunction\fP (self, \fBname\fP, args, \fBrhs\fP)"
.br
.ti -1c
.RI "def \fBupdaterefs\fP (self, stmt)"
.br
.ti -1c
.RI "def \fBstatement\fP (self, \fBname\fP, stmt)"
.br
.ti -1c
.RI "def \fBreads\fP (self, node, expr)"
.br
.ti -1c
.RI "def \fBwrites\fP (self, node, expr)"
.br
.ti -1c
.RI "def \fBaccesses\fP (self, expr, alist)"
.br
.ti -1c
.RI "def \fBdatanodes\fP (self, snode, \fBaccesses\fP)"
.br
.ti -1c
.RI "def \fBbound\fP (self, bound)"
.br
.ti -1c
.RI "def \fBoperators\fP (self)"
.br
.ti -1c
.RI "def \fBisoper\fP (self, chr)"
.br
.ti -1c
.RI "def \fBisnumeric\fP (self, expr)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def pdfg\&.pdfgs\&.PDFGParser\&.__init__ ( self,  file = \fC''\fP,  name = \fC''\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def pdfg\&.pdfgs\&.PDFGParser\&.accesses ( self,  expr,  alist)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.assign ( self,  line,  pos)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.bound ( self,  bound)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.constants ( self,  constlist)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.datanodes ( self,  snode,  accesses)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.expression ( self,  line)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.function ( self,  name,  args,  rhs)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.isnumeric ( self,  expr)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.isoper ( self,  chr)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.operators ( self)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.parse ( self,  spec = \fC''\fP)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.reads ( self,  node,  expr)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.relation ( self,  name,  relstr)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.statement ( self,  name,  stmt)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.updaterefs ( self,  stmt)"

.SS "def pdfg\&.pdfgs\&.PDFGParser\&.writes ( self,  node,  expr)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
