.TH "perfmodel" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
perfmodel
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBusage\fP ()"
.br
.ti -1c
.RI "def \fBparse_dom\fP (\fBdomain\fP)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def perfmodel\&.main ()"

.SS "def perfmodel\&.parse_dom ( domain)"

.SS "def perfmodel\&.usage ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
