.TH "lib/isl/include/isl/polynomial_type.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/polynomial_type.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBisl_qpolynomial\fP \fBisl_qpolynomial\fP"
.br
.ti -1c
.RI "typedef struct \fBisl_term\fP \fBisl_term\fP"
.br
.ti -1c
.RI "typedef struct \fBisl_pw_qpolynomial\fP \fBisl_pw_qpolynomial\fP"
.br
.ti -1c
.RI "typedef struct \fBisl_qpolynomial_fold\fP \fBisl_qpolynomial_fold\fP"
.br
.ti -1c
.RI "typedef struct \fBisl_pw_qpolynomial_fold\fP \fBisl_pw_qpolynomial_fold\fP"
.br
.ti -1c
.RI "typedef struct \fBisl_union_pw_qpolynomial\fP \fBisl_union_pw_qpolynomial\fP"
.br
.ti -1c
.RI "typedef struct \fBisl_union_pw_qpolynomial_fold\fP \fBisl_union_pw_qpolynomial_fold\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBisl_fold\fP { \fBisl_fold_min\fP, \fBisl_fold_max\fP, \fBisl_fold_list\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "struct \fB__isl_export\fP \fBisl_pw_qpolynomial\fP"

.SS "typedef struct \fBisl_pw_qpolynomial_fold\fP \fBisl_pw_qpolynomial_fold\fP"

.SS "typedef struct \fBisl_qpolynomial\fP \fBisl_qpolynomial\fP"

.SS "typedef struct \fBisl_qpolynomial_fold\fP \fBisl_qpolynomial_fold\fP"

.SS "typedef struct \fBisl_term\fP \fBisl_term\fP"

.SS "struct \fB__isl_export\fP \fBisl_union_pw_qpolynomial\fP"

.SS "typedef struct \fBisl_union_pw_qpolynomial_fold\fP \fBisl_union_pw_qpolynomial_fold\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBisl_fold\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIisl_fold_min \fP\fP
.TP
\fB\fIisl_fold_max \fP\fP
.TP
\fB\fIisl_fold_list \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
