.TH "lib/isl/polyhedron_sample.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/polyhedron_sample.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <isl_map_private\&.h>\fP
.br
\fC#include 'isl_sample\&.h'\fP
.br
\fC#include <isl/vec\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
