.TH "powers" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
powers
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmp\-impl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmp_ptr\fP \fBp\fP"
.br
.ti -1c
.RI "\fBmp_size_t\fP \fBn\fP"
.br
.ti -1c
.RI "\fBmp_size_t\fP \fBshift\fP"
.br
.ti -1c
.RI "size_t \fBdigits_in_base\fP"
.br
.ti -1c
.RI "int \fBbase\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int powers::base"

.SS "size_t powers::digits_in_base"

.SS "\fBmp_size_t\fP powers::n"

.SS "\fBmp_ptr\fP powers::p"

.SS "\fBmp_size_t\fP powers::shift"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
