.TH "lib/chill/omega/omega_lib/src/pres_conj.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/src/pres_conj.cc
.SH SYNOPSIS
.br
.PP
\fC#include <omega/omega_core/oc\&.h>\fP
.br
\fC#include <omega/pres_conj\&.h>\fP
.br
\fC#include <omega/pres_cmpr\&.h>\fP
.br
\fC#include <omega/Relation\&.h>\fP
.br
\fC#include <omega/omega_i\&.h>\fP
.br
\fC#include <set>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBomega::new_WC\fP (Conjunct *nc, Problem *)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBomega::get_var_name\fP (unsigned int \fBcol\fP, void *void_conj)"
.br
.ti -1c
.RI "void \fBomega::internal_copy_conjunct\fP (Conjunct *to, Conjunct *fr)"
.br
.ti -1c
.RI "void \fBomega::copy_conj_header\fP (Conjunct *to, Conjunct *fr)"
.br
.ti -1c
.RI "Conjunct * \fBomega::_merge_conjs\fP (Conjunct *conj1, Conjunct *conj2, Merge_Action action, Rel_Body *body)"
.br
.ti -1c
.RI "int \fBomega::simplify_conj\fP (Conjunct *conj, int ver_sim, int simplificationEffort, int color)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBomega::NR_CONJUNCTS\fP"
.br
.ti -1c
.RI "int \fBomega::MAX_CONJUNCTS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
