.TH "lib/chill/omega/omega_lib/include/omega/pres_quant.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include/omega/pres_quant.h
.SH SYNOPSIS
.br
.PP
\fC#include <omega/pres_decl\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::F_Exists\fP"
.br
.RI "Existential qualifier\&. "
.ti -1c
.RI "class \fBomega::F_Forall\fP"
.br
.RI "Universal qualifier\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
