.TH "lib/chill/omega/omega_lib/include/omega/pres_conj.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include/omega/pres_conj.h
.SH SYNOPSIS
.br
.PP
\fC#include <limits\&.h>\fP
.br
\fC#include <omega/pres_decl\&.h>\fP
.br
\fC#include <omega/pres_logic\&.h>\fP
.br
\fC#include <omega/pres_cnstr\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::Conjunct\fP"
.br
.RI "\fBConjunct\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBomega::copy_column\fP (Problem *tp, int to_col, Problem *fp, int fr_col, int start_EQ, int start_GEQ)"
.br
.ti -1c
.RI "void \fBomega::zero_column\fP (Problem *tp, int to_col, int start_EQ, int start_GEQ, int no_EQs, int no_GEQs)"
.br
.ti -1c
.RI "Conjunct * \fBomega::merge_conjs\fP (Conjunct *conj1, Conjunct *conj2, Merge_Action action, Rel_Body *body=0)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP int \fBomega::CantBeNegated\fP = INT_MAX\-10"
.br
.ti -1c
.RI "\fBconst\fP int \fBomega::AvoidNegating\fP = INT_MAX\-11"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
