.TH "lib/chill/omega/omega_lib/include/omega/pres_var.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include/omega/pres_var.h
.SH SYNOPSIS
.br
.PP
\fC#include <omega/pres_gen\&.h>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::Var_Decl\fP"
.br
.ti -1c
.RI "class \fBomega::Global_Input_Output_Tuple\fP"
.br
.ti -1c
.RI "class \fBomega::Global_Var_Decl\fP"
.br
.RI "Abstract data type for Global Variable declarations\&. "
.ti -1c
.RI "class \fBomega::Coef_Var_Decl\fP"
.br
.ti -1c
.RI "class \fBomega::Free_Var_Decl\fP"
.br
.RI "Named global variable\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBomega::Global_Kind\fP { \fBomega::Free_Var\fP, \fBomega::Coef_Var\fP, \fBomega::Bomega_Var\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBomega::rm_variable\fP (Variable_ID_Tuple &vl, Variable_ID v)"
.br
.ti -1c
.RI "void \fBomega::reset_remap_field\fP (Sequence< Variable_ID > &\fBS\fP)"
.br
.ti -1c
.RI "void \fBomega::reset_remap_field\fP (Sequence< Variable_ID > &\fBS\fP, int var_no)"
.br
.ti -1c
.RI "void \fBomega::reset_remap_field\fP (Variable_ID v)"
.br
.ti -1c
.RI "void \fBomega::reset_remap_field\fP (Variable_ID_Tuple &\fBS\fP)"
.br
.ti -1c
.RI "void \fBomega::reset_remap_field\fP (Variable_ID_Tuple &\fBS\fP, int var_no)"
.br
.ti -1c
.RI "Variable_ID \fBomega::input_var\fP (int nth)"
.br
.ti -1c
.RI "Variable_ID \fBomega::output_var\fP (int nth)"
.br
.ti -1c
.RI "Variable_ID \fBomega::set_var\fP (int nth)"
.br
.ti -1c
.RI "void \fBomega::copy_var_decls\fP (Variable_ID_Tuple &new_vl, Variable_ID_Tuple &vl)"
.br
.RI "Copy variable declarations except global var-s due to uniqueness\&. "
.ti -1c
.RI "void \fBomega::free_var_decls\fP (Variable_ID_Tuple &vl)"
.br
.RI "Destroy variable declarations except global var-s\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBomega::wildCardInstanceNumber\fP"
.br
.RI "Counter for the wild card instance number, reused in different scope\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
