.TH "lib/chill/omega/omega_lib/include/omega/pres_dnf.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include/omega/pres_dnf.h
.SH SYNOPSIS
.br
.PP
\fC#include <omega/pres_gen\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::DNF\fP"
.br
.RI "Disjunctive Normal Form -- list of Conjuncts\&. "
.ti -1c
.RI "class \fBomega::DNF_Iterator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "DNF * \fBomega::conj_and_not_dnf\fP (Conjunct *pos_conj, DNF *neg_conjs, bool weak=false)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
