.TH "lib/chill/omega/omega_lib/include/omega/pres_form.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include/omega/pres_form.h
.SH SYNOPSIS
.br
.PP
\fC#include <omega/pres_gen\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::Formula\fP"
.br
.RI "Presburger \fBFormula\fP base class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBomega::Node_Type\fP { \fBomega::Op_Relation\fP, \fBomega::Op_Not\fP, \fBomega::Op_And\fP, \fBomega::Op_Or\fP, \fBomega::Op_Conjunct\fP, \fBomega::Op_Forall\fP, \fBomega::Op_Exists\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
