.TH "lib/chill/omega/omega_lib/include/omega/pres_logic.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include/omega/pres_logic.h
.SH SYNOPSIS
.br
.PP
\fC#include <omega/pres_form\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::F_And\fP"
.br
.RI "Represents the logical conjunction of its children nodes\&. "
.ti -1c
.RI "class \fBomega::F_Or\fP"
.br
.RI "Represents the logical disjunction of its children nodes\&. "
.ti -1c
.RI "class \fBomega::F_Not\fP"
.br
.RI "Represents the logical negation of its single child node\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
