.TH "lib/chill/omega/omega_lib/src/pres_col.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/src/pres_col.cc
.SH SYNOPSIS
.br
.PP
\fC#include <omega/pres_conj\&.h>\fP
.br
\fC#include <omega/RelBody\&.h>\fP
.br
\fC#include <omega/omega_i\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBomega::copy_column\fP (Problem *tp, int to_col, Problem *fp, int fr_col, int start_EQ, int start_GEQ)"
.br
.ti -1c
.RI "void \fBomega::zero_column\fP (Problem *tp, int to_col, int start_EQ, int start_GEQ, int no_EQs, int no_GEQs)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
