.TH "lib/chill/omega/omega_lib/include/omega/pres_subs.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include/omega/pres_subs.h
.SH SYNOPSIS
.br
.PP
\fC#include <omega/pres_gen\&.h>\fP
.br
\fC#include <omega/Relation\&.h>\fP
.br
\fC#include <omega/pres_conj\&.h>\fP
.br
\fC#include <omega/pres_cnstr\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::Substitutions\fP"
.br
.ti -1c
.RI "class \fBomega::Sub_Handle\fP"
.br
.ti -1c
.RI "class \fBomega::Sub_Iterator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
