.TH "lib/chill/omega/omega_lib/include/omega/pres_cnstr.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/include/omega/pres_cnstr.h
.SH SYNOPSIS
.br
.PP
\fC#include <omega/pres_var\&.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::Constraint_Handle\fP"
.br
.ti -1c
.RI "class \fBomega::GEQ_Handle\fP"
.br
.RI "Handle to access GEQ constraints\&. "
.ti -1c
.RI "class \fBomega::EQ_Handle\fP"
.br
.RI "Handle to access EQ constraints\&. "
.ti -1c
.RI "class \fBomega::Constraint_Iterator\fP"
.br
.ti -1c
.RI "class \fBomega::EQ_Iterator\fP"
.br
.ti -1c
.RI "class \fBomega::GEQ_Iterator\fP"
.br
.ti -1c
.RI "struct \fBomega::Variable_Info\fP"
.br
.ti -1c
.RI "class \fBomega::Constr_Vars_Iter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBomega::copy_constraint\fP (Constraint_Handle H, \fBconst\fP Constraint_Handle initial)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
