.TH "src/util/Profiler.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/Profiler.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <sys/time\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProfiler\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMICRO\fP   1\fBe\fP\-6"
.br
.ti -1c
.RI "#define \fBNULL\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MICRO   1\fBe\fP\-6"

.SS "#define NULL   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
