.TH "lib/chill/omega/omega_lib/src/reach.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/omega_lib/src/reach.cc
.SH SYNOPSIS
.br
.PP
\fC#include <omega\&.h>\fP
.br
\fC#include <omega/Relations\&.h>\fP
.br
\fC#include <basic/Dynamic_Array\&.h>\fP
.br
\fC#include <omega/reach\&.h>\fP
.br
\fC#include '\&.\&./\&.\&./\&.\&./chill_io\&.hh'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDUMP_INITIAL\fP   1"
.br
.ti -1c
.RI "#define \fBDUMP_CLOSED\fP   1"
.br
.ti -1c
.RI "#define \fBDUMP_INITIAL\fP   1"
.br
.ti -1c
.RI "#define \fBDUMP_CLOSED\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Dynamic_Array1< Relation > \fBomega::Rel_Array1\fP"
.br
.ti -1c
.RI "typedef Dynamic_Array2< Relation > \fBomega::Rel_Array2\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBomega::dump_rels\fP (Rel_Array2 &\fBa\fP, reachable_information *\fBreachable_info\fP)"
.br
.ti -1c
.RI "void \fBomega::dump_sets\fP (Rel_Array1 &\fBa\fP, reachable_information *\fBreachable_info\fP)"
.br
.ti -1c
.RI "Dynamic_Array1< Relation > * \fBomega::Reachable_Nodes\fP (reachable_information *\fBreachable_info\fP)"
.br
.ti -1c
.RI "Dynamic_Array1< Relation > * \fBomega::I_Reachable_Nodes\fP (reachable_information *\fBreachable_info\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DUMP_CLOSED   1"

.SS "#define DUMP_CLOSED   1"

.SS "#define DUMP_INITIAL   1"

.SS "#define DUMP_INITIAL   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
