.TH "scan_samples" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scan_samples
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_scan_callback\fP \fBcallback\fP"
.br
.ti -1c
.RI "struct \fBisl_mat\fP * \fBsamples\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_scan_callback\fP scan_samples::callback"

.SS "struct \fBisl_mat\fP* scan_samples::samples"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
