.TH "schedtree.ExpansionNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schedtree.ExpansionNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBschedtree\&.ScheduleNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An expansion node maps each of the domain elements that reach the node to one or more domain elements. The
   image of this mapping forms the set of domain elements that reach the child of the expansion node. Expansion
   nodes are useful for grouping instances of several statements into an instance of a single virtual statement
   to ensure that those instances are always executed together.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def schedtree\&.ExpansionNode\&.__init__ ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
