.TH "schedtree.ScheduleTreeVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schedtree.ScheduleTreeVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits Visitor\&.
.PP
Inherited by \fBschedtree\&.ScheduleTreePrinter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBvisit\fP (self, node)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def schedtree\&.ScheduleTreeVisitor\&.visit ( self,  node)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
