.TH "schedtree.DomainNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schedtree.DomainNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBschedtree\&.ScheduleNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBdomain\fP='')"
.br
.ti -1c
.RI "def \fBdomain\fP (self)"
.br
.ti -1c
.RI "def \fBdomain\fP (self, domain)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A domain node appears as the root of a schedule tree and introduces the statement instances that are scheduled
   by the descendants of the domain node. The statement instances are described by a named Presburger set.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def schedtree\&.DomainNode\&.__init__ ( self,  domain = \fC''\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def schedtree\&.DomainNode\&.domain ( self)"

.SS "def schedtree\&.DomainNode\&.domain ( self,  domain)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
