.TH "schedtree.ExtensionNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schedtree.ExtensionNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBschedtree\&.ScheduleNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An extension node instructs the AST generator to add additional domain elements that need to be scheduled,
   described in terms of the outer schedule dimensions. A typical use case is the introduction of data copying
   statements for locality optimization. This is expressed as a relation between the outer schedule dimensions
   and the set of array elements accessed by the statement instances scheduled to a give value of those schedule
   dimensions. The new statement instances of extension nodes are only introduced if any of the instances
   introduced in outer nodes may still be executed at the given position of the schedule tree.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def schedtree\&.ExtensionNode\&.__init__ ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
