.TH "schedtree.ScheduleNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schedtree.ScheduleNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBschedtree\&.BandNode\fP, \fBschedtree\&.ContextNode\fP, \fBschedtree\&.DomainNode\fP, \fBschedtree\&.ExpansionNode\fP, \fBschedtree\&.ExtensionNode\fP, \fBschedtree\&.FilterNode\fP, \fBschedtree\&.GuardNode\fP, \fBschedtree\&.LeafNode\fP, \fBschedtree\&.MarkNode\fP, \fBschedtree\&.SequenceNode\fP, and \fBschedtree\&.SetNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, childmax=1, color='black')"
.br
.ti -1c
.RI "def \fBadd\fP (self, child)"
.br
.ti -1c
.RI "def \fBaccept\fP (self, visitor)"
.br
.ti -1c
.RI "def \fBchildren\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Abstract class for schedule tree children.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def schedtree\&.ScheduleNode\&.__init__ ( self,  childmax = \fC1\fP,  color = \fC'black'\fP)"

.PP
Reimplemented in \fBschedtree\&.MarkNode\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def schedtree\&.ScheduleNode\&.accept ( self,  visitor)"

.SS "def schedtree\&.ScheduleNode\&.add ( self,  child)"

.SS "def schedtree\&.ScheduleNode\&.children ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
