.TH "schedtree" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schedtree
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBandNode\fP"
.br
.ti -1c
.RI "class \fBContextNode\fP"
.br
.ti -1c
.RI "class \fBDomainNode\fP"
.br
.ti -1c
.RI "class \fBExpansionNode\fP"
.br
.ti -1c
.RI "class \fBExtensionNode\fP"
.br
.ti -1c
.RI "class \fBFilterNode\fP"
.br
.ti -1c
.RI "class \fBGuardNode\fP"
.br
.ti -1c
.RI "class \fBLeafNode\fP"
.br
.ti -1c
.RI "class \fBMarkNode\fP"
.br
.ti -1c
.RI "class \fBScheduleNode\fP"
.br
.ti -1c
.RI "class \fBScheduleTree\fP"
.br
.ti -1c
.RI "class \fBScheduleTreePrinter\fP"
.br
.ti -1c
.RI "class \fBScheduleTreeVisitor\fP"
.br
.ti -1c
.RI "class \fBSequenceNode\fP"
.br
.ti -1c
.RI "class \fBSetNode\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBCHILD_MAX\fP = 1000000"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Implementation of the 'schedule tree' data structure as defined in journal paper:
Polyhedral AST Generation is More than Just Scanning Polyhedra -- Grosser et al.

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "int schedtree\&.CHILD_MAX = 1000000"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
