.TH "schedtree.FilterNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schedtree.FilterNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBschedtree\&.ScheduleNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBfilter\fP='')"
.br
.ti -1c
.RI "def \fBfilter\fP (self)"
.br
.ti -1c
.RI "def \fBfilter\fP (self, filter)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A filter node selects a subset of the statement instances introduced by outer domain, expansion or extension
   nodes and retained by outer filter nodes. Filter nodes are typically used as children of set and sequence nodes,
   where the siblings select the other statement instances. Filters can also be used to select the statement
   instances that are mapped to a given value of a symbolic con- stant introduced in an outer context node.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def schedtree\&.FilterNode\&.__init__ ( self,  filter = \fC''\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def schedtree\&.FilterNode\&.filter ( self)"

.SS "def schedtree\&.FilterNode\&.filter ( self,  filter)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
