.TH "schedtree.SequenceNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schedtree.SequenceNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBschedtree\&.ScheduleNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A sequence node expresses that its children should be executed in order. These children must be filter nodes,
   with mutually disjoint filters.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def schedtree\&.SequenceNode\&.__init__ ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
