.TH "schedtree.BandNode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schedtree.BandNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBschedtree\&.ScheduleNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBschedule\fP='')"
.br
.ti -1c
.RI "def \fBschedule\fP (self)"
.br
.ti -1c
.RI "def \fBschedule\fP (self, schedule)"
.br
.ti -1c
.RI "def \fBpermutable\fP (self)"
.br
.ti -1c
.RI "def \fBpermutable\fP (self, permutable)"
.br
.ti -1c
.RI "def \fBcoincident\fP (self)"
.br
.ti -1c
.RI "def \fBcoincident\fP (self, coincident)"
.br
.ti -1c
.RI "def \fBoptions\fP (self)"
.br
.ti -1c
.RI "def \fBoptions\fP (self, \fBoptions\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A band node contains a partial schedule on the statement instances introduced by outer domain, expansion or
   extension nodes and retained by outer filter nodes. This partial schedule may be piecewise quasi-affine, but
   is required to be total on those statement instances. Additionally, a band node contains options that control
   the AST generation, e.g., separation, unrolling, or isolation. The ability to specify AST generation options
   for each band separately allows for great flexibility for more complicated programs with statements that,
   after scheduling, are spread over different, possibly nested, loop nests. Each band node contains an
   unstructured schedule of the type accepted by the AST generator.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def schedtree\&.BandNode\&.__init__ ( self,  schedule = \fC''\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def schedtree\&.BandNode\&.coincident ( self)"

.SS "def schedtree\&.BandNode\&.coincident ( self,  coincident)"

.SS "def schedtree\&.BandNode\&.options ( self)"

.SS "def schedtree\&.BandNode\&.options ( self,  options)"

.SS "def schedtree\&.BandNode\&.permutable ( self)"

.SS "def schedtree\&.BandNode\&.permutable ( self,  permutable)"

.SS "def schedtree\&.BandNode\&.schedule ( self)"

.SS "def schedtree\&.BandNode\&.schedule ( self,  schedule)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
