.TH "lib/isl/include/isl/deprecated/set_int.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/deprecated/set_int.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/deprecated/int\&.h>\fP
.br
\fC#include <isl/set_type\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_basic_set\fP * \fBisl_basic_set_fix\fP (\fB__isl_take\fP \fBisl_basic_set\fP *bset, enum \fBisl_dim_type\fP type, unsigned \fBpos\fP, \fBisl_int\fP value)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_set\fP * \fBisl_set_lower_bound\fP (\fB__isl_take\fP \fBisl_set\fP *\fBset\fP, enum \fBisl_dim_type\fP type, unsigned \fBpos\fP, \fBisl_int\fP value)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_set\fP * \fBisl_set_upper_bound\fP (\fB__isl_take\fP \fBisl_set\fP *\fBset\fP, enum \fBisl_dim_type\fP type, unsigned \fBpos\fP, \fBisl_int\fP value)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_set\fP * \fBisl_set_fix\fP (\fB__isl_take\fP \fBisl_set\fP *\fBset\fP, enum \fBisl_dim_type\fP type, unsigned \fBpos\fP, \fBisl_int\fP value)"
.br
.ti -1c
.RI "int \fBisl_set_plain_is_fixed\fP (\fB__isl_keep\fP \fBisl_set\fP *\fBset\fP, enum \fBisl_dim_type\fP type, unsigned \fBpos\fP, \fBisl_int\fP *\fBval\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_basic_set\fP* isl_basic_set_fix (\fB__isl_take\fP \fBisl_basic_set\fP * bset, enum \fBisl_dim_type\fP type, unsigned pos, \fBisl_int\fP value)"

.SS "\fB__isl_give\fP \fBisl_set\fP* isl_set_fix (\fB__isl_take\fP \fBisl_set\fP * set, enum \fBisl_dim_type\fP type, unsigned pos, \fBisl_int\fP value)"

.SS "\fB__isl_give\fP \fBisl_set\fP* isl_set_lower_bound (\fB__isl_take\fP \fBisl_set\fP * set, enum \fBisl_dim_type\fP type, unsigned pos, \fBisl_int\fP value)"

.SS "int isl_set_plain_is_fixed (\fB__isl_keep\fP \fBisl_set\fP * set, enum \fBisl_dim_type\fP type, unsigned pos, \fBisl_int\fP * val)"

.SS "\fB__isl_give\fP \fBisl_set\fP* isl_set_upper_bound (\fB__isl_take\fP \fBisl_set\fP * set, enum \fBisl_dim_type\fP type, unsigned pos, \fBisl_int\fP value)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
