.TH "setlib.Skew" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setlib.Skew
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsetlib\&.Function\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBname\fP='skew', offsets=[])"
.br
.ti -1c
.RI "def \fBapply\fP (self, schedule)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def setlib\&.Skew\&.__init__ ( self,  name = \fC'skew'\fP,  offsets = \fC[]\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def setlib\&.Skew\&.apply ( self,  schedule)"

.PP
Reimplemented from \fBsetlib\&.Function\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
