.TH "setlib.Generator" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setlib.Generator
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBbenchmark\fP={}, out=None)"
.br
.ti -1c
.RI "def \fBbenchmark\fP (self)"
.br
.ti -1c
.RI "def \fBcode\fP (self)"
.br
.ti -1c
.RI "def \fBisl\fP (self)"
.br
.ti -1c
.RI "def \fBreadISL\fP (self, file='')"
.br
.ti -1c
.RI "def \fBtransform\fP (self, schedule, \fBdomain\fP)"
.br
.ti -1c
.RI "def \fBgetISL\fP (self)"
.br
.ti -1c
.RI "def \fBgenerate\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def setlib\&.Generator\&.__init__ ( self,  benchmark = \fC{}\fP,  out = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def setlib\&.Generator\&.benchmark ( self)"

.SS "def setlib\&.Generator\&.code ( self)"

.SS "def setlib\&.Generator\&.generate ( self)"

.SS "def setlib\&.Generator\&.getISL ( self)"

.SS "def setlib\&.Generator\&.isl ( self)"

.SS "def setlib\&.Generator\&.readISL ( self,  file = \fC''\fP)"

.SS "def setlib\&.Generator\&.transform ( self,  schedule,  domain)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
