.TH "setlib" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setlib
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApply\fP"
.br
.ti -1c
.RI "class \fBCall\fP"
.br
.ti -1c
.RI "class \fBConstant\fP"
.br
.ti -1c
.RI "class \fBDomain\fP"
.br
.ti -1c
.RI "class \fBFunction\fP"
.br
.ti -1c
.RI "class \fBFuse\fP"
.br
.ti -1c
.RI "class \fBGenerator\fP"
.br
.ti -1c
.RI "class \fBISLError\fP"
.br
.ti -1c
.RI "class \fBSet\fP"
.br
.ti -1c
.RI "class \fBSkew\fP"
.br
.ti -1c
.RI "class \fBUnion\fP"
.br
.ti -1c
.RI "class \fBVar\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBformat_latex\fP (formula)"
.br
.ti -1c
.RI "def \fBreplace_chars\fP (formula)"
.br
.ti -1c
.RI "def \fBlist_vars\fP (sets)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def setlib\&.format_latex ( formula)"

.SS "def setlib\&.list_vars ( sets)"

.SS "def setlib\&.replace_chars ( formula)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
