.TH "setlib.Function" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setlib.Function
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBsetlib\&.Apply\fP, \fBsetlib\&.Call\fP, \fBsetlib\&.Fuse\fP, \fBsetlib\&.Skew\fP, and \fBsetlib\&.Union\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBname\fP='', \fBsets\fP=[], \fBmapping\fP=[])"
.br
.ti -1c
.RI "def \fBfrom_expr\fP (cls, expr)"
.br
.ti -1c
.RI "def \fB__len__\fP (self)"
.br
.ti -1c
.RI "def \fBadd\fP (self, space)"
.br
.ti -1c
.RI "def \fBname\fP (self)"
.br
.ti -1c
.RI "def \fBname\fP (self, name)"
.br
.ti -1c
.RI "def \fBmapping\fP (self)"
.br
.ti -1c
.RI "def \fBmapping\fP (self, mapping)"
.br
.ti -1c
.RI "def \fBsets\fP (self)"
.br
.ti -1c
.RI "def \fBsets\fP (self, sets)"
.br
.ti -1c
.RI "def \fBapply\fP (self, other)"
.br
.ti -1c
.RI "def \fB__mul__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fBlatex\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def setlib\&.Function\&.__init__ ( self,  name = \fC''\fP,  sets = \fC[]\fP,  mapping = \fC[]\fP)"

.PP
Reimplemented in \fBsetlib\&.Union\fP, and \fBsetlib\&.Apply\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def setlib\&.Function\&.__len__ ( self)"

.SS "def setlib\&.Function\&.__mul__ ( self,  other)"

.SS "def setlib\&.Function\&.__str__ ( self)"

.PP
Reimplemented in \fBsetlib\&.Fuse\fP, \fBsetlib\&.Call\fP, \fBsetlib\&.Union\fP, and \fBsetlib\&.Apply\fP\&.
.SS "def setlib\&.Function\&.add ( self,  space)"

.SS "def setlib\&.Function\&.apply ( self,  other)"

.PP
Reimplemented in \fBsetlib\&.Skew\fP, \fBsetlib\&.Union\fP, \fBsetlib\&.Apply\fP, and \fBsetlib\&.Fuse\fP\&.
.SS "def setlib\&.Function\&.from_expr ( cls,  expr)"

.SS "def setlib\&.Function\&.latex ( self)"

.PP
Reimplemented in \fBsetlib\&.Fuse\fP, \fBsetlib\&.Call\fP, \fBsetlib\&.Union\fP, and \fBsetlib\&.Apply\fP\&.
.SS "def setlib\&.Function\&.mapping ( self)"

.SS "def setlib\&.Function\&.mapping ( self,  mapping)"

.SS "def setlib\&.Function\&.name ( self)"

.SS "def setlib\&.Function\&.name ( self,  name)"

.SS "def setlib\&.Function\&.sets ( self)"

.SS "def setlib\&.Function\&.sets ( self,  sets)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
