.TH "SetRelationTest" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SetRelationTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExp\fP \fBe1\fP"
.br
.ti -1c
.RI "\fBExp\fP \fBe2\fP"
.br
.ti -1c
.RI "\fBExp\fP \fBx_minus_y\fP"
.br
.ti -1c
.RI "\fBExp\fP \fBx\fP"
.br
.ti -1c
.RI "\fBExp\fP \fBnegx_plus_y\fP"
.br
.ti -1c
.RI "\fBConjunction\fP * \fBconj1\fP"
.br
.ti -1c
.RI "\fBConjunction\fP * \fBconj2\fP"
.br
.ti -1c
.RI "\fBConjunction\fP * \fBconj1r\fP"
.br
.ti -1c
.RI "\fBConjunction\fP * \fBconj2r\fP"
.br
.ti -1c
.RI "std::string \fBroot_dir\fP"
.br
.ti -1c
.RI "std::string \fBdot_data\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SetRelationTest::SetUp ()\fC [protected]\fP, \fC [virtual]\fP"

.SS "void SetRelationTest::TearDown ()\fC [protected]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBConjunction\fP* SetRelationTest::conj1"

.SS "\fBConjunction\fP* SetRelationTest::conj1r"

.SS "\fBConjunction\fP* SetRelationTest::conj2"

.SS "\fBConjunction\fP* SetRelationTest::conj2r"

.SS "std::string SetRelationTest::dot_data"

.SS "\fBExp\fP SetRelationTest::e1"

.SS "\fBExp\fP SetRelationTest::e2"

.SS "\fBExp\fP SetRelationTest::negx_plus_y"

.SS "std::string SetRelationTest::root_dir"

.SS "\fBExp\fP SetRelationTest::x"

.SS "\fBExp\fP SetRelationTest::x_minus_y"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
