.TH "sh_data_entry" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sh_data_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisl_hash_table\fP * \fBtable\fP"
.br
.ti -1c
.RI "struct \fBisl_tab\fP * \fBtab\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBisl_tab\fP* sh_data_entry::tab"

.SS "struct \fBisl_hash_table\fP* sh_data_entry::table"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
