.TH "lib/chill/omega/basic/include/basic/SimpleList.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/omega/basic/include/basic/SimpleList.h
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <basic/Iterator\&.h>\fP
.br
\fC#include <basic/Collection\&.h>\fP
.br
\fC#include <basic/Link\&.h>\fP
.br
\fC#include <basic/SimpleList\&.c>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBomega::Simple_List_Iterator< T >\fP"
.br
.ti -1c
.RI "class \fBomega::Simple_List< T >\fP"
.br
.ti -1c
.RI "class \fBomega::Simple_List_Iterator< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBomega\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSimple_List\fP   Omega_Simple_List"
.br
.ti -1c
.RI "#define \fBSimple_List_Iterator\fP   Omega_Simple_List_Iterator"
.br
.ti -1c
.RI "#define \fBinstantiate_Simple_List\fP(\fBT\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define instantiate_Simple_List(\fBT\fP)"
\fBValue:\fP
.PP
.nf
  template class Simple_List<T>;  \
  template class Simple_List_Iterator<T>;                           \
  instantiate_Only_List_Element(T)                                  \
  instantiate_Sequence(T)
.fi
.SS "#define Simple_List   Omega_Simple_List"

.SS "#define Simple_List_Iterator   Omega_Simple_List_Iterator"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
