.TH "artifact/src/chill/smv.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
artifact/src/chill/smv.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'smv\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsmv\fP (struct \fBsparse_matrix\fP *\fBA\fP, \fBREAL\fP *\fBx\fP, \fBREAL\fP *\fBy\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void smv (struct \fBsparse_matrix\fP * A, \fBREAL\fP * x, \fBREAL\fP * y)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
