.TH "somewhere" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
somewhere \- Polyhedral Dataflow Graph class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Polyhedral Dataflow Graph class\&. 

Polyhedral Dataflow Graph \fBVisitor\fP\&.
.PP
C++ implementation of polyhedral dataflow graphs (PDFGs)\&.
.PP
\fBAuthor\fP
.RS 4
Eddie Davis 
.RE
.PP
\fBVersion\fP
.RS 4
.RE
.PP
\fBRevision\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
$Date: 2018/12/03 Contact: eddiedavis@boisestate.edu 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
