.TH "artifact/include/chill/sparse_matrix.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
artifact/include/chill/sparse_matrix.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsparse_matrix\fP"
.br
.ti -1c
.RI "struct \fBsparse_args\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE\fP   16"
.br
.ti -1c
.RI "#define \fBBLOCKSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBDEBUG\fP   0"
.br
.ti -1c
.RI "#define \fBBILLION\fP   1E9"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef float \fBREAL\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBspmv\fP (int \fBn\fP, int *index, float *\fBa\fP, float *\fBy\fP, float *\fBx\fP, int *\fBcol\fP)"
.br
.ti -1c
.RI "char \fBspmv_comp\fP (int \fBn\fP, float *\fBb\fP, float *b2)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BILLION   1E9"

.SS "#define BLOCKSIZE   4"

.SS "#define DEBUG   0"

.SS "#define SIZE   16"

.SH "Typedef Documentation"
.PP 
.SS "typedef float \fBREAL\fP"

.SH "Function Documentation"
.PP 
.SS "void spmv (int n, int * index, float * a, float * y, float * x, int * col)"

.SS "char spmv_comp (int n, float * b, float * b2)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
