.TH "sparse_matrix" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sparse_matrix
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sparse_matrix\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmax_row_len\fP"
.br
.ti -1c
.RI "int \fBnrows\fP"
.br
.ti -1c
.RI "int \fBncols\fP"
.br
.ti -1c
.RI "int \fBnnz\fP"
.br
.ti -1c
.RI "int * \fBrows\fP"
.br
.ti -1c
.RI "int * \fBcols\fP"
.br
.ti -1c
.RI "\fBREAL\fP * \fBvals\fP"
.br
.ti -1c
.RI "float * \fBvals\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int * sparse_matrix::cols"

.SS "int sparse_matrix::max_row_len"

.SS "int sparse_matrix::ncols"

.SS "int sparse_matrix::nnz"

.SS "int sparse_matrix::nrows"

.SS "int * sparse_matrix::rows"

.SS "float* sparse_matrix::vals"

.SS "\fBREAL\fP* sparse_matrix::vals"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
