.TH "Statement" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Statement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <loop\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBomega::CG_outputRepr\fP * \fBcode\fP"
.br
.ti -1c
.RI "\fBomega::Relation\fP \fBIS\fP"
.br
.ti -1c
.RI "\fBomega::Relation\fP \fBxform\fP"
.br
.ti -1c
.RI "std::vector< \fBLoopLevel\fP > \fBloop_level\fP"
.br
.ti -1c
.RI "\fBir_tree_node\fP * \fBir_stmt_node\fP"
.br
.ti -1c
.RI "bool \fBhas_inspector\fP"
.br
.ti -1c
.RI "int \fBreduction\fP"
.br
.RI "Whether reduction is possible\&. "
.ti -1c
.RI "\fBIR_OPERATION_TYPE\fP \fBreductionOp\fP"
.br
.ti -1c
.RI "class \fBstencilInfo\fP * \fBstatementStencil\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBomega::CG_outputRepr\fP* Statement::code"

.SS "bool Statement::has_inspector"

.SS "\fBir_tree_node\fP* Statement::ir_stmt_node"

.SS "\fBomega::Relation\fP Statement::IS"

.SS "std::vector<\fBLoopLevel\fP> Statement::loop_level"

.SS "int Statement::reduction"

.PP
Whether reduction is possible\&. 0 == reduction not possible, 1 == reduction possible, 2 == reduction with some processing 
.SS "\fBIR_OPERATION_TYPE\fP Statement::reductionOp"

.SS "class \fBstencilInfo\fP* Statement::statementStencil"

.SS "\fBomega::Relation\fP Statement::xform"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
