.TH "lib/isl/include/isl/stdint.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/stdint.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_GENERATED_STDINT_H\fP   'isl 0\&.20'"
.br
.ti -1c
.RI "#define \fB_STDINT_HAVE_STDINT_H\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _GENERATED_STDINT_H   'isl 0\&.20'"

.SS "#define _STDINT_HAVE_STDINT_H   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
