.TH "lib/chill/stencil.hh" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/stencil.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'ir_chill\&.hh'\fP
.br
\fC#include 'chill_ast\&.hh'\fP
.br
\fC#include 'code_gen/CG_chillRepr\&.h'\fP
.br
\fC#include 'ir_code\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstencilInfo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
