.TH "lib/chill/stencil.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/chill/stencil.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'ir_chill\&.hh'\fP
.br
\fC#include 'chill_io\&.hh'\fP
.br
\fC#include 'stencil\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBisLoopConstant\fP (\fBchillAST_node\fP *node)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool isLoopConstant (\fBchillAST_node\fP * node)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
