.TH "strings" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strings
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBisMatch\fP (inStr, pattern)"
.br
.ti -1c
.RI "def \fBgrep\fP (pattern, list, regex=False)"
.br
.ti -1c
.RI "def \fBfastJoin\fP (list, delim='')"
.br
.ti -1c
.RI "def \fBcapFirst\fP (\fBstr\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def strings\&.capFirst ( str)"

.SS "def strings\&.fastJoin ( list,  delim = \fC''\fP)"

.SS "def strings\&.grep ( pattern,  list,  regex = \fCFalse\fP)"

.SS "def strings\&.isMatch ( inStr,  pattern)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
