.TH "system" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
system
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBrun\fP (cmd='', input='', sh=True, verbose=False)"
.br
.ti -1c
.RI "def \fBncpus\fP ()"
.br
.ti -1c
.RI "def \fBthreaded\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def system\&.ncpus ()"

.SS "def system\&.run ( cmd = \fC''\fP,  input = \fC''\fP,  sh = \fCTrue\fP,  verbose = \fCFalse\fP)"

.SS "def system\&.threaded ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
