.TH "lib/gmp/tal-reent.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/tal-reent.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'gmp\&.h'\fP
.br
\fC#include 'gmp\-impl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSIZ\fP   \fBROUND_UP_MULTIPLE\fP (sizeof (struct \fBtmp_reentrant_t\fP), \fB__TMP_ALIGN\fP)"
.br
.ti -1c
.RI "#define \fBP\fP   ((struct \fBtmp_reentrant_t\fP *) \fBp\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fB__gmp_tmp_reentrant_alloc\fP (struct \fBtmp_reentrant_t\fP **markp, size_t \fBsize\fP)"
.br
.ti -1c
.RI "void \fB__gmp_tmp_reentrant_free\fP (struct \fBtmp_reentrant_t\fP *\fBmark\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HSIZ   \fBROUND_UP_MULTIPLE\fP (sizeof (struct \fBtmp_reentrant_t\fP), \fB__TMP_ALIGN\fP)"

.SS "Good P   ((struct \fBtmp_reentrant_t\fP *) \fBp\fP)"

.SH "Function Documentation"
.PP 
.SS "void* __gmp_tmp_reentrant_alloc (struct \fBtmp_reentrant_t\fP ** markp, size_t size)"

.SS "void __gmp_tmp_reentrant_free (struct \fBtmp_reentrant_t\fP * mark)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
