.TH "test/TensorDecompTest.hpp" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/TensorDecompTest.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <tuple>\fP
.br
\fC#include <util/MatrixIO\&.hpp>\fP
.br
\fC#include 'InspExecTest\&.hpp'\fP
.br
\fC#include <linalg\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest::TensorDecompTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtest\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef float \fBreal\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef float \fBreal\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
