.TH "test" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBenchmarkTest\fP"
.br
.ti -1c
.RI "class \fBConjGradCOOTest\fP"
.br
.ti -1c
.RI "class \fBConjGradCSBTest\fP"
.br
.ti -1c
.RI "class \fBConjGradCSRTest\fP"
.br
.ti -1c
.RI "class \fBConjGradDIATest\fP"
.br
.ti -1c
.RI "class \fBConjGradDSRTest\fP"
.br
.ti -1c
.RI "class \fBConjGradELLTest\fP"
.br
.ti -1c
.RI "class \fBConjGradTest\fP"
.br
.ti -1c
.RI "class \fBInspExecTest\fP"
.br
.ti -1c
.RI "class \fBJacobiTest\fP"
.br
.ti -1c
.RI "class \fBMiniFluxDivTest\fP"
.br
.ti -1c
.RI "class \fBTACO_Test\fP"
.br
.ti -1c
.RI "class \fBTensAlgCompTest\fP"
.br
.ti -1c
.RI "class \fBTensorDecompTest\fP"
.br
.ti -1c
.RI "class \fBTensorDecompTestCOO\fP"
.br
.ti -1c
.RI "class \fBTensorDecompTestCSF\fP"
.br
.ti -1c
.RI "class \fBTensorDecompTestHiCOO\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBConjGradCOOTest\fP, CG)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBConjGradCSBTest\fP, CG)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBConjGradCSRTest\fP, CG)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBConjGradDIATest\fP, CG)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBConjGradDSRTest\fP, CG)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBConjGradELLTest\fP, CG)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMiniFluxDivTest\fP, MFD)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTACO_Test\fP, Convert)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTensAlgCompTest\fP, Convert)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTensorDecompTestCOO\fP, CPD)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTensorDecompTestCSF\fP, CPD)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTensorDecompTestHiCOO\fP, CPD)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "test::TEST_F (\fBConjGradCOOTest\fP, CG)"

.SS "test::TEST_F (\fBConjGradCSBTest\fP, CG)"

.SS "test::TEST_F (\fBConjGradCSRTest\fP, CG)"

.SS "test::TEST_F (\fBConjGradDIATest\fP, CG)"

.SS "test::TEST_F (\fBConjGradDSRTest\fP, CG)"

.SS "test::TEST_F (\fBConjGradELLTest\fP, CG)"

.SS "test::TEST_F (\fBMiniFluxDivTest\fP, MFD)"

.SS "test::TEST_F (\fBTACO_Test\fP, Convert)"

.SS "test::TEST_F (\fBTensAlgCompTest\fP, Convert)"

.SS "test::TEST_F (\fBTensorDecompTestCOO\fP, CPD)"

.SS "test::TEST_F (\fBTensorDecompTestCSF\fP, CPD)"

.SS "test::TEST_F (\fBTensorDecompTestHiCOO\fP, CPD)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
