.TH "testing::internal::RemoveConst< const T[N]>" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::RemoveConst< const T[N]>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBRemoveConst\fP< \fBT\fP >::type \fBtype\fP[\fBN\fP]"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T , size_t N> typedef \fBRemoveConst\fP<\fBT\fP>::type \fBtesting::internal::RemoveConst\fP< \fBconst\fP \fBT\fP[\fBN\fP]>::type[\fBN\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
