.TH "testing::internal::EqHelper< true >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::EqHelper< true >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 > static \fBAssertionResult\fP \fBCompare\fP (\fBconst\fP char *lhs_expression, \fBconst\fP char *rhs_expression, \fBconst\fP T1 &\fBlhs\fP, \fBconst\fP T2 &\fBrhs\fP, typename \fBEnableIf\fP<!\fBis_pointer\fP< T2 >::value >::type *=0)"
.br
.ti -1c
.RI "template<typename T > static \fBAssertionResult\fP \fBCompare\fP (\fBconst\fP char *lhs_expression, \fBconst\fP char *rhs_expression, Secret *, \fBT\fP *\fBrhs\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 , typename T2 > static \fBAssertionResult\fP \fBtesting::internal::EqHelper\fP< true >::Compare (\fBconst\fP char * lhs_expression, \fBconst\fP char * rhs_expression, \fBconst\fP T1 & lhs, \fBconst\fP T2 & rhs, typename \fBEnableIf\fP<!\fBis_pointer\fP< T2 >::value >::type * = \fC0\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static \fBAssertionResult\fP \fBtesting::internal::EqHelper\fP< true >::Compare (\fBconst\fP char * lhs_expression, \fBconst\fP char * rhs_expression, Secret *, \fBT\fP * rhs)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
