.TH "testing::internal::CodeLocation" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::CodeLocation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCodeLocation\fP (\fBconst\fP std::string &a_file, int a_line)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfile\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::CodeLocation::CodeLocation (\fBconst\fP std::string & a_file, int a_line)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string testing::internal::CodeLocation::file"

.SS "int testing::internal::CodeLocation::line"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
