.TH "testing::internal::DefaultGlobalTestPartResultReporter" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::DefaultGlobalTestPartResultReporter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\-inl\&.h>\fP
.PP
Inherits \fBtesting::TestPartResultReporterInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefaultGlobalTestPartResultReporter\fP (\fBUnitTestImpl\fP *unit_test)"
.br
.ti -1c
.RI "virtual void \fBReportTestPartResult\fP (\fBconst\fP \fBTestPartResult\fP &result)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::DefaultGlobalTestPartResultReporter::DefaultGlobalTestPartResultReporter (\fBUnitTestImpl\fP * unit_test)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult (\fBconst\fP \fBTestPartResult\fP & result)\fC [virtual]\fP"

.PP
Implements \fBtesting::TestPartResultReporterInterface\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
