.TH "test::ConjGradCOOTest" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test::ConjGradCOOTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest::ConjGradTest\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBConjGradCOOTest\fP ()"
.br
.ti -1c
.RI "virtual void \fBExecute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "test::ConjGradCOOTest::ConjGradCOOTest ()\fC [inline]\fP, \fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void test::ConjGradCOOTest::Execute ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBtest::BenchmarkTest\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
