.TH "testing::internal::ParamGenerator< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamGenerator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBParamIterator\fP< \fBT\fP > \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParamGenerator\fP (\fBParamGeneratorInterface\fP< \fBT\fP > *impl)"
.br
.ti -1c
.RI "\fBParamGenerator\fP (\fBconst\fP \fBParamGenerator\fP &other)"
.br
.ti -1c
.RI "\fBParamGenerator\fP & \fBoperator=\fP (\fBconst\fP \fBParamGenerator\fP &other)"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP () \fBconst\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef \fBParamIterator\fP<\fBT\fP> \fBtesting::internal::ParamGenerator\fP< \fBT\fP >::\fBiterator\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBtesting::internal::ParamGenerator\fP< \fBT\fP >::\fBParamGenerator\fP (\fBParamGeneratorInterface\fP< \fBT\fP > * impl)\fC [inline]\fP, \fC [explicit]\fP"

.SS "template<typename T > \fBtesting::internal::ParamGenerator\fP< \fBT\fP >::\fBParamGenerator\fP (\fBconst\fP \fBParamGenerator\fP< \fBT\fP > & other)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBiterator\fP \fBtesting::internal::ParamGenerator\fP< \fBT\fP >::begin () const\fC [inline]\fP"

.SS "template<typename T > \fBiterator\fP \fBtesting::internal::ParamGenerator\fP< \fBT\fP >::end () const\fC [inline]\fP"

.SS "template<typename T > \fBParamGenerator\fP& \fBtesting::internal::ParamGenerator\fP< \fBT\fP >::operator= (\fBconst\fP \fBParamGenerator\fP< \fBT\fP > & other)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
