.TH "testing::internal::RemoveReference< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::RemoveReference< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef \fBT\fP \fBtesting::internal::RemoveReference\fP< \fBT\fP >::\fBtype\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
