.TH "testing::internal::IsRecursiveContainerImpl< C, bool >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsRecursiveContainerImpl< C, bool >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
