.TH "testing::internal::ParamIteratorInterface< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamIteratorInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ParamIteratorInterface\fP ()"
.br
.ti -1c
.RI "virtual \fBconst\fP \fBParamGeneratorInterface\fP< \fBT\fP > * \fBBaseGenerator\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual void \fBAdvance\fP ()=0"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP * \fBClone\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual \fBconst\fP \fBT\fP * \fBCurrent\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual bool \fBEquals\fP (\fBconst\fP \fBParamIteratorInterface\fP &other) \fBconst\fP =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > virtual \fBtesting::internal::ParamIteratorInterface\fP< \fBT\fP >::~\fBParamIteratorInterface\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > virtual void \fBtesting::internal::ParamIteratorInterface\fP< \fBT\fP >::Advance ()\fC [pure virtual]\fP"

.SS "template<typename T > virtual \fBconst\fP \fBParamGeneratorInterface\fP<\fBT\fP>* \fBtesting::internal::ParamIteratorInterface\fP< \fBT\fP >::BaseGenerator () const\fC [pure virtual]\fP"

.SS "template<typename T > virtual \fBParamIteratorInterface\fP* \fBtesting::internal::ParamIteratorInterface\fP< \fBT\fP >::Clone () const\fC [pure virtual]\fP"

.SS "template<typename T > virtual \fBconst\fP \fBT\fP* \fBtesting::internal::ParamIteratorInterface\fP< \fBT\fP >::Current () const\fC [pure virtual]\fP"

.SS "template<typename T > virtual bool \fBtesting::internal::ParamIteratorInterface\fP< \fBT\fP >::Equals (\fBconst\fP \fBParamIteratorInterface\fP< \fBT\fP > & other) const\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
