.TH "testing::internal::ScopedPrematureExitFile" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ScopedPrematureExitFile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedPrematureExitFile\fP (\fBconst\fP char *premature_exit_filepath)"
.br
.ti -1c
.RI "\fB~ScopedPrematureExitFile\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::ScopedPrematureExitFile::ScopedPrematureExitFile (\fBconst\fP char * premature_exit_filepath)\fC [inline]\fP, \fC [explicit]\fP"

.SS "testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
