.TH "testing::internal::GTestFlagSaver" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::GTestFlagSaver
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\-inl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGTestFlagSaver\fP ()"
.br
.ti -1c
.RI "\fB~GTestFlagSaver\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::GTestFlagSaver::GTestFlagSaver ()\fC [inline]\fP"

.SS "testing::internal::GTestFlagSaver::~GTestFlagSaver ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
