.TH "testing::internal::UniversalPrinter< T[N]>" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::UniversalPrinter< T[N]>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-printers\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPrint\fP (\fBconst\fP \fBT\fP(&\fBa\fP)[\fBN\fP], ::std::ostream *os)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , size_t N> static void \fBtesting::internal::UniversalPrinter\fP< \fBT\fP[\fBN\fP]>::Print (\fBconst\fP \fBT\fP(&) a[N], ::std::ostream * os)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
