.TH "test::TensorDecompTestHiCOO" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test::TensorDecompTestHiCOO
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest::TensorDecompTest\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTensorDecompTestHiCOO\fP (\fBconst\fP string &\fBname\fP='TensorDecompTestHiCOO')"
.br
.ti -1c
.RI "virtual \fB~TensorDecompTestHiCOO\fP ()"
.br
.ti -1c
.RI "virtual void \fBInspect\fP ()"
.br
.ti -1c
.RI "virtual void \fBExecute\fP ()"
.br
.ti -1c
.RI "virtual void \fBTensorEqua3D\fP ()"
.br
.ti -1c
.RI "virtual void \fBTensorEqual4D\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned * \fB_bptr\fP"
.br
.ti -1c
.RI "unsigned short * \fB_bindices\fP"
.br
.ti -1c
.RI "unsigned char * \fB_eindices\fP"
.br
.ti -1c
.RI "unsigned \fB_nb\fP"
.br
.ti -1c
.RI "unsigned \fB_bs\fP"
.br
.ti -1c
.RI "\fBreal\fP * \fB_bval\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "test::TensorDecompTestHiCOO::TensorDecompTestHiCOO (\fBconst\fP string & name = \fC'TensorDecompTestHiCOO'\fP)\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual test::TensorDecompTestHiCOO::~TensorDecompTestHiCOO ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void test::TensorDecompTestHiCOO::Execute ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBtest::BenchmarkTest\fP\&.
.SS "virtual void test::TensorDecompTestHiCOO::Inspect ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtest::TensorDecompTest\fP\&.
.SS "virtual void test::TensorDecompTestHiCOO::TensorEqua3D ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.SS "virtual void test::TensorDecompTestHiCOO::TensorEqual4D ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtest::TensorDecompTest\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned short* test::TensorDecompTestHiCOO::_bindices\fC [protected]\fP"

.SS "unsigned* test::TensorDecompTestHiCOO::_bptr\fC [protected]\fP"

.SS "unsigned test::TensorDecompTestHiCOO::_bs\fC [protected]\fP"

.SS "\fBreal\fP* test::TensorDecompTestHiCOO::_bval\fC [protected]\fP"

.SS "unsigned char* test::TensorDecompTestHiCOO::_eindices\fC [protected]\fP"

.SS "unsigned test::TensorDecompTestHiCOO::_nb\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
