.TH "testing::Message" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::Message
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP ()"
.br
.ti -1c
.RI "\fBMessage\fP (\fBconst\fP \fBMessage\fP &msg)"
.br
.ti -1c
.RI "\fBMessage\fP (\fBconst\fP char *\fBstr\fP)"
.br
.ti -1c
.RI "template<typename T > \fBMessage\fP & \fBoperator<<\fP (\fBconst\fP \fBT\fP &\fBval\fP)"
.br
.ti -1c
.RI "template<typename T > \fBMessage\fP & \fBoperator<<\fP (\fBT\fP *\fBconst\fP &pointer)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (BasicNarrowIoManip \fBval\fP)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (bool \fBb\fP)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (\fBconst\fP wchar_t *wide_c_str)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (wchar_t *wide_c_str)"
.br
.ti -1c
.RI "std::string \fBGetString\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::Message::Message ()"

.SS "testing::Message::Message (\fBconst\fP \fBMessage\fP & msg)\fC [inline]\fP"

.SS "testing::Message::Message (\fBconst\fP char * str)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string testing::Message::GetString () const"

.SS "\fBMessage\fP& testing::Message::operator<< (BasicNarrowIoManip val)\fC [inline]\fP"

.SS "\fBMessage\fP& testing::Message::operator<< (bool b)\fC [inline]\fP"

.SS "template<typename T > \fBMessage\fP& testing::Message::operator<< (\fBconst\fP \fBT\fP & val)\fC [inline]\fP"

.SS "\fBMessage\fP & testing::Message::operator<< (\fBconst\fP wchar_t * wide_c_str)"

.SS "template<typename T > \fBMessage\fP& testing::Message::operator<< (\fBT\fP *\fBconst\fP & pointer)\fC [inline]\fP"

.SS "\fBMessage\fP & testing::Message::operator<< (wchar_t * wide_c_str)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
