.TH "testing::TestEventListeners" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestEventListeners
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestEventListeners\fP ()"
.br
.ti -1c
.RI "\fB~TestEventListeners\fP ()"
.br
.ti -1c
.RI "void \fBAppend\fP (\fBTestEventListener\fP *listener)"
.br
.ti -1c
.RI "\fBTestEventListener\fP * \fBRelease\fP (\fBTestEventListener\fP *listener)"
.br
.ti -1c
.RI "\fBTestEventListener\fP * \fBdefault_result_printer\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBTestEventListener\fP * \fBdefault_xml_generator\fP () \fBconst\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTestCase\fP"
.br
.ti -1c
.RI "class \fBTestInfo\fP"
.br
.ti -1c
.RI "class \fBinternal::DefaultGlobalTestPartResultReporter\fP"
.br
.ti -1c
.RI "class \fBinternal::NoExecDeathTest\fP"
.br
.ti -1c
.RI "class \fBinternal::TestEventListenersAccessor\fP"
.br
.ti -1c
.RI "class \fBinternal::UnitTestImpl\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::TestEventListeners::TestEventListeners ()"

.SS "testing::TestEventListeners::~TestEventListeners ()"

.SH "Member Function Documentation"
.PP 
.SS "void testing::TestEventListeners::Append (\fBTestEventListener\fP * listener)"

.SS "\fBTestEventListener\fP* testing::TestEventListeners::default_result_printer () const\fC [inline]\fP"

.SS "\fBTestEventListener\fP* testing::TestEventListeners::default_xml_generator () const\fC [inline]\fP"

.SS "\fBTestEventListener\fP * testing::TestEventListeners::Release (\fBTestEventListener\fP * listener)"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBinternal::DefaultGlobalTestPartResultReporter\fP\fC [friend]\fP"

.SS "friend class internal::NoExecDeathTest\fC [friend]\fP"

.SS "friend class internal::TestEventListenersAccessor\fC [friend]\fP"

.SS "friend class \fBinternal::UnitTestImpl\fP\fC [friend]\fP"

.SS "friend class \fBTestCase\fP\fC [friend]\fP"

.SS "friend class \fBTestInfo\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
