.TH "test::ConjGradELLTest" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test::ConjGradELLTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest::ConjGradTest\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBConjGradELLTest\fP ()"
.br
.ti -1c
.RI "virtual \fB~ConjGradELLTest\fP ()"
.br
.ti -1c
.RI "virtual void \fBInspect\fP ()"
.br
.ti -1c
.RI "virtual void \fBExecute\fP ()"
.br
.ti -1c
.RI "virtual void \fBMatrixEqual\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned \fB_nell\fP"
.br
.ti -1c
.RI "unsigned * \fB_lcol\fP"
.br
.ti -1c
.RI "double * \fB_lval\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "test::ConjGradELLTest::ConjGradELLTest ()\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual test::ConjGradELLTest::~ConjGradELLTest ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void test::ConjGradELLTest::Execute ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBtest::BenchmarkTest\fP\&.
.SS "virtual void test::ConjGradELLTest::Inspect ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtest::ConjGradTest\fP\&.
.SS "virtual void test::ConjGradELLTest::MatrixEqual ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtest::ConjGradTest\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned* test::ConjGradELLTest::_lcol\fC [protected]\fP"

.SS "double* test::ConjGradELLTest::_lval\fC [protected]\fP"

.SS "unsigned test::ConjGradELLTest::_nell\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
