.TH "testing::internal::ScopedTrace" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ScopedTrace
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedTrace\fP (\fBconst\fP char *file, int line, \fBconst\fP \fBMessage\fP &message)"
.br
.ti -1c
.RI "\fB~ScopedTrace\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::ScopedTrace::ScopedTrace (\fBconst\fP char * file, int line, \fBconst\fP \fBMessage\fP & message)"

.SS "testing::internal::ScopedTrace::~ScopedTrace ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
