.TH "testing::internal::edit_distance" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::edit_distance
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEditType\fP { \fBkMatch\fP, \fBkAdd\fP, \fBkRemove\fP, \fBkReplace\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP std::vector< \fBEditType\fP > \fBCalculateOptimalEdits\fP (\fBconst\fP std::vector< size_t > &left, \fBconst\fP std::vector< size_t > &right)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP std::vector< \fBEditType\fP > \fBCalculateOptimalEdits\fP (\fBconst\fP std::vector< std::string > &left, \fBconst\fP std::vector< std::string > &right)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP std::string \fBCreateUnifiedDiff\fP (\fBconst\fP std::vector< std::string > &left, \fBconst\fP std::vector< std::string > &right, size_t \fBcontext\fP=2)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtesting::internal::edit_distance::EditType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkMatch \fP\fP
.TP
\fB\fIkAdd \fP\fP
.TP
\fB\fIkRemove \fP\fP
.TP
\fB\fIkReplace \fP\fP
.SH "Function Documentation"
.PP 
.SS "std::vector< \fBEditType\fP > testing::internal::edit_distance::CalculateOptimalEdits (\fBconst\fP std::vector< size_t > & left, \fBconst\fP std::vector< size_t > & right)"

.SS "std::vector< \fBEditType\fP > testing::internal::edit_distance::CalculateOptimalEdits (\fBconst\fP std::vector< std::string > & left, \fBconst\fP std::vector< std::string > & right)"

.SS "std::string testing::internal::edit_distance::CreateUnifiedDiff (\fBconst\fP std::vector< std::string > & left, \fBconst\fP std::vector< std::string > & right, size_t context = \fC2\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
