.TH "testing::TestCase" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestCase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestCase\fP (\fBconst\fP char *\fBname\fP, \fBconst\fP char *a_type_param, \fBTest::SetUpTestCaseFunc\fP set_up_tc, \fBTest::TearDownTestCaseFunc\fP tear_down_tc)"
.br
.ti -1c
.RI "virtual \fB~TestCase\fP ()"
.br
.ti -1c
.RI "\fBconst\fP char * \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBtype_param\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBshould_run\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBsuccessful_test_count\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBfailed_test_count\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBreportable_disabled_test_count\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBdisabled_test_count\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBreportable_test_count\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBtest_to_run_count\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBtotal_test_count\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBPassed\fP () \fBconst\fP"
.br
.ti -1c
.RI "bool \fBFailed\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBTimeInMillis\fP \fBelapsed_time\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBTestInfo\fP * \fBGetTestInfo\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBTestResult\fP & \fBad_hoc_test_result\fP () \fBconst\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTest\fP"
.br
.ti -1c
.RI "class \fBinternal::UnitTestImpl\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::TestCase::TestCase (\fBconst\fP char * name, \fBconst\fP char * a_type_param, \fBTest::SetUpTestCaseFunc\fP set_up_tc, \fBTest::TearDownTestCaseFunc\fP tear_down_tc)"

.SS "testing::TestCase::~TestCase ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP \fBTestResult\fP& testing::TestCase::ad_hoc_test_result () const\fC [inline]\fP"

.SS "int testing::TestCase::disabled_test_count () const"

.SS "\fBTimeInMillis\fP testing::TestCase::elapsed_time () const\fC [inline]\fP"

.SS "bool testing::TestCase::Failed () const\fC [inline]\fP"

.SS "int testing::TestCase::failed_test_count () const"

.SS "\fBconst\fP \fBTestInfo\fP * testing::TestCase::GetTestInfo (int i) const"

.SS "\fBconst\fP char* testing::TestCase::name () const\fC [inline]\fP"

.SS "bool testing::TestCase::Passed () const\fC [inline]\fP"

.SS "int testing::TestCase::reportable_disabled_test_count () const"

.SS "int testing::TestCase::reportable_test_count () const"

.SS "bool testing::TestCase::should_run () const\fC [inline]\fP"

.SS "int testing::TestCase::successful_test_count () const"

.SS "int testing::TestCase::test_to_run_count () const"

.SS "int testing::TestCase::total_test_count () const"

.SS "\fBconst\fP char* testing::TestCase::type_param () const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBinternal::UnitTestImpl\fP\fC [friend]\fP"

.SS "friend class \fBTest\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
