.TH "testing::internal::IsRecursiveContainerImpl< C, true >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsRecursiveContainerImpl< C, true >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBIteratorTraits\fP< typename C::iterator >::\fBvalue_type\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBis_same\fP< \fBvalue_type\fP, \fBC\fP > \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename C > typedef \fBis_same\fP<\fBvalue_type\fP, \fBC\fP> \fBtesting::internal::IsRecursiveContainerImpl\fP< \fBC\fP, true >::\fBtype\fP"

.SS "template<typename C > typedef \fBIteratorTraits\fP<typename C::iterator>::\fBvalue_type\fP \fBtesting::internal::IsRecursiveContainerImpl\fP< \fBC\fP, true >::\fBvalue_type\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
