.TH "testing::WithParamInterface< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::WithParamInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.PP
Inherited by \fBtesting::TestWithParam< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP \fBParamType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~WithParamInterface\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBParamType\fP & \fBGetParam\fP () \fBconst\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class TestClass > class \fBinternal::ParameterizedTestFactory\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef \fBT\fP \fBtesting::WithParamInterface\fP< \fBT\fP >::\fBParamType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > virtual \fBtesting::WithParamInterface\fP< \fBT\fP >::~\fBWithParamInterface\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBconst\fP \fBParamType\fP& \fBtesting::WithParamInterface\fP< \fBT\fP >::GetParam () const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename T > template<class TestClass > friend class \fBinternal::ParameterizedTestFactory\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
