.TH "testing::internal::posix" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::posix
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct stat \fBStatStruct\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBFileNo\fP (FILE *file)"
.br
.ti -1c
.RI "int \fBIsATTY\fP (int fd)"
.br
.ti -1c
.RI "int \fBStat\fP (\fBconst\fP char *path, \fBStatStruct\fP *buf)"
.br
.ti -1c
.RI "int \fBStrCaseCmp\fP (\fBconst\fP char *\fBs1\fP, \fBconst\fP char *\fBs2\fP)"
.br
.ti -1c
.RI "char * \fBStrDup\fP (\fBconst\fP char *src)"
.br
.ti -1c
.RI "int \fBRmDir\fP (\fBconst\fP char *dir)"
.br
.ti -1c
.RI "bool \fBIsDir\fP (\fBconst\fP \fBStatStruct\fP &st)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBStrNCpy\fP (char *dest, \fBconst\fP char *src, size_t n)"
.br
.ti -1c
.RI "int \fBChDir\fP (\fBconst\fP char *dir)"
.br
.ti -1c
.RI "FILE * \fBFOpen\fP (\fBconst\fP char *path, \fBconst\fP char *mode)"
.br
.ti -1c
.RI "FILE * \fBFReopen\fP (\fBconst\fP char *path, \fBconst\fP char *mode, FILE *stream)"
.br
.ti -1c
.RI "FILE * \fBFDOpen\fP (int fd, \fBconst\fP char *mode)"
.br
.ti -1c
.RI "int \fBFClose\fP (FILE *fp)"
.br
.ti -1c
.RI "int \fBRead\fP (int fd, void *buf, unsigned int \fBcount\fP)"
.br
.ti -1c
.RI "int \fBWrite\fP (int fd, \fBconst\fP void *buf, unsigned int \fBcount\fP)"
.br
.ti -1c
.RI "int \fBClose\fP (int fd)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBStrError\fP (int errnum)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBGetEnv\fP (\fBconst\fP char *\fBname\fP)"
.br
.ti -1c
.RI "void \fBAbort\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct stat \fBtesting::internal::posix::StatStruct\fP"

.SH "Function Documentation"
.PP 
.SS "void testing::internal::posix::Abort ()\fC [inline]\fP"

.SS "int testing::internal::posix::ChDir (\fBconst\fP char * dir)\fC [inline]\fP"

.SS "int testing::internal::posix::Close (int fd)\fC [inline]\fP"

.SS "int testing::internal::posix::FClose (FILE * fp)\fC [inline]\fP"

.SS "FILE* testing::internal::posix::FDOpen (int fd, \fBconst\fP char * mode)\fC [inline]\fP"

.SS "int testing::internal::posix::FileNo (FILE * file)\fC [inline]\fP"

.SS "FILE* testing::internal::posix::FOpen (\fBconst\fP char * path, \fBconst\fP char * mode)\fC [inline]\fP"

.SS "FILE* testing::internal::posix::FReopen (\fBconst\fP char * path, \fBconst\fP char * mode, FILE * stream)\fC [inline]\fP"

.SS "\fBconst\fP char* testing::internal::posix::GetEnv (\fBconst\fP char * name)\fC [inline]\fP"

.SS "int testing::internal::posix::IsATTY (int fd)\fC [inline]\fP"

.SS "bool testing::internal::posix::IsDir (\fBconst\fP \fBStatStruct\fP & st)\fC [inline]\fP"

.SS "int testing::internal::posix::Read (int fd, void * buf, unsigned int count)\fC [inline]\fP"

.SS "int testing::internal::posix::RmDir (\fBconst\fP char * dir)\fC [inline]\fP"

.SS "int testing::internal::posix::Stat (\fBconst\fP char * path, \fBStatStruct\fP * buf)\fC [inline]\fP"

.SS "int testing::internal::posix::StrCaseCmp (\fBconst\fP char * s1, \fBconst\fP char * s2)\fC [inline]\fP"

.SS "char* testing::internal::posix::StrDup (\fBconst\fP char * src)\fC [inline]\fP"

.SS "\fBconst\fP char* testing::internal::posix::StrError (int errnum)\fC [inline]\fP"

.SS "\fBconst\fP char* testing::internal::posix::StrNCpy (char * dest, \fBconst\fP char * src, size_t n)\fC [inline]\fP"

.SS "int testing::internal::posix::Write (int fd, \fBconst\fP void * buf, unsigned int count)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
