.TH "testing::internal2::TypeWithoutFormatter< T, kProtobuf >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal2::TypeWithoutFormatter< T, kProtobuf >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-printers\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPrintValue\fP (\fBconst\fP \fBT\fP &value, ::std::ostream *os)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static void \fBtesting::internal2::TypeWithoutFormatter\fP< \fBT\fP, \fBkProtobuf\fP >::PrintValue (\fBconst\fP \fBT\fP & value, ::std::ostream * os)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
