.TH "testing::internal::ParamGeneratorInterface< T >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamGeneratorInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.PP
Inherited by \fBtesting::internal::RangeGenerator< T, IncrementT >\fP, and \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP \fBParamType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ParamGeneratorInterface\fP ()"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< \fBT\fP > * \fBBegin\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< \fBT\fP > * \fBEnd\fP () \fBconst\fP =0"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef \fBT\fP \fBtesting::internal::ParamGeneratorInterface\fP< \fBT\fP >::\fBParamType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > virtual \fBtesting::internal::ParamGeneratorInterface\fP< \fBT\fP >::~\fBParamGeneratorInterface\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > virtual \fBParamIteratorInterface\fP<\fBT\fP>* \fBtesting::internal::ParamGeneratorInterface\fP< \fBT\fP >::Begin () const\fC [pure virtual]\fP"

.PP
Implemented in \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP, and \fBtesting::internal::RangeGenerator< T, IncrementT >\fP\&.
.SS "template<typename T > virtual \fBParamIteratorInterface\fP<\fBT\fP>* \fBtesting::internal::ParamGeneratorInterface\fP< \fBT\fP >::End () const\fC [pure virtual]\fP"

.PP
Implemented in \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP, and \fBtesting::internal::RangeGenerator< T, IncrementT >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
