.TH "testing::internal::TestMetaFactory< TestCase >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestMetaFactory< TestCase >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.PP
Inherits \fBtesting::internal::TestMetaFactoryBase< TestCase::ParamType >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef TestCase::ParamType \fBParamType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestMetaFactory\fP ()"
.br
.ti -1c
.RI "virtual \fBTestFactoryBase\fP * \fBCreateTestFactory\fP (\fBParamType\fP parameter)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<class TestCase > typedef TestCase::ParamType \fBtesting::internal::TestMetaFactory\fP< \fBTestCase\fP >::\fBParamType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class TestCase > \fBtesting::internal::TestMetaFactory\fP< \fBTestCase\fP >::\fBTestMetaFactory\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class TestCase > virtual \fBTestFactoryBase\fP* \fBtesting::internal::TestMetaFactory\fP< \fBTestCase\fP >::CreateTestFactory (\fBParamType\fP parameter)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::internal::TestMetaFactoryBase< TestCase::ParamType >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
