.TH "testing::internal::TraceInfo" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TraceInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\-inl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP char * \fBfile\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP char* testing::internal::TraceInfo::file"

.SS "int testing::internal::TraceInfo::line"

.SS "std::string testing::internal::TraceInfo::message"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
