.TH "testing::internal::TestResultAccessor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestResultAccessor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\-inl\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRecordProperty\fP (\fBTestResult\fP *test_result, \fBconst\fP std::string &xml_element, \fBconst\fP \fBTestProperty\fP &property)"
.br
.ti -1c
.RI "static void \fBClearTestPartResults\fP (\fBTestResult\fP *test_result)"
.br
.ti -1c
.RI "static \fBconst\fP std::vector< \fBtesting::TestPartResult\fP > & \fBtest_part_results\fP (\fBconst\fP \fBTestResult\fP &test_result)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void testing::internal::TestResultAccessor::ClearTestPartResults (\fBTestResult\fP * test_result)\fC [inline]\fP, \fC [static]\fP"

.SS "static void testing::internal::TestResultAccessor::RecordProperty (\fBTestResult\fP * test_result, \fBconst\fP std::string & xml_element, \fBconst\fP \fBTestProperty\fP & property)\fC [inline]\fP, \fC [static]\fP"

.SS "static \fBconst\fP std::vector<\fBtesting::TestPartResult\fP>& testing::internal::TestResultAccessor::test_part_results (\fBconst\fP \fBTestResult\fP & test_result)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
