.TH "test::InspExecTest" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test::InspExecTest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InspExecTest\&.hpp>\fP
.PP
Inherits \fBtest::BenchmarkTest\fP\&.
.PP
Inherited by \fBtest::ConjGradTest\fP, \fBtest::JacobiTest\fP, and \fBtest::TensorDecompTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBInspTime\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBInspExecTest\fP (\fBconst\fP string &\fBname\fP='')"
.br
.ti -1c
.RI "virtual void \fBInspect\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBRun\fP ()"
.br
.ti -1c
.RI "virtual void \fBVerify\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fB_inspFlag\fP"
.br
.ti -1c
.RI "double \fB_inspTime\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "test::InspExecTest::InspExecTest (\fBconst\fP string & name = \fC''\fP)\fC [inline]\fP, \fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void test::InspExecTest::Inspect ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBtest::TensorDecompTest\fP, \fBtest::ConjGradTest\fP, \fBtest::JacobiTest\fP, \fBtest::ConjGradCSBTest\fP, \fBtest::ConjGradDIATest\fP, \fBtest::ConjGradELLTest\fP, \fBtest::ConjGradDSRTest\fP, \fBtest::ConjGradCSRTest\fP, \fBtest::TensorDecompTestHiCOO\fP, and \fBtest::TensorDecompTestCSF\fP\&.
.SS "double test::InspExecTest::InspTime () const\fC [inline]\fP"

.SS "virtual void test::InspExecTest::Run ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtest::BenchmarkTest\fP\&.
.SS "virtual void test::InspExecTest::Verify ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtest::BenchmarkTest\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool test::InspExecTest::_inspFlag\fC [protected]\fP"

.SS "double test::InspExecTest::_inspTime\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
