.TH "test::TACO_Test" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test::TACO_Test
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTACO_Test\fP ()"
.br
.ti -1c
.RI "virtual \fB~TACO_Test\fP ()"
.br
.ti -1c
.RI "void \fBSetUp\fP (\fBconst\fP string &filename, \fBconst\fP int rank=10)"
.br
.ti -1c
.RI "void \fBInitMatrix\fP (Tensor< double > &\fBmtx\fP, double \fBval\fP=0\&.0)"
.br
.ti -1c
.RI "void \fBRandMatrix\fP (Tensor< double > &\fBmtx\fP, double \fBmin\fP=0\&.0, double \fBmax\fP=1\&.0)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "test::TACO_Test::TACO_Test ()\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual test::TACO_Test::~TACO_Test ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void test::TACO_Test::InitMatrix (Tensor< double > & mtx, double val = \fC0\&.0\fP)\fC [inline]\fP, \fC [protected]\fP"

.SS "void test::TACO_Test::RandMatrix (Tensor< double > & mtx, double min = \fC0\&.0\fP, double max = \fC1\&.0\fP)\fC [inline]\fP, \fC [protected]\fP"

.SS "void test::TACO_Test::SetUp (\fBconst\fP string & filename, \fBconst\fP int rank = \fC10\fP)\fC [inline]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
