.TH "testing::internal::ValueArray2< T1, T2 >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ValueArray2< T1, T2 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\-generated\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueArray2\fP (T1 v1, T2 v2)"
.br
.ti -1c
.RI "template<typename T > \fBoperator ParamGenerator< T >\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T1 , typename T2 > \fBtesting::internal::ValueArray2\fP< T1, T2 >::\fBValueArray2\fP (T1 v1, T2 v2)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 , typename T2 > template<typename T > \fBtesting::internal::ValueArray2\fP< T1, T2 >::operator \fBParamGenerator\fP< \fBT\fP > () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
