.TH "testing::internal::RangeGenerator< T, IncrementT >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::RangeGenerator< T, IncrementT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.PP
Inherits \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRangeGenerator\fP (\fBT\fP begin, \fBT\fP end, IncrementT step)"
.br
.ti -1c
.RI "virtual \fB~RangeGenerator\fP ()"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< \fBT\fP > * \fBBegin\fP () \fBconst\fP"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< \fBT\fP > * \fBEnd\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T , typename IncrementT > \fBtesting::internal::RangeGenerator\fP< \fBT\fP, IncrementT >::\fBRangeGenerator\fP (\fBT\fP begin, \fBT\fP end, IncrementT step)\fC [inline]\fP"

.SS "template<typename T , typename IncrementT > virtual \fBtesting::internal::RangeGenerator\fP< \fBT\fP, IncrementT >::~\fBRangeGenerator\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T , typename IncrementT > virtual \fBParamIteratorInterface\fP<\fBT\fP>* \fBtesting::internal::RangeGenerator\fP< \fBT\fP, IncrementT >::Begin () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.
.SS "template<typename T , typename IncrementT > virtual \fBParamIteratorInterface\fP<\fBT\fP>* \fBtesting::internal::RangeGenerator\fP< \fBT\fP, IncrementT >::End () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
