.TH "testing::internal::XmlUnitTestResultPrinter" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::XmlUnitTestResultPrinter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::EmptyTestEventListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlUnitTestResultPrinter\fP (\fBconst\fP char *output_file)"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationEnd\fP (\fBconst\fP \fBUnitTest\fP &unit_test, int iteration)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::XmlUnitTestResultPrinter::XmlUnitTestResultPrinter (\fBconst\fP char * output_file)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd (\fBconst\fP \fBUnitTest\fP & unit_test, int iteration)\fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::EmptyTestEventListener\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
