.TH "testing::internal::OsStackTraceGetter" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::OsStackTraceGetter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\-inl\&.h>\fP
.PP
Inherits \fBtesting::internal::OsStackTraceGetterInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOsStackTraceGetter\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBCurrentStackTrace\fP (int max_depth, int skip_count)"
.br
.ti -1c
.RI "virtual void \fBUponLeavingGTest\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::OsStackTraceGetter::OsStackTraceGetter ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string testing::internal::OsStackTraceGetter::CurrentStackTrace (int max_depth, int skip_count)\fC [virtual]\fP"

.PP
Implements \fBtesting::internal::OsStackTraceGetterInterface\fP\&.
.SS "void testing::internal::OsStackTraceGetter::UponLeavingGTest ()\fC [virtual]\fP"

.PP
Implements \fBtesting::internal::OsStackTraceGetterInterface\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
