.TH "testing::internal::UnitTestOptions" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::UnitTestOptions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\-inl\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBGetOutputFormat\fP ()"
.br
.ti -1c
.RI "static std::string \fBGetAbsolutePathToOutputFile\fP ()"
.br
.ti -1c
.RI "static bool \fBPatternMatchesString\fP (\fBconst\fP char *pattern, \fBconst\fP char *\fBstr\fP)"
.br
.ti -1c
.RI "static bool \fBFilterMatchesTest\fP (\fBconst\fP std::string &test_case_name, \fBconst\fP std::string &test_name)"
.br
.ti -1c
.RI "static bool \fBMatchesFilter\fP (\fBconst\fP std::string &\fBname\fP, \fBconst\fP char *filter)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool testing::internal::UnitTestOptions::FilterMatchesTest (\fBconst\fP std::string & test_case_name, \fBconst\fP std::string & test_name)\fC [static]\fP"

.SS "std::string testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile ()\fC [static]\fP"

.SS "std::string testing::internal::UnitTestOptions::GetOutputFormat ()\fC [static]\fP"

.SS "bool testing::internal::UnitTestOptions::MatchesFilter (\fBconst\fP std::string & name, \fBconst\fP char * filter)\fC [static]\fP"

.SS "bool testing::internal::UnitTestOptions::PatternMatchesString (\fBconst\fP char * pattern, \fBconst\fP char * str)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
