.TH "testing::TestPartResultArray" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestPartResultArray
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-test\-part\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestPartResultArray\fP ()"
.br
.ti -1c
.RI "void \fBAppend\fP (\fBconst\fP \fBTestPartResult\fP &result)"
.br
.ti -1c
.RI "\fBconst\fP \fBTestPartResult\fP & \fBGetTestPartResult\fP (int index) \fBconst\fP"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::TestPartResultArray::TestPartResultArray ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void testing::TestPartResultArray::Append (\fBconst\fP \fBTestPartResult\fP & result)"

.SS "\fBconst\fP \fBTestPartResult\fP & testing::TestPartResultArray::GetTestPartResult (int index) const"

.SS "int testing::TestPartResultArray::size () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
