.TH "testing::TestParamInfo< ParamType >" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestParamInfo< ParamType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestParamInfo\fP (\fBconst\fP ParamType &a_param, size_t an_index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ParamType \fBparam\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ParamType > \fBtesting::TestParamInfo\fP< ParamType >::\fBTestParamInfo\fP (\fBconst\fP ParamType & a_param, size_t an_index)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<class ParamType > size_t \fBtesting::TestParamInfo\fP< ParamType >::index"

.SS "template<class ParamType > ParamType \fBtesting::TestParamInfo\fP< ParamType >::param"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
