.TH "texture_memory_mapping" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
texture_memory_mapping
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mem_mapping_utils\&.hh>\fP
.PP
Inherits \fBmemory_mapping\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtexture_memory_mapping\fP (bool used, \fBconst\fP char *array_name)"
.br
.ti -1c
.RI "void \fBset_devptr_symbol\fP (\fBconst\fP char *array_name, SgVariableSymbol *sym)"
.br
.ti -1c
.RI "SgVarRefExp * \fBget_devptr_symbol_exp\fP (\fBconst\fP char *array_name)"
.br
.ti -1c
.RI "\fBtexture_memory_mapping\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "texture_memory_mapping::texture_memory_mapping (bool used, \fBconst\fP char * array_name)"

.SS "texture_memory_mapping::texture_memory_mapping ()"

.SH "Member Function Documentation"
.PP 
.SS "SgVarRefExp* texture_memory_mapping::get_devptr_symbol_exp (\fBconst\fP char * array_name)"

.SS "void texture_memory_mapping::set_devptr_symbol (\fBconst\fP char * array_name, SgVariableSymbol * sym)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
