.TH "tftest" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tftest
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBread_tensor\fP (tnsfile)"
.br
.ti -1c
.RI "def \fBtensorly_test\fP (tns)"
.br
.ti -1c
.RI "def \fBpinv_test\fP (\fBsize\fP=4)"
.br
.ti -1c
.RI "def \fBsktensor_test\fP (indices, vals, dims)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def tftest\&.main ()"

.SS "def tftest\&.pinv_test ( size = \fC4\fP)"

.SS "def tftest\&.read_tensor ( tnsfile)"

.SS "def tftest\&.sktensor_test ( indices,  vals,  dims)"

.SS "def tftest\&.tensorly_test ( tns)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
