.TH "tmp_align_t" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmp_align_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmp\-impl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmp_limb_t\fP \fBl\fP"
.br
.ti -1c
.RI "char * \fBp\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmp_limb_t\fP tmp_align_t::l"

.SS "char* tmp_align_t::p"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
