.TH "trycatch_exception" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trycatch_exception
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exception\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "char * \fBmsg\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int trycatch_exception::code"

.SS "char* trycatch_exception::msg"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
