.TH "lib/iegenlib/src/set_relation/TupleDecl_test.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/set_relation/TupleDecl_test.cc \- Test for the TupleDecl class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'expression\&.h'\fP
.br
\fC#include 'set_relation\&.h'\fP
.br
\fC#include '\&.\&./util/util\&.h'\fP
.br
\fC#include 'TupleDecl\&.h'\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (TupleDeclTest, TupleDeclMethods)"
.br
.ti -1c
.RI "\fBTEST\fP (TupleDeclTest, TupleDeclLessThanByVariables)"
.br
.ti -1c
.RI "\fBTEST\fP (TupleDeclTest, TupleDeclLessThanBySizes)"
.br
.ti -1c
.RI "\fBTEST\fP (TupleDeclTest, TupleDeclLessThanByConstants)"
.br
.ti -1c
.RI "\fBTEST\fP (TupleDeclTest, TupleDeclLessThanByMixedVarsConsts)"
.br
.ti -1c
.RI "\fBTEST\fP (TupleDeclTest, TupleDeclLessThanByEqualItems)"
.br
.ti -1c
.RI "\fBTEST\fP (TupleDeclTest, TupleDeclEqualsWithEqualItems)"
.br
.ti -1c
.RI "\fBTEST\fP (TupleDeclTest, TupleDeclEqualsWithNonEqualItems)"
.br
.ti -1c
.RI "\fBTEST\fP (TupleDeclTest, TupleDeclLessThanBugFixing)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test for the TupleDecl class\&. 


.PP
\fBDate\fP
.RS 4
Started: 1/25/2013 
.RE
.PP
.SH "$Revision:: 628                $: last committed revision"
.PP
.SH "$Date:: 2013-01-25             $: date of last committed revision"
.PP
.SH "$Author:: heim                 $: author of last committed revision"
.PP
\fBAuthors\fP
.RS 4
Michelle Strout, Joe Strout, Mark Heim
.RE
.PP
Copyright (c) 2012, Colorado State University 
.br
 All rights reserved\&. 
.br
 See \&.\&./\&.\&./COPYING for details\&. 
.br
 
.SH "Function Documentation"
.PP 
.SS "TEST (TupleDeclTest, TupleDeclEqualsWithEqualItems)"

.SS "TEST (TupleDeclTest, TupleDeclEqualsWithNonEqualItems)"

.SS "TEST (TupleDeclTest, TupleDeclLessThanBugFixing)"

.SS "TEST (TupleDeclTest, TupleDeclLessThanByConstants)"

.SS "TEST (TupleDeclTest, TupleDeclLessThanByEqualItems)"

.SS "TEST (TupleDeclTest, TupleDeclLessThanByMixedVarsConsts)"

.SS "TEST (TupleDeclTest, TupleDeclLessThanBySizes)"

.SS "TEST (TupleDeclTest, TupleDeclLessThanByVariables)"

.SS "TEST (TupleDeclTest, TupleDeclMethods)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
