.TH "Tuple_Part" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tuple_Part
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AST\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTuple_Part\fP (\fBVariable_Ref\fP *\fBf\fP, \fBVariable_Ref\fP *\fBt\fP)"
.br
.ti -1c
.RI "\fBTuple_Part\fP (\fBVariable_Ref\fP *\fBf\fP)"
.br
.ti -1c
.RI "\fBTuple_Part\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVariable_Ref\fP * \fBfrom\fP"
.br
.ti -1c
.RI "\fBVariable_Ref\fP * \fBto\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tuple_Part::Tuple_Part (\fBVariable_Ref\fP * f, \fBVariable_Ref\fP * t)\fC [inline]\fP"

.SS "Tuple_Part::Tuple_Part (\fBVariable_Ref\fP * f)\fC [inline]\fP"

.SS "Tuple_Part::Tuple_Part ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBVariable_Ref\fP* Tuple_Part::from"

.SS "\fBVariable_Ref\fP * Tuple_Part::to"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
