.TH "tupleDescriptor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tupleDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AST\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtupleDescriptor\fP ()"
.br
.ti -1c
.RI "void \fBextend\fP ()"
.br
.ti -1c
.RI "void \fBextend\fP (\fBast::Exp\fP *\fBe\fP)"
.br
.ti -1c
.RI "void \fBextend\fP (\fBast::Exp\fP *\fBlb\fP, \fBast::Exp\fP *\fBub\fP)"
.br
.ti -1c
.RI "void \fBextend\fP (\fBast::Exp\fP *\fBlb\fP, \fBast::Exp\fP *\fBub\fP, \fBomega::coef_t\fP stride)"
.br
.ti -1c
.RI "void \fBextend\fP (char *s, \fBast::Exp\fP *\fBe\fP)"
.br
.ti -1c
.RI "void \fBextend\fP (char *s)"
.br
.ti -1c
.RI "void \fBextend\fP (char *s, \fBomega::Argument_Tuple\fP, int)"
.br
.ti -1c
.RI "\fB~tupleDescriptor\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "std::vector< \fBVariable_Ref\fP * > \fBvars\fP"
.br
.ti -1c
.RI "\fBstd::set\fP< \fBast::Exp\fP * > \fBeq_constraints\fP"
.br
.ti -1c
.RI "\fBstd::set\fP< \fBast::Exp\fP * > \fBgeq_constraints\fP"
.br
.ti -1c
.RI "\fBstd::set\fP< \fBstrideConstraint\fP * > \fBstride_constraints\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tupleDescriptor::tupleDescriptor ()\fC [inline]\fP"

.SS "tupleDescriptor::~tupleDescriptor ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void tupleDescriptor::extend ()"

.SS "void tupleDescriptor::extend (\fBast::Exp\fP * e)"

.SS "void tupleDescriptor::extend (\fBast::Exp\fP * lb, \fBast::Exp\fP * ub)"

.SS "void tupleDescriptor::extend (\fBast::Exp\fP * lb, \fBast::Exp\fP * ub, \fBomega::coef_t\fP stride)"

.SS "void tupleDescriptor::extend (char * s)"

.SS "void tupleDescriptor::extend (char * s, \fBast::Exp\fP * e)"

.SS "void tupleDescriptor::extend (char * s, \fBomega::Argument_Tuple\fP of, int pos)"

.SH "Member Data Documentation"
.PP 
.SS "\fBstd::set\fP<\fBast::Exp\fP *> tupleDescriptor::eq_constraints"

.SS "\fBstd::set\fP<\fBast::Exp\fP *> tupleDescriptor::geq_constraints"

.SS "int tupleDescriptor::size"

.SS "\fBstd::set\fP<\fBstrideConstraint\fP *> tupleDescriptor::stride_constraints"

.SS "std::vector<\fBVariable_Ref\fP *> tupleDescriptor::vars"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
