.TH "lib/iegenlib/src/set_relation/UFCallMap.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/set_relation/UFCallMap.h \- Interface of UFCallMap class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'expression\&.h'\fP
.br
\fC#include 'TupleDecl\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBiegenlib::UFCallMap\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBiegenlib\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface of UFCallMap class\&. 


.PP
\fBDate\fP
.RS 4
Started: 2016-02-02
.RE
.PP
\fBAuthors\fP
.RS 4
Michelle Strout, Mahdi Soltan Mohammadi
.RE
.PP
Copyright (c) 2015-2016, University of Arizona 
.br
 All rights reserved\&. See \&.\&./\&.\&./COPYING for details\&. 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
