.TH "lib/iegenlib/src/set_relation/UninterpFunc.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/set_relation/UninterpFunc.cc \- Implementation of UninterpFunc class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'UninterpFunc\&.h'\fP
.br
\fC#include 'set_relation\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBiegenlib\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of UninterpFunc class\&. 


.PP
\fBDate\fP
.RS 4
Started: 2013-06-20 
.RE
.PP
.SH "$Revision:: 727                $: last committed revision"
.PP
.SH "$Date:: 2013-07-25 22:45:15 -0#$: date of last committed revision"
.PP
.SH "$Author:: mstrout              $: author of last committed revision"
.PP
\fBAuthors\fP
.RS 4
Michelle Strout
.RE
.PP
Copyright (c) 2013 Colorado State University All rights reserved\&. See \&.\&./\&.\&./COPYING for details\&. 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
