.TH "UNION" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNION
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref\fP"
.br
.ti -1c
.RI "\fBisl_space\fP * \fBspace\fP"
.br
.ti -1c
.RI "struct \fBisl_hash_table\fP \fBtable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int UNION::ref"

.SS "\fBisl_space\fP * UNION::space"

.SS "struct \fBisl_hash_table\fP UNION::table"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
