.TH "lib/isl/include/isl/deprecated/union_map_int.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/deprecated/union_map_int.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/deprecated/int\&.h>\fP
.br
\fC#include <isl/union_map_type\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_union_map\fP * \fBisl_union_map_fixed_power\fP (\fB__isl_take\fP \fBisl_union_map\fP *umap, \fBisl_int\fP exp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_union_map\fP* isl_union_map_fixed_power (\fB__isl_take\fP \fBisl_union_map\fP * umap, \fBisl_int\fP exp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
