.TH "lib/isl/include/isl/union_map_type.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/union_map_type.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/ctx\&.h>\fP
.br
\fC#include <isl/list\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBisl_union_map\fP \fBisl_union_map\fP"
.br
.ti -1c
.RI "typedef struct \fBisl_union_set\fP \fBisl_union_set\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "struct \fB__isl_export\fP \fBisl_union_map\fP"

.SS "struct \fB__isl_export\fP \fBisl_union_set\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
