.TH "util::MatrixIO::_coo_mnode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::MatrixIO::_coo_mnode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatrixIO\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBrow\fP"
.br
.ti -1c
.RI "unsigned \fBcol\fP"
.br
.ti -1c
.RI "\fBdtype\fP \fBval\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned util::MatrixIO::_coo_mnode::col"

.SS "unsigned util::MatrixIO::_coo_mnode::row"

.SS "\fBdtype\fP util::MatrixIO::_coo_mnode::val"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
