.TH "util::Parser" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::Parser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parser\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP ()"
.br
.ti -1c
.RI "virtual \fB~Parser\fP ()"
.br
.ti -1c
.RI "int \fBeval\fP (\fBconst\fP string &expression, \fBconst\fP \fBmap\fP< string, int > &consts={})"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "util::Parser::Parser ()\fC [inline]\fP, \fC [explicit]\fP"

.SS "virtual util::Parser::~Parser ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int util::Parser::eval (\fBconst\fP string & expression, \fBconst\fP \fBmap\fP< string, int > & consts = \fC{}\fP)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
