.TH "util::PAPI" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::PAPI
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PAPI\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPAPI\fP ()"
.br
.ti -1c
.RI "int \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBerror\fP (\fBconst\fP string &errstr, int code=PAPI_OK)"
.br
.ti -1c
.RI "int \fBadd\fP (int event)"
.br
.ti -1c
.RI "int \fBadd\fP (\fBconst\fP string &\fBname\fP)"
.br
.ti -1c
.RI "int \fBstart\fP ()"
.br
.ti -1c
.RI "int \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBreport\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "util::PAPI::PAPI ()\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int util::PAPI::add (\fBconst\fP string & name)\fC [inline]\fP"

.SS "int util::PAPI::add (int event)\fC [inline]\fP"

.SS "void util::PAPI::error (\fBconst\fP string & errstr, int code = \fCPAPI_OK\fP)\fC [inline]\fP"

.SS "int util::PAPI::init ()\fC [inline]\fP"

.SS "void util::PAPI::report ()\fC [inline]\fP"

.SS "int util::PAPI::start ()\fC [inline]\fP"

.SS "int util::PAPI::stop ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
