.TH "lib/iegenlib/src/util/util.cc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/iegenlib/src/util/util.cc \- Implementation for the util classes/routines\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <util/util\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBiegenlib\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBiegenlib::compareFileContentsToString\fP (string file, string contents)"
.br
.ti -1c
.RI "string \fBiegenlib::createUniqueName\fP (string \fBname\fP, \fBset\fP< string > &taken)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation for the util classes/routines\&. 


.PP
\fBDate\fP
.RS 4
Started: 9/13/10 
.RE
.PP
.SH "$Revision:: 738                $: last committed revision"
.PP
.SH "$Date:: 2013-08-04 23:04:41 -0#$: date of last committed revision"
.PP
.SH "$Author:: mstrout              $: author of last committed revision"
.PP
\fBAuthors\fP
.RS 4
Alan LaMielle
.RE
.PP
Copyright (c) 2009, 2010, 2011, 2012, Colorado State University 
.br
 All rights reserved\&. 
.br
 See \&.\&./\&.\&./COPYING for details\&. 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
