.TH "util::TensorIO::_coo_tnode" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::TensorIO::_coo_tnode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatrixIO\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned * \fBcoords\fP"
.br
.ti -1c
.RI "unsigned \fBorder\fP"
.br
.ti -1c
.RI "\fBdtype\fP \fBval\fP"
.br
.ti -1c
.RI "struct \fB_coo_tnode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned* util::TensorIO::_coo_tnode::coords"

.SS "struct \fB_coo_tnode\fP* util::TensorIO::_coo_tnode::next"

.SS "unsigned util::TensorIO::_coo_tnode::order"

.SS "\fBdtype\fP util::TensorIO::_coo_tnode::val"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
