.TH "lib/isl/include/isl/deprecated/val_int.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/deprecated/val_int.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/deprecated/int\&.h>\fP
.br
\fC#include <isl/val\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_val_int_from_isl_int\fP (\fBisl_ctx\fP *ctx, \fBisl_int\fP \fBn\fP)"
.br
.ti -1c
.RI "int \fBisl_val_get_num_isl_int\fP (\fB__isl_keep\fP \fBisl_val\fP *v, \fBisl_int\fP *\fBn\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isl_val_get_num_isl_int (\fB__isl_keep\fP \fBisl_val\fP * v, \fBisl_int\fP * n)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_val_int_from_isl_int (\fBisl_ctx\fP * ctx, \fBisl_int\fP n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
