.TH "lib/isl/include/isl/val_gmp.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/val_gmp.h
.SH SYNOPSIS
.br
.PP
\fC#include <gmp\&.h>\fP
.br
\fC#include <isl/val\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_val_int_from_gmp\fP (\fBisl_ctx\fP *ctx, \fBmpz_t\fP \fBz\fP)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_val\fP * \fBisl_val_from_gmp\fP (\fBisl_ctx\fP *ctx, \fBconst\fP \fBmpz_t\fP \fBn\fP, \fBconst\fP \fBmpz_t\fP d)"
.br
.ti -1c
.RI "int \fBisl_val_get_num_gmp\fP (\fB__isl_keep\fP \fBisl_val\fP *v, \fBmpz_t\fP \fBz\fP)"
.br
.ti -1c
.RI "int \fBisl_val_get_den_gmp\fP (\fB__isl_keep\fP \fBisl_val\fP *v, \fBmpz_t\fP \fBz\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_val\fP* isl_val_from_gmp (\fBisl_ctx\fP * ctx, \fBconst\fP \fBmpz_t\fP n, \fBconst\fP \fBmpz_t\fP d)"

.SS "int isl_val_get_den_gmp (\fB__isl_keep\fP \fBisl_val\fP * v, \fBmpz_t\fP z)"

.SS "int isl_val_get_num_gmp (\fB__isl_keep\fP \fBisl_val\fP * v, \fBmpz_t\fP z)"

.SS "\fB__isl_give\fP \fBisl_val\fP* isl_val_int_from_gmp (\fBisl_ctx\fP * ctx, \fBmpz_t\fP z)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
