.TH "variable" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
variable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.ti -1c
.RI "struct \fBvariable\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* variable::name"

.SS "struct \fBvariable\fP* variable::next"

.SS "int variable::pos"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
