.TH "lib/isl/include/isl/deprecated/vec_int.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/deprecated/vec_int.h
.SH SYNOPSIS
.br
.PP
\fC#include <isl/deprecated/int\&.h>\fP
.br
\fC#include <isl/vec\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisl_vec_get_element\fP (\fB__isl_keep\fP \fBisl_vec\fP *vec, int \fBpos\fP, \fBisl_int\fP *v)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vec\fP * \fBisl_vec_set_element\fP (\fB__isl_take\fP \fBisl_vec\fP *vec, int \fBpos\fP, \fBisl_int\fP v)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vec\fP * \fBisl_vec_set\fP (\fB__isl_take\fP \fBisl_vec\fP *vec, \fBisl_int\fP v)"
.br
.ti -1c
.RI "\fB__isl_give\fP \fBisl_vec\fP * \fBisl_vec_fdiv_r\fP (\fB__isl_take\fP \fBisl_vec\fP *vec, \fBisl_int\fP \fBm\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__isl_give\fP \fBisl_vec\fP* isl_vec_fdiv_r (\fB__isl_take\fP \fBisl_vec\fP * vec, \fBisl_int\fP m)"

.SS "int isl_vec_get_element (\fB__isl_keep\fP \fBisl_vec\fP * vec, int pos, \fBisl_int\fP * v)"

.SS "\fB__isl_give\fP \fBisl_vec\fP* isl_vec_set (\fB__isl_take\fP \fBisl_vec\fP * vec, \fBisl_int\fP v)"

.SS "\fB__isl_give\fP \fBisl_vec\fP* isl_vec_set_element (\fB__isl_take\fP \fBisl_vec\fP * vec, int pos, \fBisl_int\fP v)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
