.TH "verify_point_bound" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
verify_point_bound
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBbound_options\fP * \fBoptions\fP"
.br
.ti -1c
.RI "int \fBstride\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int \fBexact\fP"
.br
.ti -1c
.RI "int \fBerror\fP"
.br
.ti -1c
.RI "\fBisl_pw_qpolynomial_fold\fP * \fBpwf\fP"
.br
.ti -1c
.RI "\fBisl_pw_qpolynomial_fold\fP * \fBbound\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBisl_pw_qpolynomial_fold\fP* verify_point_bound::bound"

.SS "int verify_point_bound::error"

.SS "int verify_point_bound::exact"

.SS "int verify_point_bound::n"

.SS "struct \fBbound_options\fP* verify_point_bound::options"

.SS "\fBisl_pw_qpolynomial_fold\fP* verify_point_bound::pwf"

.SS "int verify_point_bound::stride"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
