.TH "lib/gmp/version.c" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gmp/version.c
.SH SYNOPSIS
.br
.PP
\fC#include 'gmp\&.h'\fP
.br
\fC#include 'gmp\-impl\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP char *\fBconst\fP \fBgmp_version\fP = \fBVERSION\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBconst\fP char* \fBconst\fP gmp_version = \fBVERSION\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
