.TH "lib/isl/include/isl/version.h" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/isl/include/isl/version.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBconst\fP char * \fBisl_version\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBconst\fP char* isl_version (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
