.TH "visit.CodeGenVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.CodeGenVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBvisit\&.DFGVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, lang='\fBC\fP', \fBprofile\fP=False, \fBstructname\fP='')"
.br
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.ti -1c
.RI "def \fBincludes\fP (self)"
.br
.ti -1c
.RI "def \fBincludes\fP (self, includes)"
.br
.ti -1c
.RI "def \fBdefines\fP (self)"
.br
.ti -1c
.RI "def \fBdefines\fP (self, defines)"
.br
.ti -1c
.RI "def \fBtypedefs\fP (self)"
.br
.ti -1c
.RI "def \fBtypedefs\fP (self, typedefs)"
.br
.ti -1c
.RI "def \fBfunctions\fP (self)"
.br
.ti -1c
.RI "def \fBfunctions\fP (self, functions)"
.br
.ti -1c
.RI "def \fBindent\fP (self)"
.br
.ti -1c
.RI "def \fBindent\fP (self, indent)"
.br
.ti -1c
.RI "def \fBpath\fP (self)"
.br
.ti -1c
.RI "def \fBpath\fP (self, path)"
.br
.ti -1c
.RI "def \fBprofile\fP (self)"
.br
.ti -1c
.RI "def \fBprofile\fP (self, profile)"
.br
.ti -1c
.RI "def \fBallocs\fP (self)"
.br
.ti -1c
.RI "def \fBstructs\fP (self)"
.br
.ti -1c
.RI "def \fBstructs\fP (self, structs)"
.br
.ti -1c
.RI "def \fBstructname\fP (self)"
.br
.ti -1c
.RI "def \fBlines\fP (self)"
.br
.ti -1c
.RI "def \fBlines\fP (self, lines)"
.br
.ti -1c
.RI "def \fBstruct_init\fP (self, \fBname\fP, data=())"
.br
.ti -1c
.RI "def \fBstruct_unroll\fP (self, \fBstructname\fP, structdata=())"
.br
.ti -1c
.RI "def \fBsetup\fP (self, g)"
.br
.ti -1c
.RI "def \fBenter\fP (self, node)"
.br
.ti -1c
.RI "def \fBfinish\fP (self, g)"
.br
.ti -1c
.RI "def \fBwrite\fP (self)"
.br
.ti -1c
.RI "def \fBbuild\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprofile\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def visit\&.CodeGenVisitor\&.__init__ ( self,  lang = \fC'\fBC\fP'\fP,  profile = \fCFalse\fP,  structname = \fC''\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def visit\&.CodeGenVisitor\&.__repr__ ( self)"

.SS "def visit\&.CodeGenVisitor\&.allocs ( self)"

.SS "def visit\&.CodeGenVisitor\&.build ( self)"

.SS "def visit\&.CodeGenVisitor\&.defines ( self)"

.SS "def visit\&.CodeGenVisitor\&.defines ( self,  defines)"

.SS "def visit\&.CodeGenVisitor\&.enter ( self,  node)"

.PP
Reimplemented from \fBvisit\&.Visitor\fP\&.
.SS "def visit\&.CodeGenVisitor\&.finish ( self,  g)"

.PP
Reimplemented from \fBvisit\&.DFGVisitor\fP\&.
.SS "def visit\&.CodeGenVisitor\&.functions ( self)"

.SS "def visit\&.CodeGenVisitor\&.functions ( self,  functions)"

.SS "def visit\&.CodeGenVisitor\&.includes ( self)"

.SS "def visit\&.CodeGenVisitor\&.includes ( self,  includes)"

.SS "def visit\&.CodeGenVisitor\&.indent ( self)"

.SS "def visit\&.CodeGenVisitor\&.indent ( self,  indent)"

.SS "def visit\&.CodeGenVisitor\&.lines ( self)"

.SS "def visit\&.CodeGenVisitor\&.lines ( self,  lines)"

.SS "def visit\&.CodeGenVisitor\&.path ( self)"

.SS "def visit\&.CodeGenVisitor\&.path ( self,  path)"

.SS "def visit\&.CodeGenVisitor\&.profile ( self)"

.SS "def visit\&.CodeGenVisitor\&.profile ( self,  profile)"

.SS "def visit\&.CodeGenVisitor\&.setup ( self,  g)"

.PP
Reimplemented from \fBvisit\&.DFGVisitor\fP\&.
.SS "def visit\&.CodeGenVisitor\&.struct_init ( self,  name,  data = \fC()\fP)"

.SS "def visit\&.CodeGenVisitor\&.struct_unroll ( self,  structname,  structdata = \fC()\fP)"

.SS "def visit\&.CodeGenVisitor\&.structname ( self)"

.SS "def visit\&.CodeGenVisitor\&.structs ( self)"

.SS "def visit\&.CodeGenVisitor\&.structs ( self,  structs)"

.SS "def visit\&.CodeGenVisitor\&.typedefs ( self)"

.SS "def visit\&.CodeGenVisitor\&.typedefs ( self,  typedefs)"

.SS "def visit\&.CodeGenVisitor\&.write ( self)"

.SH "Member Data Documentation"
.PP 
.SS "visit\&.CodeGenVisitor\&.profile"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
