.TH "visit.FlowGraphVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.FlowGraphVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBvisit\&.NodeVisitor\fP\&.
.PP
Inherited by \fBvisit\&.IEGenGraphVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, graph, \fBouter\fP=None)"
.br
.ti -1c
.RI "def \fBcode\fP (self)"
.br
.ti -1c
.RI "def \fBlatex\fP (self)"
.br
.ti -1c
.RI "def \fBomega\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def visit\&.FlowGraphVisitor\&.__init__ ( self,  graph,  outer = \fCNone\fP)"

.PP
Reimplemented from \fBvisit\&.NodeVisitor\fP\&.
.PP
Reimplemented in \fBvisit\&.IEGenGraphVisitor\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def visit\&.FlowGraphVisitor\&.code ( self)"

.PP
Reimplemented in \fBvisit\&.IEGenGraphVisitor\fP\&.
.SS "def visit\&.FlowGraphVisitor\&.latex ( self)"

.SS "def visit\&.FlowGraphVisitor\&.omega ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
