.TH "visit.DOTVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.DOTVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBvisit\&.DFLRVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBout\fP=sys\&.stdout)"
.br
.ti -1c
.RI "def \fBenter\fP (self, node)"
.br
.ti -1c
.RI "def \fBvisit\fP (self, node)"
.br
.ti -1c
.RI "def \fBexit\fP (self, node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBout\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def visit\&.DOTVisitor\&.__init__ ( self,  out = \fCsys\&.stdout\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def visit\&.DOTVisitor\&.enter ( self,  node)"

.PP
Reimplemented from \fBvisit\&.Visitor\fP\&.
.SS "def visit\&.DOTVisitor\&.exit ( self,  node)"

.PP
Reimplemented from \fBvisit\&.Visitor\fP\&.
.SS "def visit\&.DOTVisitor\&.visit ( self,  node)"

.PP
Reimplemented from \fBvisit\&.DFLRVisitor\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "visit\&.DOTVisitor\&.out"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
