.TH "visit.NodeVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.NodeVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBvisit\&.DataNodeVisitor\fP, \fBvisit\&.FlowGraphVisitor\fP, \fBvisit\&.IterNodeVisitor\fP, and \fBvisit\&.StmtNodeVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBnode\fP=None, \fBouter\fP=None)"
.br
.ti -1c
.RI "def \fBnode\fP (self)"
.br
.ti -1c
.RI "def \fBouter\fP (self)"
.br
.ti -1c
.RI "def \fBcreate\fP (cls, \fBnode\fP, \fBouter\fP=None)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def visit\&.NodeVisitor\&.__init__ ( self,  node = \fCNone\fP,  outer = \fCNone\fP)"

.PP
Reimplemented in \fBvisit\&.IterNodeVisitor\fP, \fBvisit\&.StructNodeVisitor\fP, \fBvisit\&.TempNodeVisitor\fP, \fBvisit\&.DataNodeVisitor\fP, \fBvisit\&.StmtNodeVisitor\fP, \fBvisit\&.IEGenGraphVisitor\fP, and \fBvisit\&.FlowGraphVisitor\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def visit\&.NodeVisitor\&.create ( cls,  node,  outer = \fCNone\fP)"

.SS "def visit\&.NodeVisitor\&.node ( self)"

.SS "def visit\&.NodeVisitor\&.outer ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
