.TH "visit.IEGenGraphVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.IEGenGraphVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBvisit\&.FlowGraphVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, graph, \fBouter\fP=None)"
.br
.ti -1c
.RI "def \fBcode\fP (self)"
.br
.ti -1c
.RI "def \fBfinish\fP (self, cgvis)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def visit\&.IEGenGraphVisitor\&.__init__ ( self,  graph,  outer = \fCNone\fP)"

.PP
Reimplemented from \fBvisit\&.FlowGraphVisitor\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def visit\&.IEGenGraphVisitor\&.code ( self)"

.PP
Reimplemented from \fBvisit\&.FlowGraphVisitor\fP\&.
.SS "def visit\&.IEGenGraphVisitor\&.finish ( self,  cgvis)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
