.TH "visit.BFSVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.BFSVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBvisit\&.Visitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, g)"
.br
.ti -1c
.RI "def \fBvisit\fP (self, node)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def visit\&.BFSVisitor\&.__init__ ( self,  g)"

.SH "Member Function Documentation"
.PP 
.SS "def visit\&.BFSVisitor\&.visit ( self,  node)"

.PP
Reimplemented from \fBvisit\&.Visitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
