.TH "visit.DFGVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.DFGVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBvisit\&.Visitor\fP\&.
.PP
Inherited by \fBvisit\&.CodeGenVisitor\fP, \fBvisit\&.LatexVisitor\fP, and \fBvisit\&.PolyVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBwalk\fP (self, g)"
.br
.ti -1c
.RI "def \fBvisit\fP (self, node)"
.br
.ti -1c
.RI "def \fBsetup\fP (self, g)"
.br
.ti -1c
.RI "def \fBfinish\fP (self, g)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def visit\&.DFGVisitor\&.__init__ ( self)"

.PP
Reimplemented in \fBvisit\&.OmegaVisitor\fP, \fBvisit\&.ISLVisitor\fP, \fBvisit\&.PolyVisitor\fP, and \fBvisit\&.LatexVisitor\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def visit\&.DFGVisitor\&.finish ( self,  g)"

.PP
Reimplemented in \fBvisit\&.CodeGenVisitor\fP, \fBvisit\&.OmegaVisitor\fP, and \fBvisit\&.ISLVisitor\fP\&.
.SS "def visit\&.DFGVisitor\&.setup ( self,  g)"

.PP
Reimplemented in \fBvisit\&.CodeGenVisitor\fP, \fBvisit\&.OmegaVisitor\fP, and \fBvisit\&.PolyVisitor\fP\&.
.SS "def visit\&.DFGVisitor\&.visit ( self,  node)"

.PP
Reimplemented from \fBvisit\&.Visitor\fP\&.
.SS "def visit\&.DFGVisitor\&.walk ( self,  g)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
