.TH "visit.OmegaVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.OmegaVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBvisit\&.PolyVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBsetup\fP (self, g)"
.br
.ti -1c
.RI "def \fBenter\fP (self, node)"
.br
.ti -1c
.RI "def \fBfinish\fP (self, g)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def visit\&.OmegaVisitor\&.__init__ ( self)"

.PP
Reimplemented from \fBvisit\&.PolyVisitor\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def visit\&.OmegaVisitor\&.enter ( self,  node)"

.PP
Reimplemented from \fBvisit\&.PolyVisitor\fP\&.
.SS "def visit\&.OmegaVisitor\&.finish ( self,  g)"

.PP
Reimplemented from \fBvisit\&.DFGVisitor\fP\&.
.SS "def visit\&.OmegaVisitor\&.setup ( self,  g)"

.PP
Reimplemented from \fBvisit\&.PolyVisitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
