.TH "visit.DataNodeVisitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.DataNodeVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBvisit\&.NodeVisitor\fP\&.
.PP
Inherited by \fBvisit\&.StructNodeVisitor\fP, and \fBvisit\&.TempNodeVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBnode\fP, \fBouter\fP=None)"
.br
.ti -1c
.RI "def \fBcode\fP (self)"
.br
.ti -1c
.RI "def \fBlatex\fP (self)"
.br
.ti -1c
.RI "def \fBomega\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def visit\&.DataNodeVisitor\&.__init__ ( self,  node,  outer = \fCNone\fP)"

.PP
Reimplemented from \fBvisit\&.NodeVisitor\fP\&.
.PP
Reimplemented in \fBvisit\&.StructNodeVisitor\fP, and \fBvisit\&.TempNodeVisitor\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def visit\&.DataNodeVisitor\&.code ( self)"

.PP
Reimplemented in \fBvisit\&.StructNodeVisitor\fP, and \fBvisit\&.TempNodeVisitor\fP\&.
.SS "def visit\&.DataNodeVisitor\&.latex ( self)"

.SS "def visit\&.DataNodeVisitor\&.omega ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
