.TH "VisitorDebugTest" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisitorDebugTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBreturnResult\fP ()"
.br
.ti -1c
.RI "void \fBpostVisitTerm\fP (\fBiegenlib::Term\fP *\fBt\fP)"
.br
.ti -1c
.RI "void \fBpostVisitUFCallTerm\fP (\fBiegenlib::UFCallTerm\fP *\fBt\fP)"
.br
.ti -1c
.RI "void \fBpostVisitTupleVarTerm\fP (\fBiegenlib::TupleVarTerm\fP *\fBt\fP)"
.br
.ti -1c
.RI "void \fBpostVisitVarTerm\fP (\fBiegenlib::VarTerm\fP *\fBt\fP)"
.br
.ti -1c
.RI "void \fBpostVisitTupleExpTerm\fP (\fBiegenlib::TupleExpTerm\fP *\fBt\fP)"
.br
.ti -1c
.RI "void \fBpostVisitExp\fP (\fBiegenlib::Exp\fP *\fBe\fP)"
.br
.ti -1c
.RI "void \fBpostVisitConjunction\fP (\fBiegenlib::Conjunction\fP *\fBc\fP)"
.br
.ti -1c
.RI "void \fBpostVisitSparseConstraints\fP (\fBiegenlib::SparseConstraints\fP *sc)"
.br
.ti -1c
.RI "void \fBpostVisitSet\fP (\fBiegenlib::Set\fP *s)"
.br
.ti -1c
.RI "void \fBpostVisitRelation\fP (\fBiegenlib::Relation\fP *r)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void VisitorDebugTest::postVisitConjunction (\fBiegenlib::Conjunction\fP * c)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void VisitorDebugTest::postVisitExp (\fBiegenlib::Exp\fP * e)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void VisitorDebugTest::postVisitRelation (\fBiegenlib::Relation\fP * r)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void VisitorDebugTest::postVisitSet (\fBiegenlib::Set\fP * s)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void VisitorDebugTest::postVisitSparseConstraints (\fBiegenlib::SparseConstraints\fP * sc)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void VisitorDebugTest::postVisitTerm (\fBiegenlib::Term\fP * t)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void VisitorDebugTest::postVisitTupleExpTerm (\fBiegenlib::TupleExpTerm\fP * t)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void VisitorDebugTest::postVisitTupleVarTerm (\fBiegenlib::TupleVarTerm\fP * t)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void VisitorDebugTest::postVisitUFCallTerm (\fBiegenlib::UFCallTerm\fP * t)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "void VisitorDebugTest::postVisitVarTerm (\fBiegenlib::VarTerm\fP * t)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBVisitor\fP\&.
.SS "std::string VisitorDebugTest::returnResult ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
