.TH "visit.Visitor" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visit.Visitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBvisit\&.BFSVisitor\fP, \fBvisit\&.DFGVisitor\fP, and \fBvisit\&.DFLRVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBvisit\fP (self, node)"
.br
.ti -1c
.RI "def \fBenter\fP (self, node)"
.br
.ti -1c
.RI "def \fBexit\fP (self, node)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def visit\&.Visitor\&.enter ( self,  node)"

.PP
Reimplemented in \fBvisit\&.CodeGenVisitor\fP, \fBvisit\&.OmegaVisitor\fP, \fBvisit\&.ISLVisitor\fP, \fBvisit\&.PolyVisitor\fP, \fBvisit\&.LatexVisitor\fP, \fBvisit\&.PDFGVisitor\fP, and \fBvisit\&.DOTVisitor\fP\&.
.SS "def visit\&.Visitor\&.exit ( self,  node)"

.PP
Reimplemented in \fBvisit\&.PDFGVisitor\fP, and \fBvisit\&.DOTVisitor\fP\&.
.SS "def visit\&.Visitor\&.visit ( self,  node)"

.PP
Reimplemented in \fBvisit\&.DFGVisitor\fP, \fBvisit\&.PDFGVisitor\fP, \fBvisit\&.DOTVisitor\fP, \fBvisit\&.DFLRVisitor\fP, and \fBvisit\&.BFSVisitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
