.TH "xml" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xml
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXmlObject\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBnodeToDict\fP (node)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBENCODING\fP = 'utf\-8'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def xml\&.nodeToDict ( node)"

.SH "Variable Documentation"
.PP 
.SS "string xml\&.ENCODING = 'utf\-8'"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
