.TH "xml.XmlObject" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xml.XmlObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBtag\fP='', \fBattribs\fP={}, text='', parent=None)"
.br
.ti -1c
.RI "def \fBsetAttribs\fP (self, \fBattribs\fP)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fBread\fP (self, \fBpath\fP)"
.br
.ti -1c
.RI "def \fBparse\fP (self, data)"
.br
.ti -1c
.RI "def \fBwrite\fP (self, \fBpath\fP)"
.br
.ti -1c
.RI "def \fBprettify\fP (self)"
.br
.ti -1c
.RI "def \fBtoDict\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtag\fP"
.br
.ti -1c
.RI "\fBnode\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBattribs\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def xml\&.XmlObject\&.__init__ ( self,  tag = \fC''\fP,  attribs = \fC{}\fP,  text = \fC''\fP,  parent = \fCNone\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def xml\&.XmlObject\&.__str__ ( self)"

.SS "def xml\&.XmlObject\&.parse ( self,  data)"

.SS "def xml\&.XmlObject\&.prettify ( self)"

.SS "def xml\&.XmlObject\&.read ( self,  path)"

.SS "def xml\&.XmlObject\&.setAttribs ( self,  attribs)"

.SS "def xml\&.XmlObject\&.toDict ( self)"

.SS "def xml\&.XmlObject\&.write ( self,  path)"

.SH "Member Data Documentation"
.PP 
.SS "xml\&.XmlObject\&.attribs"

.SS "xml\&.XmlObject\&.node"

.SS "xml\&.XmlObject\&.path"

.SS "xml\&.XmlObject\&.tag"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
