.TH "yyalloc" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyalloc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fByytype_int16\fP \fByyss_alloc\fP"
.br
.ti -1c
.RI "\fBYYSTYPE\fP \fByyvs_alloc\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fByytype_int16\fP yyalloc::yyss_alloc"

.SS "\fBYYSTYPE\fP yyalloc::yyvs_alloc"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
