.TH "YYSTYPE" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YYSTYPE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.tab\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBINT_VALUE\fP"
.br
.ti -1c
.RI "\fBomega::coef_t\fP \fBCOEF_VALUE\fP"
.br
.ti -1c
.RI "\fBRel_Op\fP \fBREL_OPERATOR\fP"
.br
.ti -1c
.RI "char * \fBVAR_NAME\fP"
.br
.ti -1c
.RI "\fBstd::set\fP< char * > * \fBVAR_LIST\fP"
.br
.ti -1c
.RI "\fBast::Exp\fP * \fBEXP\fP"
.br
.ti -1c
.RI "\fBstd::set\fP< \fBast::Exp\fP * > * \fBEXP_LIST\fP"
.br
.ti -1c
.RI "\fBAST\fP * \fBASTP\fP"
.br
.ti -1c
.RI "\fBomega::Argument_Tuple\fP \fBARGUMENT_TUPLE\fP"
.br
.ti -1c
.RI "\fBAST_constraints\fP * \fBASTCP\fP"
.br
.ti -1c
.RI "\fBDeclaration_Site\fP * \fBDECLARATION_SITE\fP"
.br
.ti -1c
.RI "\fBomega::Relation\fP * \fBRELATION\fP"
.br
.ti -1c
.RI "\fBtupleDescriptor\fP * \fBTUPLE_DESCRIPTOR\fP"
.br
.ti -1c
.RI "std::pair< std::vector< \fBomega::Relation\fP >, std::vector< \fBomega::Relation\fP > > * \fBREL_TUPLE_PAIR\fP"
.br
.ti -1c
.RI "\fBomega::Dynamic_Array1\fP< \fBomega::Relation\fP > * \fBRELATION_ARRAY_1D\fP"
.br
.ti -1c
.RI "std::string * \fBSTRING_VALUE\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBomega::Argument_Tuple\fP YYSTYPE::ARGUMENT_TUPLE"

.SS "\fBAST_constraints\fP* YYSTYPE::ASTCP"

.SS "\fBAST\fP* YYSTYPE::ASTP"

.SS "\fBomega::coef_t\fP YYSTYPE::COEF_VALUE"

.SS "\fBDeclaration_Site\fP* YYSTYPE::DECLARATION_SITE"

.SS "\fBast::Exp\fP* YYSTYPE::EXP"

.SS "\fBstd::set\fP<\fBast::Exp\fP *>* YYSTYPE::EXP_LIST"

.SS "int YYSTYPE::INT_VALUE"

.SS "\fBRel_Op\fP YYSTYPE::REL_OPERATOR"

.SS "std::pair<std::vector<\fBomega::Relation\fP>, std::vector<\fBomega::Relation\fP> >* YYSTYPE::REL_TUPLE_PAIR"

.SS "\fBomega::Relation\fP* YYSTYPE::RELATION"

.SS "\fBomega::Dynamic_Array1\fP<\fBomega::Relation\fP>* YYSTYPE::RELATION_ARRAY_1D"

.SS "std::string* YYSTYPE::STRING_VALUE"

.SS "\fBtupleDescriptor\fP* YYSTYPE::TUPLE_DESCRIPTOR"

.SS "\fBstd::set\fP<char *>* YYSTYPE::VAR_LIST"

.SS "char* YYSTYPE::VAR_NAME"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
