.TH "ZZSTYPE" 3 "Sun Jul 12 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZZSTYPE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gen_parser\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string * \fBsval\fP"
.br
.ti -1c
.RI "int \fBival\fP"
.br
.ti -1c
.RI "\fBiegenlib::TupleDecl\fP * \fBtdecl\fP"
.br
.ti -1c
.RI "\fBiegenlib::Environment\fP * \fBenv\fP"
.br
.ti -1c
.RI "\fBiegenlib::Set\fP * \fBset\fP"
.br
.ti -1c
.RI "\fBiegenlib::Relation\fP * \fBrelation\fP"
.br
.ti -1c
.RI "\fBiegenlib::Conjunction\fP * \fBconj\fP"
.br
.ti -1c
.RI "std::list< \fBiegenlib::Conjunction\fP * > * \fBconjlist\fP"
.br
.ti -1c
.RI "\fBiegenlib::Exp\fP * \fBexp\fP"
.br
.ti -1c
.RI "std::list< \fBiegenlib::Exp\fP * > * \fBexplist\fP"
.br
.ti -1c
.RI "std::list< std::string > * \fBsymlist\fP"
.br
.ti -1c
.RI "std::list< std::string > * \fBexistslist\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBiegenlib::Conjunction\fP * ZZSTYPE::conj"

.SS "std::list< \fBiegenlib::Conjunction\fP * > * ZZSTYPE::conjlist"

.SS "\fBiegenlib::Environment\fP * ZZSTYPE::env"

.SS "std::list< std::string > * ZZSTYPE::existslist"

.SS "\fBiegenlib::Exp\fP * ZZSTYPE::exp"

.SS "std::list< \fBiegenlib::Exp\fP * > * ZZSTYPE::explist"

.SS "int ZZSTYPE::ival"

.SS "\fBiegenlib::Relation\fP * ZZSTYPE::relation"

.SS "\fBiegenlib::Set\fP * ZZSTYPE::set"

.SS "std::string * ZZSTYPE::sval"

.SS "std::list< std::string > * ZZSTYPE::symlist"

.SS "\fBiegenlib::TupleDecl\fP * ZZSTYPE::tdecl"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
